### ISSUE TITLE
DLNA profile support for Cyberlink PowerDVD 15 Ultra

### ISSUE THREAD

**Issue by HLFH** [MediaBrowser/Emby#1094]
Hi,

As you can see [here](http://emby.media/community/index.php?/topic/7407-powerdvd-dlna-server-issues/page-2), a DLNA profile is needed for Cyberlink PowerDVD 15 Ultra.

**Comment by LukePulverenti** [comment]
It looks like there's a user in that thread who has created one. why not post there and team up on it? If you guys can get it tested we can include it in a future server release.

**Comment by HLFH** [comment]
@LukePulverenti Ok. I'll post in the forum too. The same user Smaky is saying
> Back to square one... server shows again as No Media Available and Play To will start playing but video will never show up in PowerDVD ; so I tested https://www.dropbox.com/s/5x7yxz6b7u4rix0/CyberLink%20PowerDVD.xml and it does not work.

**Comment by SmakyTaky** [comment]
I have updated the post with a newer version of the profile. It is not yet fully functional but it works to some extent with MKVs and most audio formats for music

**Comment by HLFH** [comment]
@SmakyTaky Thanks a lot!! We can close it.
