### ISSUE TITLE
Emby web client: 3D not supported

### ISSUE THREAD

**Issue by HLFH** [MediaBrowser/Emby#1095]
Hi,

When I'm playing on the Emby web client a MKV 3D movie, it does not work, the image is always duplicated. Here is an example for a HTAB movie: 
![capture2](https://cloud.githubusercontent.com/assets/2359059/7444627/c60f4634-f18c-11e4-9dd1-e34f9c7cc29b.PNG)

And the media info:
![capture](https://cloud.githubusercontent.com/assets/2359059/7444629/d02ddefa-f18c-11e4-9563-e8aa33648cad.PNG)

I precise I installed mkvtoolnix on ArchLinux. So I added the stereoscopic flag to the MKV:
```bash
 mkvmerge -o test.mkv --stereo-mode 0:'top_bottom_left_first' Mr.\ Peabody\ et\ Sherman.3D-HTAB.mkv 
```

According to the [documentation](https://www.bunkus.org/videotools/mkvtoolnix/doc/mkvmerge.html)... But it does not solve the issue!

**Comment by kashmirix** [comment]
Should be <code>--stereo-mode 2</code>. Or, better, add the correct flag using MKVToolNixGUI - Edit Headers tab.

**Comment by HLFH** [comment]
In fact, I have a Vivitek Qumi Q7 3D Ready videoprojectorthat uses 3D frame sequential/alternating frames output.

**Comment by LukePulverenti** [comment]
Can someone provide an ffmpeg transcoding log? thanks.
