### ISSUE TITLE
Mono SSL Trust Issues

### ISSUE THREAD

**Issue by Fmstrat** [MediaBrowser/Emby#1097]
Hi,

Writing to report a problem that seems to be occuring with mono 3.10 on an Ubuntu install, and validated on a CentOS 7 install as well. This is being discussed in the forum here: http://emby.media/community/index.php?/topic/21017-ssl-errrors-with-startssl-cert/#entry204666 and has been so far reported by myself and one other user.

Problem
--------
While web browsers work fine, when connecting to `https://host.ext` with port `9999` (public HTTPS port for Emby) from the Android app (and also reported by another user from their iPhone browser), the following error is reported in the server logs:

    2015-05-04 00:49:18.8658 Error - HttpServer: Error in ProcessAccept
        *** Error Report ***
        Version: 3.0.5597.1
        Command line: /opt/mediabrowser/MediaBrowser.Server.Mono.exe -programdata /var/lib/mediabrowser
        Operating system: Unix 3.13.0.51
        Processor count: 2
        64-Bit OS: True
        64-Bit Process: True
        Program data path: /var/lib/mediabrowser
        Mono: 3.10.0 (tarball Wed Nov  5 12:50:04 UTC 2014)
        Application Path: /opt/mediabrowser/MediaBrowser.Server.Mono.exe
        The authentication or decryption has failed.
        System.IO.IOException
          at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0
        InnerException: Mono.Security.Protocol.Tls.TlsException
        The authentication or decryption has failed.
          at Mono.Security.Protocol.Tls.RecordProtocol.ProcessAlert (AlertLevel alertLevel, AlertDescription alertDesc) [0x00000] in <filename unknown>:0
          at Mono.Security.Protocol.Tls.RecordProtocol.ReceiveRecord (System.IO.Stream record) [0x00000] in <filename unknown>:0
          at Mono.Security.Protocol.Tls.SslServerStream.EndNegotiateHandshake (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0
          at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0

The cert is a StartSSL cert, converted to PFX using the following command:

    ~# openssl pkcs12 -export -in host.cer -inkey host.decrypted.key -out host.pfx

As a note, I have attempted to use just `host.cer` as well as a `united.cer` that includes the StartSSL CA, with the same results in all cases. Secondarily, I have a RapidSSL cert, too, and it has the same results. I have also run the following which did not change the results:

	~# mozroots --import -–sync
	~# certmgr -add -c Trust ./host.cer

Lastly, I've tried forcing mono 4, to see if the latest version of mono would work:

	~# apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
	~# echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
	~# apt-get update
	~# apt-get install mono-devel mono-complete referenceassemblies-pcl ca-certificates-mono
	~# dpkg -i /var/cache/apt/archives/mediabrowser_3.0.5597.1-0.bzr3774+201504301608~ubuntu14.04.1_all.deb
	~# service mediabrowser start

You will notice that I had to force-reinstall mediabrowser, as during the update it removed it due to dependencies. After this, the SSL error still occurred, but everything else appeared to function fine. While this could theoretically be an issue with the Android app, the fact that another user reported it from an iPhone in the browser makes me think otherwise.

Thanks, and let me know if I can help further.

**Comment by Fmstrat** [comment]
Verified on Ubuntu mini 14.04 and Ubuntu Server 15.04 now, too. As per direction from jabbera in the forums, I'm going to help out by creating a Windows 8.1 VM and testing that, too.

**Comment by Fmstrat** [comment]
Connecting to a Windows server with the Android client works flawlessly. Windows 8.1 Enterprise, fresh install, using the "unified" cert which is a combination of StartSSL CA, my certificate, and my decrypted key. This is the same file installed on the Linux server that the Android client does have problems with.

**Comment by Fmstrat** [comment]
In addition to working in windows, under Ubuntu, I decided to try using nginx as an SSL proxy. This works flawlessly with Android, and in fact is significantly faster than the SSL service built into Emby (from the web console). Here is the nginx config I'm using:

	server {
	    listen 9999;
	    server_name MYHOSTNAME.com;

	    gzip             on;
	    gzip_proxied     any;
	    gzip_types       text/css text/plain text/xml application/xml application/javascript application/x-javascript text/javascript application/json text/$
	    gzip_vary        on;

	    ssl on;
	    ssl_certificate /opt/certs/certificate.combined.cer;
	    ssl_certificate_key /opt/certs/ssl.decrypted.key;
	    ssl_session_cache shared:SSL:10m;

	    location / {
		proxy_pass              http://localhost:8096;
		proxy_set_header        Host $host:$server_port;
		proxy_set_header        X-Real-IP       $remote_addr;
		proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_redirect          http://$host:$server_port https://$host:$server_port;
	    }

**Comment by williamkray** [comment]
i can confirm that using a proxy eliminates the problem, I use apache with a reverse proxy and a StartSSL certificate from various clients, with no issues.

**Comment by LukePulverenti** [comment]
I believe this is resolved with mono 4.4.2. Can anyone try it out? thanks.

**Comment by Phlogi** [comment]
Works with mono-4.4.1.0-1-x86_64 here on arch linux.

**Comment by LukePulverenti** [comment]
Have you guys seen this announcement about mono 4.6? It has a rewritten TLS layer:

http://tirania.org/blog/archive/2016/Sep-30.html

If there's still an issue, we should look at it as a new topic. Thanks.
