### ISSUE TITLE
Playlists: No indication new playlist is being created (webui)

### ISSUE THREAD

**Issue by ScottIsAFool** [MediaBrowser/Emby#1104]
Steps:
1. Choose an item to add to a playlist
2. In the sidebar, choose new playlist, give it a name
3. Press enter

No indication that anything is happening is presented to the user. This means if they then click on the submit button (after pressing enter), they will end up with duplicate playlists.

This is particularly noticeable if you are on a slower network connection.

**Comment by LukePulverenti** [comment]
Resolved in 3.0.5724.2
