### ISSUE TITLE
Webplayer: Mouseover should move subtitles

### ISSUE THREAD

**Issue by hasdf** [MediaBrowser/Emby#1110]
If I mouseover the webplayer, the controls show up and cover up the subtitles.

Could be fixed, if the subtitles would move up too.

![bildschirmfoto von 2015-05-27 19-53-23](https://cloud.githubusercontent.com/assets/1760609/7843450/0d195b84-04aa-11e5-83a9-bf95ec15e547.png)

**Comment by LukePulverenti** [comment]
Done, but supported in Chrome only.
