### ISSUE TITLE
invalid user (installation bug)

### ISSUE THREAD

**Issue by matthiaslexer** [MediaBrowser/Emby#1112]
I installed emby-server and used emby as the standard user. 
In the /etc/default/emby-server file is the user called 'ok'. 

As a result emby can't be configured and it get the following error on the system (debian 7):
[FAIL] EmbyServer: fatal pgrep error (2), aborting ... failed!

**Comment by LukePulverenti** [comment]
Hi there. Since the time you filed this issue, we have revamped our packages and this is no longer applicable. Please try again and let us know how it goes. Thanks.
