### ISSUE TITLE
emby (web interface) keep yelling the error "Argument cannot be null. Parameter name: appVersion"

### ISSUE THREAD

**Issue by gissehel** [MediaBrowser/Emby#1113]
I'm using Version **3.0.5621.4**
I'm using it from official docker image (image name : **emby/embyserver:latest** ; id : **91dfda99bbbb**)

Whenever I browse the web interface, I keep getting the message **"Argument cannot be null. Parameter name: appVersion"**. Here is an example:

![emby-error-appversion-null](https://cloud.githubusercontent.com/assets/199364/7898716/0b80cb02-0709-11e5-9337-83f349a02677.png)

I had at that point no idea what version was missing or where.

I investigated the logs and found:
```
2015-05-30 20:23:15.4725 Error - DtoUtils: ServiceBase<TRequest>::Service Exception
        *** Error Report ***
        Version: 3.0.5621.4
        Command line: /opt/emby-server/MediaBrowser.Server.Mono.exe -programdata /config -ffmpeg /usr/bin/ffmpeg -ffprobe /usr/bin/ffprobe
        Operating system: Unix 3.13.0.32
        Processor count: 4
        64-Bit OS: True
        64-Bit Process: True
        Program data path: /config
        Mono: 4.0.1 (tarball Tue May 26 04:28:10 UTC 2015)
        Application Path: /opt/emby-server/MediaBrowser.Server.Mono.exe
        Argument cannot be null.
        Parameter name: appVersion
        System.ArgumentNullException
          at MediaBrowser.Server.Implementations.Session.SessionManager+<LogSessionActivity>c__async1.MoveNext () [0x00000] in <filename unknown>:0
        --- End of stack trace from previous location where exception was thrown ---
          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0
          at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0
          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0
          at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0
          at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[MediaBrowser.Controller.Session.SessionInfo].GetResult () [0x00000] in <filename unknown>:0
          at MediaBrowser.Api.BaseApiService+<GetSession>c__async0.MoveNext () [0x00000] in <filename unknown>:0
```

That leds me to look at the `SessionManager.cs` class and found line 228: https://github.com/MediaBrowser/MediaBrowser/blob/master/MediaBrowser.Server.Implementations/Session/SessionManager.cs#L228

By watching the code, I found that the doc description of the parameter `appName` was **Type of the client.**. Thus I found that the version was the version of the client (here my web browser...).

So let me describe my installation :

(A : client host with web browser) ---- ( INTERNET ) ---- (B : serveur with docker) --- (C : web server nginx docker container serving all vhosts for server B) ---- (D: emby docker container)

**A** have Firefox 38.0.1 if that matters
**C** serve content for a lot of different servers on different vhosts, mainly docker images
**C** reverse proxy sub sites per vhosts.
**D** only sees connexion from host **C**

When I connect to the dash board, I can see "Unknown device", "Unknown version" in the section "Active Devices".

My guess is that nginx reverse proxy mess with browser detection, and the class SessionManager can't handle it.

I tried the following configuration:

(A : client host with web browser) ---- ( INTERNET ) ---- (B : serveur with docker) --- (E : squid proxy) ---- (D: emby docker container)

This time **firefox** version **38.0.1** is recognized by emby in "Active Devices" section, and I don't get thoses messages.

I do want to serve the web content throught nginx (for https + vhosts).

**Comment by LukePulverenti** [comment]
Thanks. Please see http://emby.media/community/index.php?/topic/790-how-to-report-a-problem/

**Comment by gissehel** [comment]
(Sorry, I validated the issue too soon, I'm currently writing the details)

**Comment by gissehel** [comment]
I investigated further what were the differences between http header in the case that worked and the case that didn't work.

I tested the same network configurations  but with a node (F: standard ubuntu docker container) instead of (D: emby docker container) and I ran a netcat process in listening mode on port 8096 in that ubuntu in order to capture de http request received on both sides, here is what I got:

http header threw nginx:
```
GET / HTTP/1.1
Host: host.example.com
X-Real-IP: 203.0.113.12
X-Scheme: http
REMOTE_ADDR: 203.0.113.12
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Cookie: _ga=GA1.2.236248100.1432991156
Authorization: Basic Xxxxxxxxxxxxxxxxxxxxxx==
```

http header threw squid:
```
GET / HTTP/1.1
Host: 172.17.1.196:8096
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Cache-Control: max-age=259200
Connection: keep-alive
```

It doesn't seem obvious to me why in the first case emby server won't recognize a firefox/38.0 client while it would in the second case.

**Comment by LukePulverenti** [comment]
There should be more headers - X-MediaBrowser-Token. Also, The Authorization header is passed from the Emby client, so it looks like that is getting lost through the proxy perhaps?

**Comment by gissehel** [comment]
`X-MediaBrowser-Token` can't be here because I didn't connect on emby, just on an netcat process. I wanted to test mainly if nginx was droping or altering the User-Agent header.

But I'll try to sniff the header received by emby in both cases.

**Comment by gissehel** [comment]
Ok, I've done the same things in emby threw both ways to connect (going on the server, login, diplaying the dashboard).

Here are the matching http headers:

Using nginx:

```
GET /web/dashboard.html HTTP/1.1
Host: host.example.com
X-Real-IP: 203.0.113.12
X-Scheme: http
REMOTE_ADDR: 203.0.113.12
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Accept: text/html, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://host.example.com/web/login.html
Authorization: Basic Y29tbW9uOmNvbWRhbnBhcw==
Cache-Control: max-age=259200
```

```
GET /Notifications/c7e6145e86b746afa4fa8f72779b690a/Summary HTTP/1.1
Host: host.example.com
X-Real-IP: 203.0.113.12
X-Scheme: http
REMOTE_ADDR: 203.0.113.12
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Authorization: Basic Xxxxxxxxxxxxxxxxxxxxxx==
X-MediaBrowser-Token: 61143104c708463cb02b32a0d5730a9a
Referer: http://host.example.com/web/dashboard.html
Cache-Control: max-age=259200
```

Using squid:

```
GET /web/dashboard.html HTTP/1.1
Host: 172.17.1.252:8096
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Accept: text/html, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://172.17.1.252:8096/web/login.html
Cache-Control: max-age=259200
Connection: keep-alive
```

```
GET /Notifications/c7e6145e86b746afa4fa8f72779b690a/Summary HTTP/1.1
Host: 172.17.1.252:8096
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Authorization: MediaBrowser Client="Emby Web Client", Device="Firefox 38.0", DeviceId="15ae165d00dc13427e3eb2f0733ae6ba6e301bd0", Version="3.0.5621.4", UserId="c7e6145e86b746afa4fa8f72779b690a"
X-MediaBrowser-Token: 2b60625ddc9346c18f4cd2dc5dd0fd7b
Referer: http://172.17.1.252:8096/web/dashboard.html
Cache-Control: max-age=259200
Connection: keep-alive
```

It seems now the problem lie in the line:
```
Authorization: MediaBrowser Client="Emby Web Client", Device="Firefox 38.0", DeviceId="15ae165d00dc13427e3eb2f0733ae6ba6e301bd0", Version="3.0.5621.4", UserId="c7e6145e86b746afa4fa8f72779b690a"
```

that is not present with the nginx version because nginx is configured to add it's own authentication layer.

**Comment by gissehel** [comment]
I've disabled all authentification trought nginx and I don't have the problem anymore.

**Comment by LukePulverenti** [comment]
Well to make things easier anyway, the server will start using X-Emby-Authorization with the next release. I will get the info out to app developers as well.
