### ISSUE TITLE
Emby isn't showing all medias

### ISSUE THREAD

**Issue by frantzz** [MediaBrowser/Emby#1115]
Hi there,
I have a folder which contains TV shows and Movies but only few shows/movies are shown, not all.
I run Emby Server on a Debian 7 x64 dedicated server and I also set a chmod 777 on all of my medias but it didn't fix the issue.
I set up my library using the last option "Non défini (contenu mélangé)" (in french).
Any ideas ?

**Comment by LukePulverenti** [comment]
Can you give an example? What content type did you select when adding it to the library?

**Comment by frantzz** [comment]
Hi. After a re-installation and few updates the issue is resolved.

**Comment by LukePulverenti** [comment]
Great, thanks for responding.
