### ISSUE TITLE
Centos 6 refusing to update

### ISSUE THREAD

**Issue by kdogisthebest** [MediaBrowser/Emby#1120]
My current version of Emby is Version 3.0.5607.2. I just installed it today and the home screen says a new version is available: 3.0.5641.4

I am unable to update to this version via yum even after using:
sudo yum-config-manager --enable MediaBrowserServer-Beta

I do have a problem with the current version. When try to edit Cinema Mode (/emby/web/cinemamodeconfiguration.html) I receive an error: "Sequence contains no matching element" and the settings don't save. I was hoping an updated version would clear this up because even reinstalling does not solve this.

**Comment by LukePulverenti** [comment]
We have a brand new CentOS package on the website. Please try that.
