### ISSUE TITLE
Add opus codec support

### ISSUE THREAD

**Issue by afics** [MediaBrowser/Emby#1126]

**Comment by LukePulverenti** [comment]
Do you mean for the server to handle audio files encoded with opus, or to transcode to opus when delivering to clients?

**Comment by afics** [comment]
I meant the first, but both, if it would make sense to deliver opus to the clients (at least android supports it).

**Comment by LukePulverenti** [comment]
.opus file extension?

**Comment by afics** [comment]
Yes.

**Comment by LukePulverenti** [comment]
It will be in the next android release.
