### ISSUE TITLE
Please support customizing ignoring rules for file names, including sample files.

### ISSUE THREAD

**Issue by hkenneth** [MediaBrowser/Emby#1139]
I know right now Emby ignores any file with ".sample." in its file name. However this is far less than enough. Many sample files are simply named differently and renaming all of them would be a tedious job especially for users migrating from other media servers. (I have tons of these files all named "Sample.mkv"). It would be really nice if Emby allows users to customize the ignoring rules - for example: using regex to filter file names with certain pattern, or setting a threshold of file size to limit the selection of sample files.

**Comment by ljani** [comment]
I agree. It would be nice to manually add [EpisodeExpressions](https://github.com/MediaBrowser/MediaBrowser.Naming/blob/1234b19990087e9036fded87bce536b97b4e1cbb/MediaBrowser.Naming/Common/EpisodeExpression.cs) too via some `advancedsettings.xml` file, similar to Kodi.

**Comment by LukePulverenti** [comment]
There's three new hidden config switch options coming in emby server 4.3:
https://emby.media/community/index.php?/topic/72655-41026-where-is-iresolverignorerule/?p=801014

These will require manually editing config file, but I'm happy to expose them in the UI if there's enough demand.
