### ISSUE TITLE
Support parsing XmlTV

### ISSUE THREAD

**Issue by LukePulverenti** [MediaBrowser/Emby#1144]
Create a standalone c# portable class library that can parse xmltv into an object, for use with our Live TV feature. This will allow us to support many more sources for guide information.

**Comment by ScottIsAFool** [comment]
Information and schema: http://wiki.xmltv.org/index.php/XMLTVFormat

**Comment by nightexcessive** [comment]
What is the minimum that this parser needs to expose?

**Comment by LukePulverenti** [comment]
Hi, here's our ProgramInfo object:

https://github.com/MediaBrowser/Emby/blob/master/MediaBrowser.Controller/LiveTv/ProgramInfo.cs

So basically as much of that data as possible. But you don't need to limit based on current emby server requirements. If there's interesting data available that we're currently not using, it could give us food for thought for future enhancements.
