### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by muhahacz** [MediaBrowser/Emby#1147]
Hi, i found in log some errors,..  Emby doesnt work as expected, 
Im using this repo:
deb http://download.opensuse.org/repositories/home:/emby/xUbuntu_15.04/ /
Well, they are not even in this package:
 https://github.com/MediaBrowser/Emby.Releases/raw/master/Server/MediaBrowser.Mono.zip 

2015-07-26 19:18:00.4570 Error - HttpServer: Error processing request for /web/web-animations-next-lite.min.js.map
        *** Error Report ***
        Version: 3.0.5675.1
        Command line: /opt/emby-server/MediaBrowser.Server.Mono.exe -programdata /var/lib/emby-server
        Operating system: Unix 3.19.0.22
        Processor count: 4
        64-Bit OS: True
        64-Bit Process: True
        Program data path: /var/lib/emby-server
        Mono: 4.0.1 (tarball Tue Jun  2 13:33:00 UTC 2015)
        Application Path: /opt/emby-server/MediaBrowser.Server.Mono.exe
        Could not find file "/opt/emby-server/dashboard-ui/web-animations-next-lite.min.js.map".
        ServiceStack.HttpError
        No Stack Trace Available

2015-07-26 19:18:00.5201 Error - HttpServer: Error processing request for /web/scripts/jquery.min.map
        *** Error Report ***
        Version: 3.0.5675.1
        Command line: /opt/emby-server/MediaBrowser.Server.Mono.exe -programdata /var/lib/emby-server
        Operating system: Unix 3.19.0.22
        Processor count: 4
        64-Bit OS: True
        64-Bit Process: True
        Program data path: /var/lib/emby-server
        Mono: 4.0.1 (tarball Tue Jun  2 13:33:00 UTC 2015)
        Application Path: /opt/emby-server/MediaBrowser.Server.Mono.exe
        Could not find file "/opt/emby-server/dashboard-ui/scripts/jquery.min.map".
        ServiceStack.HttpError
        No Stack Trace Available

ls -lha /opt/emby-server/dashboard-ui:
about.html                    css                      forgotpassword.html      livetvchannels.html       login.html              musicrecommended.html        plugincatalog.html      syncjob.html              userprofiles.html
addplugin.html                dashboardgeneral.html    forgotpasswordpin.html   livetvguide.html          metadataadvanced.html   musicvideos.html             plugins.html            syncsettings.html         voice
advanced.html                 dashboardhosting.html    gamegenres.html          livetvitems.html          metadata.html           mypreferencesdisplay.html    reports.html            themes                    vulcanize-in.html
apiclient                     dashboard.html           games.html               livetvnewrecording.html   metadataimages.html     mypreferenceshome.html       scheduledtask.html      thirdparty                vulcanize-out.html
appservices.html              device.html              gamesrecommended.html    livetvprogram.html        metadatanfo.html        mypreferenceslanguages.html  scheduledtasks.html     tvgenres.html             wizardagreement.html
autoorganizelog.html          devices.html             gamestudios.html         livetvrecording.html      metadatasubtitles.html  myprofile.html               scripts                 tvlatest.html             wizardfinish.html
autoorganizetv.html           devicesupload.html       gamesystems.html         livetvrecordinglist.html  moviegenres.html        mysync.html                  secondaryitems.html     tvpeople.html             wizardlibrary.html
bower_components              dlnaprofile.html         index.html               livetvrecordings.html     moviepeople.html        mysyncjob.html               selectserver.html       tvrecommended.html        wizardservice.html
channelitems.html             dlnaprofiles.html        itembynamedetails.html   livetvseriestimer.html    movies.html             notificationlist.html        serversecurity.html     tvshows.html              wizardsettings.html
channelsettings.html          dlnaserversettings.html  itemdetails.html         livetvseriestimers.html   moviesrecommended.html  notificationsetting.html     shared.html             tvstudios.html            wizardstart.html
channels.html                 dlnasettings.html        itemlist.html            livetvsettings.html       moviestudios.html       notificationsettings.html    songs.html              tvupcoming.html           wizarduser.html
channelslatest.html           edititemmetadata.html    kids.html                livetvstatus.html         movietrailers.html      nowplaying.html              streamingsettings.html  useredit.html
cinemamodeconfiguration.html  encodingsettings.html    library.html             livetvsuggested.html      musicalbumartists.html  photos.html                  supporter.html          userlibraryaccess.html
collections.html              episodes.html            librarypathmapping.html  livetvtimer.html          musicalbums.html        playbackconfiguration.html   supporterkey.html       usernew.html
connectlogin.html             favicon.ico              librarysettings.html     livetvtimers.html         musicartists.html       playlistedit.html            support.html            userparentalcontrol.html
cordova                       files                    livetvchannel.html       log.html                  musicgenres.html        playlists.html               syncactivity.html       userpassword.html

**Comment by LukePulverenti** [comment]
That's not an error. web-animations-next-lite.min.js.map is only requested when you open the chrome console. Do you have an actual problem?

**Comment by muhahacz** [comment]
I'm getting a weird  formatting. Movies, that has more than one string name shows merged on dashboard.
http://postimg.org/image/5wi8vc1qn/

**Comment by muhahacz** [comment]
Well, I guess this is a problem.... !? 

2015-07-26 20:40:19.2070 Error - App: Error getting response from http://img.omdbapi.com/?i=tt2899956&apikey=82e83907
        *** Error Report ***
        Version: 3.0.5675.1
        Command line: /opt/emby-server/MediaBrowser.Server.Mono.exe -programdata /var/lib/emby-server
        Operating system: Unix 3.19.0.22
        Processor count: 4
        64-Bit OS: True
        64-Bit Process: True
        Program data path: /var/lib/emby-server
        Mono: 4.0.1 (tarball Tue Jun  2 13:33:00 UTC 2015)
        Application Path: /opt/emby-server/MediaBrowser.Server.Mono.exe
        The remote server returned an error: (404) Not Found.
        System.Net.WebException
          at System.Net.HttpWebRequest.CheckFinalStatus (System.Net.WebAsyncResult result) [0x00000] in <filename unknown>:0 
          at System.Net.HttpWebRequest.SetResponseData (System.Net.WebConnectionData data) [0x00000] in <filename unknown>:0

**Comment by LukePulverenti** [comment]
No not really. The server wil handle that and continue marching on. But we need to know why your movies didn't get images. Best thing to do is add a new movie, then post the complete log from the time you added it. Thanks.

**Comment by muhahacz** [comment]
Well, it is working now. I purged whole emby installation, i should have messed up metadata library.
In default, can i just delete the /var/lib/emby-server/metadata folder to delete/restore my library?
Thanks
