### ISSUE TITLE
roboto fonts in the wrong dir

### ISSUE THREAD

**Issue by gardar** [MediaBrowser/Emby#1150]
2015-08-09 16:12:33.9242 Error - HttpServer: Error processing request for /web/css/fonts/Roboto/RobotoMedium.woff
	*** Error Report ***
	Version: 3.0.5675.1
	Command line: /opt/emby-server/MediaBrowser.Server.Mono.exe -programdata /var/lib/emby-server
	Operating system: Unix 3.16.0.4
	Processor count: 4
	64-Bit OS: False
	64-Bit Process: False
	Program data path: /var/lib/emby-server
	Mono: 4.0.1 (tarball Tue Jun  2 13:33:39 UTC 2015)
	Application Path: /opt/emby-server/MediaBrowser.Server.Mono.exe
	Could not find a part of the path "/opt/emby-server/dashboard-ui/css/fonts/Roboto/RobotoMedium.woff".
	ServiceStack.HttpError
	No Stack Trace Available

the roboto fonts are in /opt/emby-server/dashboard-ui/css/fonts/roboto

copying the dir from Roboto to roboto gets rid of this error.
Not sure if it's just the debian package that's affected.

**Comment by LukePulverenti** [comment]
Thanks. Resolved for next release.
