### ISSUE TITLE
[Suggestions] for the Webview / Webplayer / Webinterface (Loved child has many names)

### ISSUE THREAD

**Issue by karbowiak** [MediaBrowser/Emby#1153]
I posted these on the forum aswell
here http://emby.media/community/index.php?/topic/24346-req-on-desktop-move-side-menu-to-navbar-instead-with-dropdown-menus-and-make-menubar-static/ and here http://emby.media/community/index.php?/topic/24165-req-forwardrewing-arrow-keys-and-show-video-title-in-titletitle/

1. Forward/Rewind using the arrowkeys, in ~10 second increments
2. Showing the view / video title in the <title></title> tags, so the title bar of the window changes.
3. Moving the sidebar to the top navbar, and making it into navbar items / navbar dropdowns
4. Making the navbar static, so it doesn't disappear when scrolling down on the page.

3 and 4 are only for desktop, not mobile. The hamburgermenu makes perfect sense on mobile, but little sense on desktop where we have the extra screen real estate available.

**Comment by LukePulverenti** [comment]
Emby Theater has 1 & 2. The regular web client will get those once it has the same video player. 3 isn't going to happen. The menu is dynamic with user generated content, therefor we can't predict how many items there are going to be. 4 is done for the administrative side.
