### ISSUE TITLE
XBMCmetadata\BaseNfoParser - trim imdb url in .nfos without trailing slash

### ISSUE THREAD

**Issue by atcronin** [MediaBrowser/Emby#1160]
some nfos contain an imdb url without a trailing slash. so the imdbId ends up being invalid..
add additional separators to split at the end of the imdb url.

       private void ParseProviderLinks(T item, string xml)
        {
            char[] seperators = new char[] { '/', ' ', '\r', '\n' };
            var imdbId = xml.Split(seperators)
                .FirstOrDefault(i => i.StartsWith("tt", StringComparison.OrdinalIgnoreCase));

            if (!string.IsNullOrWhiteSpace(imdbId))
            {
                item.SetProviderId(MetadataProviders.Imdb, imdbId);
            }

            // TODO: Support Tmdb
            // http://www.themoviedb.org/movie/36557
        }

**Comment by atcronin** [comment]
I made these changes to BaseNfoParser and my movie library imported with <0.5% movies not getting internet metadata loaded, where previously it was closer to a 20% failure rate.


        private void Fetch(LocalMetadataResult<T> item, string metadataFile, XmlReaderSettings settings, CancellationToken cancellationToken)
        {
            if (!SupportsUrlAfterClosingXmlTag)
            {
                using (var streamReader = BaseNfoSaver.GetStreamReader(metadataFile))
                {
                    // Use XmlReader for best performance
                    using (var reader = XmlReader.Create(streamReader, settings))
                    {
                        reader.MoveToContent();
                        // Loop through each element
                        while (reader.Read())
                        {
                            cancellationToken.ThrowIfCancellationRequested();

                            if (reader.NodeType == XmlNodeType.Element)
                            {
                                FetchDataFromXmlNode(reader, item);
                            }
                        }
                    }
                }
                return;
            }

            using (var streamReader = BaseNfoSaver.GetStreamReader(metadataFile))
            {
                // Need to handle a url after the xml data
                // http://kodi.wiki/view/NFO_files/movies

                var xml = streamReader.ReadToEnd();

                //Find last closing Tag
                var index = xml.LastIndexOf(@"</");

                //If closing tag exists, move to end of Tag
                if (index != -1)
                {
                    index = xml.LastIndexOf('>', index);
                }

                if (index != -1)
                {
                    
                    var endingXml = xml.Substring(index);

                    ParseProviderLinks(item.Item, endingXml);

                    // If the file is just an imdb url, don't go any further
                    if (index == 0)
                    {
                        return;
                    }

                    xml = xml.Substring(0, index + 1);
                }
                else
                {
                    // If the file is just an Imdb url, handle that

                    ParseProviderLinks(item.Item, xml);

                    return;
                }

                using (var ms = new MemoryStream())
                {
                    var bytes = Encoding.UTF8.GetBytes(xml);

                    ms.Write(bytes, 0, bytes.Length);
                    ms.Position = 0;

                    // Use XmlReader for best performance
                    using (var reader = XmlReader.Create(ms, settings))
                    {
                        //Catch error reading invalid xml data
                        try
                        {
                            reader.MoveToContent();

                            // Loop through each element
                            while (reader.Read())
                            {
                                cancellationToken.ThrowIfCancellationRequested();

                                if (reader.NodeType == XmlNodeType.Element)
                                {
                                    FetchDataFromXmlNode(reader, item);
                                }
                            }

                        }
                        catch (XmlException)
                        {
                            Logger.Log(LogSeverity.Error, "Error Parsing XML in: " + metadataFile);
                        }
                        
                    }

                }
            }
        }

        private void ParseProviderLinks(T item, string xml)
        {
            //Split on trailing slash and blank space or new line
            char[] seperators = new char[] { '/', ' ', '\r', '\n' };
            var imdbId = xml.Split(seperators)
                .FirstOrDefault(i => i.StartsWith("tt", StringComparison.OrdinalIgnoreCase));

            if (!string.IsNullOrWhiteSpace(imdbId))
            {
                item.SetProviderId(MetadataProviders.Imdb, imdbId);
            }

            // TODO: Support Tmdb
            // http://www.themoviedb.org/movie/36557
        }

**Comment by LukePulverenti** [comment]
Can you provide test cases that don't work with the current code? Thanks.

**Comment by atcronin** [comment]
a "/" in front of the name means the nfo did not have a trailing slash in
the imdb url - the majority of failures.
a "x" means it did have a trailing slash so something else was the problem,
usually stray <'s, or unusual characters that throw a xml exception.

/ 9 April
x 21
x 21 Grams
/ 22 Jump street
/ 47 Ronin
x Almost Famous
x Back to the future
x Blade Runner
x Blown Away
x Coherence
x Der Untergang
x Fast and Furious 6
x Friends with Benefits

**Comment by atcronin** [comment]
Might also change the imdbId detection method to use a regex match, or at
least check the id is numeric, as a few of the remaining failures are for
nfos that contain a "tt" that is not part of the imdb url.

**Comment by atcronin** [comment]
a better imdb id finder

        //Add using System.Text.RegularExpressions;
        private void ParseProviderLinks(T item, string xml)
        {
            //Look for a match for the Regex pattern "tt" followed by 7 digits
            System.Text.RegularExpressions.Match m = 
                System.Text.RegularExpressions.Regex.Match(xml, @"tt([0-9]{7})", 
                System.Text.RegularExpressions.RegexOptions.IgnoreCase);
            if (m.Success)
            {
                item.SetProviderId(MetadataProviders.Imdb, m.Value);
            }

            // TODO: Support Tmdb
            // http://www.themoviedb.org/movie/36557
        }

**Comment by atcronin** [comment]
Another slight change to correct my mistake finding closing bracket. 
using IndexOf instead of LastIndexOf.

            using (var streamReader = BaseNfoSaver.GetStreamReader(metadataFile))
            {
                // Need to handle a url after the xml data
                // http://kodi.wiki/view/NFO_files/movies

                var xml = streamReader.ReadToEnd();

                //Find last closing Tag
                var index = xml.LastIndexOf(@"</");

                //If closing tag exists, move to end of Tag
                if (index != -1)
                {
                    index = xml.IndexOf('>', index);
                }

                if (index != -1)
                {

**Comment by LukePulverenti** [comment]
Can you provide a couple test nfo files that fail with the current code? thanks.

**Comment by atcronin** [comment]
http://1drv.ms/1hherfL

**Comment by atcronin** [comment]
puzzle-fourbrothers-bd5.nfo contains the string "tttiijLL"
so trying to find an imdb id with splits on {'\', ' ', '\r', '\n'} fails, whereas the regex pattern match works of course.

**Comment by atcronin** [comment]
an import on [21.2008.1080p.BluRay.x264.DTS-HD.MA5.1.SiMPLE.nfo] produces this error.

2015-08-28 02:25:17.3680 Error - App: Error in Nfo
	*** Error Report ***
	Version: 3.0.5675.1
	Command line: C:\Users\Andrew\AppData\Roaming\Emby-Server\System\MediaBrowser.ServerApplication.exe
	Operating system: Microsoft Windows NT 6.2.9200.0
	Processor count: 4
	64-Bit OS: True
	64-Bit Process: False
	Program data path: C:\Users\Andrew\AppData\Roaming\Emby-Server
	Application Path: C:\Users\Andrew\AppData\Roaming\Emby-Server\System\MediaBrowser.ServerApplication.exe
	Data at the root level is invalid. Line 1, position 1.
	System.Xml.XmlException
	   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
	   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
	   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
	   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
	   at System.Xml.XmlTextReaderImpl.Read()
	   at System.Xml.XmlReader.MoveToContent()
	   at MediaBrowser.XbmcMetadata.Parsers.BaseNfoParser`1.Fetch(LocalMetadataResult`1 item, String metadataFile, XmlReaderSettings settings, CancellationToken cancellationToken)
	   at MediaBrowser.XbmcMetadata.Parsers.BaseNfoParser`1.Fetch(LocalMetadataResult`1 item, String metadataFile, CancellationToken cancellationToken)
	   at MediaBrowser.XbmcMetadata.Providers.BaseVideoNfoProvider`1.Fetch(LocalMetadataResult`1 result, String path, CancellationToken cancellationToken)
	   at MediaBrowser.XbmcMetadata.Providers.BaseNfoProvider`1.<GetMetadata>d__0.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
	   at MediaBrowser.Providers.Manager.MetadataService`2.<RefreshWithProviders>d__32.MoveNext()

**Comment by LukePulverenti** [comment]
Thanks. I incorporated a couple things into the dev branch - the imdb regex, and the indexOf change on the closing tag. I also made sure not to fail the provider on xml exceptions since these are not valid xml anyway. I tested with your blade runner sample and it worked perfectly.
