### ISSUE TITLE
Emby offers trancoding while having Transcode disabled

### ISSUE THREAD

**Issue by HazCod** [MediaBrowser/Emby#1161]
Users with a non-beefy CPU should be able to disable transcoding for web-interface and server.
Personally, I am using videoJS at the moment where a very large subset can be played without any transcoding. [Example code here](https://github.com/HazCod/Gunther/blob/master/application/views/media/watch.php)
(I set type to video/mp4 as this tricks browsers into playing more formats.. I know)

**Comment by LukePulverenti** [comment]
We already have this on a per-user level. And the video player does some mp4 remapping already with content types for mkv, m4v, and mov. are there other types that will play that way?

**Comment by HazCod** [comment]
You do? I must have missed that one.
Checking back on this once I verified.
And Yeah, I testes with mkv.

**Comment by HazCod** [comment]
@LukePulverenti; where do you see this?

**Comment by psxlover** [comment]
Settings --> Users --> Select a user --> Allow video playback that requires transcoding

**Comment by HazCod** [comment]
Unrelated but funny enough; it fails to play Big Buck Bunny. :(

**Comment by HazCod** [comment]
To come back on this: ![https://i.imgur.com/Dsagm64.jpg](screen)

I disabled trancode sync and media transcode. I can still select lower resolutions instead of direct. Is this normal?

**Comment by HazCod** [comment]
thank you @LukePulverenti :+1:
