### ISSUE TITLE
"Played" checkbox doesn't work for whole seasons

### ISSUE THREAD

**Issue by karlshea** [MediaBrowser/Emby#1166]
Clicking the "Played" checkbox on either the season's thumbnail in the show season list or on the season's page doesn't mark all of the episodes as watched.

POST JSON in both cases is:

    {"PlayedPercentage":100,"UnplayedItemCount":0,"PlaybackPositionTicks":0,"PlayCount":0,"IsFavorite":false,"Played":true,"Key":"213221004"}

Nothing is output in the log file after the click.

**Comment by LukePulverenti** [comment]
I cannot reproduce this. Please let me know if the problem still occurs on the latest release.

**Comment by karlshea** [comment]
Still not working for me with 3.0.5724.6. Is there any information I could provide that would help with debugging?

**Comment by LukePulverenti** [comment]
Server log i suppose. For verification i am simply going to a season detail screen, clicking the checkmark, then refreshing the page, and all episodes now have checkmarks.

**Comment by karlshea** [comment]
Even with debug logging on there's nothing output when I click the watched checkbox on the season detail page. I checked the .nfo files for the unwatched episodes and they still say <watched>false</watched>

**Comment by LukePulverenti** [comment]
that doens't matter, please supply the whole thing anyway,. thanks.

**Comment by karlshea** [comment]
http://pastebin.com/JpdhH8cD

**Comment by LukePulverenti** [comment]
the request never even made it into the server. you can try checking the debugger inside the browser for errors. you can also try a different browser.

**Comment by karlshea** [comment]
This is the click Request:

```
POST /Users/378f394f550b4e4398c5af8ff545cb63/PlayedItems/2231ec6ae8174b8b25db3db19c3c6325? HTTP/1.1
Host: citywall.internal:8096
Connection: keep-alive
Content-Length: 0
Accept: application/json, text/javascript, */*; q=0.01
X-MediaBrowser-Token: aaea1a18944049299d47a8eb06d164d5
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
X-Emby-Authorization: MediaBrowser Client="Emby Web Client", Device="Chrome 45.0.2454.101", DeviceId="c00de97d96081ec370d8fc63efb538fcce8f9065", Version="3.0.5724.6", UserId="378f394f550b4e4398c5af8ff545cb63"
Origin: http://citywall.internal:8096
Referer: http://citywall.internal:8096/web/itemdetails.html?id=2231ec6ae8174b8b25db3db19c3c6325&context=tv
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8
Cookie: Cacti=h84peo9giqesomoqvvgn41lam2; clickedFolder=tree_1%5Etree_1_leaf_19%5Etree_1_leaf_8%5Etree_1_leaf_9%5Etree_1_leaf_7%5E; highlightedTreeviewLink=tree_1_leaf_7; mythweb_id=74btuv0ev50bvce6agjvneov57; template=phpsysinfo_bootstrap; _pk_id.1.d4f5=ab951938b8b957c8.1414720769.86.1433481130.1433173812.; TVView=poster; plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0
```

Response:

```
HTTP/1.1 200 OK
X-UA-Compatible: IE=Edge
X-Frame-Options: SAMEORIGIN
Vary: Accept-Encoding
X-Powered-By: ServiceStack/4.00 Unix/Mono
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Headers: Content-Type, Authorization, Range, X-MediaBrowser-Token, X-Emby-Authorization
Content-Encoding: deflate
Server: Mono-HTTPAPI/1.1
Content-Type: application/json; charset=utf-8
Date: Fri, 02 Oct 2015 20:12:28 GMT
Content-Length: 109
```

Response content:
```{"PlayedPercentage":90,"UnplayedItemCount":1,"PlaybackPositionTicks":0,"PlayCount":0,"IsFavorite":false,"Played":false,"Key":"273181001"}```

That's from Chrome 45.0.2454.101, it also doesn't work in Firefox 40.0.3

**Comment by LukePulverenti** [comment]
does it work if the season is already watched and you mark it unwatched?

**Comment by karlshea** [comment]
No, that doesn't seem to be an option? I have a season with every episode watched, and the checkmark on the detail page isn't a different color. I tried clicking it and it didn't toggle anything.

**Comment by karlshea** [comment]
Oh, my mistake. I thought the log was /var/logs/emby-server.log but it doesn't seem like that's the main thing. It looks like they are in /var/lib/emby-server/logs.

This is the latest log from there with debugging enabled: http://pastebin.com/ucCxY3TK

**Comment by LukePulverenti** [comment]
if every episode is watched, then just refresh the page, the season check mark should be red.

**Comment by karlshea** [comment]
It's not, every episode has a green checkmark badge and the season's checkmark at the top next to the thumbs and heart is white.

**Comment by LukePulverenti** [comment]
ok, do you have episodes directly in your series folder without season subfolders?

**Comment by karlshea** [comment]
None of the shows have season folders, is that the problem? I used to use MySQL with Kodi and never used season folders. I just recently moved over to Emby (month or so?) and had it just scan the directory that all of the show folders are in.

**Comment by LukePulverenti** [comment]
I see the issue, thank you. It will be resolved for the next release.

**Comment by karlshea** [comment]
Awesome! Thanks, I appreciate it!

**Comment by ajhix36** [comment]
I've been having same issue. And even if every episode in a season is watched, it does not update the season checkmark to red, it stays white.

None of my shows have season folders.

Pastebin: http://pastebin.com/mPkrRgtt

When I click Season "Played"
Requesting url without automatic networking: http://192.168.1.190:8096/emby/Users/5346e8b80b0b403b8a2ed0856e1bb840/PlayedItems/d593758f16b3fd622273e3719700d766

When I click Episode "Played"
Requesting url without automatic networking: http://192.168.1.190:8096/emby/Users/5346e8b80b0b403b8a2ed0856e1bb840/PlayedItems/c2d9acd2b0b444105452204e5288baa5
event.trigger websocketmessage

**Comment by karlshea** [comment]
This isn't fixed in 3.0.5768.7.

Am I misunderstanding what marking a season as watched means? My assumption is that it would mark every episode in that season with the watched flag. Some reading elsewhere leads me to believe that's not the case?

**Comment by karlshea** [comment]
Marking the whole show as watched does mark every episode as watched, none of the season buttons do it.

**Comment by ajhix36** [comment]
I tried using the phone app as well, same problems.
