### ISSUE TITLE
Subtitle downloader

### ISSUE THREAD

**Issue by danergo** [MediaBrowser/Emby#1171]
Subtitle downloader downloads subtitles from opensubtitles.org.
This works great, however these subtitles are encoded as ANSI ISOabcd-e (i.e. ISO-8859-2).
And they contain specific characters like 'á'.
These characters couldn't be played over DLNA and they substitued with '?' mark.

If I manually convert these subtitles into UTF8, everything works as intended.

So there should be an option in the subtitles downloader to select whether I want to re-encode them to UTF8. (linux equivalent command is like iconv -i ISO-8859-2 -o UTF8 subtitle.srt > subtitle.srt)

**Comment by rchovan** [comment]
Yes, I can confirm it. I use this in cron:
`````
find /data/ -iname "*.srt" -exec enca -x UTF-8 {} \;
`````

**Comment by Drol** [comment]
This is annoying. I've got a scheduled convert script too.

**Comment by anderbytes** [comment]
Any progress on this?
I had to disable subtitle download via Emby, because managing a script of this kind is ridiculous.  :-(

**Comment by nfnty** [comment]
A chardet library is perfect for this: https://github.com/superstrom/chardetsharp

Encode with 'UTF-8-SIG' for maximum performance.

**Comment by LukePulverenti** [comment]
We've already got the same thing:

https://github.com/MediaBrowser/UniversalDetector

We use it at the time of playback, not downloading.

**Comment by nfnty** [comment]
Nice, why not use it for both? Playback detection would be instant with `UTF-8-SIG`

**Comment by anderbytes** [comment]
Most subtitle download tools allow us to specify a parameter to determine the file encoding.
**Ex**: subliminal  ->     -e UTF-8

This means the OpenSubtitles API can receive a request to send the UTF-8 version of the file. This could be implemented in Emby subtitle download.

**Comment by anderbytes** [comment]
Is that difficult to implement? Even because it's already used in playback....

**Comment by LukePulverenti** [comment]
This is resolved for the next release of Emby Server, thanks.
