### ISSUE TITLE
Add DirectStream option alongside Disable Transcoding

### ISSUE THREAD

**Issue by HazCod** [MediaBrowser/Emby#1177]
For some users it may be a viable option to allow directstream but not allow transcoding for users.
This way, low-power CPUs can still do some type of conversion. (Directstream shouldn't take a lot of power)

**Comment by psxlover** [comment]
There 's an option in Settings --> Users --> (select a user) to "Allow video playback that requires transcoding" which you can turn of for each individual user. Isn't that what you are asking for?

**Comment by HazCod** [comment]
I believe you misunderstood. Currently we can only choose transcoding and directstreaming or nothing. While transcoding requires CPU power, directstreaming is not very taxing.

We could just allow directstream, but maybe for super -low-power boxes..idk

**Comment by HazCod** [comment]
Looking at https://github.com/MediaBrowser/Emby/blob/670e4ea31b2aa3e68f034f959f16d696a8afb6ae/MediaBrowser.WebDashboard/dashboard-ui/scripts/mediaplayer.js#L892, it seems that Emby does indeed offer directstreaming when transcoding is enabled as far as I can see. 

Can someone familiar with the code confirm?

**Comment by ebr11** [comment]
Yes, we will direct stream and that is not considered transcoding.
