### ISSUE TITLE
Emby (stable) does not see changes when switching to dev

### ISSUE THREAD

**Issue by HazCod** [MediaBrowser/Emby#1178]
Hi,

Installed emby-server from APT repositories.
In advanced config, I selected dev to test the changes in the git repo.
But when restarting (emby does not come back on by the way) or forcing the version check, Emby still lists the latest stable version as latest.

OS is debian x64.

**Comment by LukePulverenti** [comment]
This is going to be "fixed", although not in the way you're looking for. When the system isn't capable of self-updating the application, we're just going to have the label say "Automatic update level for plugins:". It is unlikely we will have this for linux and mac in the short term, so this will at least prevent users from reporting it's not working.

**Comment by HazCod** [comment]
I see. Is there any way to manually pull in dev?
I looked at installing from source too, but can't find anything about it in the docs for linux.
