### ISSUE TITLE
Auto-Organize: Series detection

### ISSUE THREAD

**Issue by softworkz** [MediaBrowser/Emby#1191]
Hi,

quite often I got situations where a series episode filename contains substrings that aren't eliminated out by the VideoParser's Clean method.

Example: "tvp-bones-S03E04.mkv"

After all processing, the series name is still "tvp-bones". As a consequence, the file cannot be auto-organized. And - even worse - all other incoming episode files will require manual interaction as well.
From my experience there are many other cases where the series name in the file does not match the series name in emby.

I have thought about two different solutions to this problem. The first one is easier to implement but might handle just a subset of the detection problems. The second one is more generic but involves a little bit more work:

1. deleted, was a bad idea

2. Fail initial detection like it is implemented at the moment. But: In the manual organize dialog add a  CheckBox option "In the future, organize all files containing 'tvp-bones' into the selected series"

**Comment by softworkz** [comment]
You are right thinking that 1 is stupid. Driven by maximized laziness to just solve my personal aspect of the problem.

Meanwhile I have implemented a prototype for 2 and would be interested in your comments...

**Comment by LukePulverenti** [comment]
Closing since this is covered by your pull request.
