### ISSUE TITLE
Trying to add a path - redirects to login screen

### ISSUE THREAD

**Issue by davegri** [MediaBrowser/Emby#1196]
I go to:
http://localhost:8096/web/library.html

movies > media locations (+) > I paste a path into the box and click "ok"

emby redirects me to login screen: http://localhost:8096/web/login.html

any idea whats going on?

**Comment by LukePulverenti** [comment]
There is an access problem. The server is unable to access the path you're attempting to add. The web interface is then mis-interpreting the access error as login access and bouncing you out. The bounce out has been fixed for the next server release. You can resolve the access error by ensuring the server process has access to that location.
