### ISSUE TITLE
No Trakt scrobbling when playing over chromecast

### ISSUE THREAD

**Issue by xsteadfastx** [MediaBrowser/Emby#1198]
Im pretty new to emby. I discovered a strange behaviour when im watching tv episodes over chromecast. The Episode gets marked as watched but this information doesnt get sent to trakt. If i unmark it and mark it again in the app or through web, it gets synced. Anything i can do about it?

**Comment by LukePulverenti** [comment]
Yes please look at the trakt plugin and see what needs to be done there:

https://github.com/MediaBrowser/Emby.Plugins/tree/master/Trakt

If it's getting marked watched correctly in the core server then it's most likely limited to the plugin.

**Comment by xsteadfastx** [comment]
i thought if its marked as watched its the same mechanism that scrobbles as if im watching it over web or app. my mono skills are really limited (zero ;-)) but i see if i can get my head around that plugin.

**Comment by LukePulverenti** [comment]
You don't need mono experience. you can test it on windows. if the content is getting marked correctly in the web interface, then the issue lies solely in the plugin.

**Comment by LukePulverenti** [comment]
There's been an update to the plugin that has resolved a few issues.
