### ISSUE TITLE
Your Chromecast reciever is unable to connect to your Emby Server

### ISSUE THREAD

**Issue by ineentho** [MediaBrowser/Emby#1206]
When I connect to the Chromecast through either the android app or web interface, the Emby app correctly starts on my chromecast and displays episode information. However, when I play a video a message pops up with "Your Chromecast reciever is unable to connect to your Emby Server".

Streaming to other computers works just fine however.

Running on arch, both through the official emby-server package and the emby-server-git package on AUR.
Server version: emby-server-3.0.5724.5-1

**Comment by LukePulverenti** [comment]
Please try again by rebooting your CC device and reconnecting from the casting app, thanks.

**Comment by ineentho** [comment]
It works now, thanks!

Did you change anything, I retried multiple times earlier.
