### ISSUE TITLE
Visual bug for some movies

### ISSUE THREAD

**Issue by nyanloutre** [MediaBrowser/Emby#1212]
As you can see on this picture, some info pages for movies are not displayed correctly. The poster is overlapping the text.

![image](https://cloud.githubusercontent.com/assets/7677321/10279284/9a6c73ba-6b64-11e5-8f9d-27fff59187b6.png)

**Comment by ebr11** [comment]
http://emby.media/community/index.php?/topic/26063-movie-poster-no-scaled-properly-when-dimensions-not-set-in-metadata-manager/

**Comment by nyanloutre** [comment]
Thanks !
