### ISSUE TITLE
Dlna server doesn't work after resuming to sleep.

### ISSUE THREAD

**Issue by psxlover** [MediaBrowser/Emby#1218]
When resuming from sleep dlna server doesn't resume broadcasting. In order for it to work you either have to restart the server or go to the settings and disable and then enable Dlna server.

**Comment by psxlover** [comment]
Unfortunately still an issue on Version 3.0.5875.28272.

**Comment by LukePulverenti** [comment]
The latest beta has a new upnp layer. This may be resolved as a result.

**Comment by LukePulverenti** [comment]
Can you try this on the latest beta? thanks !

**Comment by psxlover** [comment]
I think it's fixed, tnx.
