### ISSUE TITLE
Metadata manager adds new entry for recently unpacked rar-files instead of merging with parent

### ISSUE THREAD

**Issue by cyr** [MediaBrowser/Emby#1221]
This is all assuming archive files are not detected as movie files:

If a movie was packed in a rar-archive when emby started watching a movie folder, it still adds an entry in the metadata manager, while no movie is there (obviously).

If you then unpack the movie and refresh the earlier added entry in the metadata manager, it detects the movie file, but as its own separate entry under the initial one.

Is it possible to merge the initial entry somehow? This makes it much harder to see folders that are unidentified in the library.

**Comment by LukePulverenti** [comment]
It would have to follow the multi-version naming so that the rar file and the unpacked video are seen as two versions of the same video. See the section on multi-resolution naming:

https://github.com/MediaBrowser/Wiki/wiki/Movie%20naming

Or they can be merged in the UI using the video grouping feature.

**Comment by cyr** [comment]
Right, but I've seen this even when the rar files is NOT detected as a media file, i.e. in the metadata manager, only the folder is seen (but not identifiable, as it contains no media files). When I unpack the containing rar files, the new movie is contained within the folder, not "taking over" the folder as the movie.

**Comment by cyr** [comment]
Ah, actually, never mind. This seems to only be an issue when you are refreshing from the metadata manager. I looked now on the same movies that had these issues, but now they seem to have been merged. Could it be a difference between how a refresh from the metadata manager is handled, vs how a library scan functions?

**Comment by LukePulverenti** [comment]
Yes if you do something on the file system that causes an item to get deleted or have it's Id changed, then use the metadata manager with the old item before the server has noticed the change, then yes this could happen.
