### ISSUE TITLE
Cannot set local address.  If detection is wrong, chromecast fails.

### ISSUE THREAD

**Issue by deads2k** [MediaBrowser/Emby#1243]
The local address ("Settings > Server > Dashboard > Server Information > Local address"), is used by the server to describe how a client can contact it.  However, if the detection is incorrect there is no way manually set the value.

This is a problem because the local address is used to build a streaming URL for the chromecast.  

From this linked forum issue: http://emby.media/community/index.php?/topic/26905-chromecast-streaming-uses-local-address/

> I have connected to the emby server with the android app using 192.168.143.25. The local address for emby server seems to immutable and it is set to 172.17.0.44. The 172 address is not routable from the Chromecast.

> When I try to stream to the Chromecast, it tries to use the 172 address. Setting a DNAT rule in my router's iptables prerouting filter chain to force 172.17.0.43 to route to 192.168.143.25 allows the Chromecast to work.

**Comment by matthazinski** [comment]
I found a workaround on the server-side to just hardcode the remote address in chromecast.js.

Replace ```message.serverAddress = info.LocalAddress;```
with ```message.serverAddress = "http://remotehost.example.com:80";``` and it works.

**Comment by LukePulverenti** [comment]
If you use windows this is available on the dev server now for testing. Please try it out and report issues. Thanks.

**Comment by deads2k** [comment]
> If you use windows this is available on the dev server now for testing. Please try it out and report issues. Thanks

Fedora, but I'll update and give this a try this week.  Thanks.
