### ISSUE TITLE
Emby seems unable to find [REC] unless brackets are removed

### ISSUE THREAD

**Issue by Bodertz** [MediaBrowser/Emby#1245]
Possibly related to https://github.com/MediaBrowser/Emby/issues/598. If so, I'm not sure that just stripping anything in brackets is the right thing to do.

**Comment by ebr11** [comment]
That is a convention we've been using for many years and it works in 99% of cases.

I believe your issue can be solved by simply naming the movie "REC".

**Comment by ebr11** [comment]
At one point, we used to make a final attempt with the raw file system name if nothing was found with the previous attempts.  Restoring that may also solve this.

**Comment by Bodertz** [comment]
>That is a convention we've been using for many years and it works in 99% of cases.

Sure, there's probably not too many movies with brackets, but I was using Kodi's scraper before and it found it fine, so it didn't occur to me that it might be an issue elsewhere. I don't know if Kodi chokes on [tags], though. I don't use them.

>I believe your issue can be solved by simply naming the movie "REC".

I solved it already by clicking Identify and removing the brackets. But it took me a while to figure out why the poster image it chose was so poor (I think it fell back to a screenshot from the beginning of the movie), and why it couldn't find any better ones when I tried Edit Images.

>At one point, we used to make a final attempt with the raw file system name if nothing was found with the previous attempts. Restoring that may also solve this.

I think that's a good plan. I could rename this issue to that so you could tag it as a wish or whatever.
