### ISSUE TITLE
Access to other users media

### ISSUE THREAD

**Issue by RedshirtMB** [MediaBrowser/Emby#1247]
Hi. 
Making an API call to User/{id}/Items/Latest will return the most recent items regardless of whether or not the user has access to them if the LatestItemsQuery contains the Id of the root channels folder. 

I discovered this last night logged in with "User B" the call returned a bunch of stuff from "user A's" library.

**Comment by LukePulverenti** [comment]
If you're on dev or running from source it's only temporary while the database is undergoing some changes.

**Comment by LukePulverenti** [comment]
Apart from blocking by tags, library separation and parental controls should now be restored in latest dev. Please let me know if you any issues. Thanks.

**Comment by RedshirtMB** [comment]
Thanks. I'm back on the release build after a server reinstall. I'll keep an eye out after the next release build.
