### ISSUE TITLE
Browsing to /web/ causes error

### ISSUE THREAD

**Issue by NickBolles** [MediaBrowser/Emby#1248]
Browsing to <Server address>:port/web/ shows the following image
![image](https://cloud.githubusercontent.com/assets/7891759/10951268/32f4b124-8302-11e5-9689-e8aa680bc758.png)

Can this redirect to /web/index.html to avoid this error?

**Comment by LukePulverenti** [comment]
Yes it can but you can also just use / without the web

**Comment by NickBolles** [comment]
yea i guess this is basically just a 404. I guess I have just typed it in a few times accidentally and found myself "saying why doesn't it just go to the dashboard?" 

Actually I left some details out though. I was trying to do a reverse proxy to the /web/ url, but I found that that would not work anyways because of resources that are based off the root directory. 

So this really isn't an issue for me anymore
