### ISSUE TITLE
[BUG] The same files gets ffprobe'd on every library scan

### ISSUE THREAD

**Issue by karbowiak** [MediaBrowser/Emby#1256]
I've noticed that the same files gets ffprobed on every library scan, for some unknown reason.

This makes the library scan take extra long time, for something that it has essentially already done once - and shouldn't have to do again. :\

**Comment by LukePulverenti** [comment]
Only if the created or modified timestamp of the file changes, or the list of external subtitle files attached to the file changes.

**Comment by karbowiak** [comment]
That's it, there are so many files that gets ffprobed again and again, and none of them have a timestamp change - it has helped a lot since i told it to write nfo files, but there is still a ton of files that gets probed again.

Most of them related to the NFO bug, where you have multiple episodes in one file, eg: S01E01-E03 episodes #1255

**Comment by LukePulverenti** [comment]
Do you have a specific, concrete example?

**Comment by karbowiak** [comment]
Hm, seems the issue has vanished - now it's just the Kodi SyncQueue that re-adds files to the sync eventho they've already been synced, but that's a different problem.

I'll close this bug report, since it has gone away again /o\
