### ISSUE TITLE
No image is shown when scraping games

### ISSUE THREAD

**Issue by smidley** [MediaBrowser/Emby#1276]
When you try to identify a game, no image is shown for the possible matches even when an image is available on thegamesdb.

**Comment by LukePulverenti** [comment]
You can take a look at it here if you like and update the search method:

https://github.com/MediaBrowser/Emby.Plugins/tree/master/GameBrowser/Providers

If you're not able to do this you can also re-open a ticket there. I am closing this from here since it is not related to the core server.
