### ISSUE TITLE
Broken animations in dashboard home.

### ISSUE THREAD

**Issue by psxlover** [MediaBrowser/Emby#1292]
On server version 3.0.5809.40202 the cards in home would slide down as soon as they slide up (when having the mouse over a card) (this was with firefox, didn't try with chrome).

On server version 3.0.5811.4300 in **Firefox** the cards never slide down, leaving the extended information always on. If you mouse over a card that has been slided up before, the animation resets and slides up again.

**Comment by LukePulverenti** [comment]
Thanks. As it's working with the native version in Chrome, I will probably just give it time and see if the polyfill gets updated and that takes care of it. If we get to the point of releasing and that doesn't happen, then I'll look into it.

**Comment by psxlover** [comment]
This seems to have been fixed. I've had a couple of instances where the animation didn't work properly, but since I can't reproduce it I'm closing this.
