### ISSUE TITLE
[DLNA] Add an option to select the interface / ip to bind to

### ISSUE THREAD

**Issue by karbowiak** [MediaBrowser/Emby#1302]
Currently it automatically selects an interface to bind to, which in my case (and others most likely too) is the wrong interface.

Being able to manually select the interface would be awesome!

**Comment by LukePulverenti** [comment]
Actually let's go over a specific problem in detail if an interface is being missed. I don't really plan on doing an option unless it's something that's impossible to be handled automatically.

**Comment by ajbrown** [comment]
This is currently an issue for me.  I'm connected to a VPN, and Emby is reporting it's IP address as the VPN's internal IP address.  When my device tries to connect via Emby Connect, it does so using the VPN internal IP address.  Since it's not on the same VPN as Emby, it can't connect.

Obviously this could be fixed by taking the Emby server off the VPN, but for my current setup (with many media-related services running on the same machine) that's not desirable.  If I could force Emby to bind to the LAN interface, that would solve it as well.

This is on Windows.

**Comment by LukePulverenti** [comment]
Hi @ajbrown do you mean to say that Emby Server is reporting the internal VPN address as the remote address? If yes, then go to Advanced -> Hosting and you can manually override your external address.

**Comment by ajbrown** [comment]
From my LAN through the Emby App, it's showing the VPN internal address (172.x.x.x) instead of the LAN address (192.x.x.x).

I don't seem to have the option to override the external address.  I'm on `3.1.11.0`

**Comment by ajbrown** [comment]
As a workaround, I shut down the VPN, restarted Emby, then reconnected to the VPN.   It's now reporting the LAN IP for local access.  I'll see how it handles any restarts or reconnects going forward and report back.

It would be nice to be able to force an interface for the advanced users, though.  Even if it's a hidden setting somewhere :-)

**Comment by ajbrown** [comment]
Emby ended up reporting the VPN internal address to Emby Connect after a while. I had to turn off the VPN in order or fix it.

It's definitely an advanced scenario, but seems this would be a problem in any multi network setup.

I guess there are a few options:
- allow secifying the interface to bind to
- allow overriding or preferring the internal address advertised to Emby Connect
- advertise all internal addresses to Emby connect, and update apps so they try the next address if they fail to connect.

If this something I can help with, let me know.

**Comment by LukePulverenti** [comment]
I've added the ability to enter an ip address to bind to. You can help test it here:

http://emby.media/community/index.php?/topic/35687-3113-bind-to-local-ip-address/

Thanks.

**Comment by m5x** [comment]
Sorry for reviving this issue but is it really solved? I run Emby on Synology Diskstation with many network interfaces and DLNA devices on the network are not detected at all. I tried setting the IP address in Settings -> Advanced -> Hosting to force DLNA to work with specific network interface that is connected to the subnet where all DLNA devices are connected to but this setting seems to only influence which IP address the HTTP server will respond on but it has no effect on which network interface is used for DLNA broadcasts.
