### ISSUE TITLE
Ubuntu Server 14.04 Crash

### ISSUE THREAD

**Issue by whackashoe** [MediaBrowser/Emby#1303]
Fresh install. Here's the log, it just repeats crashing in loop.

Info, Main, Emby
	Command line: /usr/lib/emby-server/bin/MediaBrowser.Server.Mono.exe -programdata /var/lib/emby-server -ffmpeg /usr/bin/ffmpeg -ffprobe /usr/bin/ffprobe -restartpath /usr/lib/emby-server/restart.sh
	Operating system: Unix 3.13.0.68
	Processor count: 8
	64-Bit OS: True
	64-Bit Process: True
	Program data path: /var/lib/emby-server
	Mono: 4.2.1 (Stable 4.2.1.102/6dd2d0d Thu Dec  3 04:04:55 UTC 2015)
	Application Path: /usr/lib/emby-server/bin/MediaBrowser.Server.Mono.exe
appHost.Init
Info, App, Application version: 3.0.5781.5
Info, App, Application configuration:
	{"EnableUPnP":true,"PublicPort":8096,"PublicHttpsPort":8920,"HttpServerPortNumber":8096,"HttpsPortNumber":8920,"EnableHttps":false,"EnableInternetProviders":true,"IsPortAuthorized":true,"SeasonZeroDisplayName":"Specials","SaveLocalMeta":false,"EnableLocalizedGuids":false,"DisableStartupScan":true,"EnableUserViews":false,"EnableLibraryMetadataSubFolder":false,"PreferredMetadataLanguage":"en","MetadataCountryCode":"US","SortReplaceCharacters":[".","+","%"],"SortRemoveCharacters":[",","&","-","{","}","'"],"SortRemoveWords":["the","a","an"],"MinResumePct":5,"MaxResumePct":90,"MinResumeDurationSeconds":300,"RealtimeLibraryMonitorDelay":40,"EnableDashboardResponseCaching":true,"EnableDashboardResourceMinification":true,"MergeMetadataAndImagesByName":false,"EnableStandaloneMetadata":false,"ImageSavingConvention":"Compatible","MetadataOptions":[{"ItemType":"Book","ImageOptions":[{"Type":"Backdrop","Limit":1,"MinWidth":1280}],"DisabledMetadataSavers":[],"LocalMetadataReaderOrder":[],"DisabledMetadataFetchers":[],"MetadataFetcherOrder":[],"DisabledImageFetchers":[],"ImageFetcherOrder":[]},{"ItemType":"Movie","ImageOptions":[{"Type":"Backdrop","Limit":1,"MinWidth":1280},{"Type":"Art","Limit":0,"MinWidth":0},{"Type":"Disc","Limit":0,"MinWidth":0},{"Type":"Primary","Limit":1,"MinWidth":0},{"Type":"Banner","Limit":0,"MinWidth":0},{"Type":"Thumb","Limit":1,"MinWidth":0},{"Type":"Logo","Limit":1,"MinWidth":0}],"DisabledMetadataSavers":[],"LocalMetadataReaderOrder":[],"DisabledMetadataFetchers":[],"MetadataFetcherOrder":[],"DisabledImageFetchers":[],"ImageFetcherOrder":[]},{"ItemType":"MusicVideo","ImageOptions":[{"Type":"Backdrop","Limit":1,"MinWidth":1280},{"Type":"Art","Limit":0,"MinWidth":0},{"Type":"Disc","Limit":0,"MinWidth":0},{"Type":"Primary","Limit":1,"MinWidth":0},{"Type":"Banner","Limit":0,"MinWidth":0},{"Type":"Thumb","Limit":1,"MinWidth":0},{"Type":"Logo","Limit":1,"MinWidth":0}],"DisabledMetadataSavers":[],"LocalMetadataReaderOrder":[],"DisabledMetadataFetchers":[],"MetadataFetcherOrder":[],"DisabledImageFetchers":[],"ImageFetcherOrder":[]},{"ItemType":"Series","ImageOptions":[{"Type":"Backdrop","Limit":1,"MinWidth":1280},{"Type":"Art","Limit":0,"MinWidth":0},{"Type":"Primary","Limit":1,"MinWidth":0},{"Type":"Banner","Limit":1,"MinWidth":0},{"Type":"Thumb","Limit":1,"MinWidth":0},{"Type":"Logo","Limit":1,"MinWidth":0}],"DisabledMetadataSavers":[],"LocalMetadataReaderOrder":[],"DisabledMetadataFetchers":[],"MetadataFetcherOrder":[],"DisabledImageFetchers":[],"ImageFetcherOrder":[]},{"ItemType":"MusicAlbum","ImageOptions":[{"Type":"Backdrop","Limit":0,"MinWidth":1280},{"Type":"Disc","Limit":0,"MinWidth":0}],"DisabledMetadataSavers":[],"LocalMetadataReaderOrder":[],"DisabledMetadataFetchers":[],"MetadataFetcherOrder":[],"DisabledImageFetchers":[],"ImageFetcherOrder":[]},{"ItemType":"MusicArtist","ImageOptions":[{"Type":"Backdrop","Limit":1,"MinWidth":1280},{"Type":"Banner","Limit":0,"MinWidth":0},{"Type":"Art","Limit":0,"MinWidth":0},{"Type":"Logo","Limit":0,"MinWidth":0}],"DisabledMetadataSavers":[],"LocalMetadataReaderOrder":[],"DisabledMetadataFetchers":[],"MetadataFetcherOrder":[],"DisabledImageFetchers":[],"ImageFetcherOrder":[]},{"ItemType":"BoxSet","ImageOptions":[{"Type":"Backdrop","Limit":1,"MinWidth":1280},{"Type":"Primary","Limit":1,"MinWidth":0},{"Type":"Thumb","Limit":1,"MinWidth":0},{"Type":"Logo","Limit":1,"MinWidth":0},{"Type":"Art","Limit":0,"MinWidth":0},{"Type":"Disc","Limit":0,"MinWidth":0},{"Type":"Banner","Limit":0,"MinWidth":0}],"DisabledMetadataSavers":[],"LocalMetadataReaderOrder":[],"DisabledMetadataFetchers":[],"MetadataFetcherOrder":[],"DisabledImageFetchers":[],"ImageFetcherOrder":[]},{"ItemType":"Season","ImageOptions":[{"Type":"Backdrop","Limit":0,"MinWidth":1280},{"Type":"Primary","Limit":1,"MinWidth":0},{"Type":"Banner","Limit":0,"MinWidth":0},{"Type":"Thumb","Limit":0,"MinWidth":0}],"DisabledMetadataSavers":[],"LocalMetadataReaderOrder":[],"DisabledMetadataFetchers":["TheMovieDb"],"MetadataFetcherOrder":[],"DisabledImageFetchers":[],"ImageFetcherOrder":[]},{"ItemType":"Episode","ImageOptions":[{"Type":"Backdrop","Limit":0,"MinWidth":1280},{"Type":"Primary","Limit":1,"MinWidth":0}],"DisabledMetadataSavers":[],"LocalMetadataReaderOrder":[],"DisabledMetadataFetchers":[],"MetadataFetcherOrder":[],"DisabledImageFetchers":["TheMovieDb"],"ImageFetcherOrder":[]}],"EnableAutomaticRestart":true,"PathSubstitutions":[],"UICulture":"en-us","PeopleMetadataOptions":{"DownloadActorMetadata":true,"DownloadDirectorMetadata":true,"DownloadProducerMetadata":false,"DownloadWriterMetadata":false,"DownloadComposerMetadata":false,"DownloadOtherPeopleMetadata":false,"DownloadGuestStarMetadata":false},"FindInternetTrailers":true,"InsecureApps9":["Windows Phone"],"SaveMetadataHidden":false,"ContentTypes":[],"EnableAudioArchiveFiles":false,"EnableVideoArchiveFiles":false,"RemoteClientBitrateLimit":0,"DenyIFrameEmbedding":true,"EnableLibraryMonitor":"Auto","SharingExpirationDays":30,"DisableXmlSavers":false,"EnableWindowsShortcuts":false,"EnableVideoFrameByFrameAnalysis":false,"EnableDateLastRefresh":false,"Migrations":[],"EnableDebugLevelLogging":false,"EnableAutoUpdate":true,"SystemUpdateLevel":"Release","LogFileRetentionDays":3,"RunAtStartup":false,"IsStartupWizardCompleted":false,"EnableCustomPathSubFolders":false}
Info, App, Loading MediaBrowser.Api, Version=3.0.5781.5, Culture=neutral, PublicKeyToken=null
Info, App, Loading MediaBrowser.WebDashboard, Version=3.0.5781.5, Culture=neutral, PublicKeyToken=null
Info, App, Loading MediaBrowser.Model, Version=3.0.5781.5, Culture=neutral, PublicKeyToken=null
Info, App, Loading MediaBrowser.Common, Version=3.0.5781.5, Culture=neutral, PublicKeyToken=null
Info, App, Loading MediaBrowser.Controller, Version=3.0.5781.5, Culture=neutral, PublicKeyToken=null
Info, App, Loading MediaBrowser.Providers, Version=3.0.5781.5, Culture=neutral, PublicKeyToken=null
Info, App, Loading MediaBrowser.Common.Implementations, Version=3.0.5781.5, Culture=neutral, PublicKeyToken=null
Info, App, Loading MediaBrowser.Server.Implementations, Version=3.0.5781.5, Culture=neutral, PublicKeyToken=null
Info, App, Loading MediaBrowser.MediaEncoding, Version=3.0.5781.5, Culture=neutral, PublicKeyToken=null
Info, App, Loading MediaBrowser.Dlna, Version=3.0.5781.5, Culture=neutral, PublicKeyToken=null
Info, App, Loading MediaBrowser.LocalMetadata, Version=3.0.5781.5, Culture=neutral, PublicKeyToken=null
Info, App, Loading MediaBrowser.XbmcMetadata, Version=3.0.5781.5, Culture=neutral, PublicKeyToken=null
Info, App, Loading MediaBrowser.IsoMounting.Linux, Version=1.0.5131.24779, Culture=neutral, PublicKeyToken=null
Info, App, Loading MediaBrowser.Server.Mono, Version=3.0.5781.5, Culture=neutral, PublicKeyToken=null
Info, App, Loading MediaBrowser.Server.Startup.Common, Version=3.0.5781.5, Culture=neutral, PublicKeyToken=null
Info, SqliteUserRepository, Sqlite 3.8.2 opening /var/lib/emby-server/data/users.db
Info, SqliteFileOrganizationRepository, Sqlite 3.8.2 opening /var/lib/emby-server/data/fileorganization.db
Info, AuthenticationRepository, Sqlite 3.8.2 opening /var/lib/emby-server/data/authentication.db
Info, SyncRepository, Sqlite 3.8.2 opening /var/lib/emby-server/data/sync14.db
Info, ImageMagick, ImageMagick version: ImageMagick 6.9.2-8 Q8 x86_64 2015-12-08 http://www.imagemagick.org
Info, ImageProcessor, ImageProcessor started with 8 max concurrent image processes
Info, App, FFMpeg: /usr/bin/ffmpeg
Info, App, FFProbe: /usr/bin/ffprobe
Info, SharingRepository, Sqlite 3.8.2 opening /var/lib/emby-server/data/shares.db
Info, ActivityRepository, Sqlite 3.8.2 opening /var/lib/emby-server/data/activitylog.db
Info, SqliteDisplayPreferencesRepository, Sqlite 3.8.2 opening /var/lib/emby-server/data/displaypreferences.db
Warn, App, ffmpeg is missing decoder h264_qsv
Info, SqliteItemRepository, Sqlite 3.8.2 opening /var/lib/emby-server/data/library.db
Warn, App, ffmpeg is missing decoder mpeg2_qsv
Warn, App, ffmpeg is missing decoder vc1_qsv
Info, SqliteProviderInfoRepository, Sqlite 3.8.2 opening /var/lib/emby-server/data/refreshinfo.db
Info, SqliteUserDataRepository, Sqlite 3.8.2 opening /var/lib/emby-server/data/userdata_v2.db
Info, SqliteNotificationsRepository, Sqlite 3.8.2 opening /var/lib/emby-server/data/notifications.db
Info, HttpServer, Calling ServiceStack AppHost.Init
Info, ServiceStackHost, Initializing Application took 3865.271ms
Info, ServerManager, Loading Http Server
Info, HttpServer, attempting to load pfx: /var/lib/emby-server/ssl/cert_9c31b7884ea5475c8687970fc5996297.pfx
Info, HttpServer, Adding HttpListener prefix http://+:8096/
Info, HttpServer, Adding HttpListener prefix https://+:8920/
Running startup tasks
Info, App, Core startup complete
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: links: not found
[1;24r[0;10m[4l[?7h[39;49m[39;49m[37m[40m[H[J[37m[40m[J[0;10m[39;49m[37m[40m[39;49m[0;10m[22d[0;10;1m[33m[44mGetting http://localhost:8096/web/wizardstart.html[K[39;49m[0;10m
[0;10;1m[33m[44mLooking up localhost:8096[K[39;49m[0;10m
[0;10;1m[33m[44mMaking HTTP connection to localhost:8096[39;49m[0;10m
[0;10;1m[33m[44mSending HTTP request.[K[39;49m[0;10mInfo, SsdpHandler, MultiCast socket created

[0;10;1m[33m[44mHTTP request sent; waiting for response.[39;49m[0;10m

[24;1H
Info, HttpServer, HTTP GET http://localhost:8096/web/wizardstart.html. UserAgent: Lynx/2.8.8pre.4 libwww-FM/2.14 SSL-MM/1.4.1 GNUTLS/2.12.23
Cannot handle address family 54016
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Net.Dns.GetHostByName_internal (string,string&,string[]&,string[]&) <0xffffffff>
  at System.Net.Dns.GetHostByName (string) <0x00047>
  at System.Net.ServicePoint.get_HostEntry () <0x001ff>
  at System.Net.WebConnection.Connect (System.Net.HttpWebRequest) <0x001ab>
  at System.Net.WebConnection.InitConnection (object) <0x00293>
  at System.Net.WebConnection.<WebConnection>m__0 (object) <0x0001f>
  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (object) <0x00048>
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) <0x0016e>
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) <0x00020>
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () <0x00053>
  at System.Threading.ThreadPoolWorkQueue.Dispatch () <0x001d6>
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0x00008>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_bool (object,intptr,intptr,intptr) <0xffffffff>

Native stacktrace:

	/usr/bin/mono-sgen() [0x4a1df8]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0x10340) [0x7f60bb800340]
	/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x39) [0x7f60bb45ecc9]
	/lib/x86_64-linux-gnu/libc.so.6(abort+0x148) [0x7f60bb4620d8]
	/usr/bin/mono-sgen() [0x62bdc9]
	/usr/bin/mono-sgen() [0x62bfcf]
	/usr/bin/mono-sgen() [0x62c072]
	/usr/bin/mono-sgen() [0x626f15]
	/usr/bin/mono-sgen() [0x57a916]
	[0x4068aa67]

Debug info from gdb:

[New LWP 28620]
[New LWP 28608]
[New LWP 28607]
[New LWP 28606]
[New LWP 28603]
[New LWP 28600]
[New LWP 28601]
[New LWP 28598]
[New LWP 28588]
[New LWP 28587]
[New LWP 28586]
[New LWP 28584]
[New LWP 28582]
[New LWP 28577]
[New LWP 28576]
[New LWP 28575]
[New LWP 28574]
[New LWP 28573]
[New LWP 28572]
[New LWP 28571]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x000000000049008e in ?? ()
  Id   Target Id         Frame 
  21   Thread 0x7f60bad3f700 (LWP 28571) "mono-sgen" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  20   Thread 0x7f60b8c4f700 (LWP 28572) "Finalizer" sem_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/sem_wait.S:85
  19   Thread 0x7f60afc7f700 (LWP 28573) "Timer-Scheduler" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  18   Thread 0x7f60b8087700 (LWP 28574) "mono-sgen" __clock_nanosleep (clock_id=1, flags=1, req=0x7f60b8086d80, rem=0xffffffffffffffff) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:49
  17   Thread 0x7f60afa7e700 (LWP 28575) "Threadpool work" 0x00007f60bb7ffee9 in __libc_waitpid (pid=28625, stat_loc=0x7f60afa7c2cc, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
  16   Thread 0x7f60af87d700 (LWP 28576) "Threadpool work" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  15   Thread 0x7f60af67c700 (LWP 28577) "Threadpool work" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  14   Thread 0x7f60ac267700 (LWP 28582) "Threadpool work" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  13   Thread 0x7f60ae197700 (LWP 28584) "Threadpool work" 0x00007f60bb51512d in poll () at ../sysdeps/unix/syscall-template.S:81
  12   Thread 0x7f608bdff700 (LWP 28586) "Threadpool work" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  11   Thread 0x7f608bbfe700 (LWP 28587) "Threadpool work" 0x00000000004a2fdd in ?? ()
  10   Thread 0x7f608b9fd700 (LWP 28588) "Threadpool work" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  9    Thread 0x7f60899ff700 (LWP 28598) "Threadpool work" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  8    Thread 0x7f60897fe700 (LWP 28601) "Threadpool work" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  7    Thread 0x7f60895fd700 (LWP 28600) "Threadpool work" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  6    Thread 0x7f60893fc700 (LWP 28603) "Threadpool work" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  5    Thread 0x7f60891fb700 (LWP 28606) "Threadpool work" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  4    Thread 0x7f6088ffa700 (LWP 28607) "Threadpool work" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  3    Thread 0x7f6088df9700 (LWP 28608) "Threadpool work" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  2    Thread 0x7f6088bf8700 (LWP 28620) "mono-sgen" __clock_nanosleep (clock_id=1, flags=1, req=0x7f6088bf7760, rem=0xffffffffffffffff) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:49
* 1    Thread 0x7f60bc3457c0 (LWP 28570) "mono-sgen" 0x000000000049008e in ?? ()

Thread 21 (Thread 0x7f60bad3f700 (LWP 28571)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00000000005fb8dc in ?? ()
#2  0x00007f60bb7f8182 in start_thread (arg=0x7f60bad3f700) at pthread_create.c:312
#3  0x00007f60bb52247d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 20 (Thread 0x7f60b8c4f700 (LWP 28572)):
#0  sem_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/sem_wait.S:85
#1  0x000000000061f167 in mono_sem_wait ()
#2  0x00000000005a4c66 in ?? ()
#3  0x000000000058741b in ?? ()
#4  0x00000000006258e6 in ?? ()
#5  0x00007f60bb7f8182 in start_thread (arg=0x7f60b8c4f700) at pthread_create.c:312
#6  0x00007f60bb52247d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 19 (Thread 0x7f60afc7f700 (LWP 28573)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
#1  0x0000000000600a37 in ?? ()
#2  0x0000000000612402 in ?? ()
#3  0x000000000058729f in ?? ()
#4  0x00000000005887d9 in ?? ()
#5  0x000000004034eadd in ?? ()
#6  0x00000000029c8fc0 in ?? ()
#7  0x0000000000000031 in ?? ()
#8  0x0000000000000031 in ?? ()
#9  0x00007f60b01a1d90 in ?? ()
#10 0x0000000000000031 in ?? ()
#11 0x00007f60a4000e00 in ?? ()
#12 0x0000000000000031 in ?? ()
#13 0x00007f60afc7e880 in ?? ()
#14 0x00007f60afc7e7f0 in ?? ()
/build/buildd/gdb-7.7.1/gdb/dwarf2-frame.c:692: internal-error: Unknown CFI encountered.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Quit this debugging session? (y or n) [answered Y; input not from terminal]
/build/buildd/gdb-7.7.1/gdb/dwarf2-frame.c:692: internal-error: Unknown CFI encountered.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Create a core file of GDB? (y or n) [answered Y; input not from terminal]

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

**Comment by LukePulverenti** [comment]
Hi, there have been major changes to the packages over the last week or so. Please try again. If the issue persists, please re-open with new info. Thanks!
