### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by ghostcoding88** [MediaBrowser/Emby#1325]
I can't display a folder structure on my sony bravia smart tv. i've setup all my folders on the server (debian 8) and libraries on the web interface (movies, tv etc) but it won't show the folders on my tv. I've been using mediatomb before and had no problems with showing  folders on my tv. any way to accomplish that?
thanks in advance

**Comment by ebr11** [comment]
What app are you using on the TV?

**Comment by ghostcoding88** [comment]
the build in tools (network settings >> home network). on the home screen i pick my connected serves

**Comment by ebr11** [comment]
Okay, so this would be via DLNA.

This isn't one of the new Sony's with Android TV on it is it?

**Comment by ghostcoding88** [comment]
it's a newer model yes but it doesn't have android I believe it's this one "65 inch X Series BRAVIA 4K LED backlight / 3D TV Model: KD65X9000C"
I can verify this as soon as i get home if you need the exact model.
Thank you for the quick response by the way.

**Comment by ebr11** [comment]
According to my search, that is an Android TV model.  If so, you can find our Android TV app in the store and it will provide you with a better interface for Emby.

**Comment by ghostcoding88** [comment]
I will check that out thank you so much for your help. I'll keep you posted.
Keep up the good work

**Comment by LukePulverenti** [comment]
in regards to dlna, what were you seeing before?
