### ISSUE TITLE
Issue with subtitles when resuming using DLNA Play To

### ISSUE THREAD

**Issue by psxlover** [MediaBrowser/Emby#1347]
When using Play To to resume a movie (on an LG TV), the subtitles appear wrong. If I rewind to the beginning of the movie I can see the subtitles that were supposed to appear at the point I resumed.

Note: The correct subtitles appear if the video gets transcoded (so the subtitles are burned in the video) and when resuming and playing the video in the Web Client.

I can reproduce the issue both in dev (Version 3.0.5833.18789) and in stable (Version 3.0.5781.8).

**Comment by LukePulverenti** [comment]
So it's direct stream. Are the subtitles internal or external?

**Comment by psxlover** [comment]
External only. I created a .mkv with embedded.srt and it worked correctly. Also files with embed .ass resume correctly as long as embed .ass is listed as supported in the DLNA profile (I guess when they aren't supported, they are extracted and served as external .srt).

Looking at the packets with Wireshark the subtitle's timestamps have been modified by the server, and it only sends the dialog from the point your resume and onwards.
