### ISSUE TITLE
[BUG] Emby recreating old folder name after renaming/moving folder

### ISSUE THREAD

**Issue by ppascher** [MediaBrowser/Emby#1404]
I had a folder for a TV show "Newshow" which I changed to all lowercase "newshow". After a "rescan library" all metadata paths for seasons and episodes were updated to the new path except for the show's root path which got recreated as "Newshow" including the .nfo file. As a workaround I had to name the folder from "Newshow" to "newshow_xyz" to "newshow" for the root folder to have the desired name.

**Comment by LukePulverenti** [comment]
Hi, what were the symptoms experienced? Do you mean image paths in nfo files? what operating system is the server running on?

**Comment by ppascher** [comment]
Hello Luke,
the server is running on CentOS 7. Here is what happened (sorry if I am not explaining it well):
- I had folder "Newshow"
- renamed folder to "newshow" (mv /mnt/freenas/media/videos/tv/Newshow /mnt/freenas/media/videos/tv/newshow" since I was in the process of renaming all my folders to underscore & lowercase
- did a "scan library" in "Manage Server -> Library" to get the changed folder name to register
- checked "Metadata-Manager -> TV -> Newshow" entry
- noticed the "path" entry was still the capitalized "Newshow" but for "Season 1" and each episode underneath had the correct new lowercase folder name "newshow" 
- Symptom was that in the show overview no images were shown (presumably because emby was looking in "Newshow" instead of "newshow"). Season and Episode images were fine.
- Doing a metadata refresh on the show resulted in the show overview images being redownloaded to /mnt/freenas/videos/tv/Newshow (fanart, landscape etc.) as to emby they were missing.

While nothing serious I now had 2 folders where there should only be one. This only happened when the new folder name was the same except for capitalization (So going from 'Newshow' to 'newshow' had this problem while going from "The New Show" to "the_new_show" correctly updated the show's root folder).

**Comment by LukePulverenti** [comment]
Ok, I traced this down to the server treating the two paths as the same library item. Going forward, the server will generate library id's using case-sensitive paths. This change is risky to make for existing servers so it will only apply to brand new installations.

**Comment by ebr11** [comment]
This will also probably make it much harder for someone to do a clean re-install and then restore information from backup.  Just FYI.
