### ISSUE TITLE
ffmpeg errors out on incorrect paramters - looks like something is parsed wrong? 

### ISSUE THREAD

**Issue by svenstaro** [MediaBrowser/Emby#1418]
Other files that I tried work fine. This particular file is erroring out and it seems that this happens because something is parsed wrong. Log file attached.

[transcode-73dbfc81-644b-4a36-b8b3-c8447101d4ff.txt](https://github.com/MediaBrowser/Emby/files/99549/transcode-73dbfc81-644b-4a36-b8b3-c8447101d4ff.txt)

**Comment by LukePulverenti** [comment]
Hi, can you please retry on the latest version of the server? thanks.

**Comment by svenstaro** [comment]
It now just says "There was an error playing the video."

**Comment by LukePulverenti** [comment]
And the transcoding log?

**Comment by svenstaro** [comment]
Basically the same. Same error with another file:

[transcode-ba34564b-3c38-4b20-af59-c7dde0bddb60.txt](https://github.com/MediaBrowser/Emby/files/115019/transcode-ba34564b-3c38-4b20-af59-c7dde0bddb60.txt)

**Comment by LukePulverenti** [comment]
Is there still an issue here on the latest versions?
