### ISSUE TITLE
Web player crashes all tabs in firefox developer edition on arch linux

### ISSUE THREAD

**Issue by danielunderwood** [MediaBrowser/Emby#1423]
The web player is crashing all tabs in firefox developer edition on arch linux for me. This does not occur if I run the web player in regular firefox and does not occur when using the developer edition on windows.

__Versions:__
_Firefox:_ 43.0.4
_Firefox Developer Edition:_ 45.0a2
_Kernel:_ SMP PREEMPT Wed Dec 23 20:09:18 CET 2015

Let me know if any other information is needed or if there's anything that I should try.

**Comment by LukePulverenti** [comment]
Thanks for the info. We probably won't be able to spend much time on it until it reaches the beta channel, by which time there's a good chance it will no longer be a problem.

**Comment by LukePulverenti** [comment]
http://emby.media/community/index.php?/topic/30148-blank-screen-on-firefox/?p=295859

**Comment by danielunderwood** [comment]
That seems to be a different issue. I am only getting the crash after a certain time using the interface and it is a total crash of all Firefox tabs rather than a blank screen. I'll try to grab a screenshot the next time that happens.

On another note, I am getting the crash on other websites as well, so it seems more likely to be a Firefox issue than an Emby issue. On an update to regular Firefox, it is having an issue in addition to the developer edition.

**Comment by LukePulverenti** [comment]
Thanks. I will close this then since i don't foresee any work for us. Thanks for the info.
