### ISSUE TITLE
[Feature Request]: Require Encryption

### ISSUE THREAD

**Issue by PatrickMurray** [MediaBrowser/Emby#1427]
Is it possible to require encryption for all server traffic? I know Plex supports this, but I haven't been able to find something like this in Emby.

**Comment by LukePulverenti** [comment]
This will come but not until we have trusted certs for all users instead of the self-signed cert we have now.

**Comment by PatrickMurray** [comment]
Ok, thanks so much!

**Comment by gardar** [comment]
How about supporting LetsEncrypt?

**Comment by anderbytes** [comment]
For what I know, that's the idea.

**Comment by anderbytes** [comment]
I tought that all traffic used in HTTPS port was encrypted. Isn't that correct?

**Comment by anderbytes** [comment]
Hello?

**Comment by AnderssonPeter** [comment]
Please support `LetsEncrypt` in combination with the user owning a domain.

**Comment by anderbytes** [comment]
Is not all traffic encrypted today with HTTPS in port 8920 ???

**Comment by LukePulverenti** [comment]
@anderbytes yes it is. The OP is asking for http to be blocked or redirected to https.

**Comment by LukePulverenti** [comment]
We are adding this for the next release of Emby Server, thanks.
