### ISSUE TITLE
media scan pick only the first file from a folder

### ISSUE THREAD

**Issue by dontspamm** [MediaBrowser/Emby#1434]
i just noticed that the scanning the library it just look like the first file ignoring the rest
for example
###folderA

####A1.avi
####Ab2.avi
####Ac3.avi

**Comment by ebr11** [comment]
Make sure you haven't named your items in such a way that they are being discovered as multiple parts of the same item.

https://github.com/MediaBrowser/Wiki/wiki/Movie%20naming

**Comment by dontspamm** [comment]
the movies are named zyx-abc-tt<imdb id>.avi

**Comment by LukePulverenti** [comment]
Please provide a screenshot of the entire folder and it's contents. thanks.

**Comment by dontspamm** [comment]
c# ls -a
./                         Cartel-Land-tt4126304.avi  Citizenfour-tt4044364.mp4
../                        Cartel-Land-tt4126304.srt

http://i.imgur.com/cei8LtL.png

**Comment by dontspamm** [comment]
i solved this by making a folder for every file ,,,,
