### ISSUE TITLE
[Feature Request] Support for media in rar archives.

### ISSUE THREAD

**Issue by gardar** [MediaBrowser/Emby#1440]
I would like to see Emby support media that's inside rar files natively. 
Preferably in a similar way that Kodi does currently. 
This means that the media is not extracted from the rar but rather accessed directly from within the rar files.

Few requirements:
- Support for multi-part rar files.
- Emby would need to look at time stamps on the directory rather than the media file in the rar archive, since the time stamp in the archive can't be changed since creation.

Further details on the requirements of this feature request:
http://emby.media/community/index.php?/topic/10765-support-for-media-in-rar-archives/
http://emby.media/community/index.php?/topic/23648-tutorial-rar-playback-with-emby/

**Comment by bauruine** [comment]
I've added 100$ to the bounty.
https://www.bountysource.com/issues/30765863-feature-request-support-for-media-in-rar-archives

**Comment by bauruine** [comment]
meh. looks like @denim2x is just a troll :-(

**Comment by krysstof** [comment]
as long as we are talking about "media in archives", comics readers use "cbz" and "cbr" files which are simply zip and rar files renamed
this would go well with this feature (and the pinch zoom one #2826 )

**Comment by ryu0** [comment]
Is this still wanted? I've been poking through the source to see how this might be done in an acceptable manner. I was thinking something like this could be integrated: [https://github.com/bobvanderlinden/sharpfilesystem](https://github.com/bobvanderlinden/sharpfilesystem) But then, I am unfamiliar with this project.

**Comment by gardar** [comment]
@ryu0 sorry about the late reply, there's still a big interest in this. 
As you can see on bountysource, we have a 260$ bounty for this feature at now but that could probably be raised if we had some goal posted from a developer.

The sharpfilesystem would definitely be a interesting approach, I did look at how Kodi and mpv are playing rar files as we might have a similar approach, here's the initial commit in mpv for example: https://github.com/mpv-player/mpv/commit/3fc3bf70f972f4e68258193f0f9c70ee6b85be5e

Maybe @LukePulverenti could chime in the discussion as to point us to where in the Emby code we would need to look to do the integration properly, just to get things started.

**Comment by gardar** [comment]
This issue was moved to jellyfin/jellyfin#85
