### ISSUE TITLE
web server dont pick certain metadata files

### ISSUE THREAD

**Issue by dontspamm** [MediaBrowser/Emby#1466]
for example the action poster and landscape files are there but the web client dont pick them even if the genre is set to use posters 

> server version 3.0.5821.0

```
metadata/Genre/Action# ls
./             ../            landscape.jpg  poster.jpg 
```
inspecting the webpage code it request this 

`<img class="itemDetailImage lazy loaded" src="....../persistent/images/df6da75945f363890769f534993bb4e4" data-src="">`

so if i go to 
`cache/images/resized-images/d`
and look for the file 
```
d# find df6*
df68ecf6-ab0e-6ac1-47a3-97f169c19716.webp
```

**Comment by dontspamm** [comment]
i think i find the problem if i go to the genre inside the media server and look at the path the path is set to a non exiting folder the web server is not pointing to the /Genre/Action but is pointing to the translated folder, manually uploading the files from the english-folder-action create a new folder and now the image is visible in the web interface

**Comment by LukePulverenti** [comment]
Ah yes. we should change these paths to not be localized, although making the change will require users who have customized images to move them to the new locations. therefore, if any change is made, it will probably only apply to fresh new installations.

**Comment by dontspamm** [comment]
that wont solve the problem if there is no genre in english folder for example there is no family folder generated

**Comment by LukePulverenti** [comment]
Sorry, I think I mis-understood this. There are no translated genre folders. You can see this by editing a genre

![untitled](https://cloud.githubusercontent.com/assets/3607463/14009540/485c4066-f163-11e5-9c0a-3bf3024ebdd7.png)

Emby server does not translate genre names from one language to another, but you might be getting translated genres from internet metadata providers. So what is your actual issue, that images in the genre folders aren't being used?
