### ISSUE TITLE
Request for User Playback details improvement

### ISSUE THREAD

**Issue by Lord-Malgus** [MediaBrowser/Emby#1529]
I would love to see more details exposed on server page when users are active.

Example of what I would like see:
Transcoding  (72fps) - HEVC 1024Kbps ->  AVC 3Mbps
                                            DTS   300K       ->  AAC 128K

Also, if user is Direct Playing content, I would still like the see the source codecs / bitrate:

Direct Play - HEVC 3Mbps / AAC 128K

Really like the new improvements in this area so far.
Thank you

**Comment by anderbytes** [comment]
That would be awesome.

**Comment by Kezine** [comment]
+1
