### ISSUE TITLE
last fm 

### ISSUE THREAD

**Issue by wayneward** [MediaBrowser/Emby#1536]
no last.fm support after a server upgrade
really ned the server to scrobble to last fm 
trakt still works fine 
is it possible to get emy scrobbling again so i can carry on using the premium version of the server?
ive tried adding the old dll from the older setup which can see the plugin but wont activate i just get a spinning round circle that just keeps spinning
tested on various browsers
the server is ubuntu 14.04

**Comment by LukePulverenti** [comment]
Hi, the last fm plugin was built by a community member who has not been around as much lately. We are hoping someone else will take a look at it: 

http://emby.media/community/index.php?/topic/30066-lastfm-addon-gone

Thanks.
