### ISSUE TITLE
[Feature Request] Provide option to select which interface(s) to bind to

### ISSUE THREAD

**Issue by c89williams** [MediaBrowser/Emby#1537]
Request: provide an option to specify which interfaces to listen on. This would apply to everything - Emby admin, DLNA, SSDP, etc.

It has been mentioned on the forums and as issues here on GitHub many times but is always shot down, mostly because it is reported that it doesn't bind correctly.

That is *not* what this request is about. This request wants the option in general.

In my case, Emby is binding to too many addresses! My machine has a VPN connection open 24/7 and Emby should not be binding to there. I'm using a firewall rule for now, but that doesn't seem to make as much sense as an actual option in Emby.

**Comment by LukePulverenti** [comment]
Thanks for the request. You can help test this here:

http://emby.media/community/index.php?/topic/35687-3113-bind-to-local-ip-address/
