### ISSUE TITLE
[Feature Request] AutoOrganize - Rsync

### ISSUE THREAD

**Issue by humantraffic** [MediaBrowser/Emby#1545]
Just thought that adding an additional option for how the server moves data could be useful for setups where not all data is on the same physical location.  Rsync that recognizes different locations and employs ssh accordingly would be fast and useful to bridge that gap.

**Comment by LukePulverenti** [comment]
Hi, thanks for the request. Please post this in the Emby community as it's the best way us to gauge the interest level from other users:

http://emby.media/community/index.php?/forum/53-windowsgeneral/

Thanks!
