### ISSUE TITLE
DenyIFrameEmbedding don't work with domains

### ISSUE THREAD

**Issue by popeen** [MediaBrowser/Emby#1547]
After changing DenyIFrameEmbedding to false I can successfully embed if I use the local or global ip addresses but when I try to use a domain (subdomain if it makes any difference) pointed to my global ip it stops working. If I navigate to the domain in the browser it works fine.

**Comment by LukePulverenti** [comment]
Hi, I think this is completely unrelated. The only thing that setting does is dictate the presence of an http header that gets added to every response

```
            if (_denyIframeEmbedding())
            {
                res.AddHeader("X-Frame-Options", "SAMEORIGIN");
            }
```

That's really all there is to it. I think your issue is elsewhere.

**Comment by popeen** [comment]
Hmm, thought I had replied to this already.

Anyway, ok that's weird because it seems to work fine outside frames but not inside, unless I use my ip. I was hoping there was something else going on inside Emby that was causing it but if that's all it does there must be something else in my browser causing it. Thanks anyway and thanks for a great software.

**Comment by LukePulverenti** [comment]
If you want to post in the community there's a good chance there will be others with a similar setup and that might lead to some clues:

http://emby.media/community/index.php?/forum/115-server-support/

Thanks.
