### ISSUE TITLE
Search containing umlauts fails

### ISSUE THREAD

**Issue by CrawX** [MediaBrowser/Emby#1571]
When using the search functionality in the web interface, I'm not able to find the German version of "This Means War" ("Das gibt Ärger") by searching for "Ärger" or "ärger". However, I can find the movie by using "Das gibt".

There is no error or anything, but the result list contains numerous items containing the string "arger", so I guess the "ä" is converted to an "a".

I checked with some other movies containing umlauts and the conclusion seems to be that it is currently not possible to use search strings containing umlauts (at least with correct results).

**Comment by n00b42** [comment]
I can confirm this issue is still present in 3.0.5912.0

**Comment by n00b42** [comment]
I seems related to 2e9645c1e06428bf3223b015b0eac90afecef84f
Problem is that while the search term is processed (accent and umlauts are removed), the searched library is processed as it is. (Like described by CrawX)
