### ISSUE TITLE
Unable to disable DLNA

### ISSUE THREAD

**Issue by nfnty** [MediaBrowser/Emby#1578]
Network is spammed with SSDP discover packets with destination 239.255.255.250:1900, even though all DLNA settings are disabled.

Version: 3.0.5882.0

**Comment by LukePulverenti** [comment]
Hi, can you give an example? Thanks.

**Comment by nfnty** [comment]
What do you mean by example? Just disable everything related to DLNA and then capture the bound interface and you'll see SSDP packets being spammed with an interval depending on 'Client discovery interval'.

**Comment by nomandera** [comment]
For reference once you have stopped SSDP via disabling `everything related to DLNA` a server restart is required for it to be fully applied.

Until this time 0.0.0.0:1900 is still bound
