### ISSUE TITLE
Metadata Manager: Disable display of "MissingTrailer" icon

### ISSUE THREAD

**Issue by softworkz** [MediaBrowser/Emby#1581]
I'm not interested in movie trailers and I haven't activated any related feature.

Though, the metadata manager tree displays a "missingtrailer.png" icon for all movie items.

It would be great if these would only be displayed if the user has activated a feature requiring movie trailers.

**Comment by Happy2Play** [comment]
There are a couple post on this in Custom CSS.

http://emby.media/community/index.php?/topic/18046-custom-css-with-the-new-server-beta/?p=178376

**Comment by softworkz** [comment]
Cool. Good decision to remove it.

**Comment by Happy2Play** [comment]
Why would your remove this?  Asked about in forum also.
http://emby.media/community/index.php?/topic/34049-issues-after-3059300-update
