### ISSUE TITLE
activitylog.db is huge and slow..

### ISSUE THREAD

**Issue by karbowiak** [MediaBrowser/Emby#1586]
activitylog.db is currently in excess of 2GB for me, leading to the activity log itself being extremely slow at loading.

Any chance of automatically clearing out entries older than, say 1-4 weeks ? :)

**Comment by Happy2Play** [comment]
Interesting I have a activitylog.db created Aug 2014 and it is only 2.38MB

**Comment by karbowiak** [comment]
Really? Mine had grown extremely huge, altho now it's barely 440KB.. Weird

I might have hit a bug or something a while ago, and it just persisted? :D
