### ISSUE TITLE
Doesn't properly support Mono 4.4.0 (or Mono >4.2.2)

### ISSUE THREAD

**Issue by MikuroK** [MediaBrowser/Emby#1610]
For a while I've been unable to complete a library scan, each time the server would crash part way through. I tried many things (removing the library db, compiling the latest git version of emby, starting from a fresh emby data store, removing all plugins, using older ffmpeg versions, etc) but I've found rolling back from Mono 4.4.0 to 4.2.2 has avoided the issue.

Another anomaly I noticed was that any transcoding I did (streaming to kodi via http, or using the internal web-based player) was unreliable, in kodi I would get video artefacts, sudden skips and loss of playback, and in the web player, loss of playback both within a minute of starting any video. playback in kodi via smb was unaffected. I'm not sure how this relates, but rolling back Mono solved this problem as well.

I've been monitoring the logs, and while there were various "*** error report ***" entries I got while trying different things, the one that seemed to correlate to the crash is attached.

My apologies if this report is invalid or inappropriate in any way.
[unhandled_eaf57807-bb66-406b-9f07-e2688ff3a060.txt](https://github.com/MediaBrowser/Emby/files/192954/unhandled_eaf57807-bb66-406b-9f07-e2688ff3a060.txt)

**Comment by LukePulverenti** [comment]
Please provide a complete server log of this scenario, thanks.

**Comment by TheDrifter363** [comment]
I also wanted to report I was having this same issue. Downgrading to mono 4.2.2 on Arch Linux corrected the error. I don't know why this error exists with mono 4.4.0, but I thought I would report it. I'll upload the server log and unhandled exception.

Unfortunately I don't know how to provide you with the server log. It's 150 MB worth of txt. Do you have any recommendations?

**Comment by LukePulverenti** [comment]
The latest stable mono release according to the website is 4.2. I would strongly suggest avoiding pre-release versions. Right now I don't think there's anything for us to do here.

**Comment by TheDrifter363** [comment]
Hey thanks Luke, I just checked that out. Sure enough, it's an alpha version. I'm kind of surprised the Arch developers updated mono to a pre release version. I'm going to file a bug report.

**Comment by PaddyMac** [comment]
I was just wondering what the status was with this issue. Out of curiosity, I tried Mono 4.4.0.148. Emby server crashed a few moments after starting it. It's no problem for me to revert back to 4.0.5.1 which was working fine, but according to http://www.mono-project.com/docs/about-mono/releases/4.4.0/ the 4.4.0 series is considered stable by the Mono project; it only lists 4.3.2 as an alpha preview release.

**Comment by PaddyMac** [comment]
Here's my server log. I'm running Funtoo, and my software is compiled from source. My ffmpeg library is compiled minimalistically, and I just enable the codecs I actually use (if I know I need them). Apparently my copy of ffmpeg doesn't supply all the codecs emby wants, and the exceptions seem to occur when emby doesn't find the codecs it wants with the new version of Mono, but it just carries on without them with the older version of Mono.
[emby-server.log.txt](https://github.com/MediaBrowser/Emby/files/315521/emby-server.log.txt)

**Comment by LukePulverenti** [comment]
Hi, thanks for the report. i'm going to have to add more logging to trace this down. Are you able to try the beta channel? thanks.

**Comment by PaddyMac** [comment]
The box that I had Emby running on was damaged sometime early in the morning yesterday during a brief power outage due to a thunderstorm, and it will no longer power on. I've got another box I can get set up, and then I'll see about using the beta version of Emby. But it may be a few days before I get things up and running again.

**Comment by PaddyMac** [comment]
I encountered a bit of divine providence today. We're having another thunderstorm today and had another short power outage. After the power came back on, I tried powering on my computer, and it worked! It's the strangest thing. Anyway, I also got in touch with the person who maintains the Emby package for Gentoo, and he has provided an ebuild for the beta channel. So I'm installing 3.1.25 now. I'll give it a spin shortly.

**Comment by PaddyMac** [comment]
I apologize for not following up sooner. Here is the log from the crash with 3.1.25.
[emby-3.1.25-crash.txt](https://github.com/MediaBrowser/Emby/files/324118/emby-3.1.25-crash.txt)

**Comment by LukePulverenti** [comment]
Hi, can you please try newer beta revisions? Thanks!

**Comment by PaddyMac** [comment]
Yes. I tried 3.1.33 later on the day it was released, and it also crashed. This morning, I tried 3.1.6030.2079-dev (along with Mono 4.4.0.182), and while I haven't had time to give it extensive testing, everything seems to be working just fine. The server started without any warnings or errors in the log, and I tried playing a movie. So great work!
