### ISSUE TITLE
Watched Status of movies reverts to unwatched on metadata refresh

### ISSUE THREAD

**Issue by DaftHonk** [MediaBrowser/Emby#1611]
Running Emby 3.0.5911 on Synology Diskstation. I migrated to Emby from Kodi MySQL by exporting library to individual files then scanning with Emby. Everything worked great, however in my old setup I only had poster and one fanart image. I decided to have Emby add the missing artwork, however when I do a refresh from the library, the watched status of watched movies reverts to unwatched. Trying it again from the Metadata Manager both "find missing info only" and "full refresh" result in watched status being overwritten. TV shows do not exhibit this behavior.

**Comment by karbowiak** [comment]
You might have something on your machine that overwrites the NFO files that Emby makes next to the media, in my case it was Sonarr that interfered with it.

Once i made Sonarr not add metadata, and let Emby handle that, it all started working perfectly :)

**Comment by DaftHonk** [comment]
Both CouchPotato and Sonarr are set to not write metadata, they simply send a notification to Emby. I tried another movie and this time deleted all files but the movie; again the watched status was reset - however the original Added Date from the old nfo was preserved and written in the new nfo. I have "Sync user watch data to nfo's" turned off as it was causing watched statuses to reset at random.

**Comment by LukePulverenti** [comment]
The user data keys are dynamic and based on tmdb or imdb id's. If i had to guess, when you first imported, you only had imdb id's attached to your movies, then later through refreshing you acquired tmdb id's and the user data key switched to that, thus unfortunately causing data loss.

**Comment by DaftHonk** [comment]
That is exactly what happened. Thank you, I may have to find a workaround.
