### ISSUE TITLE
Show season listing shows "Season -1" only

### ISSUE THREAD

**Issue by stacimail** [MediaBrowser/Emby#1612]
I am running Emby via Kodi and after the initial scan I see all TV shows only show "Season -1" and all episodes from all seasons are in this listing. IE: If there are seven seasons, they're all just in the "Season -1" area and not separated. Is this a setup error on my part? Have researched with no luck.

**Comment by LukePulverenti** [comment]
Hi there. Can you tell us what your tv folder structure looks like? I'd like to see what a series folder looks like as well as some of the episode file names. Thanks!

**Comment by stacimail** [comment]
Absolutely, here it is:

![image](https://cloud.githubusercontent.com/assets/10871411/14154716/a6be4512-f683-11e5-97c6-96e343540644.png)

**Comment by LukePulverenti** [comment]
Thanks. Can you also show an example of a later season that is not displaying correctly? Thanks.

**Comment by stacimail** [comment]
![image](https://cloud.githubusercontent.com/assets/10871411/14155176/3793cb8c-f686-11e5-8967-c992a70a7430.png)

![image](https://cloud.githubusercontent.com/assets/10871411/14155194/4966fbcc-f686-11e5-8759-d1200978bbaf.png)

**Comment by stacimail** [comment]
It seems there is no data showing for any episodes as well...

**Comment by wyznerd** [comment]
Having the same issue here.  Refreshing item by item in media manager takes care of the _missing_ seasons, but still leaves the weird season-1 entry

**Comment by LukePulverenti** [comment]
What does the web interface look like? can you show a screenshot, as well as a screenshot of your actual folders? thanks.

**Comment by wyznerd** [comment]
@LukePulverenti Web view shows normally.  

Folder structure is 
![image](https://cloud.githubusercontent.com/assets/709934/14579067/06875e8a-0362-11e6-9bde-342641c00326.png)

This only seems to have affected Kodi clients for me.  The one strange part is that metadata manager showed everything normally, but was missing all of the associated metadata.  Refreshing 'TV' under metadata manager brought everything back into line and then doing a Refresh DB on Kodi clients brought them back into line.  It definitely happened with last week's update, but no idea why.

**Comment by wyznerd** [comment]
Also, to clarify, the Season-1 "directory" in Kodi was where "All Seasons" should be.

**Comment by LukePulverenti** [comment]
Ok then if it happens again, before attempting any workarounds please post in the Kodi section of our community:

**Comment by LukePulverenti** [comment]
Thanks.

**Comment by LukePulverenti** [comment]
http://emby.media/community/index.php?/forum/99-kodi/

**Comment by wyznerd** [comment]
Definitely will.  I thought it was just me until I stumbled upon this thread.  Thanks @LukePulverenti

**Comment by stacimail** [comment]
Update: Seems to happen when the library isn't finished syncing or failed to do so. Waiting or manually syncing fixes the issue for me.
