### ISSUE TITLE
Allow to "mark as watched" when using multi-select.

### ISSUE THREAD

**Issue by elboletaire** [MediaBrowser/Emby#1615]
Currently we're not able to mark multiple episodes as watched when using the multi-select feature.

On desktop one can mark as watched episodes one by one using the hover layer, but on mobile devices (using the app) one needs to access every episode to mark them as watched.

Can you please add the "mark as watched" option to the multi-select interface?

**Comment by anderbytes** [comment]
True, very useful.

**Comment by elboletaire** [comment]
Great @LukePulverenti! Can't wait to try it :smile:
