### ISSUE TITLE
Sync quality cannot be changed.

### ISSUE THREAD

**Issue by ruifung** [MediaBrowser/Emby#1621]
When a sync job is created, no matter what quality is selected, whenever the job is saved, the quality selector is always set to high.

**Comment by anderbytes** [comment]
This is a problem when viewing an existing job. Even if the job is "Medium" or "Original", it shows as high, only when being looked at.

The worst comes when transcoding is off, and it doesn't let you choose the sync quality, using "High" instead of "Original"

**Comment by ruifung** [comment]
Huh, I just took a look at the replies from the server, and yeah, the response contains the correct quality, its just the clientside code seems to not be reading it correctly.

**Comment by LukePulverenti** [comment]
Resolved via 7ba6722e620d4966688eebd36bbb3a57ee3a2f80. Thanks.
