### ISSUE TITLE
Bug: When trying to view DRM channel on LiveTV

### ISSUE THREAD

**Issue by Toggie** [MediaBrowser/Emby#1633]
Through HDHomeRun when I try to view a drm channel, it obviously fails to load that channel, but something happens where I can't watch anything else until I restart the server as well.

I am happy to try to help with this bug in any way that I can, just tell me what I must do or I can just give you login to the box.  I also humbly ask for a feature, that the channels list scans for DRM channels and just doesn't add them to the channel list if it isn't going to work anyways (or at least have a checkbox to tick where this is the behavior)

**Comment by LukePulverenti** [comment]
DRM channels are just going to be removed fro the next release, thanks.
