### ISSUE TITLE
Library cleared when hard drive disconnected

### ISSUE THREAD

**Issue by deblockt** [MediaBrowser/Emby#1672]
Hello,

When I disconnect my hard drive, my library is completly cleaned.
in file log, I have this error message : 

2016-04-20 19:52:55.2135 Error HttpServer: Error processing request for /emby/Items/0064b6093032d66533584aff8adc70d1/Images/Primary?maxHeight=450&maxWidth=300&tag=bf23f8f8602ccf1cba6e6dd0a673119b&enableImageEnha
ncers=true&quality=90
    **\* Error Report ***
    Version: 3.0.5913.0
    Command line: /usr/lib/emby-server/MediaBrowser.Server.Mono.exe -programdata /var/lib/emby -ffmpeg /usr/bin/ffmpeg -ffprobe /usr/bin/ffprobe
    Operating system: Unix 4.4.7.1
    Processor count: 4
    64-Bit OS: False
    64-Bit Process: False
    Program data path: /var/lib/emby
    Mono: 4.2.2 (Stable 4.2.2.30/996df3c Sat Apr 16 14:06:56 UTC 2016)
    Application Path: /usr/lib/emby-server/MediaBrowser.Server.Mono.exe
    Object reference not set to an instance of an object
    ServiceStack.HttpError
    No Stack Trace Available

I think this is do it because video files are "deleted" on file system.
Is it possible to differentiate delete file event, and hard drive diconnected event?

My server is installed on linux.

**Comment by RaymondSchnyder** [comment]
Obviously, if you disconnect the source of the library, it cleans.
And no, its not possible. Close the ticket

**Comment by LukePulverenti** [comment]
Hi, please try again with the latest release of Emby Server. Thanks!
