### ISSUE TITLE
Microsoft Edge on Xbox one

### ISSUE THREAD

**Issue by dredrizzah** [MediaBrowser/Emby#1692]
When I try to select a movie emby keeps doing the loading circle. Now if I hover over what I'm trying to select, and wait for the play arrow to pop up it will play to movie. Also there's no way to go back when using emby on the Xbox One. If you press the b button you go back to the consoles dashboard....

**Comment by LukePulverenti** [comment]
Hi, are you using the built-in web app on Xbox One?

**Comment by dredrizzah** [comment]
Yes I'm using the built-in app. When trying to select a video, there's a
play arrow on the bottom right. If I try playing it from there it doesn't
play. Now if I hover over the file it will show a smaller arrow on the left
side, now if I use that play arrow it will play the movie. Now with the
issue that I'm experiencing if I try to play something from one of my
collections you can only watch all the movies. You can't go in the
collection and select the movie you want to watch.

**Comment by LukePulverenti** [comment]
Ok. We are not testing the built-in web app anymore on Xbox One because we have a new web app dedicated for TV use, which you can read about here:

http://emby.media/community/index.php?/blog/1/entry-293-introducing-emby-theater-for-xbox-one/
