### ISSUE TITLE
pdf files for books category 

### ISSUE THREAD

**Issue by icf20** [MediaBrowser/Emby#1707]
Hi, i have set up a folder for pdf's using the books option on my server, sadly no files are detected

is there any trick to view pdf files ?

**Comment by LukePulverenti** [comment]
Hi, the best thing to do is post in our community and collaborate with other members:

http://emby.media/community/

Book support was added by a community developer in the form of a plugin called BookShelf, and unfortunately I cannot really speak to the functions that the plugin supports. At the very least, you should make sure to have it installed, it's available in the server plugin catalog. Thanks.
