### ISSUE TITLE
[FEATURE REQUEST] Add disk space check and notifications

### ISSUE THREAD

**Issue by michaeljbailey** [MediaBrowser/Emby#1760]
I run Emby on a dedicated VM and every now and then I'll notice that it stops updating some of the content on the server. When I notice, it's almost always because my VM ran out of disk space and I have to remote into it to manually confirm and expand the disk.

Can you add a disk space check and notification to the GUI? It would go a long way towards me realizing this in advance of having to check out the VM manually.

**Comment by LukePulverenti** [comment]
Hi there @michaeljbailey, I would suggest posting about this in our community to potentially encourage a community member to build a plugin:

https://emby.media/community/

I think it is unlikely this will become a point of focus for the core Emby team. Thanks !
