### ISSUE TITLE
DLNA crashes when trying to get movies list

### ISSUE THREAD

**Issue by topjor** [MediaBrowser/Emby#1763]
When trying to get the list of movies or tv series DLNA crahses
here is the error. it seems like there is a column missing in the database.
i have done a clean install to make sure it was not something else that messed up the database.
I did first time setup, with library and tested DLNA again. no settings were changed. music works fine
[stacktrace.txt](https://github.com/MediaBrowser/Emby/files/276498/stacktrace.txt)

**Comment by LukePulverenti** [comment]
Thanks!
