### ISSUE TITLE
When upgrading Emby Server for Windows, check for service

### ISSUE THREAD

**Issue by nexxai** [MediaBrowser/Emby#1764]
In Windows, I have Emby Server installed as a service.  When I go to upgrade the server, I stop the service, run the installer, but then the installer starts the server app as an interactive process, which I then have to kill and then start the service manually.  Normally this isn't _too_ much of a problem (more just annoying than anything) but with the upgrade to .5970, the DB upgrade started and I have to wait (hours) for it to finish so that the DB upgrade doesn't break.

What I was wondering is if in the installer/upgrader, there could be a check to see if the server is installed as a service, and if so, just start the service rather than running the app interactively.

**Comment by jpdillingham** [comment]
Is the source for the installer/updater available?  I see the binaries in the "Tools" folder but that's it.

**Comment by gerritv** [comment]
@LukePulverenti If we can get source for the updater then I am willing to have a go at this. Or some hints on the Setup/Updater flow. Trolling the source tree hasn't provide a way into solving the problem.

**Comment by gerritv** [comment]
I think this is a user error Issue, not a defect/missing functionality.

Looking at the source code, MediaBrowser.ServerApplication:MainStartup.cs checks to see if running as a service as part of its PerformUpdateIfNeeded() code. It would appear that if you are running MB as a service, you should not stop the service prior to doing the update. Updater.exe (which I can't see the source code for??)  is passed the service name to restart after the update completes.

So the solution is: don't stop the service prior to doing an update.

**Comment by LukePulverenti** [comment]
Occasionally an update will require user interaction, therefore I don't think this is something we want to do. You guys are encouraged to try the new .NET Core version of Emby Server which is currently in testing, and there is a new process for the Windows Service:
https://emby.media/community/index.php?/topic/50012-emby-server-for-net-core/

Thanks.
