### ISSUE TITLE
IsInLocalNetwork returns wrong value

### ISSUE THREAD

**Issue by J4nsen** [MediaBrowser/Emby#1769]
Hi, in BaseNetworkManager.cs (Line 122) an IPv4 adress is assumed local if IsInPrivateAddressSpace (Line 77) returns true. 
IsInPrivateAddressSpace returns true if a string comparison against 192, 127... etc matches.

However, I'm accessing Emby via OpenVPN, hence I get falsely marked as local. A match against the subnet would fix this. (e.g. http://stackoverflow.com/questions/1499269/how-to-check-if-an-ip-address-is-within-a-particular-subnet)

Thanks for this nice software!

**Comment by LukePulverenti** [comment]
Thanks, will take a look, and/or pull requests are welcome :)

**Comment by J4nsen** [comment]
Hi Luke, I thought so :).  I will try to create a pull request. Currently I'm on a Linux only machine. I assume the easiest way to test my code is to install Visual Studio in a Windows VM?

**Comment by LukePulverenti** [comment]
probably yes, or mono develop.
