### ISSUE TITLE
Detecting Browser as device bug

### ISSUE THREAD

**Issue by wirehack7** [MediaBrowser/Emby#1779]
There is an issue with version 3.0.5971.0 for Emby Server on Linux (I'm using Debian 8):
A Browser model is detected as one Device, despite the fact that seperate users are using the same browser model, but for theirself.
Example: 

- User A uses latest Chrome for Windows, has T as ISP and an own IP (let's call that 3)
- User B uses latest Chrome for Windows, has X as ISP and an own IP (let's call that 4)

What's happening now is: only one folder in ```/var/lib/emby-server/data/devices/``` will be created, for one device: the Chrome Browser. The problem which is occuring is then that watched movies, episodes etc get out of sync. Because User B watches Episode 4, progress processes. Then User A watches Episode 30. But he sees that that he should continue Episode 4. 

In Admin Dashboard only one user is shown watching, despite the fact that both are watching.

I hope I wrote that in a understandable way.

**Comment by SvenVandenbrande** [comment]
@wirehack7 this is still an issue? Or it's already solved in newer versions?

**Comment by LukePulverenti** [comment]
Resolved via 465ac8c62587f688703e1423872aed7f5c2d2f38
