### ISSUE TITLE
iPad app only shows "Collections" under My Media

### ISSUE THREAD

**Issue by tylerapplebaum** [MediaBrowser/Emby#1787]
![img_2052](https://cloud.githubusercontent.com/assets/8419153/15630767/b21cd088-24fd-11e6-8eae-97372882d291.PNG)

I'm on server 3.1.1.0 beta.

**Comment by LukePulverenti** [comment]
Thanks for testing beta. This should be resolved with the newer builds.

**Comment by tylerapplebaum** [comment]
Ok, thanks. I ended up having to reassign the permissions on the user account in order for them to view the libraries they previously had permission to view.
