### ISSUE TITLE
[Feature Request] Auto Organize: Also check folder name

### ISSUE THREAD

**Issue by horstepipe** [MediaBrowser/Emby#1816]
At the moment auto organize feature only checks file names.
But it's very common that the folder containing the episode has the "utilizable" pattern and the file name is just unreadable.
For example:
**Folder name:** Game.of.Thrones.S06E06.Blut.von.meinem.Blut.German.DD51.Synced.DL.1080p.AmazonHD.x264-TVS
**File name**
tvs-got-dd51-sed-dl-18p-azhd-x264-606.mkv

So please make it work similar to this:
- First check file name
- if no matches found, check parent folder name

**Comment by LukePulverenti** [comment]
Closing - auto-organize will soon be moved to a plugin, and the community will have more freedom to help add new features to it. Thanks !
