### ISSUE TITLE
[Feature Request] auto-lock tags in tv shows

### ISSUE THREAD

**Issue by horstepipe** [MediaBrowser/Emby#1817]
I see no reason why tv show tags should be marked as active for data changes by default.
Refreshing a TV show always clears the field. But if tags exist, they are always created by user and the user wants them to persist.

**Comment by LukePulverenti** [comment]
Maybe there was an issue with older versions of the server but I can't reproduce the problem. I tested adding tags to both Series and Episodes, refreshed, and the data remained.
