### ISSUE TITLE
[Feature Request] start scheduled task after other task finishes

### ISSUE THREAD

**Issue by horstepipe** [MediaBrowser/Emby#1818]
instead of specify the time for a task, it would be nice if you could say:
start task a after task b has finished.
On lower powered servers it is more safe to run only one task at once, and on this way there would be no loss of time between the tasks.

**Comment by LukePulverenti** [comment]
I don't want the tasks to be this complicated. If this much setup is required, we've done something wrong. Instead we could do some kind of setting such as "allow only one task at a time". something along those lines.
