### ISSUE TITLE
[Feature Request] Hardware accelerated media transcoding/encoding Raspberry Pi

### ISSUE THREAD

**Issue by joaodriessen** [MediaBrowser/Emby#1833]
Emby is fantastic!
I run it on my raspberry Pi and came across a fantastic development in the FFmpeg (originally from forked Libav project)
H.264 and MPEG4 encoders using OpenMAX IL.
This means the Raspberry Pi is capable of encoding/transcoding video on the fly. Which is absolutely necessary over the internet!
Are you aware of this capability and is there any chance this can be implemented?

**Comment by LukePulverenti** [comment]
This has been added to the new stable release, 3.0.5984. It is bring your own ffmpeg though, and then the server will utilize it.
