### ISSUE TITLE
Prioritize movie.nfo when it exists

### ISSUE THREAD

**Issue by twarkie** [MediaBrowser/Emby#1849]
Currently, if there are multiple NFO files present, only the first one is used during scraping. This gets problematic when there is a movie.nfo and a filename.nfo. In my case the latter is useless for Emby and the result is that most of my movies are not scrapable.

The default setup for Kodi is that "movie.nfo will override all and any .nfo files in the same folder". It would be great if the same could be implemented for Emby.

Thoughts?

**Comment by Jellyfrog** [comment]
I've been looking for this too

> movie.nfo will override all and any .nfo files in the same folder as the media files if you use the "Use foldernames for lookups" setting. If you don't, then moviename.nfo is used
http://kodi.wiki/view/NFO_files/Movies

**Comment by LukePulverenti** [comment]
But it also says if you use the "Use foldernames for lookups" setting. What is the default out of box setting for that?

**Comment by LukePulverenti** [comment]
Anyone?
