### ISSUE TITLE
User can access all media when restrictions are set.

### ISSUE THREAD

**Issue by pankookis** [MediaBrowser/Emby#1887]
Using version 3.1.44.0

Even though restrictions are set between users, if I search, media that the specific user shouldn't have access to shows up and can be played.

Example: A friend of mine can access my home videos without access set in the dashboard. This can be done if for example the user searches for "beach" and I have a home video called "beach with dog.mkv" will show up and can be played.

**Comment by LukePulverenti** [comment]
Resolved in 3.1.48+
