### ISSUE TITLE
Emby crash

### ISSUE THREAD

**Issue by danergo** [MediaBrowser/Emby#1946]
Hi!

I'm running Emby on linux with mono.
It worked very well for the last few months, however now it is crashing.
Please find the crashlog here: http://pastebin.com/7gpGHfVN

Could you recommend me something? I can't reach the web console, so I'm not able to enable verbose logging.

Thank you.

**Comment by LukePulverenti** [comment]
Please make sure to attach complete logs, thanks.

**Comment by danergo** [comment]
Sorry for that, here is the complete log:
http://pastebin.com/CpLDg0ca

**Comment by LukePulverenti** [comment]
Ok, since you're running an older version of the server, I would start by updating to the latest version.

**Comment by danergo** [comment]
Okay.
This was a hw issue. HDD had spun down and didn't restart due to a power outage.

Please close this issue.
