### ISSUE TITLE
File/Folder naming patterns

### ISSUE THREAD

**Issue by kronflux** [MediaBrowser/Emby#1947]
In each location where naming patterns can be used(ie: the season folder naming convention) there should be clearer options for what patterns work.
Unfortunately in my searching, I also couldn't find a pattern that would result in release year(example: "Season 1 (2016)")
So I'd love to see a Year pattern be added. Right now I can obviously use %s as the season number, perhaps %y for release year?

**Comment by LukePulverenti** [comment]
Everything that is supported is listed in the naming wiki, including examples:

Movies - https://github.com/MediaBrowser/Wiki/wiki/Movie%20naming
https://github.com/MediaBrowser/Wiki/wiki/TV%20naming

Season folders are probably the one area that could use some discussion in the wiki but to answer the question, it's "Season X", "X", or "Anything", where "Anything" is just an arbitrary name for a season without a number attached.

**Comment by kronflux** [comment]
In this case, I was more referring to the specific case of season folder naming including the year.
I completely understand variables and/or wildcards.
I absolutely know that "Season %s" results in "Season 1" for example, but I was hoping that either a Release Year variable either exists already, or could be added.
Such that would result in "Season %s (%y)" which would provide "Season 1 (2016)" for example.

The web interface actually does have a basic rundown of these variables, however none is listed for Year.

**Comment by LukePulverenti** [comment]
We don't do anything with that value, so Season 1 (2016) is still season 1.

**Comment by kronflux** [comment]
I think you're missing my point entirely. perhaps another can be assigned to this ticket? No offense intended.

I'm specifically **-requesting-** that a value be added for automatic folder naming under:
Auto-Organize > TV > Season Folder Pattern
for release year (%y was an example for what could be used as the year variable name)
as currently it only allows %s, which is season number.

I don't really care how emby detects it in the library, but this is how I (and many others) store TV shows. (example: Show Name > Season X (YEAR) > Episode 1.mp4)

**Comment by LukePulverenti** [comment]
Ok I see. Yes I guess this is possible but since it it organizes that one episode you might not be happy if you end up with two folders for the same season because it went through December past January of the next year. Obviously there is a solution to that but now in order to organize an episode we have to go and get info about the first episode of the season.

**Comment by kronflux** [comment]
Ah yes, I see the issue.
Perhaps look for episode 1, grab the release date - if no episode 1 is found when organizing, simply fallback to a non-year season folder?

either way, I understand the issue, thanks for pointing it out. hopefully there will be a solution to it :)

**Comment by LukePulverenti** [comment]
This ticket is likely to remain here in limbo indefinitely, therefore I'm going to close it. Please open a discussion topic in our community:

https://emby.media/community

If we see enough demand for this enhancement then we'll be happy to add it. Thanks !
