### ISSUE TITLE
locked out of account when resetting password via webinterface

### ISSUE THREAD

**Issue by kugelzucker** [MediaBrowser/Emby#1948]
after setting a password for an account AND setting up the easy pin too i needed to authenticate. so far so good. i reset the password using the webinterface which made the easy-pin-dialogue go away as well. i was unable to log in after that using the emby app on my fireTV.

possible that some things are going wrong there?

**Comment by ebr11** [comment]
Can you please describe exactly what happens when you try to log in?  Also, had you set up the FTV to automatically log in to that person and remember the password?

**Comment by kugelzucker** [comment]
sorry, had notifications disabled. i dont recall, but ill try again and report back.
