### ISSUE TITLE
Wrong input being passed to ffmpeg for .iso files

### ISSUE THREAD

**Issue by fluver** [MediaBrowser/Emby#1952]
Tried to play a bluray.iso and experienced an error:
```
Info App: Mounting /mnt/Movies/2022/This.is.a.Movie/bluray.iso...
Info App: /mnt/storage/2022/This.is.a.Movie/bluray.iso mounted to /tmp/mediabrowser/6c111ccb-6e37-4d4d-9423-c2f355b60b9e
Info App: /usr/bin/ffmpeg -fflags +genpts -i file:"/mnt/storage/2016/This.is.a.Movie/bluray.iso" [options] -y "/var/lib/emby-server/transcoding-temp/4510b3636c9f6312a3844d65609271c8.mkv"
Info App: Unmounting /tmp/mediabrowser/6c111ccb-6e37-4d4d-9423-c2f355b60b9e...
Info App: FFMpeg exited with code 1
```
Notice the iso file being passed to ffmpeg instead of the acutal video files in 
"/tmp/mediabrowser/6c111ccb-6e37-4d4d-9423-c2f355b60b9e/BDMV/STREAM/"
Runnign ffmpeg against one of the discs video files produces the correct transcode:
`
/usr/bin/ffmpeg -fflags +genpts -i file:"/tmp/mediabrowser/6c111ccb-6e37-4d4d-9423-c2f355b60b9e/BDMV/STREAM/00811.m2ts" [options] -y "/var/lib/emby-server/transcoding-temp/4510b3636c9f1232a3844d65609271c8.mkv"
`

**Comment by LukePulverenti** [comment]
Try refreshing the title from the detail screen to allow it to fill in media info.  Given enough media info, it should use the mounted m2ts path.

**Comment by LukePulverenti** [comment]
Any result?
