### ISSUE TITLE
Title does not reset on home browse (Web Interface)

### ISSUE THREAD

**Issue by kronflux** [MediaBrowser/Emby#1958]
If you select a show or movie using the web interface, then navigate back home, the html "title" tag of the website does not reset back to "Emby" as it should, and instead still shows the show or movie name in the browser titlebar.

**Comment by anderbytes** [comment]
I've already posted that bug in forum. Seems easy, but nobody gave much importance

**Comment by anderbytes** [comment]
Thanks for fixing!!
