### ISSUE TITLE
Feature Suggestion:  Lock user logon to specific ip range/network

### ISSUE THREAD

**Issue by Luticus** [MediaBrowser/Emby#1981]
I just became an Emby lifetime supporter and love the product, but one thing I'd REALLY love to see added is the ability to optionally lock logins for certain user accounts to just my home network.  I would need this feature on a per account basis.  IE:  some accounts may log in remotely, but some accounts may only log in from a device on the local network/subnet.  Locking them via CIDR notation would be perfect.  

Thanks!

**Comment by LukePulverenti** [comment]
In the next release of Emby Server you'll be able to configure remote access on a per-user basis. Thanks.
