### ISSUE TITLE
Collections doesn't respect UserPolicy

### ISSUE THREAD

**Issue by 7illusions** [MediaBrowser/Emby#2008]
When looking at Collections under Movies, ALL server collections are returned.
Expected behavior would be to only include the ones under the parentID OR at least what the user has access to. (Kids seeing parents collections etc.. they can't play it anyways, but they see the posters)

**Comment by LukePulverenti** [comment]
Thanks, yes known issue right now. It does respect parental rating and blocking via tags but not library separation.
