### ISSUE TITLE
[Feature Request] Ability to hide Movie: prefix before searching metadata providers

### ISSUE THREAD

**Issue by denz2** [MediaBrowser/Emby#2010]
I am subscriber to IceTV tv guide service and each movie has a Movie: prefix I personally like that very much that in the tv guide it shows that prefix but the consequence is that I don't get any thumbnails for movies or if I do most of the time they are wrong ones.   

Thank you

**Comment by LukePulverenti** [comment]
Is this still needed? I have seen your newer screenshots generally do not have the Movie: prefix anymore. Thanks !

**Comment by denz2** [comment]
Hi Luke, I am using a workaround downloading the file then using an application called f.a.r.t to remove Movie: prefix.

I would prefer that I just use the url as there is less things to go wrong and since here there is not many movies it is very helpful when you see it in the guide in emby I use upcoming movies but it would be great if in the guide the movie stands out.

Thank you.

Get Outlook for Android<https://aka.ms/ghei36>



On Mon, Nov 14, 2016 at 4:18 AM +0800, "Luke" <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this still needed? I have seen your newer screenshots generally do not have the Movie: prefix anymore. Thanks !

-

**Comment by LukePulverenti** [comment]
Are you saying you can't control these prefixes being applied? If so then that makes this a bit more urgent. I had thought all along you were just adding the prefixes as a preference.

**Comment by denz2** [comment]
Hi Luke, No they were always there. In my guide data provider there is a setting to not show movie prefix but what that does is only not show it wmc guide I guess it does this because I have their application installed that does the import into wmc sees this setting and when it does the conversion to mxf removes it but this setting has no effect on the xmltv file that I or any one else downloads.

So that is why I have to use 2 more utilities before it gets imported into emby and it will be preferable if they weren't needed. But would prefer if in the guide the movie prefix would show.

Thanks

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by LukePulverenti** [comment]
This will be in the next set of test builds, thanks.
