### ISSUE TITLE
WD Nas support

### ISSUE THREAD

**Issue by StevenRudenko** [MediaBrowser/Emby#2015]
I am wondering whether there is a plan to support WD Nas as server.
Here is list of devices where Plex works so I think it should be possible to have Emby work too:
WD MyCloud EX2, WD MyCloud EX2 Ultra, WD MyCloud EX4, WD MyCloud EX2100 and WD MyCloud EX4100 (arm based), WD MyCloud DL2100 and WD MyCloud DL4100 (Intel based), WD MyCloud PR2100 and MyCloud PR4100

**Comment by LukePulverenti** [comment]
Hi, while we don't have a one-click package at this point, you should be able to follow the manual setup instructions on the linux download page:

http://emby.media/linux-server.html

**Comment by StevenRudenko** [comment]
event with SSH access to WD MyCloud EX2, I didn't find way to install anything manually. Installation needs restart and after restart I see blank folders without anything I did before.

**Comment by LukePulverenti** [comment]
Closing in favor of #3298 

Please continue discussion there. Thanks.

**Comment by LukePulverenti** [comment]
You can participate in testing here: https://emby.media/community/index.php?/topic/59597-emby-server-for-western-digital-nas/

Thanks guys.
