### ISSUE TITLE
[Feature Request] Store configuration and other data file in seprate directory.

### ISSUE THREAD

**Issue by fanthos** [MediaBrowser/Emby#2067]
I am running Emby on Linux, and using a small SSD as system drive, but other data files and temporary files need lots of space to store them so I put them on another HDD.
I hope I can configure it so I don't need to create many symbolic links in data directory.

**Comment by LukePulverenti** [comment]
Hi, in the Emby web interface you can configure the cache location and metadata location. These are the two locations that take up by far the most space used by Emby. Is this what you're looking for?
