### ISSUE TITLE
Vaapi broken for graphical subs

### ISSUE THREAD

**Issue by uglymagoo** [MediaBrowser/Emby#2165]
BaseStreamingService.GetGraphicalSubtitleParam does not add "format=nv12|vaapi,hwupload" if vaapi is used, so ffmpeg exits with e.g. "Impossible to convert between the formats supported by the filter 'Parsed_overlay_3' and the filter 'auto-inserted scaler 1'" at least in HLS streaming (VideoHlsService.GetVideoArguments calls GetGraphicalSubtitleParam but not GetOutputSizeParam for graphical subtitles).

Btw: Why is there so much duplicate code in MediaBrowser.Api and MediaBrowser.MediaEncoding? Above problem affects both.

**Comment by uglymagoo** [comment]
I am currently unable to get ffmpeg 3.1.3 to utilize vaapi to burn my subtitles into the video, at all. I will provide more details in this issue once I found the solution.

**Comment by uglymagoo** [comment]
Ah, I got it. The -hwaccel_output_format is the problem.

**Comment by uglymagoo** [comment]
Fixed it in #2167

**Comment by LukePulverenti** [comment]
Thanks !
