### ISSUE TITLE
Search needs improvment

### ISSUE THREAD

**Issue by Luticus** [MediaBrowser/Emby#2172]
Emby search is borderline useless in the web portal because it doesn't offer any kind of result filtering.  If I search for a show it might return the show entry, all the various episodes, and the cast and crew pages.  If I search for a movie and there are music, shows, or bands with similar names, it will return everything, and in many cases will actually miss results.  Emby search should have filters so I can specify if I want results to include episodes, cast and crew, various other libraries, etc.  When I go to netflix and search for a show I get only the show in the results, not all it's episodes and everything that has to do with it.  Emby would be much better if search behaved like search on netflix, or at least offered a way to filter out bad results.

**Comment by anderbytes** [comment]
I already created one feature request in forum about hiding episodes from searches. Still nothing so far...

**Comment by mashranga** [comment]
Really search is surprisingly useless !! Need update on this feature.  Also needs different filtering option like year, IMDB ranking, genre and so on.

**Comment by anderbytes** [comment]
Hey @LukePulverenti , I didn't notice the difference for the old search. What has changed?

Can't you please make the search also find stuff in "Original Title"??? Is this difficult?

**Comment by Luticus** [comment]
I noticed the difference right away.  The search results are organized much better and has become much more usable.  Although you can't filter the list other than by the origional search query, it is still much better than before.

Thanks!


Thanks,

Joe McEntire
getjoe@live.com
On May 8, 2017, at 6:56 AM, anderbytes <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey @LukePulverenti<https://github.com/LukePulverenti> , I didn't notice the difference for the old search. What has changed?

Can't you please make the search also find stuff in "Original Title"??? Is this difficult?

**Comment by anderbytes** [comment]
Hmmm yeah they are more organized than before. That's cool.

I may be too demanding but... wouldn't be much better to allow admin to enable/disable which sections are searched? (Movies/Shows/Episodes/People/Artists...etc...)

Because: In my case I'll never search anything of a specific episode (don't see the point), but CPU and network are being spent anyway.
