### ISSUE TITLE
Live TV program information does not appear in guide or channel

### ISSUE THREAD

**Issue by DomenicTroilo** [MediaBrowser/Emby#2190]
I have installed the LiveTV Plugin for VDR https://emby.media/community/index.php?/topic/21231-vdr-plugin-development/ and have made some changes (see the link above)  I don't belive I am missing any data when it is imported, 

I have attacched a log of the import and a viewing of the data.  And a snapshot of the display.

Can anyone take a look?

**Comment by DomenicTroilo** [comment]
![screenshot_2016-09-24-21-24-56](https://cloud.githubusercontent.com/assets/2089542/18816443/c7ade156-830f-11e6-94ee-317f2f6265fc.png)
[server.example.txt.zip](https://github.com/MediaBrowser/Emby/files/491749/server.example.txt.zip)

**Comment by LukePulverenti** [comment]
Hi, we can continue this in the emby community, where there is already active discussion. thanks.

**Comment by DomenicTroilo** [comment]
sorry I thought this would be the place to discuss issues rather than in the fourm

**Comment by LukePulverenti** [comment]
No problem !
