### ISSUE TITLE
More raw image format support

### ISSUE THREAD

**Issue by fanthos** [MediaBrowser/Emby#2193]
NRW is already supported by imagemagick, so please support NRW and some other raw types in Emby.

After install imagemagick on linux machine, run `identify -list format` shows all supported formats.

**Comment by fanthos** [comment]
Is it OK to make raw type extension configurable, so I can add new file extension that already supported by ImageMagick to my photo library?

https://github.com/MediaBrowser/Emby/blob/master/Emby.Drawing/ImageMagick/ImageMagickEncoder.cs#L35

**Comment by LukePulverenti** [comment]
There is nothing wrong with that, but then again why not just add them to the core for everyone to take advantage of. What formats are they?

**Comment by fanthos** [comment]
Thanks.
I owe a Nikon P7700 that using NRW extension and already supported by ImageMagick. Some other file types are ERF by Epson, RAF by Fujifilm and RW2 by Panasonic.

**Comment by fanthos** [comment]
Thanks for the update, but NRW used by some Nikon devices is not in the list.

**Comment by LukePulverenti** [comment]
Ok, I'll add that, thanks.
