### ISSUE TITLE
Transcoding options broken for libx264-10bit 2:148.20160613

### ISSUE THREAD

**Issue by bsdfirst** [MediaBrowser/Emby#2197]
It seems that the above version of `libx264` requires the `high10` profile to be used to support 10bit output.  Emby appears to hardcode the profile to `high` in the file:

`Emby/MediaBrowser.MediaEncoding/Encoder/BaseEncoder.cs`

I can confirm that switching to the `high10` profile resolves the issue.  I am running Archlinux which tends to be at the bleeding edge with package versions.  I couldn't find any reference to anyone else experiencing this issue, thus it may be sentinel with new versions of `libx264`.  Or I'm doing it wrong...

This error is evidence when attempting to stream non x264 media to a Chromecast.

Versions:

```
libx264-10bit 2:148.20160613-2
ffmpeg 1:3.1.3-2
emby-server 3.0.7200-1
```

The ffmpeg error is as below:

```
{"Protocol":"File","Id":"5d07cf2bba4a3d6dc9ab3e9b0e1c070b","Path":"/file.avi","Type":"Default","Container":"avi","Name":"SD/MPEG4/MP3","ETag":"5a683ac4446e4afb48c54b6cf7349ca6","RunTimeTicks":61291290000,"ReadAtNativeFramerate":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"RequiresOpening":false,"RequiresClosing":false,"VideoType":"VideoFile","MediaStreams":[{"Codec":"mpeg4","CodecTag":"XVID","TimeBase":"125/2997","CodecTimeBase":"125/2997","IsInterlaced":false,"BitRate":807883,"RefFrames":1,"IsDefault":false,"IsForced":false,"Height":240,"Width":576,"AverageFrameRate":23.976,"RealFrameRate":23.976,"Type":"Video","AspectRatio":"2.40:1","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p","Level":-99,"IsAnamorphic":false},{"Codec":"mp3","TimeBase":"3/125","CodecTimeBase":"1/48000","DisplayTitle":"MP3 stereo","IsInterlaced":false,"ChannelLayout":"stereo","BitRate":132136,"Channels":2,"SampleRate":48000,"IsDefault":false,"IsForced":false,"Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0}],"PlayableStreamFileNames":[],"Formats":[],"Bitrate":952729,"RequiredHttpHeaders":{}}

/usr/bin/ffmpeg -fflags +genpts -i file:"/file.avi" -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -force_key_frames "expr:gte(t,n_forced*5)" -vf "scale=trunc(min(max(iw\,ih*dar)\,720)/2)*2:trunc(ow/dar/2)*2" -copyts -avoid_negative_ts disabled -start_at_zero -pix_fmt yuv420p -preset veryslow -crf 23 -b:v 807883 -maxrate 807883 -bufsize 1615766 -vsync -1 -profile:v high -level 41 -map_metadata -1 -threads 0 -codec:a:0 copy -y "/tmp/emby-server_trans/transcoding-temp/9aeba931324fe71d1cbb1a466e046d85.mkv"


ffmpeg version 3.1.3 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 6.2.1 (GCC) 20160830
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-netcdf --enable-shared --enable-version3 --enable-x11grab
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 48.101 / 57. 48.101
  libavformat    57. 41.100 / 57. 41.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 47.100 /  6. 47.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
Input #0, avi, from 'file:/file.avi':
  Metadata:
    encoder         : Nandub v1.0rc2
  Duration: 01:42:09.13, start: 0.000000, bitrate: 952 kb/s
    Stream #0:0: Video: mpeg4 (XVID / 0x44495658), yuv420p, 576x240 [SAR 1:1 DAR 12:5], 807 kb/s, 23.98 fps, 23.98 tbr, 23.98 tbn, 23.98 tbc
    Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, s16p, 132 kb/s
Incompatible pixel format 'yuv420p' for codec 'libx264', auto-selecting format 'yuv420p10le'
x264 [error]: high profile doesn't support a bit depth of 10
[libx264 @ 0x55558869f7e0] Error setting profile high.
[libx264 @ 0x55558869f7e0] Possible profiles: baseline main high high10 high422 high444
Output #0, matroska, to '/tmp/emby-server_trans/transcoding-temp/9aeba931324fe71d1cbb1a466e046d85.mkv':
    Stream #0:0: Unknown: none, SAR 1:1 DAR 0:0
    Metadata:
      encoder         : Lavc57.48.101 libx264
    Stream #0:1: Unknown: none
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg4 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (copy)
Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
```

**Comment by LukePulverenti** [comment]
I think we should just force 8-bit output because not all devices are going to be able to play 10-bit.

**Comment by bsdfirst** [comment]
I've had a dig around.  It appears to be a compile time option.  ffmpeg is either linked against an 8bit OR a 10bit libx264.  I can't see a way to force 8bit h264 when compiled against the 10bit library (which is the default in Arch).

Basically, the whole thing is getting forced to 10bit (despite the `high` profile being 8-bit) because of this:
```
Incompatible pixel format 'yuv420p' for codec 'libx264', auto-selecting format 'yuv420p10le'
```

We are already specifying `-pix_fmt yuv420p` but the `libx264` codec is forcing a switch to the `yuv420p10le` colour space.  Which then causes and error because the `high` profile is also forced on the commandline.

One solution could be to abstract the `-profile` parameter to allow the user to choose between `high` and `high10` in the config?  That may not be desirable though - I'm pretty new to Emby (okay...2 days now) but the philosophy seems to be "just work" without exposing lots of complex options to the user.

I'll keep looking, but at the moment I don't see another obvious solution that won't break things as people shift to `libx264-10bit`.  (Short of shipping a statically compiled ffmpeg as part of the build.)

**Comment by LukePulverenti** [comment]
That is possible but it's not an end to end solution. If we fix that, then the next problem that will be reported is video not playing when the client app does not support 10-bit output.

We have some validation relating to the user's installed ffmpeg build, for example, we reject really old versions as well as libav forks. So perhaps this should be incorporated and just not allow the server to use it. What will happen in this case is the user will be given a choice between either updating their installed version, or they can just download a standalone copy to the folder of their choice and point emby to that folder.

**Comment by bsdfirst** [comment]
Yeah.  Being able to change the path to `ffmpeg` would solve the problem for advanced users (and those are going to be the users that have managed to install the 10bit version of `libx264`).  I suspect the problem will crop up again as the 10bit version of the library starts to become the default across other distros.

I don't think there is a single easy answer.  On a positive note however, I have replaced the `libx264-10bit` package with the `libx264` package.  It satisfies the same packaging depend for `ffmpeg` and installs the same library in the same location - so it's all good from a linking perspective.

I've only tested on the commandline not in Emby proper, but that certainly seems to work.  So perhaps the short term answer is to check the `libx264` version as part of your ffmpeg validation?

**Comment by LukePulverenti** [comment]
if you run ffmpeg -encoders what is the output?

**Comment by bsdfirst** [comment]
[ffmpeg-enconders-8bit.txt](https://github.com/MediaBrowser/Emby/files/499242/ffmpeg-enconders-8bit.txt)
[ffmpeg-enconders-10bit.txt](https://github.com/MediaBrowser/Emby/files/499243/ffmpeg-enconders-10bit.txt)

**Comment by bsdfirst** [comment]
Identical if you were hoping to use that for detection...

**Comment by LukePulverenti** [comment]
installing ffmpeg gives users a choice between libx264 and libx264-10bit, the former being the default choice. libx264-10bit is indeed incapable of outputting 8bit content though.

Right now we would just prefer to require 8-bit than attempt to support both. thanks.
