### ISSUE TITLE
Current .WTV thumbnail generation method takes too long

### ISSUE THREAD

**Issue by Lord-Malgus** [MediaBrowser/Emby#2203]
Currently Emby with ServerWMC generates thumbnail images using ffmpeg:

Example syntax:

`"D:\ffmpeg\ffmpeg.exe" -i file:"D:\Recorded TV\Blindspot_WGALHD_2016_05_09_22_00_00.wtv" -map 0:v:1 -threads 0 -v quiet -vframes 1 -vf "scale=600:trunc(600/dar/2)*2,thumbnail=30" -f image2 "E:\1f0b323e-e250-4c48-8446-caedb11025c9.jpg"
`

However this method appears to incur a long duration to complete (sometimes VERY long).  I believe something has changed in the way ffmpeg is handling this thumbnail generation with WTV.  After some testing,  the thumbnail=30 method appears to be semi-broken with WTV.  Dropping this flag seems to be a good workaround as thumbnail generation completes instantly from my tests.

With the current method of using thumbnail=30, a backlog of ffmpeg instances can occur, with over 20+ instances running at once.  This can heavily impact a media PC.

**Comment by LukePulverenti** [comment]
Resolved in beta.
