### ISSUE TITLE
Major Stability issues

### ISSUE THREAD

**Issue by FoxUSA** [MediaBrowser/Emby#2221]
![image](https://cloud.githubusercontent.com/assets/886680/19295939/db208f6a-8fec-11e6-851a-fa54524d7b7f.png)

I have a lifetime subscription if that means anything. 
For the past few months the server will randomly crash.

Seems consistently with the mobile apps.
I can stream from the web app.

Also there are random issues with gibberish subtitles coming up by default.
Running Ubuntu 16.04

**Comment by LukePulverenti** [comment]
Hi there, sorry to hear about this. Can you please provide a server log from the timeframe of encountering this issue? Instructions are here:

https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/
Thanks !

**Comment by FoxUSA** [comment]
@LukePulverenti 
![image](https://cloud.githubusercontent.com/assets/886680/19413381/4338c23e-92e0-11e6-9544-bcdf6570aa34.png)
Radom subtitle pic

Logs
[Log5.txt](https://github.com/MediaBrowser/Emby/files/531460/Log5.txt)
[Log4.txt](https://github.com/MediaBrowser/Emby/files/531461/Log4.txt)
[Log3.txt](https://github.com/MediaBrowser/Emby/files/531462/Log3.txt)
[Log2.txt](https://github.com/MediaBrowser/Emby/files/531458/Log2.txt)
[Log.txt](https://github.com/MediaBrowser/Emby/files/531459/Log.txt)

**Comment by LukePulverenti** [comment]
Hi, can you please try the latest release of the server? Also, when uploading a log file, please indicate the problem that was experienced during the time of that particular log. Thanks !
