### ISSUE TITLE
Halloween theme can't be permanently disabled and is loaded over http

### ISSUE THREAD

**Issue by ForsakenHarmony** [MediaBrowser/Emby#2260]
As the title says, the Halloween theme can't be permanently disabled, it is reactivated on reload, pressing no in the continue option thing doesn't change that, even disabling "Enable theme songs" under display options doesn't change anything

The other thing bothering me is chrome complaining that one thing is loaded over http instead of https, which is the song

**Comment by LukePulverenti** [comment]
Fixed via 75798465e1e3a8ea6edd505e8a6189b27edfb925
