### ISSUE TITLE
Trying to click a actionSheetMenuItem in Chrome gives "TypeError: undefined is not a function"

### ISSUE THREAD

**Issue by kreiger** [MediaBrowser/Emby#2261]
The first few clicks produce nothing except leaving behind a translucent circle where i clicked, then i start getting:

```
router.js?v=3.0.8300.0:283 embyRouter - processing path request /web/index.html
router.js?v=3.0.8300.0:304 embyRouter - user is authenticated
router.js?v=3.0.8300.0:283 embyRouter - processing path request /web/home.html
router.js?v=3.0.8300.0:304 embyRouter - user is authenticated
router.js?v=3.0.8300.0:325 embyRouter - proceeding to /web/home.html
router.js?v=3.0.8300.0:373 Uncaught TypeError: undefined is not a function
```

router.js line 373 says

```
skinManager.getCurrentSkin().showBackMenu().then(function () {
```

So i guess the current skin is undefined?

**Comment by LukePulverenti** [comment]
Hi, is this still an issue? I have not been able to reproduce this. Thanks !

**Comment by kreiger** [comment]
Hi! I upgraded my Chrome, which was like a half dozen versions behind, and the problem went away. So i guess the actionSheetMenuItems relies on some newer HTML 5 API for clicks to work?

**Comment by LukePulverenti** [comment]
Thanks for the info. So you think it was about a half dozen? Just trying to get sense of  how far back it was.

**Comment by kreiger** [comment]
I think it might have been something like Chrome version 38 or 36.

**Comment by LukePulverenti** [comment]
Thanks. We'll close and see if it comes up again.
