### ISSUE TITLE
Viewing images/videos in collections does not go between libraries

### ISSUE THREAD

**Issue by mitch10102000** [MediaBrowser/Emby#2306]
I am running Emby Server version 3.0.8500.0 on a CentOS Linux box.
This issue arises in both the web client and Android App.

Issue:
I have created a collection of photos from two different photo libraries (Library A and Library B).  When I look at the collection of photos in the folder, it looks good.  All of the photos show up in the collection as they should from the selected photos in each library.  

The issue arises when I start viewing the photos with the Emby viewer.  If I start viewing a photo in the collection that is from Library A, thew viewer sticks with Library A and never displays any of the photos in Library B.  In fact, as I view, it just keeps going with Library A, even if some of the photos aren't in the collection.

Here is an example of the issue.
Library A has photo1a, photo2a and photo3a
Library B has photo1b, photo2b and photo3b

Collection has photo1a, photo2a, photo1b.

If I view the collection from a high level, photo1a, photo2a and photo1b all show as expected.  If I start the viewer and view the collection, it shows:
photo1a, photo2a, photo3a, photo4a, etc.  It never passes over to photo1b, nor does it stop from Library A (just keeps going through the photos).

It almost appears that the viewer is unable to view the order of the photos in the collection...it just plays the photos in the library.

**Comment by LukePulverenti** [comment]
Hi, can you please show screenshots to demonstrate the issue? I am having a hard time visualizing this. Thanks !
