### ISSUE TITLE
Emby freezing in Collection View

### ISSUE THREAD

**Issue by lordfiSh** [MediaBrowser/Emby#2316]
Everytime I click on the Collection View the Emby Server is freezing.
Logs:

> ********************************************************************************
> Upload completed successfully, please include this filename with your ticket...
> sendlogs_Gorleben_synology_bromolow_3615xs_20161128T171836UTC.tgz
> ********************************************************************************

**Comment by LukePulverenti** [comment]
It's due to the way collection images are generated. It's resolved for the next release, thanks.
