### ISSUE TITLE
Description text for "Display a folder view to show plain media folders" is incorrect.

### ISSUE THREAD

**Issue by DotNetDoctor** [MediaBrowser/Emby#2319]
Hi,
 I'm currently running v3.0.8500.0 and in the display settings (/web/librarydisplay.html) the description text for "Display a folder view to show plain media folders" says:
"If you have a dynamic DNS enter it here. Emby apps will use it when connecting remotely. This field is required when used with a custom SSL certificate."

![emby-error](https://cloud.githubusercontent.com/assets/24277844/20765834/f364bba8-b72b-11e6-8c49-e1e921bb111b.PNG)

**Comment by LukePulverenti** [comment]
Thanks. This is a translation error. It is resolved for the next release.
