### ISSUE TITLE
[Possible Bug] Loading library means poking every single file on a page

### ISSUE THREAD

**Issue by karbowiak** [MediaBrowser/Emby#2326]
Basically the problem is that, when Emby loads, say Movies - it pokes all the actual files on the hard drive, and not just metadata + db.

So say i open a 007 Movie which is located at `/mnt/storage/movies/007 - something/007 - blabla.mkv`
It then pokes that file to make sure it exists, instead of just loading the data in the database and showing it on the webpage.

Now, normally this wouldn't be a problem, because local hard drives are fast at this sort of thing, but it is a problem when using something like Amazon Cloud Drive / Google Drive / OneDrive / Dropbox mounted over Fuse, where the access time pr. file can be several hundred milliseconds.

All of this compounds together, and means that loading a single page can take anywhere from 5 to 60 seconds (sometimes even more).

Ideally it would only poke an episode of a tv series / movie during scanning and when you hit play on it - but yeah, figured i'd report it :)

edit://
Forgot to mention that this is with the latest dev version.. Version 3.1.6181.36295 dev

**Comment by LukePulverenti** [comment]
Hi, sorry, but this is just not true at all. The only thing it touches are the image files, if not already cached, and then the theme songs/videos.

**Comment by karbowiak** [comment]
Hm, that could possibly be it then - i do have nfo/png/jpg files amongst the video files - i just figured it was the movie files themselves that was touched and not the images (since it's set to store them separately)

Welp - my apologies! :)

**Comment by LukePulverenti** [comment]
It will store images internally if configured but local images in the media folders always take priority. So those would have to be removed to avoid them from getting hit.
