### ISSUE TITLE
Subtitles missing before processing is complete

### ISSUE THREAD

**Issue by warcode** [MediaBrowser/Emby#2338]
Because of the ability to play movies before they have finished processing a user can think that subtitle/multiple audio support is lacking or bugged (MKV in my case). This is either not stated to the user, or it is mentioned in such a way that it is easily missed.

I suggest that the audio and CC buttons on the web playback screen should always show up, but if you click them before it is ready it explains that you have to wait for processing to finish.

**Comment by LukePulverenti** [comment]
Hi, thanks for the feedback. Can you explain more what you mean about processing? thanks !
