### ISSUE TITLE
UI Issue - Web player

### ISSUE THREAD

**Issue by tylerapplebaum** [MediaBrowser/Emby#2358]
The play button in the lower right is useless, as the transparent popover puts a smaller, separate play button in the upper left. See attached images.

![emby1](https://cloud.githubusercontent.com/assets/8419153/21329641/91e49160-c5ee-11e6-87f3-e996297f65c0.png)

![emby2](https://cloud.githubusercontent.com/assets/8419153/21329640/91e44070-c5ee-11e6-9d49-969c0c1b7168.png)

**Comment by NickBolles** [comment]
What version of the emby server, and what browser are you using?

The intended functionality is that you hover over the image for 3 seconds and then the transparent popover displays. Mine (on server version 3.1.2.0 and chrome 55.0.2883.87, and frankly every other browser I have tried)  functions this way and the pop up menu also looks like this:
![emby ui issue popover](https://cloud.githubusercontent.com/assets/7891759/21671154/09a554e4-d2df-11e6-8832-7816ca385afc.PNG)

So it has the "play button" the "kabob", or "mmore options" button, the "marked as played" button and the "favorite" button. 

Clicking on the picture before this popover comes up results in going to the details page for the element and clicking the play button directly plays the item right away.

**Comment by tylerapplebaum** [comment]
Since the update to 3.1.2, mine now looks like your screenshot. Prior to that, I had a very quick timeout and it looked like my original screenshot.

Since the update fixed my issue, I'll go ahead and close this.
