### ISSUE TITLE
[ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method 'Array.Empty' not found.

### ISSUE THREAD

**Issue by ipsec** [MediaBrowser/Emby#2363]
# mono --version
Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+hard
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

Starting with: /usr/bin/mono-sgen --optimize=all /storage.local/apps/Emby/MediaBrowser.Server.Mono.exe -programdata /storage.local/apps/Emby_data_dir/ -ffmpeg /usr/bin/ffmpeg -ffprobe /usr/bin/ffprobe -restartpath /storage.local/apps/Emby_data_dir/systemctl_restart.sh

Unable to start.
How to fix?

**Comment by LukePulverenti** [comment]
Hi, the mono runtime 4.2.X is no longer supported. The minimum version we require is 4.4.2, but 4.6.2 is recommended. Thanks.

**Comment by ipsec** [comment]
Updating.
Thanks.
