### ISSUE TITLE
External bitmap subtitles are loaded incorrectly

### ISSUE THREAD

**Issue by untitledxi** [MediaBrowser/Emby#2365]
When Emby plays a video file with external bitmap subtitles, I've noticed that the timing is wrong and the color palette is defaulting to a very obscure combination (black outline with yellow letters).

The issue is that Emby always feeds the ```sub``` file to ffmpeg, even when there is ```idx``` file present in the directory. The ```idx``` file stores metadata related to the bitmaps such as time-stamps, color palette, smoothing, scaling etc, as such is needed to properly display the bitmaps stored in the ```sub``` file.

For example, the current ffmpeg parameters (copied from the logs) are:

```
ffmpeg -i file:"<video>.mkv" -i "<lang>.sub" ...
```

however, in order to display the bitmaps correctly they should become:

```
ffmpeg -i file:"<video>.mkv" -i "<lang>.idx" ...
```

when there is ```idx``` present with the same filename.

Tested similar issue #1481 and without adding canvas, simply by selecting the idx subtitle, everything works as expected.

**Comment by LukePulverenti** [comment]
Thanks for the tip !

**Comment by untitledxi** [comment]
Thanks for the quick fix, I've noticed however that Emby does not properly parse ```idx``` files.

An ```idx``` file may contain multiple languages, however Emby does not properly index multiple languages and shows ```Unknown Language``` for every ```idx```/```sub``` file. Meaning it doesn't properly parse the language code as well.

For example, excerpt from an ```idx``` file with multiple languages defined:

```
id: en, index: 0
timestamp: 00:00:0x:xxx, filepos: 000000000
...
id: fr, index: 1
timestamp: 00:00:0x:xxx, filepos: 000000000
...
id: es, index: 2
timestamp: 00:00:0x:xxx, filepos: 000000000
```

In the example above, the ```idx``` file contains the reference to 3 languages (en, fr, es) and the respective position in the ```sub``` file.

The language can be changed by tweaking the overlay:

```
-filter_complex "[1:x]scale=res_w:res_y[sub] ; [0:0] [sub] overlay
```

```x``` is the language index as extracted from the ```idx``` file

**Comment by LukePulverenti** [comment]
It's not that we don't parse them properly, it's that we don't parse them at all.
