### ISSUE TITLE
Emby crashes constantly

### ISSUE THREAD

**Issue by Luticus** [MediaBrowser/Emby#2373]
Every day emby will crash with the following error:

Dec 29 12:08:51 media emby-server[7420]: at System.Threading.Tasks.Task.FinishContinuations () <0x00243>
Dec 29 12:08:51 media emby-server[7420]: at System.Threading.Tasks.Task.FinishStageThree () <0x00068>
Dec 29 12:08:51 media emby-server[7420]: at System.Threading.Tasks.Task.FinishStageTwo () <0x00133>
Dec 29 12:08:51 media emby-server[7420]: at System.Threading.Tasks.Task.Finish (bool) <0x00089>
Dec 29 12:08:51 media emby-server[7420]: at System.Threading.Tasks.Task.ExecuteWithThreadLocal (System.Threading.Tasks.Task&) <0x00131>
Dec 29 12:08:51 media emby-server[7420]: at System.Threading.Tasks.Task.ExecuteEntry (bool) <0x000d6>
Dec 29 12:08:51 media emby-server[7420]: at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () <0x0000e>
Dec 29 12:08:51 media emby-server[7420]: at System.Threading.ThreadPoolWorkQueue.Dispatch () <0x001d6>
Dec 29 12:08:51 media emby-server[7420]: at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0x00008>
Dec 29 12:08:51 media emby-server[7420]: at (wrapper runtime-invoke) <Module>.runtime_invoke_bool (object,intptr,intptr,intptr) <0x00056>
Dec 29 12:08:51 media emby-server[7420]: Native stacktrace:
Dec 29 12:08:51 media emby-server[7420]: /usr/bin/mono-sgen() [0x4b1a20]
Dec 29 12:08:51 media emby-server[7420]: /usr/bin/mono-sgen() [0x508f4e]
Dec 29 12:08:51 media emby-server[7420]: /usr/bin/mono-sgen() [0x428e93]
Dec 29 12:08:51 media emby-server[7420]: /lib/x86_64-linux-gnu/libpthread.so.0(+0xf8d0) [0x7f7572e9e8d0]
Dec 29 12:08:51 media emby-server[7420]: /lib/x86_64-linux-gnu/libc.so.6(+0x92040) [0x7f7572960040]
Dec 29 12:08:51 media emby-server[7420]: /usr/lib/emby-server/x86_64-linux-gnu/libEmbyMagickCore-6.Q8.so.2(ReadBlob+0x2c8) [0x7f75657a4c68]
Dec 29 12:08:51 media emby-server[7420]: /usr/lib/emby-server/x86_64-linux-gnu/EmbyMagick-6.9.6/modules-Q8/coders/jpeg.so(+0x3c7f) [0x7f74ea6f7c7f]
Dec 29 12:08:51 media emby-server[7420]: /usr/lib/x86_64-linux-gnu/libjpeg.so.62(jpeg_fill_bit_buffer+0x7a) [0x7f74ea4b87da]
Dec 29 12:08:51 media emby-server[7420]: /usr/lib/x86_64-linux-gnu/libjpeg.so.62(+0x23fbf) [0x7f74ea4c0fbf]
Dec 29 12:08:51 media emby-server[7420]: /usr/lib/x86_64-linux-gnu/libjpeg.so.62(+0x189f7) [0x7f74ea4b59f7]
Dec 29 12:08:51 media emby-server[7420]: /usr/lib/x86_64-linux-gnu/libjpeg.so.62(jpeg_start_decompress+0x86) [0x7f74ea4b4ee6]
Dec 29 12:08:51 media emby-server[7420]: /usr/lib/emby-server/x86_64-linux-gnu/EmbyMagick-6.9.6/modules-Q8/coders/jpeg.so(+0x4ad3) [0x7f74ea6f8ad3]
Dec 29 12:08:51 media emby-server[7420]: /usr/lib/emby-server/x86_64-linux-gnu/libEmbyMagickCore-6.Q8.so.2(ReadImage+0x198) [0x7f75657d8a58]
Dec 29 12:08:51 media emby-server[7420]: /usr/lib/emby-server/x86_64-linux-gnu/libEmbyMagickWand-6.Q8.so.2(MagickReadImage+0x6a) [0x7f7565e8333a]
Dec 29 12:08:51 media emby-server[7420]: [0x41d1c9c4]
Dec 29 12:08:51 media emby-server[7420]: Debug info from gdb:
Dec 29 12:08:51 media emby-server[7420]: =================================================================
Dec 29 12:08:51 media emby-server[7420]: Got a SIGSEGV while executing native code. This usually indicates
Dec 29 12:08:51 media emby-server[7420]: a fatal error in the mono runtime or one of the native libraries
Dec 29 12:08:51 media emby-server[7420]: used by your application.
Dec 29 12:08:51 media emby-server[7420]: =================================================================
Dec 29 12:08:52 media su[7420]: pam_unix(su:session): session closed for user emby
Dec 29 12:08:52 media systemd[1]: emby-server.service: main process exited, code=exited, status=134/n/a
Dec 29 12:08:52 media systemd[1]: Unit emby-server.service entered failed state.

Emby is on the newest version and I'm running and up-to-date Debian Jessie in a virtual machine.  It has 15 GB of RAM and a 6 core cpu.  There are no active plugins, and no additional software is installed other than the base Debian image and Emby.

**Comment by micahscopes** [comment]
I'm having trouble with Emby crashing non-stop as well... always in the middle of scanning.  And the worst part is that if I restart it, the library.db file gets corrupted.

**Comment by micahscopes** [comment]
It's unusable now.

**Comment by LukePulverenti** [comment]
Can you please attach the complete emby server log? thanks !

**Comment by Luticus** [comment]
My logs:  
[Emby.txt](https://github.com/MediaBrowser/Emby/files/679777/Emby.txt)

**Comment by LukePulverenti** [comment]
Hi, please try 3.1.2. Thanks !
