### ISSUE TITLE
Movieset format changed in Kodi v16 - Emby fails on importing nfos with this tags

### ISSUE THREAD

**Issue by al1505** [MediaBrowser/Emby#2376]
New set tags where added in Kodi v16 - now the format is like this:
 
<set>
        <name>'name of set'</name>
        <overview>'plot of set'</overview>
</set>
 
Here the info from the release notes:
* Added support for set overview (plot) in movie sets in the video library
 
Any chance to support this in the ?

**Comment by LukePulverenti** [comment]
Where is this documented? In the kodi wiki, the examples of the set tag appear to be the same as before:
http://kodi.wiki/view/NFO_files/Movies

Thanks !

**Comment by al1505** [comment]
Hi,


its in the release note - see also my post in the emby forum:

https://emby.media/community/index.php?/topic/42392-movienfoprovider-problem-with-set-tag/

MovieNfoProvider problem with <set> tag - Windows/General ...<https://emby.media/community/index.php?/topic/42392-movienfoprovider-problem-with-set-tag/>
emby.media
Hello, i am new to emby - so far i only used Kodi as standalon and TMM for metadata management. Today i installed emby and also got the connection to kodi running but ...





lg

Alois


________________________________
Von: Luke <notifications@github.com>
Gesendet: Montag, 20. März 2017 19:42
An: MediaBrowser/Emby
Cc: al1505; Author
Betreff: Re: [MediaBrowser/Emby] Movieset format changed in Kodi v16 - Emby fails on importing nfos with this tags (#2376)


Where is this documented? In the kodi wiki, the examples of the set tag appear to be the same as before:
http://kodi.wiki/view/NFO_files/Movies

NFO files/Movies - Official Kodi Wiki<http://kodi.wiki/view/NFO_files/Movies>
kodi.wiki
1. The *.nfo file is an XML file containing the data for inclusion in the library. movie.nfo will override all and any .nfo files in the same folder as the media ...



Thanks !

**Comment by LukePulverenti** [comment]
I'm closing this. The kodi wiki on movie sets has never been updated to reflect any of this:

http://kodi.wiki/view/NFO_files/Movies

We use the kodi wiki as our NFO reference. If you can please ask the Kodi team to update the NFO wiki, then once that is done you are more than welcome to re-open the ticket and then we'll take a look at what work needs to be done.

Thanks !

**Comment by al1505** [comment]
Hi

Sure i can do that but you know the details from the release notes i provided would it be not better to adjust it right away as your solution is not working anymore? Its also quite strangw to get thid feedback quite late as you could mention this right away..

Nevertheless thanks for your help and efforts
Lg
Alois


-------- Ursprüngliche Nachricht --------
Von: Luke <notifications@github.com>
Datum: 19.07.17 00:35 (GMT+05:30)
An: MediaBrowser/Emby <Emby@noreply.github.com>
Cc: al1505 <a.schacherl@aon.at>, Author <author@noreply.github.com>
Betreff: Re: [MediaBrowser/Emby] Movieset format changed in Kodi v16 - Emby fails on importing nfos with this tags (#2376)


I'm closing this. The kodi wiki on movie sets has never been updated to reflect any of this:

http://kodi.wiki/view/NFO_files/Movies

We use the kodi wiki as our NFO reference. If you can please ask the Kodi team to update the NFO wiki, then once that is done you are more than welcome to re-open the ticket and then we'll take a look at what work needs to be done.

Thanks !

**Comment by al1505** [comment]
hi,

do you have any timeplan when this could be fixed?

Thanks
lg
AL

**Comment by LukePulverenti** [comment]
What exactly is the issue at this point? The failure should be resolved.

**Comment by al1505** [comment]
Hi Luke,

i downloaded today the latest beta and only added a share with some movies including the set info – they are imported but no set was set ?

THANKS
Lg
Alois

Von: Luke<mailto:notifications@github.com>
Gesendet: Mittwoch, 20. September 2017 19:23
An: MediaBrowser/Emby<mailto:Emby@noreply.github.com>
Cc: al1505<mailto:a.schacherl@aon.at>; Author<mailto:author@noreply.github.com>
Betreff: Re: [MediaBrowser/Emby] Movieset format changed in Kodi v16 - Emby fails on importing nfos with this tags (#2376)


Closed #2376<https://github.com/MediaBrowser/Emby/issues/2376> via 363cb7e<https://github.com/MediaBrowser/Emby/commit/363cb7e79f96bee613695ca839a4fd80976c6669>.
