### ISSUE TITLE
Unable to change default port in emby theater for xbox

### ISSUE THREAD

**Issue by NickBolles** [MediaBrowser/Emby#2379]
![img_20170102_245400669](https://cloud.githubusercontent.com/assets/7891759/21622162/c66ce1ba-d1c1-11e6-834b-f29270d37217.jpg)

As you can see... Well kinda, its a terrible picture... I didn't wanna get up haha. 
Anyways... The cursor is stuck before the default "8096" in the port text box. You can add other stuff (including letters) and backspace that, or use the right bumper and left bumper to navigate through the entered charectors, but not for the "8096"

I tried rebooting the app, the Xbox etc. Eventually I just went to my public IP for my server in edge (as I'm on a separate network than my server) to access it and that worked fine. 

I also tried using emby connect and it did not work. It just went to the "new server" and "emby connect" options on the server select screen. 

I'd be willing to check this out if you point me in the right direction

**Comment by LukePulverenti** [comment]
Resolved for next app update, thanks.
