### ISSUE TITLE
[API Question] User Creating

### ISSUE THREAD

**Issue by RaymondSchnyder** [MediaBrowser/Emby#2380]
Hello developers of my favourite media Server!

I have a question regarding the API:

Is it possible to create a Server plugin with the API, which is able to create Users?

Ive searched through the documentation, but found only a paper about authentication of already created users..

Is this possible or do i have to do some "hacks" in the source code?

Edit: I found this pull request on your repository: https://github.com/MediaBrowser/Emby/pull/2139/
Is this implementable or is this far away in the future?

I would be very happy if i get a Response :-)

Greetings

Raymond

**Comment by LukePulverenti** [comment]
you can create users with a plugin. you can also just do it with the api. no need to work with the source code

**Comment by RaymondSchnyder** [comment]
Thanks for the response, is there any link i can look at the API in detail?
On the GITHUB wiki im not able to find something user related :/

**Comment by LukePulverenti** [comment]
You can find some api info on our wiki here:

https://github.com/MediaBrowser/Emby/wiki

However, creating users is not documented so the best reference will be our api library:
https://github.com/MediaBrowser/Emby.ApiClient.Javascript/blob/master/apiclient.js

Thanks.
