### ISSUE TITLE
Incorrect day for upcoming TV Shows

### ISSUE THREAD

**Issue by haggis663** [MediaBrowser/Emby#2383]
Hi, I am living in a UTC+10 timezone and it is reporting TV Shows airing today as yesterday.

**Comment by LukePulverenti** [comment]
Hi, check your system and make sure the timezone is set correctly. Beyond that, we're limited by the data coming from tvdb. The dates are not localized for different regions.

**Comment by haggis663** [comment]
The system/user timezone is correct and Sonarr shows the upcoming shows with correct time / date stamps. the wrong date/time is evident in all clients web, Android & Windows desktop.

The forum link https://emby.media/community/index.php?/topic/26050-premiered-date-is-showing-up-wrong/page-5 indicates that it is not just me having the problem.

If the source is not timestamped, please include a configuration option to allow us to default the source timestamp.

Regards,
Haggis

**Comment by LukePulverenti** [comment]
Closing, see #2486
