### ISSUE TITLE
Bad URL when browsing a music library by genre

### ISSUE THREAD

**Issue by MarinBernard** [MediaBrowser/Emby#2407]
Hi,

On Emby server 3.1.2.0, if I create a music library and try to browse it through genre links (displayed under the album title), I get a page with no matching result.

I found out that each genre link points to a URL `<hostname>/web/secondaryitems.html?type=Movie&musicgenre=<genre>`. If I replace `type=Movie` by `type=Audio`, I get correct results. I suppose this is a bug that needs to be corrected.

Thanks,

~ Marin

**Comment by LukePulverenti** [comment]
Hi, this is already resolved for the next release, thanks!

**Comment by MarinBernard** [comment]
Thanks!
