### ISSUE TITLE
Connectivity problems with Android app

### ISSUE THREAD

**Issue by xmaestro** [MediaBrowser/Emby#2409]
Hi,
I am able to connect to my Emby media server which i setup on my laptop using my android app when im on the aame wifi network as the media server.
But when i change to my 4g network, two things happen. One, it logs me out of android app. Two, when i do sign in, it clicking on the server shows me error that its not able to connect.
Am I doing something wrong?

**Comment by LukePulverenti** [comment]
It sounds like your router is preventing access from the outside. You might need to configure port forwarding on it.

I would suggest checking out our Connection Troubleshooter:

https://github.com/MediaBrowser/Wiki/wiki/Connectivity

Please try the steps listed there and let us know if you're still having issues. thanks !
