### ISSUE TITLE
Edit subtitles not working

### ISSUE THREAD

**Issue by Jeroenhuisjes** [MediaBrowser/Emby#2410]
It won't find any subtitles anymore. Worked flawlessly yesterday.
What happened?

It's an important feature for me.

**Comment by LukePulverenti** [comment]
Hi there, in order for us to best help you, we need a bit more information. Please provide the information requested here:

https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/

Thanks !

**Comment by Jeroenhuisjes** [comment]
So I'm trying to use the function "Edit subtitles". It's a function I use often. But suddenly it stopped finding any subtitles. Doesn't matter what movie or series I try to use it on.
[Log.txt](https://github.com/MediaBrowser/Emby/files/722859/Log.txt)
![nosubs](https://cloud.githubusercontent.com/assets/23723678/22194854/073b276e-e145-11e6-8606-26931b9cb6f9.PNG)

I hope this is enough information!

PS I have a opensubtitles VIP account.

**Comment by LukePulverenti** [comment]
I can reproduce it as well, there's some error about their ssl certificate. Similar errors have happened before and have been on their side. I am going to give it another day or so to see if it resolves itself before I spend any time on it. Thanks.

**Comment by Jeroenhuisjes** [comment]
Ah yeah that's kinda what I thought! But I'm not really good at reading the log haha. But thanks! Let's give it some time :)

**Comment by Jeroenhuisjes** [comment]
It's working again. You can close this.
