### ISSUE TITLE
Transcoding not working on Android app

### ISSUE THREAD

**Issue by nscottnichols** [MediaBrowser/Emby#2411]
Transcoding is not working for the Android app, but is working on the web client. I am currently running server version 3.1.6231.38340 dev. As a side note, my setup is running behind a reverse proxy.
The error log is attached.
[transcodeErrorEmby.txt](https://github.com/MediaBrowser/Emby/files/722334/transcodeErrorEmby.txt)

**Comment by LukePulverenti** [comment]
Please attach the complete emby server log. thanks.

**Comment by nscottnichols** [comment]
Actually, this doesn't seem to be a transcoding issue. Instead, it might be a problem with the Android app reporting selections and related to issue #2410. When on the Android app, subtitles would not work if I selected them too.
Here is the full log: [server-63620706263.txt](https://github.com/MediaBrowser/Emby/files/722350/server-63620706263.txt)

**Comment by Jeroenhuisjes** [comment]
Subtitles not working in the app or browser seem to be related to embedded subtitles in a MKV file.

**Comment by LukePulverenti** [comment]
What do you mean reporting selections? Playback has nothing to do with the Edit Subtitles popup.

**Comment by nscottnichols** [comment]
If I have an episode open and click here
![button1](https://cloud.githubusercontent.com/assets/8723338/22195850/0de35c4e-e118-11e6-9120-7f55bc756eec.png)
and then select subtitles
![button2](https://cloud.githubusercontent.com/assets/8723338/22195858/1e7502e2-e118-11e6-9793-5348fa306213.png)
and change the subtitle to english,
![button3](https://cloud.githubusercontent.com/assets/8723338/22195931/6f72853e-e118-11e6-9164-f9e3dd675c7f.png)
the subtitles do not work on the android app. Changing the subtitles does work on the web client.
If instead of choosing subtitles, I try to change the quality by clicking here
![button4](https://cloud.githubusercontent.com/assets/8723338/22195936/7a1fbbaa-e118-11e6-9a66-0f437668b819.png)
and select 144p,
![button5](https://cloud.githubusercontent.com/assets/8723338/22195942/7feb029c-e118-11e6-9acb-53aff4430f72.png)
the video quality does not change.

The episode had external subtitles. I tried doing these same steps with a movie that had embedded subtitles and changing the subtitles worked. However, changing the quality still didn't work.

**Comment by LukePulverenti** [comment]
Can you try the open beta version:
https://emby.media/community/index.php?/topic/24350-android-open-beta-testing/

Thanks !
