### ISSUE TITLE
Unable to not set port with external domain

### ISSUE THREAD

**Issue by benbar21** [MediaBrowser/Emby#2418]
Hey!

I'm having a (probably unique) problem with Emby.

I want to run it through a reverse proxy and then CloudFlare, and I want to be able to access this from app.emby.media, the app, and so on.

Let's pretend that my domain is media.com. I currently have it so https://media.com/emby goes to my server and runs through cloudflare. The problem comes when I want to be able to access Emby this way through apps and such without manually entering in the server. I set the external domain to "media.com/emby" and have selected 'report https as external address'. The problem is I cannot leave the port blank. So, I set the port to 443. The problem is that Emby now believes my server is accessible at https://media.com/emby:443. This obviously does not work, and instead for it to work it would have to either be https://media.com:443/emby or just https://media.com/emby.

So, the fix would either be to not require a port when an external domain is being used or to separate the base directory from the external domain, so that it goes domain:port/base.

Hopefully I've explained this properly! I'd love to be able to use Emby properly but I don't seem to be able to do that until this is fixed. If you want any more explanations let me know.

Also, I'm not alone with this issue! It's been mentioned a few times in the forums:

https://emby.media/community/index.php?/topic/32543-reverse-proxy-and-remote-access-url/
https://emby.media/community/index.php?/topic/25788-server-emby-connect-reverse-proxy/

Thanks

**Comment by benbar21** [comment]
Anything?

**Comment by LukePulverenti** [comment]
try entering the full url and leaving the port blank.

**Comment by benbar21** [comment]
unfortunately when I do that it won't let me save and says "please fill out this field".

I've also tried manually setting no port in system.xml but when emby starts it just read the file as corrupt and creates a new config

**Comment by benbar21** [comment]
@LukePulverenti think you'll be able to fix this?

**Comment by benbar21** [comment]
@LukePulverenti I'd really appreciate a response, even if it is just to tell me that you aren't going to implement this

**Comment by hotio** [comment]
Tried filling in port 80?

**Comment by hotio** [comment]
Shouldn't it just leave the port away, if it's 80 or 443....

**Comment by benbar21** [comment]
It doesn't, unfortunately.

If I set it to 443 it'll go to https://domain.com/emby:443 instead of domain.com:443/emby

**Comment by LukePulverenti** [comment]
What Emby app are you referring to? I have tested the web app, android, Theater, and iOS and the port is optional on all of them.

**Comment by animosity22** [comment]
Why not just not use the /emby at all and just use a virtualhost in Apache with something like emby.media.app?

I use 1 A Record and 2 CNAME DNS entries to map to my DDNS for my apache proxy at home.

I have mappings for:

apps.media.apps
ombi.media.apps
emby.media.apps

I like using default with no path appended for the stuff that I have other folks use and all my apps (Sonarr/NZBGet/Radarr/etc) all use additional paths.

I use 3 certbots to autorenew the certs as well so it's pretty smooth. I tend to try to make things as simple for the folks using my stuff as possible.

**Comment by LukePulverenti** [comment]
Thanks @animosity22 . In my testing I don't see any problems here. The OP can re-open if there is an issue. Thanks.

**Comment by benbar21** [comment]
Sorry for never replying. I don't check Git very often.

While @animosity22's solution would work, it still is just a workaround. 

I've attached an image that demonstrates my issue well, I believe: 
<img width="654" alt="screen shot 2017-08-30 at 2 42 13 am" src="https://user-images.githubusercontent.com/4377293/29858756-e908e8aa-8d2c-11e7-9e1a-ecfdd278aad6.png">

I've replaced my actual domain with domain.com, just for the sake of privacy. 

I have a caddy server proxying /emby to my local server. I then want to access the server from p.domain.com/emby. The issue is that I need to set a port in the Emby server. So, I tried setting it to 443, with the intention of the external url being p.domain.com:443/emby. The issue then is that it appends the port after the external url, as shown.

All I am asking is for the ability to have an external url instead of an address:port, or for the ability to leave out the port, or for the ability to have the port come before the domain path.

Let me know if you want me to further clarify!

**Comment by animosity22** [comment]
I've never used caddy but from a few searches, I'm not sure why you want to use /emby to append to the end.

Just map the root to the domain:

emby.domain.com

There is a pretty good link here that goes through the same concepts I use on apache on caddy. With custom DNS records, it makes it simple and avoids a lot of the overhead.

https://drive.google.com/file/d/0BzPd75yQAJYhWG1keDJpWU9QZVU/view
