### ISSUE TITLE
[Feature] - Multi version support for TV shows.

### ISSUE THREAD

**Issue by rehanone** [MediaBrowser/Emby#2431]
Storing multiple resolution files for TV shows does not combine each episode as one. Similar feature is supported in movies like - 720p or - 1080p at the end of file names. Can this feature be added for TV shows as well?

**Comment by kaithar** [comment]
This would also be really handy for the occasions where TV shows decide to do a directors cut or similar, for those who want to keep around both the "as aired" version and any additional versions.  Probably less common than for movies, but I know of at least one show that has done directors cut and remastered releases.

**Comment by jaketame** [comment]
Any sign of this coming soon?

**Comment by jaketame** [comment]
Looks like I didn't need to create https://github.com/MediaBrowser/Emby/issues/3272

**Comment by LukePulverenti** [comment]
This will be in Emby Server 3.6.
