### ISSUE TITLE
Update request for documentation

### ISSUE THREAD

**Issue by GentleRV** [MediaBrowser/Emby#2435]
Is it possible to update the documentation howto and where place the physical files (mp3, movies) and so on to ne able to use the emby server?
Does it need a large HDD (raid5 set) with all the files on it or can a MYBOOKLIVE also be used?
In case of a internal HDD set, does it need to install samba to share that disk and put the files in the right directories?
Please make things more clear for the new users

**Comment by andlo** [comment]
I'm a new user to, but maybe I can answer.

You need as large HDD as you mediacollection requeres. It is not requered to have it  in raid, but always good to have HDD in raid as it makes risks for loosing data if one disk breaks smaller.

You do not need to install samba.

You can setup emby to have many directories and show it all under one - so Movies could be setup to look in more than one place.

**Comment by LukePulverenti** [comment]
Our documentation is up to date. Have you taken a look at our wiki?

https://github.com/MediaBrowser/Wiki/wiki
