### ISSUE TITLE
No playqueue

### ISSUE THREAD

**Issue by CDrummond** [MediaBrowser/Emby#2442]
When playing music to chromecast audio, there is no playqueue shown in the now playing screen. If I play locally (in the webapp) then the playqueue is displayed.

**Comment by BloodyIron** [comment]
I get this too. I can't for the life of me figure out how to manipulate what's next! D:

**Comment by LukePulverenti** [comment]
This will be in the next updates to the mobile apps for Chromecast, and in all other cases (dlna, remote control other emby apps), will be in first 4.6 beta channel build.
