### ISSUE TITLE
Audiobooks need separate resuming  constraints 

### ISSUE THREAD

**Issue by Haplo164** [MediaBrowser/Emby#2447]
Audiobooks currently use the same resuming rules as everything else, default of 5% min 95% max. That's great for short things like a TV show or a movie, but 5% of most of my books are about 2 hours.
I think books should have their own resuming options or just per library options.

**Comment by LukePulverenti** [comment]
This will be in Emby Server 3.6. Thanks.

**Comment by yermak** [comment]
It, seems this setting disappeared completely in version 4.0.0.2
However correct resume is crucial for audibooks, as most of my books 10+ hours, so after listening book about 30 mins. It's reset to start.

**Comment by LukePulverenti** [comment]
Hi, it did not disappear but was moved to per library settings under each library. But after further review I can see that they are not showing for the audio books content type. This will be resolved in 4.0.1. Thanks.
