### ISSUE TITLE
mpeg4 is still trying to be transcoded by VAAPI

### ISSUE THREAD

**Issue by dyleck** [MediaBrowser/Emby#2485]
I am runnign the server version 3.2.1.116. Apparently fix for bug #2285 (merged into 3.1.0) should make the problem go away but it didn't for me. Here are the output I have when trying to transcode the mpeg4 file:

`[vaapi @ 0x7f4ee88a0240] No VAAPI support for codec mpeg4 profile 15.`
`[vaapi @ 0x7f4ee88a0240] If you want attempt decoding anyway with a possibly-incompatible profile, add the option -hwaccel_lax_profile_check.`
`[vaapi @ 0x7f4ee88a0240] No supported configuration for this codec.vaapi hwaccel requested for input stream #0:0, but cannot be initialized.`
`[mpeg4 @ 0x34bbf60] decoding to AV_PIX_FMT_NONE is not supported.
Error while decoding stream #0:0: Operation not permitted`
`[mpeg4 @ 0x34bc920] Context scratch buffers could not be allocated due to unknown size.
Error while decoding stream #0:0: Operation not permitted`

**Comment by LukePulverenti** [comment]
Thanks for the report. We have been checking for specific levels but we're just going to skip it for all mpeg4.

**Comment by dyleck** [comment]
I must say I am really impressed by your response time. Kudos!
I've just tested latest beta and now transcoding mpe4 makes my CPU hurt.
