### ISSUE TITLE
Premiere/Upcoming/Added dates incorrect due to timezone offsets

### ISSUE THREAD

**Issue by simonk83** [MediaBrowser/Emby#2486]
As discussed with Luke in this thread: https://emby.media/community/index.php?/topic/26050-premiered-date-is-showing-up-wrong/page-6

Details at the top of page 6.  Good to have an issue open for it.

**Comment by simonk83** [comment]
Any progress with this one?

**Comment by LukePulverenti** [comment]
This is resolved in Emby Server 3.6. Thanks.
