### ISSUE TITLE
Subtitles not advancing with episode

### ISSUE THREAD

**Issue by flyingdan** [MediaBrowser/Emby#2492]
Running version 3.2.1 as a plugin on FreeNAS. Playback in browser.

When going from episode 1 to episode 2 automatically the subtitles displayed are those for episode 1. Exiting playback and resuming will select the correct subtitles.

**Comment by LukePulverenti** [comment]
Hi @flyingdan, are the subtitles changing with the time in this scenario, or are they stuck on a particular text? what kind of subtitles are these? thanks.

**Comment by flyingdan** [comment]
Hi @LukePulverenti,
The subtitles are changing with the time. If I exit playback (go back to the episode list for example) and resume, the correct subtitle file is referenced and correct subtitles are shown.

These are subtitles automatically downloaded by Emby from Open Subtitles in .srt format:
```Episode # - Episode name.mp4``` has ```Episode # - Episode name.language.srt``` as subtitles file.

**Comment by LukePulverenti** [comment]
What web browser is this?

**Comment by flyingdan** [comment]
I was using Firefox.

Your question prompted me to test it in Chrome as well and the issue is not present when using Chrome so it seems to be browser related.

**Comment by flyingdan** [comment]
Just an update to this bug: in 3.2.13.0 and the issue is present in Chrome as well.

**Comment by LukePulverenti** [comment]
I'm aware of the issue in firefox but i cannot reproduce it in chrome. Thanks.
