### ISSUE TITLE
[Feature] LDAP authentication

### ISSUE THREAD

**Issue by Criena** [MediaBrowser/Emby#2493]
Doing the authentication against LDAP or optionally against an external script/program would be benefitial for integrating Emby into existing infrastructures.

**Comment by fbartels** [comment]
Hello @Criena ,

this is already an open topic: https://github.com/MediaBrowser/Emby/issues/1146 (at least the ldap part)

**Comment by Criena** [comment]
Ah, my bad. I scimmed through the issues, but only checking for "^feature". Considering there are quite a few people interested in this, I wonder why nothing is happening since 2015.

**Comment by untotren** [comment]
Make sure to +1 this FR
https://emby.media/community/index.php?/topic/26495-ldap-support/
