### ISSUE TITLE
Emby ignoring albums

### ISSUE THREAD

**Issue by CountMurphy** [MediaBrowser/Emby#2500]
I discovered a strange issue with Emby's music player. I have a few albums that are "missing." It would seem that emby is including the missing albums tracks but classifying them as a completely different album. For example, for the artist LEAH, I have ~4 albums, yet every song shows up as the same album. In [screenshot 1](http://imgur.com/a/ybXJF) you can clearly see the artist has one album. However if I click edit info on of the songs, [you can see](http://imgur.com/a/J1svJ) that emby does indeed know it belongs to an album that "doesn't exist" Searching for the missing album "otherworld"  yields no results.

**Comment by LukePulverenti** [comment]
Can we see what the folder structure looks like? thanks.

**Comment by CountMurphy** [comment]
I'd give you a screen shot, but dont have access to a gui of that server. This work?

LEAH/
├── Kings & Queens
│   ├── 01-01- Arcadia.mp3
│   ├── 01-02- Save the World.mp3
│   ├── 01-03- Angel Fell.mp3
│   ├── 01-04- Enter the Highlands.mp3
│   ├── 01-05- In the Palm of Your Hands.mp3
│   ├── 01-06- Alpha Et Omega.mp3
│   ├── 01-07- Heart of Poison.mp3
│   ├── 01-08- Hourglass.mp3
│   ├── 01-09- Palace of Dreams.mp3
│   ├── 01-10- This Present Darkness.mp3
│   ├── 01-11- The Crown.mp3
│   ├── 01-12- Remnant.mp3
│   ├── 01-13- There Is No Farewell.mp3
│   ├── 01-14- Siúil a Rún.mp3
│   └── 01-15- Siúil a Rún (Bonus Rock Version).mp3
├── LEAH - Silent Night.ogg
├── LEAH - Veni Veni Emmanuel (O Come, O Come, Emmanuel).ogg
├── LEAH - We Will Go Home (single).ogg
├── Let All Mortal Flesh Keep Silence
│   ├── cover.png
│   ├── LEAH - Let All Mortal Flesh Keep Silence - 01 Let All Mortal Flesh Keep Silence.ogg
│   ├── LEAH - Let All Mortal Flesh Keep Silence - 02 The Holly & The Ivy.ogg
│   └── LEAH - Let All Mortal Flesh Keep Silence - 03 God Rest Ye Merry Gentlemen.ogg
├── Of Earth And Angels
│   ├── cover.jpg
│   ├── LEAH - Of Earth & Angels - 01 Prisoner.ogg
│   ├── LEAH - Of Earth & Angels - 02 Remember.ogg
│   ├── LEAH - Of Earth & Angels - 03 Old World.ogg
│   ├── LEAH - Of Earth & Angels - 04 I Fade.ogg
│   ├── LEAH - Of Earth & Angels - 05 Ex Cathedra.ogg
│   ├── LEAH - Of Earth & Angels - 06 Ocean.ogg
│   ├── LEAH - Of Earth & Angels - 07 A Thousand Years.ogg
│   ├── LEAH - Of Earth & Angels - 08 Tragedy & Magic.ogg
│   ├── LEAH - Of Earth & Angels - 09 Mainland.ogg
│   ├── LEAH - Of Earth & Angels - 10 Say Yes.ogg
│   ├── LEAH - Of Earth & Angels - 11 Confess My Love.ogg
│   └── LEAH - Of Earth & Angels - 12 Illusion.ogg
├── Otherworld
│   ├── cover.jpg
│   ├── LEAH - Otherworld (EP) - 01 Shores of Your Lies.ogg
│   ├── LEAH - Otherworld (EP) - 02 The Northern Edge.ogg
│   ├── LEAH - Otherworld (EP) - 03 Surrounded.ogg
│   ├── LEAH - Otherworld (EP) - 04 Do Not Stand at My Grave and Weep.ogg
│   ├── LEAH - Otherworld (EP) - 05 Dreamland (Feat. Eric Peterson).ogg
│   └── LEAH - Otherworld (EP) - Otherworld_Booklet.pdf
├── Project Aegis - Angel In The Ashes.ogg
└── Winter Sun
 |   ├── cover.jpg
 |   └── LEAH - Winter Sun.ogg

**Comment by LukePulverenti** [comment]
It appears the issue is you have songs directly in the artist folder, try making a sub-folder for the album and moving them into there. Thanks !

**Comment by CountMurphy** [comment]
That seems to have fixed the issue on my end. Thanks for your help. Emby really is fantastic software.
