### ISSUE TITLE
Not respecting tag blocking

### ISSUE THREAD

**Issue by Nerdy314159265** [MediaBrowser/Emby#2502]
I'm currently working on setting up my first Emby server.
I'm running it via the FreeNAS plugin on FreeNAS-9.10.2-U1 (86c7ef5) with Emby version 3.2.4.0

I'm attempting to create a new user and restrict the visibility of some shows. I'd like to keep some of my collection separate from the rest of my family.

I've created a new user. Limited library access to only Movies and TV and added a tag to "Block content with tags"

Here's where the issue seems to begin. I created a tag for my shows that is just my name and tagged my shows with it. Then I added it to my new users "block content with tags" list. I've confirmed that the spelling and capitalization is the same but when I log in with the new user, they still can see and play the shows with the tag.

I don't know what other details to add but I can provide them on request if told how to get them.

**Comment by komodo2** [comment]
I am seeing this behavior as well with 3.2.7.0

**Comment by LukePulverenti** [comment]
I am not able to reproduce this. Please re-open if you are still seeing an issue. Thanks !

**Comment by Nerdy314159265** [comment]
I'm still experiencing this issue.

I tested by adding a tag to some TV shows that I have added and setting it to block the tag on another account.

Within the TV menu the shows aren't visible, however, under the "Next Up" subheading the shows are still visible and are still playable.

**Comment by LukePulverenti** [comment]
Please try again with the next release of Emby Server. Make sure to run a library scan after updating. Thanks !
