### ISSUE TITLE
Server won't authenticate

### ISSUE THREAD

**Issue by MediaAnalyst17** [MediaBrowser/Emby#2508]
Every time I put the access numbers in, the server is denied

**Comment by LukePulverenti** [comment]
Hi there, can you please describe your issue with a little more detail? What are you entering where? Is there an error message? If so, what does it say? Thanks.

**Comment by MediaAnalyst17** [comment]
I enter the server code for LAN but when it loads, it says, "We're unable to connect to the selected server right now. Please ensure it is running and try again." I tried the WAN code but the same thing pops up.

**Comment by LukePulverenti** [comment]
What code?

**Comment by MediaAnalyst17** [comment]
The in-home access code. And the remote access code

**Comment by LukePulverenti** [comment]
Where did you get those values?

**Comment by MediaAnalyst17** [comment]
From my laptop's server's dashboard.

**Comment by LukePulverenti** [comment]
And where exactly did you enter it?

**Comment by MediaAnalyst17** [comment]
To my home desktop's server finder

**Comment by LukePulverenti** [comment]
Can you explain that in more detail? What is home desktop server finder?

**Comment by MediaAnalyst17** [comment]
When I put in my emby connect account, and clicked: "Add Server"

**Comment by LukePulverenti** [comment]
Where did you put in your emby connect account?

**Comment by MediaAnalyst17** [comment]
After i went to the main site and clicked log in

**Comment by MediaAnalyst17** [comment]
On the app, after I clicked "SIGN IN" on the main site.

**Comment by MediaAnalyst17** [comment]
Just tried it. usual happen.

**Comment by MediaAnalyst17** [comment]
Just tried inputing the code and ports on my iPad mini, still nothing. It happens with everything,
