### ISSUE TITLE
Emby via iPhone, dialog boxes rarely work

### ISSUE THREAD

**Issue by simonk83** [MediaBrowser/Emby#2510]
Navigating Emby via an iPhone (Chrome) is really quite hard.  Anytime a dialog box pops up it's almost impossible to choose an item and dismiss the box . More often than not, choosing an option just goes back a page instead.
This makes changing settings hard of course, but also watching a show is often impossible as if you need to disable subtitles or changes settings, it's not possible to remove the dialog box once it's open.

I'll try in safari in a sec to see if it's the same.

**Comment by simonk83** [comment]
Actually it's fine in safari so that's a workaround for now.

**Comment by LukePulverenti** [comment]
Can you describe in more detail? I have never seen this, sorry. It pops up, you pick something, and then the box dismisses on it's own. Thanks.

**Comment by simonk83** [comment]
So the dialog box pops up, but it won't dismiss.  Clicking an option highlights it as you'd expect, but the click seems to either go right through the dialog and click whatever's behind it, or it acts as a back button.

Is it possible to record a gif from an iPhone screen?  I'll look into that.

**Comment by LukePulverenti** [comment]
What version of Chrome on iPhone?

**Comment by simonk83** [comment]
56.0.2924.79

**Comment by animosity22** [comment]
If you hit the home button and the lock button on the side (iphone 7), it records a screenshot.
