### ISSUE TITLE
Unable to decode certificate for https traffic.

### ISSUE THREAD

**Issue by dkanada** [MediaBrowser/Emby#2513]
I have looked through the forums and other issues here but haven't found anything, am I missing a dependency?

Here is the line that has the error.

> 2017-03-06 02:56:58.0703 Error App: Error loading cert from /var/lib/emby/ssl/cert_54522e99effc77b8a5bc7ed2e196033b.pfx

Here is another line that looked useful from the log.

> System.Security.Cryptography.CryptographicException: Unable to decode certificate. ---> Mono.Btls.MonoBtlsException: MonoBtlsPkcs12.Import failed.

Let me know if you need the whole text file, I can upload it somewhere if necessary. I have tried both a custom cert and leaving the field blank so emby uses a generated cert.

**Comment by LukePulverenti** [comment]
Is this mono 4.8?

**Comment by dkanada** [comment]
Yes, mono is on version 4.8.0 on the machine.

**Comment by dkanada** [comment]
Here is a [link](http://pastebin.com/z6CJhyVc) to the full error message, let me know if this helps at all.

**Comment by flaub** [comment]
This might be related: https://bugzilla.xamarin.com/show_bug.cgi?id=1660

**Comment by LukePulverenti** [comment]
That's an older ticket, but this looks like one to keep an eye on: https://bugzilla.xamarin.com/show_bug.cgi?id=52675

**Comment by LukePulverenti** [comment]
There was a mono service release today. I haven't had a chance to test it yet but that would be good info to know if it still occurs with that.

**Comment by dkanada** [comment]
The mono update has not been added to my repos yet but I downgraded mono to 4.6 and HTTPS is working again. I will close the ticket since it is probably an issue with mono. Let me know if you want more information.
