### ISSUE TITLE
Issues with self generating titles in Emby for TV Series

### ISSUE THREAD

**Issue by Timk69** [MediaBrowser/Emby#2529]
Hello,  I am new using Emby.  I was able to figure it out... The issue I am encountering is that when I upload my TV series that I have on my external hard drive, all my Season 1 folder list uses, the same exact title..(Shaitaan-a Criminal Mind, Tv Season 1 [India]),  Now even after editing the files, I was able to delete that title that it self generates, but even after refreshing... it comes back showing that.  Is there any way to permanently delete that?

**Comment by LukePulverenti** [comment]
Hi there @Timk69, can you please go over an example? What does the folder structure look like? Thanks !

**Comment by Timk69** [comment]
Hi there Luke, 
Thanks, but I played around with the program...and figured it out.
