### ISSUE TITLE
Subtitles not streaming to chromecast

### ISSUE THREAD

**Issue by kaithar** [MediaBrowser/Emby#2537]
Similar to #835 I'm trying to stream an MKV container with ASS subtitles.  The video and audio is playing fine (I'm pretty sure it's H264 w/ AAC) but the subtitles aren't being transcoded.  I'd guess the video and audio are being detected as suitable for direct play and the subtitles are being ignored in that logic?

Not sure how to trouble shoot it or what information you'd need.  I'm trying to cast from the web app and the server is 3.2.7.0 on FreeNAS using the standard plugin.

**Comment by LukePulverenti** [comment]
Hi there, sorry to hear about this. Can you please provide the info requested in how to report a media playback issue? You can learn how to do that here:

https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/

Thanks !

**Comment by kaithar** [comment]
In preparing the log I think I see what's happening.

So it's saying  to encode subs:
> http://192.168.1.38:8096/videos/XXX/stream.mkv?DeviceId=XXX&MediaSourceId=XXX&VideoCodec=h264&AudioCodec=mp3,aac&AudioStreamIndex=1&SubtitleStreamIndex=2&VideoBitrate=10808000&AudioBitrate=192000&StartTimeTicks=314398190&Level=51&Profile=high&PlaySessionId=XXX&api_key=XXX&CopyTimestamps=true&SubtitleMethod=Encode&TranscodingMaxAudioChannels=2&EnableSubtitlesInManifest=false&Tag=XXX&RequireAvc=true

It found the subtitles:
> 
> {"Protocol":"File","Id":"XXX","Path":"Ange Vierge - S01E12 - I Will Evolve with You.mkv","Type":"Default","Container":"mkv","Name":"1080P/H264/AAC","IsRemote":false,"ETag":"XXX","RunTimeTicks":14170900480,"ReadAtNativeFramerate":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"SupportsProbing":true,"VideoType":"VideoFile","MediaStreams":[{"Codec":"h264","Language":"jpn","TimeBase":"1/1000","CodecTimeBase":"125/5994","NalLengthSize":"4","IsInterlaced":false,"IsAVC":true,"BitRate":2235226,"BitDepth":8,"RefFrames":4,"IsDefault":true,"IsForced":false,"Height":1080,"Width":1920,"AverageFrameRate":23.97443,"RealFrameRate":23.97443,"Profile":"High","Type":"Video","AspectRatio":"16:9","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p","Level":40,"IsAnamorphic":false},{"Codec":"aac","Language":"jpn","TimeBase":"1/1000","CodecTimeBase":"1/44100","DisplayTitle":"Jpn AAC stereo Default","IsInterlaced":false,"ChannelLayout":"stereo","Channels":2,"SampleRate":44100,"IsDefault":true,"IsForced":false,"Profile":"LC","Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0,"IsAnamorphic":false},{"Codec":"ass","Language":"eng","TimeBase":"1/1000","CodecTimeBase":"1/1000","DisplayTitle":"Eng Default","IsInterlaced":false,"IsDefault":true,"IsForced":false,"Type":"Subtitle","Index":2,"IsExternal":false,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Level":0,"IsAnamorphic":false}],"PlayableStreamFileNames":[],"Formats":[],"Bitrate":2235226,"RequiredHttpHeaders":{}}

But ffmpeg goes:

> /usr/pbi/emby-amd64/bin/ffmpeg -ss 00:00:31.439 -f matroska -codec:0 h264 -codec:1 aac -i file:"Ange Vierge - S01E12 - I Will Evolve with You.mkv" -map 0:0 -map 0:1 -codec:v:0 libx264 -force_key_frames "expr:gte(t,n_forced*5)" -copyts -vf "scale=trunc(min(max(iw\,ih*dar)\,1280)/2)*2:trunc(ow/dar/2)*2,subtitles='Ange Vierge - S01E12 - I Will Evolve with You.mkv:si=0'" -avoid_negative_ts disabled -start_at_zero -pix_fmt yuv420p -preset superfast -crf 23 -maxrate 2235226 -bufsize 4470452 -vsync -1 -profile:v high -level 4.1 -x264opts:0 subme=0:rc_lookahead=10:me_range=4:me=dia:no_chroma_me:8x8dct=0:partitions=none -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 libmp3lame -ac 2 -ab 192000 -af "aresample=async=1" -y "/var/db/emby-server/transcoding-temp/XXX.mkv"
> 
>     Stream #0:2(eng): Subtitle: ass (default)
>     Metadata:
>       BPS             : 120
>       DURATION        : 00:21:44.690000000
>       NUMBER_OF_FRAMES: 349
>       NUMBER_OF_BYTES : 19626
> Fontconfig error: Cannot load default config file
> [Parsed_subtitles_1 @ 0x80a6d6260] No usable fontconfig configuration file found, using fallback.
> Fontconfig error: Cannot load default config file

So, the FreeNAS plugin image doesn't have a working fontconfig by the look of it... or rather, it has fontconfig but not a default config file for it.  I think that's something that would be fixed in the plugin config?

**Comment by josh4trunks** [comment]
I'm wondering if this can be fixed similar to what is done for the subsonic plugin.
See https://github.com/josh4trunks/freenas-plugins/blob/master/plugins/subsonic/scripts/post-install.sh#L16-L25

Can you try creating a font config at '/usr/local/etc/fonts/fonts.conf' with...
```
<?xml version="1.0"?>
<fontconfig>
	<dir>/usr/local/lib/X11/fonts</dir>
</fontconfig>
```
If that works I can have the plugin create that file automatically

**Comment by LukePulverenti** [comment]
Did you have a chance to try this?

**Comment by kaithar** [comment]
Sorry, I went on holiday just after and completely forgot.  Mea Culpa.

Good news!  I have another error log!  Wait, that's not good news.

```
[Parsed_subtitles_1 @ 0x80a799320] Unable to open /media-library/long ass titles suck.mkv
[AVFilterGraph @ 0x80a45b720] Error initializing filter 'subtitles' with args '/media-library/long ass title\'s suck.mkv:si=0'
Error opening filters!
```
The filter spec looks to be this one:
`-vf "scale=trunc(min(max(iw\,ih*dar)\,1280)/2)*2:trunc(ow/dar/2)*2,subtitles='/media-library/long ass title'\\\''s suck.mkv:si=0'"`

Something dodgy in how it's handling those apostrophes (I was careful to keep the formatting intact, those lines in the file are missing, `\` and `'\\\''` respectively).... very weird.

So, trying another file minus the apostrophe, that file gets rid of the error but doesn't seem to make my subtitles appear either.  No new errors either.  Weird.

No errors jumping out, though I'm not sure if this detail is relevant:
`video:230808kB audio:33286kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.238557%`
Subtitle is 0 there because it's applying as a filter, right?

Any ideas?

**Comment by kaithar** [comment]
I've updated to 3.2.17.0 and I'm still seeing both of these problems.  If there's anything I can do to help debug it, please do yell.

**Comment by LukePulverenti** [comment]
Please try again, thanks.

**Comment by LukePulverenti** [comment]
Any news?

**Comment by kaithar** [comment]
Sorry, the downside of crazy times at work is less time to check notifications. So, lemmie try...

The ... heck ...
I'm still running version 3.2.17.0 but it seems like both the apostrophe issue and the subtitle issue have gone away since I last tested.  I swear I retested when I last commented and I don't think I've updated or restarted anything since, weird.

So, I'm guessing it's the chromecast app update even though the problem seemed like it was on server side.  Either way, I'm very happy to be able to watch subbed stuff on my tv again.  Thank you ^_^

**Comment by Sweetie2024** [comment]
Got it to work by going to settings, "username"preferences, subtitles, subtitle mode, check "always play subtitles." "Default" mode won't work unless it's in the file metadata, so just adding a subtitle won't suffice. "Smart" mode won't work unless the default audio is in a foreign language. "Only forced" won't work because.... well it's self explanatory." "Hearing impaired" will only work with SDH subtitles. Therefore, "Always play" is the only option if you want to turn on a subtitle in your preferred language.
