### ISSUE TITLE
Add Wake on Lan feature to Emby Server

### ISSUE THREAD

**Issue by bjoerns1983** [MediaBrowser/Emby#2540]
Hi there,
i think it would be a great enhancement if the Emby Server would be capeable to wake up NAS Servers when a client is requesting a file.

So the Emby Server could run on a low power consumption 24/7 Server while the media reside on NAS Server which normally need far more power.  

This topic was also discussed on the forum: https://emby.media/community/index.php?/topic/46106-wake-on-lan-over-htpc-emby-server-nas/

**Comment by bennySB** [comment]
i´m with him.

This would be a great feature.

Important is the Magic Package Feature.

**Comment by NeskireDK** [comment]
Yeah this would be brilliant. Magic package is the only way to go.

**Comment by LukePulverenti** [comment]
This has been added for the next release, thanks. Emby apps will need a little time to get updated but the android and windows uwp apps have been updated for their next releases. Thanks.
