### ISSUE TITLE
Full screen when embedded

### ISSUE THREAD

**Issue by Luticus** [MediaBrowser/Emby#2546]
I run a nextcloud server and one of the things I do with it is embed my emby server through the external apps app.  it works perfectly with one unfortunate exception.  The fullscreen button is rendered useless during playback.

I would like to request the feature to give emby the capability of playing full screen video even when embedded in other web apps.

**Comment by LukePulverenti** [comment]
To be honest I don't think we have much control over this. We are using the browser's full screen api. There's no other way to do it besides that.

**Comment by Luticus** [comment]
Hum, that's a shame.  I wonder if I can figure out a way to have it open in a new tab then instead of an embedded iframe.  That might solve it.

**Comment by LukePulverenti** [comment]
Yes in general i would not recommend embedding because some browsers will dis-allow certain features within the embedded frame.
