### ISSUE TITLE
 System.IO.FileNotFoundException iconosd.css

### ISSUE THREAD

**Issue by Al-25** [MediaBrowser/Emby#2551]
Hello,

I encounter an issue in the webui, which doesn't want to start correctly anymore.
A quick look on the log show the following error :
System.IO.FileNotFoundException: Could not find file "/usr/lib/emby-server/bin/dashboard-ui/scripts/iconosd.css"

A  search of the missing file show that this file exists but in another directory :
:~$ locate iconosd.css
/usr/lib/emby-server/bin/dashboard-ui/bower_components/emby-webcomponents/playback/iconosd.css 

Any idea of where this problem(the missing file/bad path) came from ? Any idea of a solution ?
The only partial workaround to solve this issue was to make an ln -s of the file but the webui now working just partially.it seems only parts of the css are functionnal.

I already encounter a similar issue before, and the only real solution was to reinstall.
 
Thanks in advance,

Kr

**Comment by LukePulverenti** [comment]
Hi there, can you please attach the complete log file? thanks.

**Comment by Al-25** [comment]
here it is !
[server-63626319647.txt](https://github.com/MediaBrowser/Emby/files/876642/server-63626319647.txt)

**Comment by LukePulverenti** [comment]
It looks like the server is starting up OK. What is the problem you are having?
