### ISSUE TITLE
URL only movie.nfo does not seem to work at all

### ISSUE THREAD

**Issue by anoma** [MediaBrowser/Emby#2559]
There are numerous references on the forum to URL only movie.nfo's working (i.e. a flat text file that lives beside the movie file called movie.nfo which contains just the IMDB URL.

Not XML as per http://kodi.wiki/view/NFO_files/Movies#Video_.nfo_files_containing_a_URL).

As far as I can tell this feature no longer works if the file is called movie.nfo but does work if the file is named moviefilename.nfo.

I verified nfo is set before Emby Xml in metadata readers and also tested it with a single nfo file to ensure precedence is not at play.

(New user attempting to migrate from Kodi headless docker and mariadb backend.)

**Comment by LukePulverenti** [comment]
Hi there, can you please discuss a specific example? thanks.

**Comment by CvH** [comment]
I had the same problem at Win10 + Emby Server
![image](https://cloud.githubusercontent.com/assets/1355173/24980134/2f7dda2a-1fd7-11e7-84b2-b6e7e17f54b8.png)
after adding it to the lib it ignores the movie.nfo and only tries to predict the movie name from the folder/file name.

**Comment by anoma** [comment]
I tested using the following:

```
mkdir "Some Name 1"
echo "http://www.imdb.com/title/tt0204946/" > "./Some Name 1/movie.nfo"
touch  "./Some Name 1/Some Name.mkv"

mkdir "Some Name 2"
echo "http://www.imdb.com/title/tt0204946/" > "./Some Name 2/Some Name.nfo"
touch  "./Some Name 2/Some Name.mkv"
```

The movie in folder  `Some Name 1` is identified incorrectly as `Some Name 1`.
The movie in folder  `Some Name 2` is identified correctly as the modern classic `Bring It On` :)

**Comment by anoma** [comment]
Thanks for accepting this as a bug.

It appears that the same issue exists for URL only `tvshow.nfo` where it is ignored in favour of the folder name.

**Comment by anoma** [comment]
Can someone independently confirm this fix works as desired because I simply cannot make URL only movie.nfo or tvshow.nfo work at all.

In all cases URL movie.nfo or tvshow.nfo is ignored and the folder name is used. Have I missed some setting?

**Comment by LukePulverenti** [comment]
I've tested and it seems to be working fine, thanks.

**Comment by CvH** [comment]
@LukePulverenti it only works if you use movie.mkv + movie.nfo
1+2 isn't working, 3+4 is working
```
Emby$ ls -lRa
Some Name 1
Some Name 2
Some Name 3
Some Name 4

./Some Name 1:
movie.nfo
some name.mkv

./Some Name 2:
movie.nfo
some name.mkv

./Some Name 3:
movie.mkv
movie.nfo

./Some Name 4:
movie.mkv
movie.nfo
```

**Comment by LukePulverenti** [comment]
Need more specific examples, thanks.

**Comment by CvH** [comment]
demo data [Emby.zip](https://github.com/MediaBrowser/Emby/files/1166230/Emby.zip)
extract somewhere, add to your lib as movies

Expected behavior is that Emby get the needed information from the `movie.nfo` for the abc.mkv file.
It does not work for folder 1+2, it works for folder 3+4.

currently it only works if the *.mkv and the *.nfo has the same basename (movie.mkv + movie.nfo, or, whatever.mkv + whatever.nfo)

**Comment by anoma** [comment]
Using Emby.zip from above I can replicate the error and agree with the conclusion that currently `it only works if the *.mkv and the *.nfo has the same basename`

**Comment by LukePulverenti** [comment]
Ok yes i can confirm movie.nfo is being ignored. thanks.

**Comment by anoma** [comment]
Confirm the 3.2.26.0 release fixes movie.nfo however tvshow.nfo appears to remain broken.

Would you like a new ticket or a continuation of this one.

**Comment by anoma** [comment]
Returning to try this again after a 5 month absence I am happy to report `tvshow.nfo ` now works in `3.2.50.0`
