### ISSUE TITLE
support Hauppauge devices

### ISSUE THREAD

**Issue by rdesfo** [MediaBrowser/Emby#2565]
I have a Hauppauge HVR950Q tv tuner and it would be great if I could use it in emby without having to setup tvheadend and installing its plugin.

**Comment by SvenVandenbrande** [comment]
@rdesfo We are working on some great stuff. Stay tuned for that. :)

**Comment by LukePulverenti** [comment]
Now available for testing: https://emby.media/community/index.php?/topic/54560-32609-hauppauge-support/

However this is currently Windows only so if you're using TvHeadEnd then I'm guessing you need Linux support.
