### ISSUE TITLE
Issues found by PVS-Studio

### ISSUE THREAD

**Issue by VasilievSerg** [MediaBrowser/Emby#2572]
Hello,
I have found a few issues using PVS-Studio analyzer. PVS-Studio is a static code analyzer for C, C++ and C#: https://www.viva64.com/en/pvs-studio/

Analyzer warnings:
- V3021 There are two 'if' statements with identical conditional expressions. The first 'if' statement contains method return. This means that the second 'if' statement is senseless MediaBrowser.Model MediaFormatProfileResolver.cs 348
[A link to the source code.]( https://github.com/MediaBrowser/Emby/blob/fdcf02a7cb00599b68d3a7e62f98eb4db03d8012/MediaBrowser.Model/Dlna/MediaFormatProfileResolver.cs#L352)
- V3080 Possible null dereference. Consider inspecting 'x'. BDInfo BDROM.cs 438
[A link to the source code.]( https://github.com/MediaBrowser/Emby/blob/fdcf02a7cb00599b68d3a7e62f98eb4db03d8012/BDInfo/BDROM.cs#L438)
- V3053 An excessive check. Examine the conditions containing search for the substrings 'comment' and 'commenturl'. SocketHttpListener.Portable CookieHelper.cs 86
[A link to the source code.]( https://github.com/MediaBrowser/Emby/blob/fdcf02a7cb00599b68d3a7e62f98eb4db03d8012/SocketHttpListener.Portable/Net/CookieHelper.cs#L86)
- V3010 The return value of function 'TrimEnd' is required to be utilized. Emby.Common.Implementations FilePath.cs 131
[A link to the source code.]( https://github.com/MediaBrowser/Emby/blob/fdcf02a7cb00599b68d3a7e62f98eb4db03d8012/Emby.Common.Implementations/IO/SharpCifs/Util/Sharpen/FilePath.cs#L131)

In addition, I suggest having a look at the emails, sent from @pvs-studio.com.

Best regards,
Sergey Vasiliev

**Comment by LukePulverenti** [comment]
Thanks !
