### ISSUE TITLE
Library Scan - Dealing with Cloud / Network Mount Points

### ISSUE THREAD

**Issue by animosity22** [MediaBrowser/Emby#2573]
I had a feature request as I have a large library in the cloud and one thing that becomes more problematic is when a mount point goes away and a scan fires off.

I rebooted today as an example and realized my mount didn't come online for my ACD folder. 

Once that happens, it has to run a ffprobe against the file as it didn't see it on first scan and now the full path is back.

The expected behavior would be to validate the file size/timestamp/etc are all the same and just repoint it back to the right file. 

Ideally, it would be great if it scanned it locally and saw the same file/timestamp/etc in a different path, to just adjust the path to the new location

Example log:
```
Apr  4 17:57:23 plex emby-server[5293]: Input #0, matroska,webm, from 'file:/media/TV_Ended/Breaking Bad/Breaking.Bad.S03E02.Caballo.Sin.Nombre.Bluray-720p.mkv':
Apr 10 14:19:04 plex mono-sgen[3648]: file:/media/TV_Ended/Breaking Bad/Breaking.Bad.S03E02.Caballo.Sin.Nombre.Bluray-720p.mkv: No such file or directory
Apr 10 14:59:41 plex mono-sgen[3648]: Input #0, matroska,webm, from 'file:/media/TV_Ended/Breaking Bad/Breaking.Bad.S03E02.Caballo.Sin.Nombre.Bluray-720p.mkv':
```

You can see I first scanned it on the 4th and today, it lost the path and then rescanned it subsequently now. While one file isn't bad, moving around a lot of files takes a day or two to scan through and that is painful.

**Comment by mikeferr** [comment]
+1 Had a power outage this morning, server booted with ip 172.0.0.1(docker0) (I'm guessing because my router hadn't fully booted yet) so no internet. My library was empty when I got back from work. Now I need to wait 3+ hours to re-scan my rclone mounted google drive folder again :(

**Comment by LukePulverenti** [comment]
Please try again with the newest release of Emby Server, thanks !
