### ISSUE TITLE
How to install Emby server with Mysql

### ISSUE THREAD

**Issue by Mokhless** [MediaBrowser/Emby#2596]
Hi,
I want to install Emby server using Mysql database.
It's Possible? if yes help me per information
Thanks

**Comment by SvenVandenbrande** [comment]
For the moment, that's not possible....

**Comment by Mokhless** [comment]
with Microsoft SQLserver?

**Comment by SvenVandenbrande** [comment]
For the moment it's only with sqlite...

**Comment by Mokhless** [comment]
ok thanks
