### ISSUE TITLE
Softsubs converted to srt

### ISSUE THREAD

**Issue by ShoelaceMan** [MediaBrowser/Emby#2600]
My anime mkv's have fancy subtitles, that integrate with the video in various ways, with position, and styling, here's an example : http://www.crymore.net/wp-content/uploads/2013/10/Underwater-KILL-la-KILL-02-720p-C0DDB47F.mkv_snapshot_04.14_2013.10.12_13.05.52.jpg

And when played normally though sftp on Kodi, they function as expected, but when I use emby, I get just plain text, with lots of numbers and data that fills up the whole screen with subtitles, leaving the video almost unwatchable, since it covers up most of the screen. I think that emby is converting my subtitles to srt? Anyways, it would be nice to have working soft subs.

**Comment by LukePulverenti** [comment]
Hi there, can you please go over a specific example, while providing the information requested here:
https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/

Thanks !

**Comment by ShoelaceMan** [comment]
Well a specific example is my particular copy of no game no life, I'll have to post screenshots later, because I obviously can't send you the video file.

**Comment by LukePulverenti** [comment]
Hi, that's very old. I'm not asking for a copy of your video file, what I'm asking for is discussion of an example by providing the information requested in the link above. Thanks !

**Comment by LukePulverenti** [comment]
Closing, but please feel free to re-open when information is supplied. Thanks !
