### ISSUE TITLE
Web App Not Playing Next Song on Android

### ISSUE THREAD

**Issue by dominic-p** [MediaBrowser/Emby#2609]
First, thanks for the excellent software. I'm having an issue where I can't get a playlist to continuing playing on Android.

## Steps to Reproduce

1. Start playing a music playlist (I usually use the Shuffle button)
2. Let the first song play until it ends

## Expected Behavior

After a song ends, the next one should start playing.

## Observed Behavior

The song ends and the next song does not start. You can start it manually, but then playback will stop again after that song ends.

## Environment

- Emby Server running on CentOS 7 from official repo
- Web App running on Opera for Android (observed same behavior on Chrome for Android)
- Android 7.0 (Galaxy S7)

In the past, I have ran into this problem on a different app I was developing. The issue then was that the browser would suspend javascript execution while the phone was asleep. So, the code to play the next song was never executed. However, I'm seeing this behavior whether or not the phone is awake, so I'm not sure that this is the problem.

Let me know if I can provide any more information.

**Comment by LukePulverenti** [comment]
This won't happen if the phone is awake and the web app is in the foreground. Once the browser moves to the background the OS will suspend it after a period of time. There is not much we can do and I don't believe the browsers support playback from a serviceWorker at this time. This is why in the native apps nowadays all playback originates from background services so that once the UI is suspended it won't effect playback.

**Comment by dominic-p** [comment]
Wow, thanks for the quick and insightful reply. I'm still pretty new to service workers. Could they be used to send an event or message to the main thread that's handling playback to start the next song? I could see it working like this:

1. Song starts.
2. A message is sent to the service worker to schedule a message/notification for when the song ends (based on song length)
3. Song ends. The service worker sends a message to the main app to start the next song.

Of course, if the user intervened in playback, any pending messages would have to be canceled.

Thoughts? Bad idea?

**Comment by LukePulverenti** [comment]
I am not sure the service worker is capable of waking the UI. It might be, I just haven't checked it's api. Even still it may not matter because if the UI is suspended then you won't get any events that the song ended. At this point we may just have to wait for more service worker features to be added.

**Comment by dominic-p** [comment]
Ok, I'll look into the service worker API when I get some time.

I know there's also a Wake Lock API that the W3C is playing with. If that gets supported, we might be able to simply acquire a CPU only wake lock when playback starts and release it when playback stops.

**Comment by LukePulverenti** [comment]
I'm going to close this because there isn't anything we can do about it as of today. Thanks.

**Comment by dominic-p** [comment]
Makes sense. I've been exploring a few different avenues that could work.

- `ExtendableEvent.waitUntil()` could be perfect, but I'm not sure how to make it work. See [this discussion](https://github.com/w3c/ServiceWorker/issues/838#issuecomment-188273853).

- The [W3C Task Scheduler API](https://www.w3.org/TR/task-scheduler/) should also be able to solve the problem if it's ever adopted. Same with the [W3C Wake Lock API](https://www.w3.org/TR/wake-lock/). I think the later is implemented behind an experimental flag in Chrome for desktop, but I'm not sure about mobile (where we need it).

- The most promising solution I found that could work now is to leverage the Push API. Basically, when the user starts playing a song, a message is sent to the server with the song's duration. Then, the server sends a push message to the client just before the song is set to end. Ideally, this would wake the client and allow it play the next song. There are 2 unresolved issues with this approach I can see so far: 1) I'm not sure if the push would actually wake the device or if it would just be queued for when the device wakes up (defeating the point). 2) I'm not sure if we can send a push message without a visible UI (which would annoy users).

Anyway, I wanted to document what I found for now. If I have time to play with it some more I'll post here. But, we can leave the issue closed until we have something concrete/usable.

**Comment by LukePulverenti** [comment]
I think the ultimate answer is playback from service worker, coupled with a wake lock in the service worker. That will allow the UI to be suspended. I am guessing that is what they will do because that would align it with typical android and ios playback.

**Comment by dominic-p** [comment]
You may be right about that, but from what I've been reading, Service Workers are [meant to be](https://github.com/WICG/webusb/issues/22#issuecomment-178647401) [short lived](https://github.com/w3c/ServiceWorker/issues/838#issue-135581344). It would probably change their life-cycle/design philosophy considerably to enable playback. But, we'll just have to see how the landscape develops.

**Comment by dominic-p** [comment]
Sorry to post again on a closed issue. I had one other idea that could work. What if we live streamed the audio?

The server could dynamically generate a stream from the files in the playlist. We wouldn't have to worry about js being suspended because the audio source wouldn't need to be changed. 

There are other advantages too including faster startup time and the ability to do fancy adaptive bitrate streaming if the bandwidth changes. 

There seem to be quite a few different streaming protocols out there including the Web Audio API. This [node package](https://www.npmjs.com/package/websockets-streaming-audio) looks like an interesting take on the problem using Web Audio over Web Sockets. 

Thoughts?

**Comment by LukePulverenti** [comment]
I suppose the stream idea is possible, in theory. I don't think the web audio thing will make any difference because the root problem is that playback in the UI cannot be controlled when the UI is suspended.
