### ISSUE TITLE
[Win7] Transcoding stopped working on updating from 3.2.13 to .15

### ISSUE THREAD

**Issue by RealTabman** [MediaBrowser/Emby#2631]
Emby Server run as a service on Windows 7 x64, Client Raspberry Pi3 with Libreelec kodi 17.1 Emby for Kodi 2.3.47

After updating to 3.2.15, transcoding (either hi10 or hevc265) playback won't start. Sometimes I get the message in Kodi (paraphrased) "playback failed, can't find next item in playlist", but most often simply nothing happens without any error message. No difference with "play from http" or smb.
After reverting to 3.2.13 transcoding works again without any apparent issue.

Some background:
I always had problems with transcoding (see also [this link](https://emby.media/community/index.php?/topic/40692-10-bit-transcoding-funky-colours-on-libreeleckodi/)) and I was quite surprised that it worked suddenly with 3.2.13. It actually may have started working in an earlier version, but I'm not sure about that since I simply stopped trying some times ago.

No log files, sorry. If they are absolutely needed, tell me and I'm installing .15 again to get them.

**Comment by LukePulverenti** [comment]
Hi, try updating the Emby for Kodi add-on. If the issue persists then yes log files are needed. Thanks.

**Comment by RealTabman** [comment]
First, I want to appologize that it took me so long to reply. SORRY! 
 And regarding my transcode problems, it seems that with 3.2.19.0 I no longer have any problems transcoding 10bit files; except for a few movie files from way back when 10bit encoding was a bit (hehe) experimental.   
Also, I'm not entirely sure that the new Emby version fixed the problem, or if it has to to with the fact that I made a clean install of Libreelec/Kodi for my Pi3 with only stable add-ons.

Anyway, you have my thanks :)
