### ISSUE TITLE
Music stops after each song

### ISSUE THREAD

**Issue by jcgruenhage** [MediaBrowser/Emby#2643]
Not sure where this comes from, but music will only play for one song on Chromium on Fedora. The music just stops after every song. Pressing next starts the next song, but that again will only play until the end of that song. It works on Firefox, so this doesn't have a high priority for me, but I think it is worth looking into anyway, since most people use chromium based browsers. Might be related to #2609.

**Comment by jcgruenhage** [comment]
The problem now started to appear on firefox too :(

**Comment by LukePulverenti** [comment]
What about Chrome instead of Chromium?

**Comment by jcgruenhage** [comment]
Have you tried it with Chromium/Firefox (on Fedora)? If I didn't care about using open source software, I'd use Plex :P

**Comment by Frozen-byte** [comment]
This Issue is valid to me on my Android Chromium Browser. Playback stops after Each song, if Lockscreen is active.

**Comment by LukePulverenti** [comment]
Please also be sure you're on the latest release of the server. Thanks.

**Comment by LukePulverenti** [comment]
I was able to test on Fedora, didn't see a problem. Please re-open if you are still having an issue. Thanks.

**Comment by jcgruenhage** [comment]
Seems to work for me too now. Haven't used it in a while, or I would have closed this earlier.
