### ISSUE TITLE
Channel groups for LiveTV

### ISSUE THREAD

**Issue by SvenVandenbrande** [MediaBrowser/Emby#2646]
https://emby.media/community/index.php?/topic/47470-channel-groups-for-live-tv/

**Comment by RacerXx** [comment]
Yes please. with 3800+ iptv channels grouped from IPTV provider its hard to go through all 3800+ channels 5 at a time. This should not be labeled as enhancement IMO but instead a priority. This is a real downside and possible deal breaker for potential lifetime customers. Myself included. NextPVR already does all this and more and its free. Only thing emby has that nextpvr does not is linux

**Comment by manolodf** [comment]
This would be HUUUGE!   I 100% agree, the channel groups from the M3U are very useful in order to have manageable Sections of channel lists.  Since there is no easy way to jump into different sections, it is the easiest way to navigate to channels of a specific country or type.

**Comment by MCTyler** [comment]
I have reported this on the User Forum without realizing this has been an issue since May 18th, 2017. Definately need to bring this up in the next Board Meeting or whatever. IPTV Service Channels now number between 4000-5000. The whole Guide and Channel Section is a absolute Mess. ([EODCrafter)](https://emby.media/community/index.php?/user/279282-eodcrafter/) I have provide @LukePulverenti a free IPTV Example from my paid service so he could better understand our predicament, hopefully this will get the ball rolling! [Ref.](https://emby.media/community/index.php?/topic/63197-emby-sort-on-group-title-not-stream/#entry625739)

**Comment by MCTyler** [comment]
> yeah well they dont seem to think its a priority...canceled membership. I'll stick with NextPVR. Its free and DOES have channel groups

NextPVR Does not work in Linux :(

**Comment by RacerXx** [comment]
then run it in windows

**Comment by MCTyler** [comment]
No thanks, I like to have a little free memory :1st_place_medal:

**Comment by RacerXx** [comment]
well then dont know what to tell ya bud. Price you pay for running linux. Buy more memory. In regards to emby using IPTV they are all being shut down anyways so there isnt really a need for emby OR NextPVR or KODI anyways. And I damm sure wouldn't pay for a "Media Center" (emby) anyways. Im running windows 10 i dont need a 3rd party media center. Windows has pretty much everything i need out of the box

**Comment by MCTyler** [comment]
Temp Fix Until this Feature is added to Emby.....
https://xteve.de/
Allows Grouping in Emby. Enjoy!

**Comment by marilson8** [comment]
> Temp Fix Until this Feature is added to Emby.....
> https://xteve.de/
> 
> Makes IPTV run as HDHR and allows Grouping. Enjoy!

Is there a service that can provide M3U list in mp4/aac format that dont need to be transcoded or this always have to transcode?

**Comment by MCTyler** [comment]
Trans-coding of Streams is Emby's Compliance with "App Store Policies, AFAIK. My Streams Never Trans-code in Emby Theater.

**Comment by rlaphoenix** [comment]
Please do this, we need it!

**Comment by tpcr** [comment]
xTeve works for me until Emby has something. But don't hold you breath.

**Comment by bernhardberger** [comment]
Any news on this..?

**Comment by softworkz** [comment]
> xTeve works for me until Emby has something. But don't hold you breath.
......
> Any news on this..?

Hold your breath! There will be something soon.

**Comment by tpcr** [comment]
Yeah. Waiting in great anticipation!

**Comment by groenator** [comment]
I lost hope with this one ...:(

**Comment by LukePulverenti** [comment]
Channel groups will be in Emby Server 4.6. You'll be able to try them out on the beta channel later today if you like. Enjoy.

**Comment by groenator** [comment]
Awesome news. After waiting for a long time, I am looking forward to try the channel groups. From my perspective, this is a very good news. Thanks Luke!

**Comment by Floflobel** [comment]
This is great news ! Thank for your works !

**Comment by Cave-Johnson** [comment]
Great news! Look forward to testing this

**Comment by LukePulverenti** [comment]
https://emby.media/community/index.php?/topic/94476-46020-live-tv-channel-groups/
