### ISSUE TITLE
Wrong livetv audio stream, randomly

### ISSUE THREAD

**Issue by elboletaire** [MediaBrowser/Emby#2650]
From time to time, when I open a livetv channel (or when emby records livetv channels), the language of the audio stream is not correct.

In my case I have spanish by default. When I open the player it always says the language is spanish, but for some reason some times that's not true and obliges me to change the audio two times, or get back and try to load again the content. 

As you probably guess, the main problem is for the recordings... as their audio stream cannot be changed after they've been recorded.

I can help you debug this if you want, but need to know how first.

**Comment by LukePulverenti** [comment]
Hi, please discuss an example and provide the information requested here:

https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/

Thanks !

**Comment by elboletaire** [comment]
How can I discuss an example about this? It's a private rpc livetv channel, and I cannot see anything special in the logs. And I don't get why I need to open a topic in the forum to report a bug; [this is not the first time I report a bug here directly][bugs], but it's the first time you tell me about opening a forum topic 😕 

btw, since last update livetv for rpc channels stopped working, and there's nothing in the logs (although I've enabled logs verbosity under `Logs` in emby server).

[bugs]: https://github.com/MediaBrowser/Emby/issues?utf8=%E2%9C%93&q=author%3Aelboletaire%20

**Comment by LukePulverenti** [comment]
Hi, you don't need to open a forum topic, but you do need to provide the information requested in that link. Thanks !

**Comment by elboletaire** [comment]
Yeah the thing is that playing rpc channels doesn't work for me since I've updated to 3.2.20.0, but that's another issue and I'll need a bit of time to open an issue for it.

**Comment by elboletaire** [comment]
Ok, here I am again. I've just had this issue (between 12:40 and 13:05) when direct playing a livetv channel. Once I've detected the issue I first tried to change the audio stream (without success) and then I closed emby player and went directly to the logs dashboard, and here are all the logs modified during today (the screenshot is for information purposes):

![imatge](https://user-images.githubusercontent.com/153305/29069556-b36e9430-7c3b-11e7-9f98-be624706ca5b.png)

And here are **all the logs** (because in the `how to report a problem` page there's no specification about which logs to include) for today:

[emby logs.zip](https://github.com/MediaBrowser/Emby/files/1207812/emby.logs.zip)

My current emby server version is 3.2.26.0, but this happens since I've started using the livetv features half a year ago. Also, maybe it's not important but just in case, I use the docker installation (using the old installation mechanism).

@LukePulverenti can you please reopen the issue? Or should I open a new one due to the emby version change?

Note: When I told you to help you with this issue was due to the huge amount of logs that emby generates. Again, if you need me for some kind of test, I'll be able during all the day until August 16th (when my vacation end).
