### ISSUE TITLE
Unmap LiveTV channels from guide?

### ISSUE THREAD

**Issue by elboletaire** [MediaBrowser/Emby#2651]
I accidentally mapped a channel for which I don't have its tv guide information. Now I'd like to unmap it, but there's no way to do it.

I'd add a button near the pencil to remove the mapping:

![imatge](https://cloud.githubusercontent.com/assets/153305/26275092/311bf688-3d59-11e7-8049-dc2d29843a47.png)

**Comment by poppabear8883** [comment]
+1 for this, this would be super useful right now !!!

@LukePulverenti Any plans for this in the near future ?

**Comment by LukePulverenti** [comment]
This will be in the upcoming Emby Server 4.6 release. Thanks.
