### ISSUE TITLE
DLNA not working on my tvbox

### ISSUE THREAD

**Issue by oczkers** [MediaBrowser/Emby#2652]
I added one file to library just to test dlna and it works in windows media player for example but on my tvbox movie titles are "broken"
**[movie title]?Params=;test;432769d83f68f45b4d7a942fdb45a50a;true;;;;;;;;;;;0;;;;;;;;;432769d83f68f45b4d7a942fdb45a50a;false;;;false;510e21b2e11df069baa9bc55b83277b3;false;;false;false**

instead of just **[movie title]**

But biggest problem is that looks like client is closing connection just after asking for stream, could you tell me why is that?
I'm 100% sure that this file is compatible with client (or vice-versa) because it's working when serving via minidlna without transcoding at all.

Logs:
server: https://gist.github.com/oczkers/a8a5ae01df6a24b16249e84b51dd9927
ffmpeg directstream: https://gist.github.com/oczkers/c9da51bae5d4175e342991afde346c45

**Comment by SvenVandenbrande** [comment]
It's also a good idea to share the name of your tvbox. :) So we can search for some more information...

**Comment by oczkers** [comment]
You might be right, sorry for this :-)
[Netgem n7700](http://www.netgem.com/datas/media/1363108406_ProductSheet-N7700-04032013.pdf)

**Comment by LukePulverenti** [comment]
Can you please attach the original ffmpeg log? That has been edited and is missing some much needed debugging info. Thanks.

**Comment by oczkers** [comment]
looks like ffmpeg is getting killed by emby to my so i posted only ffmpeg params. Anyway retested on latest version, logs without any modifications - there are few missing files first but that's not the case i just didn't rescanned library.

server: https://gist.github.com/oczkers/50370bb8b4b12642ed75b67d234998dc
ffmpeg1: https://gist.github.com/oczkers/5c53e0714ec01546a9489a6f00abb1ec
ffmpeg2: https://gist.github.com/oczkers/50832b90e5da0a8ef062f58ff941cf96
ffmpeg3: https://gist.github.com/oczkers/9a60100786afc265647666f0a86899b5
ffmpeg4: https://gist.github.com/oczkers/3dca8ca39fad6154961ed635e4cdc43c

**Comment by LukePulverenti** [comment]
Did you customize anything under dlna? because i see things here that should not be happening under a default installation. thanks.

**Comment by LukePulverenti** [comment]
Any info?

**Comment by oczkers** [comment]
I don't think so but it was working exactly like this from beginning (fresh install). What things exactly are You talking about?

I probably won't use this box anymore with emby but of course i can make any test You like, just tell me.

**Comment by LukePulverenti** [comment]
Is this still an issue?
