### ISSUE TITLE
Error changing movie language

### ISSUE THREAD

**Issue by hudsonof** [MediaBrowser/Emby#2686]
When I am connected to another device and try to change the language of the movie an error occurs, it resets the movie timer and does not change the language.

Situation in which the error occurs:
Connected to the emby server by the chrome browser of the android smartphone.
I connect the cable to my LG Smart TV.
I play a movie.
I change the language by smarphone.

Then the error occurs.

**Comment by SvenVandenbrande** [comment]
Can you also add a log file?

**Comment by hudsonof** [comment]
[ffmpeg-remux-1ef7eec4-5083-435a-b7c9-78c230e9150b.txt](https://github.com/MediaBrowser/Emby/files/1049846/ffmpeg-remux-1ef7eec4-5083-435a-b7c9-78c230e9150b.txt)
[ffmpeg-remux-a5de3150-af59-4c0c-815f-84dc4fe70137.txt](https://github.com/MediaBrowser/Emby/files/1049847/ffmpeg-remux-a5de3150-af59-4c0c-815f-84dc4fe70137.txt)

**Comment by LukePulverenti** [comment]
What model LG is this? On the latest release of Emby Server I tested, no problem found. I am on a newer LG though. Did you start playback from the TV or from the phone?

**Comment by LukePulverenti** [comment]
Closing. Need more information to proceed further. Thanks.
