### ISSUE TITLE
10Bit HEVC decoding on FireTV Stick (Gen2) improperly attempts to direct play

### ISSUE THREAD

**Issue by Lord-Malgus** [MediaBrowser/Emby#2696]
The FireTV Stick (Gen2) model now supports HEVC decoding, Hooray!  However it currently only supports 8-Bit HEVC decoding.   If it attempts to decode 10-Bit HEVC it bombs out.  It does not appear that Emby takes this factor into account.  As when attempting to watch a 10Bit Encoded x265 video file, it attempts to directplay it.

encoder         : Lavf57.72.101
Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv), 1920x800 [SAR 1:1 DAR 12:5], q=2-31, 23.98 fps, 23.98 tbr, 90k tbn, 1k tbc (default)
Stream #0:1: Audio: aac, 48000 Hz, stereo, fltp
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 2467 fps=0.0 q=-1.0 size=   43466kB time=00:01:42.81 bitrate=3463.4kbits/s speed= 206x    
frame= 4695 fps=4693 q=-1.0 size=   88718kB time=00:03:15.73 bitrate=3713.0kbits/s speed= 196x    

All looks fine from the server side, however the Emby client fails to play. 

This is a request for Emby to Detect when the client is a FireTV Stick Gen2, to only initiate directPlay on an HEVC encode if it is 8Bit.   10Bit or greater should transcode.

**Comment by LukePulverenti** [comment]
is there an ffmpeg log? can you please attach that? thanks !

**Comment by Lord-Malgus** [comment]
Mediainfo does report the 10bit encoding in the log:
"Profile":"Main 10"


[hevc_10bit_fireTV_stick_gen2_log.txt](https://github.com/MediaBrowser/Emby/files/1065187/hevc_10bit_fireTV_stick_gen2_log.txt)

**Comment by ebr11** [comment]
Hi.  Can you please send a log from the app and then provide the information requested in the instructions linked below?  Thanks.

https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/

**Comment by Lord-Malgus** [comment]
Lost access to FireTV stick Gen2 at this time.  I will re-open when I have access to another Gen2 stick, and am able to supply logs for this issue.
