### ISSUE TITLE
Emby refuses to run on Windows Server 2016 Core

### ISSUE THREAD

**Issue by marukka** [MediaBrowser/Emby#2697]
I tried installing Emby 3.2.19.0 on Windows Server 2016 Core, however it refuses to run. Installing it on Windows Server 2016 Desktop Experience works just fine. It would be nice if you guys could figure out a way to work around whatever dependencies you have on the GUI so it will run on Server Core, or absent that add some logic to the installer to detect that it is running on a Core edition, and to notify the user of the dependency on the Windows Desktop Experience packages. Logs from the Server Core installation are attached.
[server-63632618073.txt](https://github.com/MediaBrowser/Emby/files/1065279/server-63632618073.txt)
[unhandled_aa531d3c-e0cb-4dfc-85ed-9e4b79ea0a81.txt](https://github.com/MediaBrowser/Emby/files/1065280/unhandled_aa531d3c-e0cb-4dfc-85ed-9e4b79ea0a81.txt)

**Comment by SvenVandenbrande** [comment]
As you can see it has a dependency on Skia... cc: @LukePulverenti

**Comment by LukePulverenti** [comment]
You might be interested in testing our new .NET core build:
https://emby.media/community/index.php?/topic/50012-emby-server-for-net-core/

Please note this is just for testing and experimentation right now. Thanks !

**Comment by LukePulverenti** [comment]
Either way, after looking at your error again, we did resolve a similar one. Please re-open if the issue persists. Thanks.
