### ISSUE TITLE
[Feature] Original title exposed in the REST API

### ISSUE THREAD

**Issue by fpietka** [MediaBrowser/Emby#2699]
I can see original title is stored into the database, but I can't seem to access it with REST API.

Am I missing something?
I'll be willing to help if it's not there, but I'm not familiar enough to the project structure (nor csharp to be honest) to spot where it happens in the code.

Thanks in advance for your insight.

**Comment by SvenVandenbrande** [comment]
Can you also tell what API call you are talking about?  :)

**Comment by LukePulverenti** [comment]
It's already in the api. It requires requesting the optional field OriginalTitle.

**Comment by fpietka** [comment]
Sorry, was talking about the movie items calls (although it is true for episodes too).
I thought I had the entire item when calling without fields.

I'll give it a try, thanks.

**Comment by fpietka** [comment]
Ok, I can confirm it is already there.
Thanks for your time.
