### ISSUE TITLE
Debian 9.0 automated builds

### ISSUE THREAD

**Issue by Nothing4You** [MediaBrowser/Emby#2725]
Hi there,
Debian 9.0 has been released, however, at https://software.opensuse.org/download.html?project=home%3Aemby&package=emby-server there is no package for Debian 9.0 available yet, only `Debian Next`.

**Comment by hurricanehrndz** [comment]
Thanks unfortunately with obs we are tied to when openSUSE finalizes the Debian 9 import and publishes. Like you said in the mean time Debian Next is available.

**Comment by hurricanehrndz** [comment]
Debian 9 has been enabled.
