### ISSUE TITLE
FLAC not being transcoded for Android sync

### ISSUE THREAD

**Issue by bobobo1618** [MediaBrowser/Emby#2735]
I have a Pixel running the Android O beta and version 2.9.15 of Emby and an Emby server running the latest Docker image (eff042ec3f77, 3.2.20.0, 7 days old).

Steps to reproduce:
- Put some FLAC on the server (in this case the 96kHz, 24-bit version of "Freesia" by "(K)NoW_NAME", purchased from [Mora.jp](http://mora.jp/package/43000033/A54197/))
- Ensure FLAC is in library
- Connect Android device to library
- Go to Android settings, select "Offline Sync", set "Max audio bitrate" to 320K
- Select album
- Press "Download"
- Select Quality "Medium"
- Press "Download"
- Open an Android file browser and navigate to `/storage/emulated/0/Android/data/com.mb.android/files/sync/<server name>/Music/<Artist>/<Album>`
- Check logs on server

Expected behaviour: ~30MB of Opus/MP3/AAC, `ffmpeg-transcode` log files on server.

Actual behaviour: ~1GB of FLAC, no `ffmpeg-transcode` logs on server.

I'm able to reproduce this with all the FLAC I've tried. Not sure whether this would be better filed against the Android app

**Comment by LukePulverenti** [comment]
The answer as of today is that offline downloading quality for music is controlled via a setting in the app, however, if you're given a prompt to select quality and you pick medium, then of course it should also take affect as you expect.

**Comment by bobobo1618** [comment]
@LukePulverenti I've set both settings. "Max audio bitrate" is 320K and I've selected "Medium" when creating the sync too.

Neither of them appears to be working as I'm getting the original FLAC.

**Comment by LukePulverenti** [comment]
This is resolved for the next update to the app and server, thanks.
