### ISSUE TITLE
Browser clients playback AAC audio rather than Opus

### ISSUE THREAD

**Issue by bobobo1618** [MediaBrowser/Emby#2736]
Steps to reproduce:
- Use Firefox (54.0.1) or Chrome (latest stable)
- Open Emby library
- Play music
- Observe network requests in dev console

Expected behaviour: Lots of Opus going backwards and forwards.

Observed behaviour: Browser makes requests to `http://<host>/emby/Audio/<id>/hls1/main/1.ts?UserId=<id>&DeviceId=<id>&MaxStreamingBitrate=1500000&Container=opus,mp3,aac,m4a,flac,webma,webm,wav,ogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&MaxSampleRate=48000&api_key=<key>&PlaySessionId=<id>&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=true&SegmentContainer=ts`

Note `AudioCodec=aac`.

ffmpeg logs show that AAC was the requested output type by the server.

My browser supports Opus (per [`canPlayType`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canPlayType) docs):

```javascript
var audio = document.createElement('audio');
audio.canPlayType('audio/ogg; codecs=opus');
> "probably"
```

**Comment by bobobo1618** [comment]
Looks like this is by design and I'm in the wrong repo:

https://github.com/MediaBrowser/emby-webcomponents/blob/a79a9fd203da8efb8cd512a3e102c6246f734ece/browserdeviceprofile.js#L497

**Comment by LukePulverenti** [comment]
Hi, no this ticket is fine here, thanks !

**Comment by LukePulverenti** [comment]
Yes we used to transcode to opus but after seeing a non-trivial number of random failures we were forced to go back to older, more stable encoders.

**Comment by bobobo1618** [comment]
Would it be possible to make this configurable? Also do you have an issue for the Opus failures that I could look at?

**Comment by LukePulverenti** [comment]
Well, i should have put more detail in my code comment but unfortunately I did not. I'll have to see if i can find the topics in the community.

**Comment by LukePulverenti** [comment]
Actually I think I recall that transcoding logs would look fine but both chrome and firefox would just randomly stop playing in the middle of the track. I can't make a setting for something that's just going to cause people to report problems. You can always find that file within your installation and customize it, although it will only affect the web app.

**Comment by bobobo1618** [comment]
Fair enough, I'll modify my local install and see if I can reproduce it and if I can, whether I can do anything about it.

**Comment by bobobo1618** [comment]
Hmm, looks like now there's a server issue. 

I disabled HLS (tore out [this](https://github.com/MediaBrowser/emby-webcomponents/blob/a79a9fd203da8efb8cd512a3e102c6246f734ece/browserdeviceprofile.js#L480)), prioritised streaming Opus (moved it to the front [here](https://github.com/MediaBrowser/emby-webcomponents/blob/a79a9fd203da8efb8cd512a3e102c6246f734ece/browserdeviceprofile.js#L498)) and begun playback.

Query params to `/emby/Audio/<id>/universal` were:

```
UserId	"<id>"
DeviceId	"<id>"
MaxStreamingBitrate	"1500000"
Container	"opus,mp3,aac,m4a,flac,webma,webm,wav,ogg"
TranscodingContainer	"opus"
TranscodingProtocol	"http"
AudioCodec	"opus"
MaxSampleRate	"48000"
api_key	"<key>"
PlaySessionId	"<id>"
StartTimeTicks	"0"
EnableRedirection	"true"
EnableRemoteMedia	"true"
```

But the response was `audio/flac`, not transcoded at all.

There doesn't appear to be anything relevant in the logs, it sees the request, prints `User policy for user. EnableAudioPlaybackTranscoding: True` then starts transmitting the raw file:
```
Setting range response values for /Music/Goose house/Bitter/01 Sing 2015.flac. RangeRequest: bytes=0- Content-Length: 38840194, Content-Range: bytes 0-38840193/38840194
Transmit file /Music/Goose house/Bitter/01 Sing 2015.flac
```

I wonder if perhaps this is related to the issue I'm seeing on Android: https://github.com/MediaBrowser/Emby/issues/2735
