### ISSUE TITLE
Subtitle font

### ISSUE THREAD

**Issue by DragsterPS** [MediaBrowser/Emby#2751]
I have some MKV that have subtitles with custom fonts attached, but on emby web server they are replaced by Arial font (i think).

**Comment by LukePulverenti** [comment]
The custom font is not available in the browser. We render the subtitles directly in the browser with a presentation designed to be close enough in exchange for avoiding having to burn them in with server transcoding. However, the next server release has added a setting that will allow you to control this and burn them in if that's what you prefer. When they are burned in on the server, then all of the custom styles will be preserved.
