### ISSUE TITLE
Continue watching of started movies later

### ISSUE THREAD

**Issue by DMWOO7** [MediaBrowser/Emby#2752]
I'm currently evaluating Emby as an OS alternative to Synology DSM. Seems a great software that fit nearly all my needs. But there is one feature that is missing for me: It's not possible to store the state of a movie to continue watching later. For example, when pause was pressed after 48:32, and the movie is played again, it begans from 0:00. Would be nice, if Emby could recognize that the movie had stopped at 48:32, and continue playing from this. 

Beside DSM, this feature is also implemented in YouTube. I think that's a great overvalue, since it avoids messing with notes about the stop time of a movie. Especially on longer videos.

**Comment by LukePulverenti** [comment]
Hi, yes this is possible and we do support it. It sounds like maybe the initial library scan has not completed and we don't know the runtime of the video. That is just my guess. In order for us to best help you, please supply the information requested in how to report a media playback issue:

https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/

Thanks !

**Comment by DMWOO7** [comment]
Hi, thanks for your quick reply! I made an upgrade to 3.2.25.0 now it works - including a movie I started before, where my test doesn't work. Seems like you were right, that the scan was incomplete. 

Awesome software and support, you deserve and get a premiere subscription from me for this 👍

**Comment by LukePulverenti** [comment]
Thanks for the feedback !
