### ISSUE TITLE
Crash due to 'Out of memory' error in ffprobe

### ISSUE THREAD

**Issue by DncrJim** [MediaBrowser/Emby#2755]
Version:  3.2.25.0
SBC:  RPi 3 B
DietPi:  V153

Any type of media scan (besides one at a time from within the Metadata Manager) crashes emby-server. I was able to get the 'tv shows' library of the scan to complete after 5 tries by scanning only that library. However, scanning an identical nas with movie results in an error, emby-server crashes and does not restart itself. (Note, I was getting the same behavior with 'tv shows' library, and after multiple tries it did make it to the end of that file structure) 

Emby can be manually restarted over ssh after the crash. It will also run indefinitely as long as I do not start the scan. After starting the folder scan, it will run for varying periods of time between 20 minutes and 3 hours (sometimes with very slow response times over ssh) and then will crash. The scan will usually add at least a few files, but after at least 10 cycles of either rebooting or restarting the service and then restarting the scan, I'm only about 1/3 done (~500 titles), 303 of which were successful on the first 'scan all libraries' attempt. While diligence tells me I can make it, logic tells me there's a better way. Two most recent log files attached. There seems to have been another error that happened several times as well.

[2017.07.13 08.38 log.txt](https://github.com/MediaBrowser/Emby/files/1146391/2017.07.13.08.38.log.txt)
[2017.03.13 13.46 log.txt](https://github.com/MediaBrowser/Emby/files/1146392/2017.03.13.13.46.log.txt)

**Comment by DncrJim** [comment]
I have done a clean install, DietPi: V154 & 3.2.26.0, and the problem persists. The system itself does appear to function and respond much faster than on previous releases, but the inability to scan even a small portion of the library is causing me great distress. (1st world problems)

Additional logs attached. I will cross post in the forum as well.

[2017.07.28 19.13 Emby Crash Log.txt](https://github.com/MediaBrowser/Emby/files/1184614/2017.07.28.19.13.27.Emby.Crash.Log.txt)
[2017.07.28 22.01 Emby Crash Log.txt](https://github.com/MediaBrowser/Emby/files/1184615/2017.07.28.22.01.29.Emby.Crash.Log.txt)

**Comment by LukePulverenti** [comment]
Closing as won't fix. Given that we are moving away from mono and onto .NET Core, we will not be pursuing a solution for this when running under the mono runtime. If you'd like to get involved with .NET Core testing, you're welcome to do so here:

https://emby.media/community/index.php?/topic/50012-emby-server-for-net-core/

We've yet to see anyone report anything like this when running under .NET Core. Thanks !
