### ISSUE TITLE
Xbox one DLNA fills devices list

### ISSUE THREAD

**Issue by Darkassassin07** [MediaBrowser/Emby#2769]
Every time my xbox one is restarted emby detects it as a new DLNA device and adds it to the device list.

**Comment by Darkassassin07** [comment]
Suppose i should add it doesn't remove the old entry of the same device so after a while i have a list of 30 xbox ones in my device list that i have to manually remove one by one

**Comment by LukePulverenti** [comment]
Resolved for next release. We just won't have xbox one in that list anymore. It is creating a new UUID on every startup which means we can't unique identify it. Thanks.
