### ISSUE TITLE
Active Devices too small for the information displayed 

### ISSUE THREAD

**Issue by Darkassassin07** [MediaBrowser/Emby#2772]
[img]https://www.dropbox.com/s/2f64xk7kubrad13/Screenshot_20170724-020252.png?dl=0[/img]

**Comment by Darkassassin07** [comment]
Forgot to add this happens on both android-Chrome android-emby theater but displays fine in windows 7-chrome

**Comment by LukePulverenti** [comment]
Resolved for next release, thanks.
