### ISSUE TITLE
HTTPS seems to not function at all.

### ISSUE THREAD

**Issue by Darkassassin07** [MediaBrowser/Emby#2773]
Attempts to connect to my emby server using the https port number displayed on the dashboard simply timeout failing to connect all together. Im using emby version 3.2.26.0 with the default self signed cert. Though this problem has persisted through the last three updates since i installed the server. 
I have tried to connect via localhost:8920 on the swrver machine, as well as the local ip from within the network and the public ip/my domain from abroad. 
Happy to post logs as requested.

**Comment by Darkassassin07** [comment]
Note: this is not the self signed cert issue people have  commonly run into. Im not even getting that far, the browser fails to find the server on port 8920

**Comment by LukePulverenti** [comment]
Have you attached an emby server log?

**Comment by Darkassassin07** [comment]
https://www.dropbox.com/s/qm4jagcarfyxs88/server-63636451199.txt?dl=0

Here is my latest server log right after a restart.

**Comment by LukePulverenti** [comment]
That is not a server restart, that's actually the automatic daily log restart. Try restarting the server and then attaching the new log. thanks.

**Comment by Darkassassin07** [comment]
https://www.dropbox.com/s/u71n5tveumbk5ko/server-63636503874.txt?dl=0

here's one after clicking shutdown, then re-launching the .exe, the last one was just clicking restart in the dashboard

**Comment by LukePulverenti** [comment]
I don't see any problems there. why again do you think https isn't working? We would have a massive uprising if that were the case. I'm not denying you're having an issue, but it sounds like it's going to be specific to your setup.

**Comment by Darkassassin07** [comment]
Any and all attempts to connect to the server using the https port (8920) timeout failing to find the server all together. This happens with localhost on the local machine as well as external ips (both in and out of network) the same connections with 8096 connect just fine.

**Comment by Darkassassin07** [comment]
The server machine is a windows 7 home premium os, could there be components of https missing possibly? 
Things that would normally be packaged with windows server?

**Comment by Darkassassin07** [comment]
Any help on fixing this? Id like to start using https for external connections... Im stuck using http publicly atm :/

**Comment by LukePulverenti** [comment]
Moving to community https://emby.media/community/index.php?/topic/49403-cant-find-server-on-https-port/?view=getnewpost&fromsearch=1
