### ISSUE TITLE
Ubuntu apt key is expired

### ISSUE THREAD

**Issue by rpatterson** [MediaBrowser/Emby#2774]
`W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org/repositories/home:/emby/xUbuntu_17.04  Release: The following signatures were invalid: EXPKEYSIG 0A506F712A7D8A28 home:emby OBS Project <home:emby@build.opensuse.org>
W: Failed to fetch http://download.opensuse.org/repositories/home:/emby/xUbuntu_17.04/Release.gpg: The following signatures were invalid: EXPKEYSIG 0A506F712A7D8A28 home:emby OBS Project <home:emby@build.opensuse.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
`

**Comment by rpatterson** [comment]
FYI, when I switch from `xUbuntu_Next` to `xUbuntu_17.04`, it seems to work.

**Comment by LukePulverenti** [comment]
OBS keys expire every two years so what you will need to do is go back to the download page of our website and do the first part of the installation process again, the part where you setup an OBS key. After that you will be able to update. Thanks.

**Comment by rpatterson** [comment]
The first thing I did was `apt-key del 0A506F712A7D8A28` and then reinstall the key per the instructions, same error.  The problem is with the `xUbuntu_Next` release.

**Comment by LukePulverenti** [comment]
See here
https://emby.media/community/index.php?/topic/13029-ubuntu/page-50#entry469837

**Comment by LukePulverenti** [comment]
Did this help?

**Comment by rpatterson** [comment]
@LukePulverenti https://github.com/MediaBrowser/Emby/issues/2774#issuecomment-317455373

**Comment by LukePulverenti** [comment]
Yes I see your comment however if you look at the thread that I linked to, everyone else seems to be able to update using the instructions given there.

**Comment by rpatterson** [comment]
The key for `xUbuntu_17.04` works.  I'm not surprised the key for `xUbuntu_16.10` also works, which is what is in the comment you linked to.  It's `xUbuntu_Next` whose key is expired.

**Comment by LukePulverenti** [comment]
Tested, not seeing any problems at this point. Please re-open if you're still blocked. Thanks.
