### ISSUE TITLE
Emby Server 2D/3D Blu-Ray titles + extras bug

### ISSUE THREAD

**Issue by schmittyd** [MediaBrowser/Emby#2777]
When importing Blu-Ray titles with 2D and 3D versions with extras, each item (movie.2d, movie.3d, extras) is scanned into the library as a separate title. In order to get titles to display correctly, the 3D video has to be moved into it's own directory as a separate title. The only way I can get them to display correctly is to create a collection, which I believe is incorrect, as it is one title, not a collection of different titles.

**Comment by LukePulverenti** [comment]
Tested, no problem found. Please refer to the wiki on 3d video naming as it goes over an example on how it is combined with multi-version support:

https://github.com/MediaBrowser/Wiki/wiki/3D%20videos

Thanks.

**Comment by schmittyd** [comment]
I have followed that guide. I even had that problem on the Windows server, before I migrated to Ubuntu. I'll have a look at it again, though.

**Comment by schmittyd** [comment]
This is a filename that I am currently using... Despicable Me (2010) [3D].H264-DTS.BluRay-1080p.3D-MVC.mkv

**Comment by LukePulverenti** [comment]
Please compare that to the example in the wiki. Thanks.
