### ISSUE TITLE
Ubuntu installation suggestions

### ISSUE THREAD

**Issue by schmittyd** [MediaBrowser/Emby#2778]
There needs to be a manual install from tar.gz files to enable installing to a different mount point (eg. /srv/emby-server). Also allow installing the beta alongside the stable release (eg. /srv/emby-server-beta)

**Comment by LukePulverenti** [comment]
Hi, rather than have this topic remain open indefinitely, please file a feature request topic in the Emby Community so that we can gauge community interest. Thanks.

**Comment by schmittyd** [comment]
Ok. Apologies
