### ISSUE TITLE
Runaway memory consumption of Emby Server for Windows process in 3.2.24+

### ISSUE THREAD

**Issue by jnheinz** [MediaBrowser/Emby#2786]
Since about a month ago after upgrading to Emby Server for Windows - 3.2.24, I have been experiencing memory consumption that renders Emby Server & the OS extremely sluggish (3+GB Emby Server process).  I have a Windows Server 2012 R2 VM (6vCPU, 4GB RAM) with just Emby Server running that is roughly about 16 months old.  It has been upgraded roughly 10 times (3.2.X).  All media is stored on an UnRAID Server installation & accessed via SMB.  Collection size is large, but definitely not anything abnormally large that it can't be handled by Emby Server.

Prior to this upgrade, Emby Server was able to run for months without a service or OS restart.  I believe the last version I was on that did not contain this problem was 3.2.22 or 3.2.20 (?).  Clients include several Emby for Kodi clients & a few Emby for Android clients.  Plug-ins initially included: Emby/Kodi Sync Queue, Podcasts, trakt.tv, Statistics, PushBullet notifications, Rotten Tomato Reviews, AutoBoxSet, & Server Configuration Backup.  Per Luke, I removed Emby/Kodi Sync Queue, trakt.tv, Statistics & AutoBoxSet.  Memory consumption still continues to creep upwards until the Emby Server becomes sluggish & eventually unresponsive.  The problem continues in 3.2.26.

I have provided some initial debugging logs on the Emby forums, but I have not filed a formal bug report yet.  Several other users report similar issues with Emby Server processes peaking at 10+GB.  Some of them include minimalistic (no plug-in) installations with no Emby for Kodi clients.  The only workaround is to schedule a daily restart of the Emby Server service.

Let me know if you need any more information from me.  I am committed to assisting the Emby Development team as necessary.

**Comment by SvenVandenbrande** [comment]
Can you run a tool like https://www.jetbrains.com/dotmemory/ when the problem occurs?

**Comment by jnheinz** [comment]
Will do.  I have asked others to help as well, in case mine is slow to appear now that I have disabled the nightly service restart.  What information do you need from this program once we run it?  Specifics would be helpful.

Link to the thread on Emby Forums - https://emby.media/community/index.php?/topic/49196-emby-server-memory-usage

**Comment by LukePulverenti** [comment]
Please try the latest release of Emby Server and let me know how that compares. Thanks !

**Comment by jnheinz** [comment]
I have been running it (3.2.28) with no automatic server/service
restarts for a few days now.  I will send out an update at the end of
the week if I can remember.

On Tue, Aug 22, 2017, at 02:41 PM, Luke wrote:
> Please try the latest release of Emby Server and let me know how that
> compares. Thanks !> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/MediaBrowser/Emby/issues/2786#issuecomment-324130723

**Comment by LukePulverenti** [comment]
Please try Emby Server 3.2.32. Thanks.

**Comment by LukePulverenti** [comment]
Please install the latest release from the website. Multiple users have confirmed improvements. Please re-open with new debugging information if you are still having an issue. Thanks !
