### ISSUE TITLE
Playback issues with Emby Server 3.2.30.0 Ubuntu 16.04 and Emby Theatre latest version Xbox One

### ISSUE THREAD

**Issue by schmittyd** [MediaBrowser/Emby#2788]
There are Playback issues with Emby Server 3.2.26.0 Ubuntu 17.04 and Emby Theatre latest version Xbox One. I don't believe the issue is the server, just the XBO app. Files seem to play fine for a while, then pause... however, logging in to the server dashboard shows they are still playing. Logs are attached.

Also, I think the transcoding/remuxing profiles are incorrect for the Xbox One, as the server seems to remux mkv's, which I know for a fact Xbox One does support natively... without chapters.

[ffmpeg-remux-53436956-73f2-4487-98b2-d4b98d9502b3.txt](https://github.com/MediaBrowser/Emby/files/1188397/ffmpeg-remux-53436956-73f2-4487-98b2-d4b98d9502b3.txt)
[ffmpeg-transcode-1c586568-f246-4bba-ad32-af4a1ec65900.txt](https://github.com/MediaBrowser/Emby/files/1188396/ffmpeg-transcode-1c586568-f246-4bba-ad32-af4a1ec65900.txt)
[server-63637147894.txt](https://github.com/MediaBrowser/Emby/files/1188399/server-63637147894.txt)
[server-63637150314.txt](https://github.com/MediaBrowser/Emby/files/1188398/server-63637150314.txt)

**Comment by SvenVandenbrande** [comment]
@schmittyd Did you already try with the newer version?
Do you still have the problem?
If the answer is yes. Can you post the new logs?

**Comment by schmittyd** [comment]
I am still having issue with playback. I have discovered that the server is transcoding everything, and not direct playing... like it used to. The CPU/RAM aren't coping with the transcodes. I have tried customising the direct play and transcoding profiles but it still isn't working correctly. Attached, are logs.
[ffmpeg-transcode-354632cf-bd00-4971-ba47-de50d6470453.txt](https://github.com/MediaBrowser/Emby/files/1260776/ffmpeg-transcode-354632cf-bd00-4971-ba47-de50d6470453.txt)
[server-63639650649.txt](https://github.com/MediaBrowser/Emby/files/1260780/server-63639650649.txt)

**Comment by LukePulverenti** [comment]
We have been waiting on a fix from Microsoft and we've finally gotten it. The next update to the Xbox One app will have major playback improvements, if you have new Fall Creators update installed to your Xbox. Without that it will continue to be the same as it's been for the past few months. Thanks.
