### ISSUE TITLE
Run systemd service as another user

### ISSUE THREAD

**Issue by koalaeagle** [MediaBrowser/Emby#2793]
I am attempting to run Emby on Linux (Arch specifically) as another user. With the default systemd configuration file Emby loads fine. When changing the User= and Group= to another user it appears to crash every time. I made sure to chown -R /var/lib/emby for ensure permissions are set to the user I intend to run the service as. My reason for this is I have created a media user that I run my various services as (sonarr/radarr/plex/etc) to avoid permission issues while still having a service account for these services. Is there something else I have to change? After some googling I found a forum thread suggesting to change the user in /etc/emby-server.conf - however this file does not appear to be in my package. I do have /etc/conf.d/emby-server. I tried adding:
EMBY_USER="media"
EMBY_GROUP="media"
As I found reference to certain environment variables here:
https://emby.media/community/index.php?/topic/45357-centos-7-emby-not-running/
However, this didn't seem to work either. Please advise if there is anyway to change the user as I would rather not change my entire setup just to cater for one application.

**Comment by alucryd** [comment]
Changing the user:group in the systemd file and chowning /var/lib/emby should just work.

Can you try:
`source /etc/conf.d/emby-server
sudo -u media emby-server`

In my case I didn't create another user but added emby to my media group, my libraries folders are 770 and setgid and I have no issues.

**Comment by LukePulverenti** [comment]
@koalaeagle please let us know if this answers your question. Thanks !

**Comment by koalaeagle** [comment]
Not really, the problem still remains. The workaround presented is quite obvious and is what will have to be done since flexibility is not allowed here. Closing since I doubt this will actually be looked at.

**Comment by alucryd** [comment]
Well, apparently not that obvious to you, that "obvious workaround" was for us to get actual log from the command line and help identify the issue. But it seems you need to fix your attitude before you're able to fix this.

**Comment by LukePulverenti** [comment]
If we're here trying to help you then why do you doubt that we'd actually look into the changes you need? Of course we want to help you.

**Comment by koalaeagle** [comment]
I guess after waiting so long for a response and seeing a permissions workaround to still use the emby user I was more focused on that part of the response so I apologize for my attitude. In any case I attempted to replicate this issue again and provide the logs, however, I can no longer replicate it. I do not believe there was any kind of error in my original execution since I tried it on two machines and executed identical commands (to what I am using now) and verified everything along the way (I also tried about 4 times). Today it is working fine - the service does not fail like it was and I can access emby on port 8096 as expected. For reference here is the procedure (Arch):
```
(Note: executed as root, add sudo to commands if needed)
pacman -S emby-server
sed -e 's/emby/media/g' -i /usr/lib/systemd/system/emby-server.service (or edit manually)
chown -R media:media /var/lib/emby
systemctl daemon-reload
systemctl start emby-server

Note: Long term it is better to create a drop-in file instead of editing the service file to ensure it is persistent such as /etc/systemd/system/emby-server.d/emby.conf with
[Service]
User=media
Group=media

```

**Comment by alucryd** [comment]
No wonder your service was failing to start, your sed command would also modify those 3 lines:

EnvironmentFile=/etc/conf.d/emby-server
WorkingDirectory=/usr/lib/emby-server
ExecStart=/usr/bin/emby-server

**Comment by koalaeagle** [comment]
That wouldn't be why, considering I never used sed. I either used ansible to create a drop-in systemd file which handled it identically to my sonarr/radarr/nzbget playbooks or I used vi to edit the file manually.

Good catch though - updated the command.
