### ISSUE TITLE
Playing LiveTV High-Definition channels is glitchy since 3.2.20.0 update

### ISSUE THREAD

**Issue by elboletaire** [MediaBrowser/Emby#2798]
Before updating to 3.2.20.0 I was able to play LiveTV HD channels without any issue (well, some glitches from time to time, but that's the normal behavior for me using LiveTV in emby).

As said in https://github.com/MediaBrowser/Emby/issues/2650#issuecomment-313882999 with the 3.2.20.0 update I wasn't able to play any kind of rpc stream, but after the very next update standard-quality streams worked as usually, but HD channels started showing glitches (so many glitches that is not watchable).

#### HD Screenshots (different channels):

![imatge](https://user-images.githubusercontent.com/153305/29070189-73174fdc-7c3e-11e7-9186-12ad4d6fba11.png)
![imatge](https://user-images.githubusercontent.com/153305/29070151-4606b668-7c3e-11e7-82d2-b8042707111f.png)
![imatge](https://user-images.githubusercontent.com/153305/29070373-5bdbf51a-7c3f-11e7-8044-6e45629e0993.png)

#### SD Screenshots (same channels than previous screenshots, but with standard-definition streams):

![imatge](https://user-images.githubusercontent.com/153305/29070457-c9caa31e-7c3f-11e7-89bd-53519f6fc9a0.png)
![imatge](https://user-images.githubusercontent.com/153305/29070443-aa2f62d8-7c3f-11e7-89c0-7a3068f321a1.png)
![imatge](https://user-images.githubusercontent.com/153305/29070397-6f088748-7c3f-11e7-8cca-9b9586836f85.png)

#### Installation details:

- **Emby server version:** docker installation (on a debian host), version 3.2.26.0.
- **Kind of LiveTV stream:** rpc channels like `rtp://@239.0.0.76:8208`
- **Emby premiere:** lifetime
- **LiveTV config:**
![imatge](https://user-images.githubusercontent.com/153305/29070925-859b5c7c-7c41-11e7-9fe3-105b2b3ddd57.png)

#### Logs

[emby logs.zip](https://github.com/MediaBrowser/Emby/files/1207907/emby.logs.zip)

**Comment by LukePulverenti** [comment]
Do you have logs from the older release for comparison purposes? thanks.

**Comment by elboletaire** [comment]
I'm sorry but no; apparently I don't have any log before August 6th 😕

**Comment by elboletaire** [comment]
Shouldn't be fixed under 3.2.27.0 ?? I'm still having issues 😕
