### ISSUE TITLE
HTTP Live Streaming broken since 3.2.14.0 (May 6)

### ISSUE THREAD

**Issue by l3obaFett** [MediaBrowser/Emby#2799]
Hi folks,

Transcoding video over DLNA to my Sony Bravia has worked great up until 3.2.14.0 (May 6).
I changed the Sony Bravia 2014 stock profile to use HLS as without it, I couldn't pause/resume or seek through a video, it would just stop playback. Now whenever transcoding is needed, I get no playback and an error is logged. The log is from when I hit play on my Emby client.
[server-63637574412.txt](https://github.com/MediaBrowser/Emby/files/1209620/server-63637574412.txt)

I think I've narrowed it down to [this change](https://github.com/MediaBrowser/Emby/commit/0c7828cdd4a9d0829642ed20087c5e80635bd185)
but I'm no programmer so I'm possibly barking up the wrong tree.

Thanks for an awesome media server by the way! :)

**Comment by SvenVandenbrande** [comment]
The link to the commit doesn't work....

**Comment by l3obaFett** [comment]
Hmm clicking it gives me a 404 yet copy and paste it into the address bar and it works.
