### ISSUE TITLE
Player don't work on mobile browser

### ISSUE THREAD

**Issue by mikafouenski** [MediaBrowser/Emby#2810]
Hello,

Playing video doesn't work on any android mobile browser.
Tested players : chrome, Firefox, via, jelly.
Android version: lineageOs 14.1, android 7.1.2

Step to reproduce : just click on the play button.

[Video](https://drive.google.com/file/d/0B0zG1iGJ07pCdXYtWkxIS2ROd00/view?usp=drivesdk)

**Comment by LukePulverenti** [comment]
I can't reproduce this although I don't have lineageOS to test with. Can you please attach the information requested in how to report a media playback issue: https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/

Thanks.
