### ISSUE TITLE
Support pinch zooming for photos

### ISSUE THREAD

**Issue by LukePulverenti** [MediaBrowser/Emby#2826]

**Comment by krysstof** [comment]
Thanks for opening this request for feature.
just a warning though, this will need a careful implementation to avoid wanting to throw the phone/tablet on the ground and stomping on it : the zoom implies a need for panning the photo/pic
and the same movement is needed to slide to next/previous photo

if you want 2 examples on a cool pinch zooming vs a bad one : 
Tonido uses a real bad implementation (where zoomed pictures slide when zoomed
cover (windows) or comic rack (android) have a really sexy implementation

it's probably simply by deactivating sliding to next picture when panning is active (probably a ratio between zoom factor and sliding force, never really payed that much attention as it looks so natural, but when it's not working correctly you start to notice these little things ;) )
and also not displaying each picture side by side as they slide, but giving a nice break between each picture as a page of a book, not a picture slideshow.


but yeah, ping for zooming would be great !

**Comment by LukePulverenti** [comment]
Added for next app releases, thanks.
