### ISSUE TITLE
Prefer external subtitles

### ISSUE THREAD

**Issue by jacaru** [MediaBrowser/Emby#2828]
I think it would be reasonable to say that if the system has the following option disabled

> Skip if the video already contains embedded subtitles
Keeping text versions of subtitles will result in more efficient delivery and decrease the likelihood of video transcoding.

then there is a preference for external subtitles. So maybe we could have something like this:

```
private static IEnumerable<MediaStream> GetSortedStreams(IEnumerable<MediaStream> streams, MediaStreamType type, List<string> languagePreferences)
        {
            // Give some preferance to external text subs for better performance
            return streams.Where(i => i.Type == type)
                .OrderBy(i =>
            {
                var index = languagePreferences.FindIndex(l => string.Equals(i.Language, l, StringComparison.OrdinalIgnoreCase));

                return index == -1 ? 100 : index;
            })
                 .ThenBy(i => GetBooleanOrderBy(i.IsExternal && ! _config.GetConfiguration<SubtitleOptions>("subtitles").SkipIfEmbeddedSubtitlesPresent))
                 .ThenBy(i => GetBooleanOrderBy(i.IsDefault))
                 .ThenBy(i => GetBooleanOrderBy(i.SupportsExternalStream))
                 .ThenBy(i => GetBooleanOrderBy(i.IsTextSubtitleStream))
                 .ThenBy(i => GetBooleanOrderBy(i.IsExternal))
                 .ThenBy(i => i.Index);
        }
```

I am trying to avoid the extraction of subtitles by always providing an external one when I can, but then if any embedded is set as default, it defeats the purpose.

Maybe we can have a separate specific option, could be by user to setup different users on different devices so this takes effect per device, or maybe on device profiles.

**Comment by LukePulverenti** [comment]
We can't do that. There would have to be some other, more explicit setting. For most that would just become a guessing game.

**Comment by LukePulverenti** [comment]
We're going to start marking the external subtitles as default. This by itself will end up giving them higher priority than embedded subtitles that are marked by default. Thanks.
