### ISSUE TITLE
Emby Doesnt follow symlinks

### ISSUE THREAD

**Issue by IvanTurgenev** [MediaBrowser/Emby#2829]
I have a symlink folder /library/SYMLINK/video.mp4
l
It doesnt pick it up 
[server-63638649505.txt](https://github.com/MediaBrowser/Emby/files/1234950/server-63638649505.txt)
fedora 26

**Comment by LukePulverenti** [comment]
We do follow symlinks, but it happens natively within the .net framework, or in this case, within the mono runtime. I think there are some cases where mono doesn't follow them, although for most they do seem to work. We are in process of switching from .net core to mono so for this type of thing we will probably just wait and re-evaluate later once we've switched.

**Comment by IvanTurgenev** [comment]
had to mount --bind meanwhile

**Comment by LukePulverenti** [comment]
Are you all set now?

**Comment by IvanTurgenev** [comment]
with the workaround yes, did it get fix ? which version?

**Comment by LukePulverenti** [comment]
Fix? See my comments above that is the status. Thanks.

**Comment by IvanTurgenev** [comment]
so no hmmm

**Comment by LukePulverenti** [comment]
You might be interested in participating in Emby Server for .NET core testing:
https://emby.media/community/index.php?/topic/50012-emby-server-for-net-core/

Please note it's just for testing and experimentation right now. Thanks !

**Comment by ydkmlt84** [comment]
@Ian could you please let me know about the specifics of your symlink? Where is the actual file located? How was this symlink added to Emby? Is it a file within a library you already had added to Emby or is it a separate library only containing the symlinked file? I'm trying to re create your issue.

**Comment by ydkmlt84** [comment]
Sorry @ivanturgenev

**Comment by IvanTurgenev** [comment]
It is a folder within a library

**Comment by LukePulverenti** [comment]
Can you provide more detail? How do we exactly test the same scenario? thanks.

**Comment by IvanTurgenev** [comment]
create the library /media/TV, add to emby as undefine content library then /home/user/Videos/SeriesX/episode*.mkv.

Then ln -s /home/user/Videos/SeriesX /media/TV

**Comment by ydkmlt84** [comment]
I am not going to lie, that is a very confusing scenario. 
In my experience you can not create a symlink to a folder that already exist... So you are creating a folder named /media/TV, with nothing inside of it. Adding that to Emby as undefined content. Then going back and creating a symlink from the Videos/SeriesX folder to /media/TV? That is the part that is confusing me because you shouldn't be able to symlink to /media/TV as it already exists.
 Also in my testing just now, that will not work. If you use CLI and try to access that new /media/TV then you will see that the symlink is now inside of that folder, instead of that folder itself being the symlink. (too many levels to the symlink)
  The best way to do this is to not have a folder named /media/TV already. ln-s /Videos/SeriesX /media/TV... then add /media/TV to Emby as content type TV. Shouldn't have any issuess.

**Comment by IvanTurgenev** [comment]
ok will try

**Comment by IvanTurgenev** [comment]
nope still doesnt work are you on a linux box?

**Comment by ydkmlt84** [comment]
yes

**Comment by IvanTurgenev** [comment]
probably will try to replicate on a vm to see

**Comment by ydkmlt84** [comment]
first make sure you do not have a /media/TV folder... then do this 
`sudo ln -s /home/user/Videos/SeriesX /media/TV` 
Do you get any errors?

**Comment by IvanTurgenev** [comment]
Nope did exactly as you did, when creating the library it doesnt even see the symlinked folder, cant select it, what distro are you using?

TV doesnt exist 

 /home/user/Videos/SeriesX/*.mkv

ln -s /home/user/Videos/SeriesX /media/TV

**Comment by IvanTurgenev** [comment]
also something weird is happening when i turn off my monitor emby stops working

**Comment by ydkmlt84** [comment]
What is the glob (*) for? Are you just showing me there are episodes in that folder? Can you cd to the symlink from terminal? Does ls /media/TV show the contents of /home/user/Videos/SeriesX? I am using Ubuntu. 
 As far as Emby stopping when you turn off your monitor that is weird. Could be the suspending. Can you ping the ip from another computer.

**Comment by IvanTurgenev** [comment]
Yes * there are episodes.

Yes i can enter the symlink, from the terminal, Yes ot shows the contents in both terminal and filebrowser.

Will try pinging or sshing while monitor is off

**Comment by LukePulverenti** [comment]
Is there still an issue here with symlinks?

**Comment by IvanTurgenev** [comment]
I think so i surrender, i suppose we wait until you migrate to the other backend

**Comment by LukePulverenti** [comment]
Our .net core installers are available on the website now. Please try that and re-open if you are still having an issue, thanks.
