### ISSUE TITLE
System.MissingMethodException error in 3.2.28.2 on Windows 10

### ISSUE THREAD

**Issue by thatchrisblack** [MediaBrowser/Emby#2837]
Installed v3.2.28.2 on a freshly installed Windows 10 (1703) device. The error happens every time Emby starts and, while it will run fine while the error message is on screen, it will immediately crash when I dismiss the pop up. Also received some uninstaller errors in the log when I uninstalled to give stable a try (it installed and runs without the error I was getting in the beta). 

Screenshot of error and logs are attached. 

[server-63638867969.txt](https://github.com/MediaBrowser/Emby/files/1238986/server-63638867969.txt)
[server-63638868246.txt](https://github.com/MediaBrowser/Emby/files/1238988/server-63638868246.txt)
[unhandled_ea4239ba-7bc8-4a4b-9b8a-56d915370de1.txt](https://github.com/MediaBrowser/Emby/files/1238987/unhandled_ea4239ba-7bc8-4a4b-9b8a-56d915370de1.txt)
![emby error](https://user-images.githubusercontent.com/4691735/29522092-a68d1c34-864d-11e7-8e52-3bf9cc1db4e3.PNG)

**Comment by LukePulverenti** [comment]
Hi, it looks like this is coming from a messenger plugin. Try going here:
C:\Users\yesth.DESKTOP-BC49PUQ\AppData\Roaming\Emby-Server\plugins
Then delete the plugin .dll file. I will let the developer know the plugin needs an update for the beta server. Thanks.
