### ISSUE TITLE
Library Scanning Halts

### ISSUE THREAD

**Issue by ginjaninja1** [MediaBrowser/Emby#284]
I have reproduced this when scanning tv  librarys from scratch, fresh install, no metadata.

this one was for movies.
https://dl.dropboxusercontent.com/u/84611964/Server-635043936879520470.rar

the log windows just stops, no timeout errors, nothing.
sysinternals just shows mediabrowser doing thread create/close indefinitely

![image](https://f.cloud.github.com/assets/4178240/518023/72b5228e-bef2-11e2-881f-470c8d1a5906.png)

solution is to stop and start scan library task.
only the scan task itself has paused, if new content is added or ammend, these changes are reflected in additional library activity.

**Comment by micahscopes** [comment]
I'm having this issue with the latest version from git, as well as 3.1.1-1.  Running Arch Linux.  

In journalctl I always get something like this: 
```
Native stacktrace:
 emby-server[12604]:         /usr/bin/mono() [0x4b18ff]
 emby-server[12604]:         /usr/bin/mono() [0x50769e]
 emby-server[12604]:         /usr/bin/mono() [0x4297b3]
 emby-server[12604]:         /usr/lib/libpthread.so.0(+0x11080) [0x7f6d9524b080]
 emby-server[12604]: Debug info from gdb:
```
It always occurs after an apparently successful ffprobe log entry, not necessarily for the same file.

If I restart emby and attempt to rescan, it freezes at 0%.  If I delete my library.db and rescan, it freezes in the exact same spot that it froze in the first time (82.1%).  This seems like a recurring issue from what I can tell.

I'm having a hard time finding any other info.  Are there other logs somewhere?
