### ISSUE TITLE
Wireless headphone On/Off

### ISSUE THREAD

**Issue by hugolapointe** [MediaBrowser/Emby#2842]
Hi!

Each time I turn off my wireless headphone or a plug out a wire headphone, the playback stop and I can't resume it. I have to exit the playback and resume it from the application.

Thank you.

**Comment by LukePulverenti** [comment]
Hi, can you please provide a little more detail? What device and what app? Is it an Emby app that you're playing from?

**Comment by hugolapointe** [comment]
I'm playing on Emby Web on Chrome and I try with several different headphone and I got the same result.

**Comment by SvenVandenbrande** [comment]
And you get any errors? I also have a wireless via Bluetooth (Bose Q35. I don't have any problems when I start or stop it. 

It goes directly from my Q35 to regular box (PC) and also in the other direction.

Do you see someting in the Emby log? Can you post them in this issue?

**Comment by LukePulverenti** [comment]
I'm not able to reproduce this, however there are recent changes that may affect this. Please re-evaluate after the next stable release. If the issue persists, please re-open with the information requested by @sven. Thanks.

**Comment by hugolapointe** [comment]
You were right, the new update has fix the issue.
