### ISSUE TITLE
Integrate support for odroid-xu4 hw transcoding

### ISSUE THREAD

**Issue by crazyquark** [MediaBrowser/Emby#2849]
I tracked down memeka's code changes to here:
[https://emby.media/community/index.php?/topic/46056-adding-a-new-encoder-interface-issues/](https://emby.media/community/index.php?/topic/46056-adding-a-new-encoder-interface-issues/)

Can this be integrated in the mainline emby-server?

**Comment by LukePulverenti** [comment]
Closing, see #2865

**Comment by LukePulverenti** [comment]
https://emby.media/community/index.php?/topic/50765-323015-beta-odroid-xu4-hardware-encoder-support/
