### ISSUE TITLE
Spawning multiple instances of ffmpeg and not closing them

### ISSUE THREAD

**Issue by shihrer** [MediaBrowser/Emby#2852]
Multiple instances of ffmpeg are spawned when switching quality on the web client.  It ends up being one for each time the quality is changed.  When the stream is ended, only one of the processes are ended.

I'm running Version 3.2.29.1 beta

Log: https://pastebin.com/GsUvGZ90

**Comment by LukePulverenti** [comment]
Hi, this log looks OK. Can you please try with the latest release of Emby Server, and then if the issue persists, please attach the complete server log? thanks !

**Comment by shihrer** [comment]
No difference.

https://paste.ee/p/TzV0E

![During Stream](https://imgur.com/Hr0xrmJ.png)

![After stream](https://imgur.com/lNzbKO5.png)

**Comment by LukePulverenti** [comment]
Ok well you're running a beta version there which has brand new changes. Can you compare to stable? thanks.

**Comment by shihrer** [comment]
@LukePulverenti It's not the end of the world for me since this was essentially a test setup to begin with, but in general it seems to be a bit weird to ask people willing to use beta builds to not use beta builds when reporting bugs.  Unless something has changed recently, it's not exactly an easy process.

Also #2860 is probably related.

Stable is the same issue.

[ffmpeg-remux-d71dafcb-f5d4-4494-921d-10b34fed81f3.txt](https://github.com/MediaBrowser/Emby/files/1275458/ffmpeg-remux-d71dafcb-f5d4-4494-921d-10b34fed81f3.txt)
[ffmpeg-transcode-0d50de71-1efe-4a2a-a1b8-8453a6a83468.txt](https://github.com/MediaBrowser/Emby/files/1275459/ffmpeg-transcode-0d50de71-1efe-4a2a-a1b8-8453a6a83468.txt)
[ffmpeg-transcode-3bef955b-1846-4cea-bfcb-966399aff9bb.txt](https://github.com/MediaBrowser/Emby/files/1275462/ffmpeg-transcode-3bef955b-1846-4cea-bfcb-966399aff9bb.txt)
[server-63640131475.txt](https://github.com/MediaBrowser/Emby/files/1275461/server-63640131475.txt)
[ffmpeg-remux-93b069ec-23c1-4860-b352-c3addce7d2b9.txt](https://github.com/MediaBrowser/Emby/files/1275460/ffmpeg-remux-93b069ec-23c1-4860-b352-c3addce7d2b9.txt)
[ffmpeg-remux-b0ee5a83-3ad4-43e2-bda2-a5ed11afd363.txt](https://github.com/MediaBrowser/Emby/files/1275463/ffmpeg-remux-b0ee5a83-3ad4-43e2-bda2-a5ed11afd363.txt)

Looking at the logs, it doesn't look like Emby even tries to exist the ffmpeg processes until playback is stopped.

**Comment by shihrer** [comment]
Furthermore, it doesn't seem to happen when using the Android TV client.  I've only been able to reproduce with the web client.

**Comment by IvanTurgenev** [comment]
I seem to have a similar problem suddenly emby started transcoding all my videos regardless it worked fine until recently, no everything transcode which it should be doing it worked perfectly before

**Comment by NickBolles** [comment]
I have been noticing this too, no hard evidence but thought I'd just chime in that I've seen issues where switching quality or audio or something or just starting a stream and going to another will stack up ffmpeg in task manager. Then transcoding performance will suffer and stagger. (Especially when my CPU is showing its age and capacity limits)

**Comment by LukePulverenti** [comment]
This is resolved for the next release. Thanks for the report.

**Comment by shihrer** [comment]
Thanks @LukePulverenti !
