### ISSUE TITLE
Episodes over 100 get incorrectly detected by Emby.

### ISSUE THREAD

**Issue by Luticus** [MediaBrowser/Emby#2856]
This tends to happen with Anime where the episode numbers go higher than 100 more often.  Episode 100 is detected as 0, 101 as 1, 102 as 2 and so on creating what appears to be duplicate episodes.  This make the show unwatchable in Emby.  Would be very nice if someone could take a look at why that might be happening.

**Comment by LukePulverenti** [comment]
what are your file names?

**Comment by Luticus** [comment]
In one case it runs like "title - 100 - episode title.ogm" in other cases it's "title - 100.mkv"

I've even tried separating them into different folders and renaming them like "title - S1 - 100"

Regardless in all cases episode 100 would be detected as episode 0.  

For instance, this episode:  "Inuyasha - 101-The Snow from Seven Years Past.mkv" would be detected as episode 1 along side the actual episode 1, even if I rename episode 1 to use 001.  This makes playing episodes from series that have episodes above 100 rather difficult.

**Comment by LukePulverenti** [comment]
This is expected behavior because many people use 101 as season 1 episode 1. Try using one of our other naming conventions  listed here:

https://github.com/MediaBrowser/Wiki/wiki/TV%20naming

For example, s01e01.

**Comment by Luticus** [comment]
I see, ill give this a try.


Thanks,

Joe McEntire
getjoe@live.com
On Sep 2, 2017, at 7:04 PM, Luke <notifications@github.com<mailto:notifications@github.com>> wrote:

This is expected behavior because many people use 101 as season 1 episode 1. Try using one of our other naming conventions listed here:

https://github.com/MediaBrowser/Wiki/wiki/TV%20naming

For example, s01e01.
