### ISSUE TITLE
Not closing ffmpeg on switching audio tracks

### ISSUE THREAD

**Issue by Earl0fPudding** [MediaBrowser/Emby#2860]
Hi,

when I watch a movie or tv series and I switch the audio track to change lanugages, my load average and cpu usage get very high.
The reason is that emby starts a new instance of ffmpeg on switching tracks, but it doesn't close the old instance. So my server has to decode the same movie twice in parallel. 

It was also the case that the movie laggs after switching tracks. My temporary fix was to kill the old ffmpeg instance via terminal and then it didn't lag anymore.

So can you please close the old ffmpeg instance in the code before creating a new one?
My emby version is  3.2.30.0.

Thank you in advance!

**Comment by Earl0fPudding** [comment]
I got tired of killing the processes myself every time. Due to this I wrote a tiny bash script that checks every 5 seconds if more then one process of ffmpeg is running and then kill the older process.

```bash
#!/usr/bin/bash

# replace with your ffmpeg executable path
ffmpeg_path="/usr/bin/ffmpeg"
while [ true ]; do
        amount=$(( $(ps aux | grep $ffmpeg_path | wc -l) - 1))
        if [ $amount -gt 1 ]; then
                pkill --oldest ffmpeg
        fi
        sleep 5
done
```

Run this script on your server in background.
I hope I could help someone with my script and also that there will be a permanent fix for that.

**Comment by LukePulverenti** [comment]
We already do close the process, so there must be something else going on here. Please attach the information requested here:
https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/

Thanks !

**Comment by LukePulverenti** [comment]
Unfortunately these logs are unreadable for me. One of the ffmpeg logs is 0 byte, the other contains just a copy of the regular emby server log.

**Comment by Earl0fPudding** [comment]
I am so sorry there was a problem by compressing the log files.
I did the whole situation again.
Now the file that was created first was ffmpeg-remux-5c0dfbe9-3dfb-4bb8-bbab-1203f0e561a5.txt and the second was ffmpeg-directstream-902834f3-62bb-4308-b706-bbcdcfe426f8.txt.

I hope you can help me now.
[logs.zip](https://github.com/MediaBrowser/Emby/files/1275370/logs.zip)

**Comment by LukePulverenti** [comment]
This is resolved for the next release. Thanks for the report.
