### ISSUE TITLE
Installer is broken on Server 2016

### ISSUE THREAD

**Issue by muhfugen** [MediaBrowser/Emby#2863]
The installer refuses to run on Windows Server 2016. From the logs it looks like your installer erroneously assumes that internet explorer, a web browser which has been depreciated years ago, is present on the system instead of using .NET HTTP APIs which are readily available.

Also the installer log is improperly written. You guys appear to just dump UTF-16 in to a plaintext file without including a Unicode byte order mark. As a result if I try to copy/paste the log in to this issue, every other character is a null byte. I had to manually edit the file in a hex editor to include a byte order mark so I could even include it here.

**install.log**
The following properties have been set:
Property: [AdminUser] = true {boolean}
Property: [InstallMode] = HomeSite {string}
Property: [NTProductType] = 3 {int}
Property: [ProcessorArchitecture] = AMD64 {string}
Property: [VersionNT] = 10.0.0 {version}
Running checks for package 'Microsoft .NET Framework 4.6.1 (x86 and x64)', phase BuildList
Reading value 'Release' of registry key 'HKLM\Software\Microsoft\NET Framework Setup\NDP\v4\Full'
Read integer value 460805
Setting value '460805 {int}' for property 'DotNet461Full_Release'
Reading value 'v4' of registry key 'HKLM\SOFTWARE\Microsoft\NET Framework Setup\OS Integration'
Read integer value 1
Setting value '1 {int}' for property 'DotNet461Full_OSIntegrated'
The following properties have been set for package 'Microsoft .NET Framework 4.6.1 (x86 and x64)':
Property: [DotNet461Full_OSIntegrated] = 1 {int}
Property: [DotNet461Full_Release] = 460805 {int}
Running checks for command 'DotNetFX461\NDP461-KB3102436-x86-x64-AllOS-ENU.exe'
Result of running operator 'ValueEqualTo' on property 'InstallMode' and value 'HomeSite': true
Result of checks for command 'DotNetFX461\NDP461-KB3102436-x86-x64-AllOS-ENU.exe' is 'Bypass'
Running checks for command 'DotNetFX461\NDP461-KB3102438-Web.exe'
Result of running operator 'ValueNotEqualTo' on property 'InstallMode' and value 'HomeSite': false
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet461Full_Release' and value '394254': true
Result of checks for command 'DotNetFX461\NDP461-KB3102438-Web.exe' is 'Bypass'
'Microsoft .NET Framework 4.6.1 (x86 and x64)' RunCheck result: No Install Needed
Launching Application.
Application appears to be an application manifest
Launching application manifest via dfshim
LaunchApplication failed with HRESULT '-2147024891'
Running command 'iexplore.exe' with arguments ' "http://embydata.com/downloads/server/release3/MediaBrowser.Server.Installer.application"'
ShellExecuteEx failed with error code 2
Running command 'http://embydata.com/downloads/server/release3/MediaBrowser.Server.Installer.application' with arguments ''
ShellExecuteEx failed with error code -2147221003
Error: The following error occurred attempting to install 'http://embydata.com/downloads/server/release3/MediaBrowser.Server.Installer.application':
"Application not found "

**Comment by LukePulverenti** [comment]
Well we're not assuming anything like that but there might be parts of the ClickOnce installer that are. I would just use the portable download which is also on our windows download page.
