### ISSUE TITLE
Odroid XU4 Hardware encoder support

### ISSUE THREAD

**Issue by studioai** [MediaBrowser/Emby#2865]
#2762 related

memeka offered links of his code

https://paste.debian.net/983453/
https://paste.debian.net/983452/

Every users of XU4 really waiting for hardware transcoding!!

It would be so nice to have it!

**Comment by LukePulverenti** [comment]
https://emby.media/community/index.php?/topic/50765-323015-beta-odroid-xu4-hardware-encoder-support/

**Comment by coltc50** [comment]
Did somebody get this to work?

When I choose Exynos V4L2 encoder should I read nv21 in the log?

Heres my log:

`/usr/bin/ffmpeg -analyzeduration 3000000 -i "http://192.168.177.98:9981/stream/channelid/515982476?ticket=6EDDBC87E3E9F85B77BD4EA06D02E966E7E3848F" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -pix_fmt yuv420p -preset ultrafast -crf 25 -maxrate 4116000 -bufsize 8232000 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames "expr:gte(t,n_forced*3)" -vf "scale=trunc(min(max(iw\,ih*dar)\,1920)/2)*2:trunc(ow/dar/2)*2" -flags -global_header -vsync cfr -codec:a:0 aac -strict experimental -ac 2 -ab 384000  -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_entry_prefix "hls/d6fca01eb50d35b0b7cc7fd2ffd285f0/" -segment_list_type m3u8 -segment_start_number 0 -segment_list "/var/lib/emby-server/transcoding-temp/d6fca01eb50d35b0b7cc7fd2ffd285f0.m3u8" -y "/var/lib/emby-server/transcoding-temp/d6fca01eb50d35b0b7cc7fd2ffd285f0%d.ts"`

**Comment by LukePulverenti** [comment]
This is added for the next release, but you need to bring your own ffmpeg build that supports the libraries that are needed for this.
