### ISSUE TITLE
Roku App repeatedly buffering

### ISSUE THREAD

**Issue by Nerdy314159265** [MediaBrowser/Emby#2872]
I'm using Emby Server running on a FreeNAS box with the plugin updated to latest.

The client is a Roku Streaming Stick, presumably running the latest version of Roku and the Emby client app for that model.

When attempting to watch a HD video, the video loads but then repeatedly stops to buffer with a "Loading..." message. Lower quality video seems to work with less issue.

The possible causes are the App, the wifi connection, the switch, the server hardware, and the server software.

I feel that I can eliminate the Wifi connection because the Roku will still lag within 10ft of a WAP and it's an enterprise grade Unifi model. The switch is also an enterprise grade Netgear. The server is also enterprise grade and is running with only light load.

There is also no issue with playing the same video file at high bitrates with the Mobile app over the same connection from the same server.

So I think there has been some sort of performance loss on the Roku App.

**Comment by LukePulverenti** [comment]
Hi there, can you please discuss an example, and attach the information requested in how to report a media playback issue: https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/

Thanks !

**Comment by Nerdy314159265** [comment]
An example would be attempting playback on the Roku Streaming Stick of a bluray copy of Stargate Continuum. The video would load, play for a short duration then would buffer with a black loading screen. When playback resumes it's very short less than 10 seconds and it buffers again.

Getting logs will take a little bit for me to retest and make sure I give you the correct ones.

**Comment by LukePulverenti** [comment]
I think what you probably need to do is just lower the in-app max streaming bitrate setting until it becomes playable.

In any event, we can't really proceed further without more information. Please re-open if you're able to supply it and we're happy to investigate. Thanks !

**Comment by Nerdy314159265** [comment]
Apologies for never following up with more details like I should've. We've dealt with it for now by lowering the max bitrate like you suggested. However, I still find it curious that the auto mode doesn't work for some reason.

Every connection along the network pipe is solid. So my only guess is that the app is trying to draw more bandwidth than the Roku can deal with, either from a memory or CPU limitation.
