### ISSUE TITLE
Enhance seeking controls

### ISSUE THREAD

**Issue by NickBolles** [MediaBrowser/Emby#2886]
I've been using Chromecast a ton lately and it's awesome!

The one thing that bugs me is seeking. Say I wanna go back 10 seconds I have to try to slide the slider back a tiny bit. I've gotten better with practice but it's still really hard, especially with a movie.

So a double tap to skip a predefined amount (would be awesome to be able to configure it) would be awesome. 

Also a precise seek feature would be cool for all apps. Basically this is where dragging horizontally with the play area is normal, but if you go a certain distance vertically it gets more precise (slower movement) and there would be like 3 or 4 levels that gets precise to the second. 
I don't remember where I've seen this but I think it was on older (possible recent) iPhones. And I think it works really slick. 

I'd be willing to do some dev work on this but wanna open the discussion first

**Comment by NickBolles** [comment]
Also, idk if this is possible because VLC and other players did the same thing. But seeking in recorded live TV is painful. I just had my Chromecast lose connection half way through a recorded football game and couldn't get back to the place I was at because it had to buffer it all it seems.

**Comment by LukePulverenti** [comment]
We already have a double tap on the left/right side of the screen to fast forward and rewind. it is just not currently working on ios devices.

**Comment by NickBolles** [comment]
I know we have double tap in the Android app and website app. But not during Chromecast playback. As far as I can tell. That's what I'm suggesting.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by BloodyIron** [comment]
> We already have a double tap on the left/right side of the screen to fast forward and rewind. it is just not currently working on ios devices.

There is? When I do chromecast this functionality... isn't self-evident. Is it a "hidden" feature?

**Comment by LukePulverenti** [comment]
The latest app updates have ff/rew buttons. Thanks.

**Comment by BloodyIron** [comment]
Yay! @LukePulverenti does this also have ff/rew buttons on the lock screen? I'd love to do that without having to unlock my device. :D

**Comment by LukePulverenti** [comment]
Do you mean in the notification? Because yes they are there.
