### ISSUE TITLE
3.2.30.0 source tarball hash change - possible security incident?

### ISSUE THREAD

**Issue by nvllsvm** [MediaBrowser/Emby#2892]
The hash for https://github.com/MediaBrowser/Emby/archive/3.2.30.0.tar.gz has changed. I'm concerned of a possible security breach.

**Old:** `10e74af636027ead90626568e8f80d29b831969073e59fcd5e18582e6af1100e`
**New:** `b1fae1169a337bf35d118b45ec9d5579e595ab70f1157c2d7699df51bda240bd`

**Comment by LukePulverenti** [comment]
Thanks. Upon a very quick initial review, I don't see any differences between that and a local copy from three weeks ago. But I will continue to investigate.

**Comment by nvllsvm** [comment]
Related Arch Linux bug: [FS#55681 - [emby-server] 3.2.30.0.tar.gz hash incorrect ](https://bugs.archlinux.org/task/55681?string=emby-server&project=5&search_name=&type%5B0%5D=&sev%5B0%5D=&pri%5B0%5D=&due%5B0%5D=&reported%5B0%5D=&cat%5B0%5D=&status%5B0%5D=open&percent%5B0%5D=&opened=&dev=&closed=&duedatefrom=&duedateto=&changedfrom=&changedto=&openedfrom=&openedto=&closedfrom=&closedto=)
