### ISSUE TITLE
Mobile device ghosts

### ISSUE THREAD

**Issue by mtompkins** [MediaBrowser/Emby#2902]
Previous mobile devices that have been removed continue to appear, likely due to IP

To reproduce:
Create DHCP reservation for a mobile device (e.g. 192.168.1.100)
Install Emby from AppStore and connect to server
Remove Emby from device and remove device from network
Update DHCP reservation for a new device using existing IP
Based on the above there is a new MAC and new device NAME
Install Emby on replacement device
Emby server now shows both devices.

This can happen during a phone/tablet replacement or upgrade.

As Emby limits the number of devices that can coexist based on licensing (which I think is a terrible practice), this should be addressed.

**Comment by LukePulverenti** [comment]
Hi, devices are actually based on device identifiers and not any kind of network related information such as mac address or ip address.

For example, in android we get the android ID, in iOS we get the uuid, etc. If you use two different devices there is no way to stop two devices from showing up.

Having said that, if you're concerned about the license, once a device stops connecting after 14 days, it will no longer count against your license limit.

Please let us know if this helps. Thanks.

**Comment by mtompkins** [comment]
Thank you for this information, and indeed you then have a bug. When I connect with my mobile device (which replaced a Nexus 6p) but the new device and the old show as Active Devices on the dashboard. The Nexus 6p is no longer in my possession let alone on the network. Your identifier / UUID needs some investigating. Many thanks.

**Comment by LukePulverenti** [comment]
Where is the device now? it sounds like the device still has the app installed on it.

**Comment by mtompkins** [comment]
Device has been wiped and sold. If it has emby on it, it isn't with my account.

**Comment by LukePulverenti** [comment]
We've investigated and have not been able to reproduce. The UUID comes from the android ID, but over time there have been changes to that (though not recently). If it happens again with any new devices then please re-open and we can look further. Thanks.
