### ISSUE TITLE
disabling transcoding for a user is not working

### ISSUE THREAD

**Issue by brianjmurrell** [MediaBrowser/Emby#2904]
For a given user, I have disabled all of:

Allow audio playback that requires transcoding
Allow video playback that requires transcoding
Allow video playback that requires conversion without re-encoding

but when that user plays an MPEG2VIDEO file, Emby (3.2.31.0) still goes ahead and fires up ffmpeg to transcode.

**Comment by LukePulverenti** [comment]
What Emby app are you playing from?

**Comment by brianjmurrell** [comment]
I was using the web app, but I'd suspect this is something that should be dealt with server-side and not client (i.e. app) side.  Never trust clients and all that.
