### ISSUE TITLE
https -> http errror redirection during installation

### ISSUE THREAD

**Issue by emixam150** [MediaBrowser/Emby#2908]
Hello, 
I try to install emby by following the instructions for Ubuntu 16.04 : https://software.opensuse.org/download.html?project=home%3Aemby&package=emby-server 

And i got this type of error during downloading for all required packages : 
```
sudo apt-get install emby-server
...
E: Failed to fetch https://download.opensuse.org/repositories/home:/emby/xUbuntu_16.04/./amd64/libmono-btls-interface4.0-cil_4.8.1.0-0xamarin1_amd64.deb  
Protocol "http" not supported or disabled in libcurl
...
```

I think there is a link with this report : https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=827365. Because the https requests to `download.opensuse.org` are redirected to http one. 

Finally, I solved the problem by changing `/etc/apt/source.list.d/emby-server.list` by : 
```
# deb https://download.opensuse.org/repositories/home:/emby/xUbuntu_16.04/ /
deb http://download.opensuse.org/repositories/home:/emby/xUbuntu_16.04/ /
```

**Comment by LukePulverenti** [comment]
Closing with won't fix. We will have an all-new installation process very soon. Thanks.
