### ISSUE TITLE
Tv Extras

### ISSUE THREAD

**Issue by Jab2870** [MediaBrowser/Emby#2917]
Often TV series DVDs include extras. Sometimes these are deleted scenes, sometimes interviews with actors and so on.

I have often included extras from `Movies` by adding them to an extras folder.

I have included them like this in a `TV` folder like this:

```
── Hustle
│   └── Season 1
│       ├── extras
│       │   ├── Track2.mkv
│       │   └── Track6.mkv
│       ├── Hustle S01E01
│       ├── Hustle S01E02
│       └── Hustle S01E03
│       └── ..............

```

But Emby now only shows 2 "episodes" that are actually just the tracks in the `extras` folder.

Could you add support for extras in TV series?

**Comment by LukePulverenti** [comment]
Hi, we do have support for extras, but they need to be under the series folder. We don't currently support them underneath the season folder.

**Comment by Jab2870** [comment]
@LukePulverenti  Thanks,

Would extras under the season be an option?  Ideally I would like to keep the extras organised by season. For the time being, I will just include the season in the file name but this adding support for season organised extras would definitely be helpful to me and I'm sure I'm not the only one who would find it helpful.

**Comment by LukePulverenti** [comment]
I believe you could do this now and they would just show up as episodes of that season. You'd probably want to lock them to prevent the server from fetching internet metadata for them.

**Comment by LukePulverenti** [comment]
Coming in Emby Server 4.8:
https://emby.media/community/index.php?/topic/55915-emby-server-theater-additional-extrasspecial-folder-types-for-tv-series-similar-to-movies/page/3/#comment-1186924
