### ISSUE TITLE
Feature Request for Windows Server Core compatibility

### ISSUE THREAD

**Issue by marukka** [MediaBrowser/Emby#2924]
Can Emby Server check if C:\Windows\system32\AVICAP32.DLL and C:\Windows\system32\MSVFW32.DLL exists on the system, and if missing prompt the user to install these files? FFMPEG has dependencies on these two DLLs and are required for it to run. They are not present on Windows Server 2016 Core edition but can be copied from a Desktop Experience edition and it will work. This was tested against 3.2.32.11-beta and FFMPEG version 20170308. They are not included with the Server Media Foundation feature, nor is that feature required.

Since the Emby installer has dependencies on the Desktop Experience edition of Windows Server the only way to install it is via one of the .7z packages of the system directory you publish. So the installer would not be the appropriate place to put this message unless you want to redo the installer to ensure comparability with Server Core - see https://github.com/MediaBrowser/Emby/issues/2697

**Comment by LukePulverenti** [comment]
You're saying ffmpeg needs this, or the server executable?

**Comment by marukka** [comment]
ffmpeg requires it

**Comment by LukePulverenti** [comment]
Normally I would retain the older ticket, but since there is a lot of useful info, I am closing this in favor of #3175 

Thanks.
