### ISSUE TITLE
Ffmpeg flag for mk3d not supported

### ISSUE THREAD

**Issue by chorca** [MediaBrowser/Emby#2937]
It appears that FFmpeg does not support the flag being specified to it by Emby when attempting to transcode .mk3d files:

When calling ffmpeg to transcode a file .mk3d, emby appends `-f mk3d` to the beginning of the command, which ffmpeg does not recognize:
`Unknown input format: 'mk3d'`

The format used with normal .mkv files is `-f matroska`, which I believe should also be used for mk3d files.
Renaming the media to .mkv causes Emby to specify the correct format specifier and allows transcoding.

**Comment by LukePulverenti** [comment]
Can you provide a sample video for testing? thanks.

**Comment by chorca** [comment]
With the latest version (3.2.34.1), refreshing a file whose container was previously detected as "`mk3d`" now detects as "`mkv`" and it's able to properly transcode the file. Thus a refresh of the library is all that's needed and I can transcode .mk3d files properly.

**Comment by LukePulverenti** [comment]
Yes i was able to obtain a sample and couldn't reproduce, thanks.
