### ISSUE TITLE
dlna jpg format

### ISSUE THREAD

**Issue by Mikohaza** [MediaBrowser/Emby#2940]
Dear All!
My Samsung and Sharp smart tv is telling me that the jpg format is not supported file format via the dlna client of the tv.Trough the internet browser is ok. The problem is that the Samsung has no internet browser. Not full smart.
Anyway the problem is present on each tv. 
Any idea?
Thanks,

**Comment by LukePulverenti** [comment]
What model TV's?

**Comment by Mikohaza** [comment]
1. Samsung UE32D5000 - Dlna Client Only - Photo Thumbnails are visible - After entering the file is telling not supported format
2. Sharp Aquos LC-43CFG6352E - Same situation over Dlna - Over builtin internet browser everitying is fine.

**Comment by LukePulverenti** [comment]
Resolved for next release, thanks.
