### ISSUE TITLE
No Emby server service

### ISSUE THREAD

**Issue by 1RV34** [MediaBrowser/Emby#2942]
With a Windows installation the service seems to no longer work, a re-install no longer installs a service anymore either.

**Comment by LukePulverenti** [comment]
Hi, we have new guidelines for setting up a Windows Service:
https://github.com/MediaBrowser/Wiki/wiki/Running%20Emby%20Server%20as%20a%20Windows%20Service

Let us know if this helps. Thanks.

**Comment by 1RV34** [comment]
Please don't recommend people to put things in System32, instead let them put this file somewhere on their system (I'd say `%LOCALAPPDATA%`) and have them add it to the `%PATH%` list.
And I really preferred the bundled service method. (probably would also be less of a hassle for less technical people.)

How will this show up in the services list? I would really prefer to see Emby in my list instead of NSSM.

**Comment by LukePulverenti** [comment]
Yea you can put it anywhere you want, and when you set it up you can name it whatever you want.

**Comment by LukePulverenti** [comment]
I've updated the instructions to let users know they can place it anywhere and update the system PATH variable:
https://github.com/MediaBrowser/Wiki/wiki/Running-Emby-Server-as-a-Windows-Service

Has this answered all of your questions?

**Comment by 1RV34** [comment]
It's become more cumbersome to set this up so I haven't had the time to go through this yet.

Why was this change made at all?

Is it possible to have the option to install the Emby service in the installer? Changes should make it easier to use not more difficult.

**Comment by LukePulverenti** [comment]
We are rebuilding around the new .NET Core runtime and the presence of the windows service would require us to maintain a project specific to windows desktops. Troubleshooting a windows service is not really something that we want to be doing.

Thank you for the feedback though. We will improve the instructions so that every step is clearly outlined.
