### ISSUE TITLE
iOS to tv stopped working 

### ISSUE THREAD

**Issue by dmgm** [MediaBrowser/Emby#2944]
I have emby installed on my Linux server  
Previously I used an iOS device to Choose content the stream it/ cast it to my lg Webb’s tv

The iOS app no longer detects the tv. 
YouTube app detects tv still. 

Has something changed?
I’m using latest versions. .

**Comment by LukePulverenti** [comment]
What model TV?

**Comment by dmgm** [comment]
Its a 55" UltraHD LG.
No model number obvious, but the webos reports itself as 04.05.21 in the about the tv screen.
From memory this is the upgraded webOS 2.0.

Problem is the same on iphone /and/ ipad with ios emby client.
Server running on debian, and is current as of today.

I use the screen app on the smart tv to connect to the emby server over wireless.
Works fine.

The ios apps appear to work for all other functionality, I can restart the server etc.
They aren't premium apps so I cant actually watch anything on them, but I found the interface better for selecting a show, that the TV smartapp.

Network seems fine. Both devices on same wireless network.
Only thing I've not tried is a power cycle of the TV (rather than just switching it on and off at the remote).

**Comment by LukePulverenti** [comment]
Hi there, does this occur with the latest release of emby server? thanks.

**Comment by dmgm** [comment]
Yes. I'm running Version 3.2.40.3, and TV-DLNA (from memory) appears on both my iOS devices (latest iOS versions).

It has worked from both, I'll keep an eye on it, but it appears to be working as expected.
Thank you.

**Comment by LukePulverenti** [comment]
Thanks. Please re-open with new information if you run into a problem.
