### ISSUE TITLE
Debian 8 repository gone?

### ISSUE THREAD

**Issue by shottothedome** [MediaBrowser/Emby#2953]
Since 3.2.33 there is no longer a Debian_8.0 repository on opensuse.org. I only see debian next in there. Is Debian 8 no longer supported? Also the how to download section on emby.media for the linux releases of stable release channel and beta release channel fail with a 503 error

When running apt-get update
W: Failed to fetch http://download.opensuse.org/repositories/home:/emby/Debian_8.0/Release.gpg  Connection failed

**Comment by LukePulverenti** [comment]
There appears to be another outage on the OpenSuse build service. There is nothing we can do about this so you'll just have to wait it out. But see here for the new direction we're headed in:
https://emby.media/community/index.php?/topic/51846-repository-not-available/
Thanks.
