### ISSUE TITLE
Problem with browser playback

### ISSUE THREAD

**Issue by martimarkov** [MediaBrowser/Emby#2955]
I'm having this issue with both Safari and Chromium on the latest MacOS High Sierra:
`HLS Error: Type: mediaError Details: bufferAddCodecError Fatal: false`

The content of the inner exception msg is:
```
"Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('audio/mp4;codecs=mp4a.40.5') is unsupported."
name
:
"NotSupportedError"
```

**Comment by LukePulverenti** [comment]
Hi, can you let me know if you're seeing this on the new server release, 3.2.34? I haven't seen this issue in my testing on High Sierra. Thanks.

**Comment by martimarkov** [comment]
Nope, not seeing this anymore.

**Comment by simontong** [comment]
I'm seeing this error in Vivaldi browser but not chrome

**Comment by martimarkov** [comment]
I think my problem was using Google Drive with an rclone mount

Thanks,
Marti Markov
