### ISSUE TITLE
Problem with DLNA Controller

### ISSUE THREAD

**Issue by benkuly** [MediaBrowser/Emby#2956]
When I start a video on the TV (LG) with the Android Emby Client and the Smartphone looses WLAN connection, then the playback stops an Emby Server does not response.

A workaround is to completely close the app on the smartphone directly after starting the playback.

[Log.txt](https://github.com/MediaBrowser/Emby/files/1385277/Log.txt)

**Comment by LukePulverenti** [comment]
What model LG?

**Comment by benkuly** [comment]
Yes. LG.




On Wed, Oct 25, 2017 at 5:15 AM +0200, "Luke" <notifications@github.com> wrote:












What model LG?

**Comment by LukePulverenti** [comment]
Is this still an issue on the latest version? thanks.

**Comment by benkuly** [comment]
In 3.2.36.0 the issue is still there.

**Comment by LukePulverenti** [comment]
Is this still an issue with 3.2.50? Thanks.

**Comment by benkuly** [comment]
Yes
.

**Comment by LukePulverenti** [comment]
Can you try 3.2.60? Thanks.

**Comment by LukePulverenti** [comment]
Any results with the latest release? thanks !

**Comment by benkuly** [comment]
I will test it in the next few days. Thanks :-)

**Comment by benkuly** [comment]
It's still an issue.

**Comment by LukePulverenti** [comment]
Hi, can you try 3.2.70? Also, does this happen when using the web app to remote control?

**Comment by benkuly** [comment]
With the Android app and two 20 min episodes as test the problem seems to be solved.

**Comment by LukePulverenti** [comment]
Thanks for the feedback !

**Comment by benkuly** [comment]
Sorry, I got the same error today...
I will try it with the web app in a few days.
