### ISSUE TITLE
MV errors in P/B frame

### ISSUE THREAD

**Issue by DaniGTA** [MediaBrowser/Emby#2958]
In the normal player(MPC-HC) there are none of this error
![firefox_2017-10-16_02-16-54](https://user-images.githubusercontent.com/20490672/31590858-3dac2e48-b218-11e7-81ad-be3a42ece583.png)
s
[ffmpeg-transcode-06be2ce0-bb7d-4916-86ef-e491d3ebb1ae.txt](https://github.com/MediaBrowser/Emby/files/1385929/ffmpeg-transcode-06be2ce0-bb7d-4916-86ef-e491d3ebb1ae.txt)

**Comment by LukePulverenti** [comment]
You may want to try a newer ffmpeg build and see if that resolves this. You can grab one from here:
https://ffmpeg.zeranoe.com/builds/

Then set it up under the server transcoding menu. Thanks.

**Comment by LukePulverenti** [comment]
Did this help?

**Comment by DaniGTA** [comment]
the problem was the newer ffmpeg, the standard one works fine.

**Comment by LukePulverenti** [comment]
Thanks.
