### ISSUE TITLE
Install instructions for Linux is a dead end

### ISSUE THREAD

**Issue by anohren** [MediaBrowser/Emby#2964]
I try to follow the instructions for installing emby server on Debian, but after following the link provided for "stable release channel" I cannot proceed. 

I select Debian on the resulting page, and nothing more happens. I should add that I have no idea what to expect, other than _something_.

This happens both on mobile and on desktop browsers.

**Comment by anohren** [comment]
![img_6739](https://user-images.githubusercontent.com/3519879/31822202-3e5b750e-b5a8-11e7-82e7-58b3a5988444.PNG)

**Comment by LukePulverenti** [comment]
It's fine here. I remember this happening once before to a user and the problem was either browser related or they had javascript disabled in the browser. Or perhaps it was a browser extension causing it.

![untitled](https://user-images.githubusercontent.com/3607463/31829778-49b01584-b58c-11e7-887f-7e3b3edfc7f1.png)

**Comment by anohren** [comment]
Thanks for the help Luke. 

I tried to make sure that the issues you mentioned were not the case. Sarai on iOS have no extensions anyway, and JS was enabled there. 

I have to assume some unfortunate coincidence — that the buttons don't work for touch devices, and that some extension was interfering on desktop (despite being told not to) making it look like the same issue.

**Comment by LukePulverenti** [comment]
Ok thanks for the info. We are about to replace the install instructions with a brand new package:
https://emby.media/community/index.php?/topic/50012-emby-server-for-net-core/

We won't even be using that website anymore, so for right now I am going to close this with won't fix. Thanks for reporting.
