### ISSUE TITLE
homepage emby logo switch for lastest movie watched logo

### ISSUE THREAD

**Issue by louisforget** [MediaBrowser/Emby#2967]
hi, i found what is probably a bug
homepage emby logo switch for the latest movie watched logo

on the home page (web interface / firefox), you see the emby logo: https://imgur.com/yLcJDkM
start any movie with a logo attached to it: https://imgur.com/L1JyPfK
go back to the homepage, now the logo in the corner is the latest movie logo: https://imgur.com/OWuoU3q

im on 3.2.33.15 beta version server
thanks

**Comment by louisforget** [comment]
same on 3.2.33.17 beta released 20 minutes ago

**Comment by louisforget** [comment]
same on 3.2.33.18 beta released 2 hours ago

**Comment by louisforget** [comment]
same on 3.2.33.20 beta released 2 hours ago

**Comment by LukePulverenti** [comment]
hi @louisforget thanks for bringing this to our attention.

**Comment by LukePulverenti** [comment]
Resolved for next release, thanks.
