### ISSUE TITLE
Identifying titles with numbers

### ISSUE THREAD

**Issue by Answer-Man** [MediaBrowser/Emby#2976]
I'm having issues with identifying some content that has numbers in it's title.
For example "Uchuu.Senkan.Yamato.2199.S01E01" will be identified as follows:
Title : Uchuu Senkan
Season : 21
Episode number : 99
And the actual episode number is totally ignored, which will also affect the episode name retrieval from metadata downloaders.

**Comment by LukePulverenti** [comment]
In the latest beta this example works just fine for me. I am going to assume it has either been previously resolved, or resolved for the next release. Thanks !
