### ISSUE TITLE
Two media libraries for the same folder (metadata override)

### ISSUE THREAD

**Issue by Answer-Man** [MediaBrowser/Emby#2977]
Let's assume I've a folder that contains both Movies and TV Shows.
We create a library of that folder (content type: TV) and then wait until metadatas are downloaded.
Now we create a second library (content type: Unset) to catch both TV and Movie metadatas.
The second library will be an exact copy of the first with the movies still unidentified and cannot be identified as movies (search filters that are specific to movies such as TMDB or even searches by name will not return values). 
Metadatas and library settings seem to be merged since the settings of the first media library apply to the second.
After removing the first library, it seems that all of the shared metadata between the two libraries will go away with it, to avoid duplicates and save some space I assume. 
Accordingly, another metadata scan for the second library is launched and now some content that was originally correctly identified is no longer identified at all and cannot be manually identified (option not displaying for root folders but still displays for episodes which is irrelevant in this case).
My suggestions are:
If the metadatas are shared between several libraries, keep them even though the "main" media library is deleted.
Add an option to manually identify content even if it's not recognized in content type "unset" for some reasons. Or even better, resolve the problem that makes some content identified in TV but not in unset libraries.

**Comment by LukePulverenti** [comment]
This is unsupported. What you need to do is just have one single library using the mixed content type.

To comment on your observations, the library options are not merged but rather it is probably a situation where it is just random as far as which set of options the library scan will utilize. By doing it this way you've set two different sets of library options on the same folders. We're not really testing this sort of thing so I would expect unpredictable behavior.

**Comment by Answer-Man** [comment]
But If I do so I end getting content that can't be identified either manually or automatically. Half of my content is just raw content without metadata. It seems that an unset library does not support the same TV/Movie naming as specific libraries. 

E.g : 
![2017-10-25_08-47-44](https://puu.sh/y6E0Y/ab9de2df63.png)

Those are basically the only available options, and the structure is:
``` 
\Animes
   \Detroit Metal City
       \[Animes]Detroit_Metal_City_01[720p].mp4
```

**Comment by LukePulverenti** [comment]
> "It seems that an unset library does not support the same TV/Movie naming as specific libraries."

Correct, because it's nearly impossible to automatically detect when supporting all features, so some are disabled for mixed libraries. That's actually why we have the content type selections in the first place.

**Comment by LukePulverenti** [comment]
Closing as this is not realistic. Suggested behavior is just have one single library using the mixed content type. I am updating the TV naming guide to reflect that season sub-folders are required in mixed content libraries. Thanks.
