### ISSUE TITLE
audio track selection not working in web client

### ISSUE THREAD

**Issue by brianjmurrell** [MediaBrowser/Emby#2978]
I have some webm files that look like this:

```
Input #0, matroska,webm, from 'file.mkv':
  Metadata:
    ENCODER         : Lavf57.71.100
  Duration: 00:42:26.77, start: 0.000000, bitrate: 3641 kb/s
    Stream #0:0(eng): Video: h264 (High), yuv420p(tv, bt709/unknown/unknown, progressive), 1280x720, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Stream #0:1: Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
    Stream #0:2: Audio: aac (LC), 48000 Hz, stereo, fltp (default)
```

When I play them in the web player, there is no sound.  I guess the first track being AC3 is a problem.  So I click on the musical note in the control bar and see the two tracks, one listed as _Dolby Digital 5.1 Default_ and the other as _AAC Stereo Default_ so I click on the latter.  Still no audio.

If I remux the file so that the AAC track is before the AC3 track the file will play with sound.

Regardless of order, shouldn't that track selection control work?

**Comment by LukePulverenti** [comment]
I'm not able to reproduce this. Can you please attach the information requested in how to report a media playback issue: https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/

Thanks !

**Comment by brianjmurrell** [comment]
Sign into emby community is not working.  I have processed the "forgot password" process and even the password sent by e-mail is not working.

**Comment by brianjmurrell** [comment]
In case anyone is following along here, also [posted in the Community](https://emby.media/community/index.php?/topic/52819-audio-track-selection-in-the-webplayer-not-working/).

**Comment by LukePulverenti** [comment]
Resolved for next release.
