### ISSUE TITLE
Update FFMPEG, libebml, libmatroska to latest versions.

### ISSUE THREAD

**Issue by Dazog** [MediaBrowser/Emby#2983]
FFMPEG to 3.4

3.4 supports x265. Possibility to add x265 transcoding?

libebml to 1.3.5 

libmatroska to 1.4.8

**Comment by LukePulverenti** [comment]
What is the reason to update?  x265 is already supported.

**Comment by Dazog** [comment]
I updated to latest beta it appears these have been updated.

I just don't see the x265 encoder and decoder being recognized in the server logs.
