### ISSUE TITLE
"Save" button of start screen settings not visible

### ISSUE THREAD

**Issue by DMW007** [MediaBrowser/Emby#2984]
I upgraded to the latest version 3.2.34.0 of Emby using our official Docker image and found out that it's not possible to change my start screen settings: The page `https://<MyDomain>/web/mypreferenceshome.html?userId=<MyUserId>` doesn't show any _save_ button. So I took a look at the html source code and found out that the button is present, but hidden: 

![](https://u-img.net/img/3736Cv.jpg)

After removing the `hidde` css class, the button appears as expected: 

![](https://abload.de/img/screenshot_22nkvm.jpg)

Now using the button seems working fine, so in my point of view there is no reason to hide it.

**Comment by LukePulverenti** [comment]
Hi, the settings are saved automatically without having to click a save button.

**Comment by DMWOO7** [comment]
Hi @LukePulverenti, thanks for the quick reply! 
This was also my suggestion, but it doesn't seem to work. I made several changes and got the old ones after a page reload. Tested in Chrome Version 61.0.3163.100 and Firefox 56.0.2 (64 Bit).

**Comment by LukePulverenti** [comment]
Resolved for next release, thanks.
