### ISSUE TITLE
Dashboard Active Recordings not showing thumbnail

### ISSUE THREAD

**Issue by hooray4me** [MediaBrowser/Emby#2992]
The Active Recordings Dashboard is not pulling the thumbnail/backdrop images.
![image](https://user-images.githubusercontent.com/12399138/32201455-237acdf2-bda5-11e7-8f75-0109f5846146.png)
![image](https://user-images.githubusercontent.com/12399138/32201459-2889624a-bda5-11e7-9bed-8d8eec4fcabd.png)

**Comment by LukePulverenti** [comment]
Resolved for net release. (not 3.2.40, the one after). Thanks.
