### ISSUE TITLE
no default audio selected on android tv

### ISSUE THREAD

**Issue by louisforget** [MediaBrowser/Emby#3006]
Hi Luke, not sure if you already know,
but since 3.2.36.2-beta version with the add of the support track selection prior to playback feature (and i just tried the latest version 3.2.36.3 and the problem still exist)

There is no default audio selected for the playback on android tv, so the movie start with no audio and you have to select the audio you want! But that's not the biggest problem, when there is only 1 audio file in the media, the movie start with no audio AND it's not possible to select the audio

My emby android tv app is on the latest beta version
sorry if you already know about this problem, i just thought it would be a good idea to let you know just in case :)

Thanks

**Comment by LukePulverenti** [comment]
Resolved for next build, thanks.
