### ISSUE TITLE
server crashes when serving photo on web client

### ISSUE THREAD

**Issue by leprinco** [MediaBrowser/Emby#3010]
In web client, on artists wall or in artist detail, server crashes when downloading image for Israel Kamakawiwoʻole. 
please see [server-63645858179.txt](https://github.com/MediaBrowser/Emby/files/1459313/server-63645858179.txt)

I have updated the artist.nfo to remove &lt;fanart&gt;'s tags and changed the folder.jpg image with one of another artist that is properly downloaded: it crashes also. So it does not seem to come from the files themselves but more from the artist's name.

**Comment by LukePulverenti** [comment]
Hi, install from the website on top of your existing version and this will be resolved, thanks.

**Comment by leprinco** [comment]
yes it works. Many thanks
