### ISSUE TITLE
Web interface: Top bar section links undiscoverable

### ISSUE THREAD

**Issue by anohren** [MediaBrowser/Emby#3015]
I just installed the server and played around in the web interface trying to find everything, but even after clicking around a lot I couldn't find any metadata scraper settings. In desperation I turned to google which led me to [this thread](https://emby.media/community/index.php?/topic/48271-reorder-metadata-sources/) but even after navigating back to Library (for the tenth time) I couldn't see where this "Metadata" option was supposed to be. 

I was starting to worry that I was looking for something that didn't exist. Finally I discovered that some links have magically appeared in the very top menu bar. 

The person in the aforementioned link says "I don't know how I missed it", but I do.

There are many problems with this placement of section links/tabs/submenu items (or whatever you want to call it):

- I don't expect submenu items to appear in what appears to be a top level menu, especially not after navigating in a side menu that appears to be secondary to the top menu bar. 
- All other subordinate content is placed in the content view, but not these section links - for some reason.
- The other items in the left-hand menu don't seem to have options in the top bar so there was even less of a reason for me to expect just the Library item to have them.
- Last but not least the links in the top bar aren't very high contrast, amplifying the problem.

Suggestions
-------
I would much rather have seen the subsections listed right under the Library menu item -- that way I would have noticed them immediately instead of missing them ten times in a row. Alternatively, tabs in the actual content view would work.

**Comment by LukePulverenti** [comment]
The next release will have a lighter header. Do you think this will be easier now?
![untitled](https://user-images.githubusercontent.com/3607463/45443547-054a4000-b693-11e8-9499-b5af65b73e01.png)

**Comment by LukePulverenti** [comment]
We are gradually moving away from these tabs. Thanks.

**Comment by anohren** [comment]
Nice to hear. I have since reinstalled Emby and had another look around, and although it might just be that I now know about this issue, I generally recall having a much easier time navigating the web UI now than a year ago.
