### ISSUE TITLE
How to escape whitespace when specifying host volumes to mount in Docker?

### ISSUE THREAD

**Issue by anohren** [MediaBrowser/Emby#3017]
As soon as I try to specify a volume when running the Docker launch script I get told "docker: invalid reference format: repository name must be lowercase."

I'm going to assume that this is because you don't escape whitespace in the paths provided to host volumes, and that docker gets fed extra arguments, because that error message dosen't make any sense to me.

I tried to escape with backslash, e.g. `/mount/Vault\ 13` but that doesn't solve the problem. Same thing with single and double quotes.

Removing the volumes with whitespace in the path from `.emby-server.volumes` allows docker to launch.

**Comment by LukePulverenti** [comment]
Have you tried putting quotes around the path?

**Comment by anohren** [comment]
Yes, they're mentioned in the third paragraph. Didn't work.

**Comment by LukePulverenti** [comment]
Ok, we've tested and verified this won't happen with the new Docker image on our website:
https://emby.media/docker-server.html

You don't need to switch, as in the near future the current Docker image will be updated with all of these changes. Please feel free to re-open if there is still an issue. Thanks !
