### ISSUE TITLE
Amazon Fire TV/Stick login user photos

### ISSUE THREAD

**Issue by hooray4me** [MediaBrowser/Emby#3018]
The user photos are not populating on the login for Amazon Fire TV/Stick devices on both the current production and beta versions of the app.
![image](https://user-images.githubusercontent.com/12399138/32811625-66a17294-c966-11e7-923a-5ab66a9cea57.png)
View from Chrome:
![image](https://user-images.githubusercontent.com/12399138/32811654-89c9c49c-c966-11e7-97cf-fbf01b68fb4c.png)

**Comment by ebr11** [comment]
Hi.  Yes, we are aware of this but have not been able to track it down yet.

Thanks!

**Comment by ebr11** [comment]
Hi.  This will be fixed with the next release of the app.

Thanks.
