### ISSUE TITLE
Problems playing MKV file from Android TV App

### ISSUE THREAD

**Issue by inlinex** [MediaBrowser/Emby#3019]
Hellow, I Have the **Season 01** of Game of Thrones and recently Added to Emby server, but for some strange reason, when I click on play on Any Episode doesn't play nothing. I followed all Naming convention for emby and nothing happens if someone can help me, it will be appreciated for me

**Comment by LukePulverenti** [comment]
Hi there, can you please attach the information requested in how to report a problem:
https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/

Thanks !

**Comment by LukePulverenti** [comment]
Closing due to abandonment, however please feel free to reopen if you can provide the requested information. You may also wish to try the app update that just went out. Thanks !
