### ISSUE TITLE
macOS: state the reason for installing into /Applications

### ISSUE THREAD

**Issue by dreness** [MediaBrowser/Emby#3030]
The install instructions clearly state to put EmbyServer.app into /Applications, but in a way that doesn't indicate that this is more than a suggestion. Historically on the mac, it's not uncommon for some users to store some applications outside of /Applications. Maybe you're one of those people who likes to run new stuff out of, say, ~/Applications, as sort of a form of probation, until someday perhaps being promoted to walk amongst the others in /Applications. However, as of recent-ish versions of macOS (10.12), apps that aren't sufficiently trusted by Apple may become the unwitting victims of "Gatekeeper path randomization", which is when the OS _tries_ to transparently chroot the app and run it in a somewhat confined environment. This isn't really described in great detail in the [code signing doc](https://developer.apple.com/library/content/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html), but it is mentioned.

In my experience, a lot of the more interesting software in the world tends to easily break Apple's assumptions about what apps could or should do in their normal operation. I'm sure you've guessed by now that EmbyServer achieves this distinction, and is broken badly by Gatekeeper path randomization. Unfortunately, Gatekeeper path randomization has no provision for communicating to the user any potential fallout of this policy.

Here's what ends up happening, from the server log:

```
2017-11-19 22:07:08.618 Error App: Error starting ffmpeg
	*** Error Report ***
	Version: 3.2.36.0
	Command line: /private/var/folders/hj/04222vxn0zbd_wdgg59gvym40000gn/T/AppTranslocation/E84CBADE-059A-49B3-8268-1289A097B1E0/d/EmbyServer.app/Contents/MacOS/EmbyServer.dll -psn_0_1458532
	Operating system: Unix 17.3.0.0
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 8
	Program data path: /Users/andre/.config/emby-server
	Application directory: /private/var/folders/hj/04222vxn0zbd_wdgg59gvym40000gn/T/AppTranslocation/E84CBADE-059A-49B3-8268-1289A097B1E0/d/EmbyServer.app/Contents/MacOS
	System.ComponentModel.Win32Exception (0x80004005): Permission denied
	   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
	   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
	   at System.Diagnostics.Process.Start()
	   at Emby.Server.Implementations.Diagnostics.CommonProcess.Start()
	   at Emby.Server.MediaEncoding.Api.BaseStreamingService.<StartFfMpeg>d__72.MoveNext()
	System.ComponentModel.Win32Exception
	   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
	   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
	   at System.Diagnostics.Process.Start()
	   at Emby.Server.Implementations.Diagnostics.CommonProcess.Start()
	   at Emby.Server.MediaEncoding.Api.BaseStreamingService.<StartFfMpeg>d__72.MoveNext()
```

This happened when EmbyServer tried to auto-transcode something in my library when I tried to view it using the web player, but I'd imagine a similar error would happen for any sort of fork/exec.

Please consider decorating the mac installation steps to include a short explanation that, really, EmbyServer won't work unless run from /Applications.

I'm specifically not suggesting that you should code-sign with an Apple-provisioned Developer ID cert, because I don't think that's a reasonable request to make of an open source, collaborative project.

**Comment by LukePulverenti** [comment]
Thanks, will do. I actually have been trying to get the build signed but the pre-signing assessments fail with unclear error messages. I think it is due to the slightly non-standard folder structure inside the bundle though.

**Comment by LukePulverenti** [comment]
I've added some text to the bottom of our MacOS install page. It's very minimal to try and avoid scaring people away.

Please re-open if you feel this is inadequate. Thanks.
