### ISSUE TITLE
[Plugin Security Cam Live] Deleting camera's does not work

### ISSUE THREAD

**Issue by GrumpyMeow** [MediaBrowser/Emby#3035]
There is a typo in the javascript:
config.Cameras = cameras;
**condif**.DataVersion = config.DataVersion + 1;
ApiClient.updatePluginConfiguration(pluginId, config).then(Dashboard.processPluginConfigurationUpdateResult);

It's on the page: /web/configurationpage?name=CameraConfigPage

**Comment by LukePulverenti** [comment]
Hi, thanks for the report. The camera plugin is a community addition and you'll need to report this to the developer of the plugin. He can be found in the Emby Community under the name chef.

You might also consider removing the plugin and using our IPTV plugin as it is essentially the same concept. Thanks.
