### ISSUE TITLE
Emby netcore image selfbuild

### ISSUE THREAD

**Issue by RaymondSchnyder** [MediaBrowser/Emby#3036]
Hello,

I wanted to ask if its possible to build the emby netcore image with a custom net framework version myself.
As of the current build is with 2.0.0.
But my setup needs the 2.1 nightly, as of the alpine netcore docker images, which are now available, only support 2.1 at the moment, and emby is build with 2.0.0 :/

Can i build this myself somehow?
Or do you have any idea how i could "ignore" the framework dependency (as of 2.1 is "newer" than 2.0.0, it should have all the capabilities 2.0.0 has too...)

**Comment by RaymondSchnyder** [comment]
Workaround for the few people who share the same issue:

use in the dotnet run command (dotnet embyserver.dll -config.....)
the parameter "--fx-version"

as an example:

dotnet --fx-version 2.1.0-preview1-25919-02 system/EmbyServer.dll -programdata /embyData

Then it uses the custom dotnet version and it works.

**Comment by LukePulverenti** [comment]
Hi, we don't currently have this publicized but I am glad you found a workaround. Thanks !

**Comment by RaymondSchnyder** [comment]
https://hub.docker.com/r/nfxus/emby/ I build this docker image as a workaround till the emby dev team releases an official image :-)

**Comment by nvllsvm** [comment]
@RaymondSchnyder 
Mind sharing/pointing to the netcore Dockerfile you created?

**Comment by RaymondSchnyder** [comment]
@nvllsvm I give it to you when i find it, this evening maybe.

**Comment by RaymondSchnyder** [comment]
@nvllsvm https://github.com/RaymondSchnyder/docker-netcore/blob/master/Dockerfile
Here, the file was already available, or did you mean something another?

**Comment by nvllsvm** [comment]
@RaymondSchnyder I was actually looking for the Emby image running with .NET Core and hoping you were compiling Emby for .NET Core within it.

Ended up finding your repo and saw you were just downloading the offical .NET Core release.

**Comment by RaymondSchnyder** [comment]
@nvllsvm Yea xD
It works pretty good that way, do you have a idea how it could be better?
Because the documentation on how compiling emby for netcore is... a bit empty.

**Comment by nvllsvm** [comment]
@RaymondSchnyder No additional thoughts on your image outside of having it compile the source code.

Speaking of that - I attempted to compile it on Linux without success.  https://github.com/MediaBrowser/Emby/issues/3064

**Comment by LukePulverenti** [comment]
Merging with #3064. Thanks.
