### ISSUE TITLE
Clientside error upon Play-button on itemdetails page when there are no episodes

### ISSUE THREAD

**Issue by GrumpyMeow** [MediaBrowser/Emby#3041]
playbackmanager.js?v=3.2.40.0:1 Uncaught (in promise) TypeError: Cannot read property 'MediaType' of undefined
    at playWithIntros (playbackmanager.js?v=3.2.40.0:1)
    at playbackmanager.js?v=3.2.40.0:2
    at <anonymous>
playWithIntros @ playbackmanager.js?v=3.2.40.0:1
(anonymous) @ playbackmanager.js?v=3.2.40.0:2
Promise resolved (async)
PlaybackManager.self.play @ playbackmanager.js?v=3.2.40.0:2
playItem @ itemdetailpage.js?v=3.2.40.0:2
playCurrentItem @ itemdetailpage.js?v=3.2.40.0:2
onPlayClick @ itemdetailpage.js?v=3.2.40.0:2

items=[];
 function playWithIntros(items, options, user) {
            var playStartIndex = options.playStartIndex || 0
              , firstItem = items[playStartIndex];
**if (!firstItem) return; < added**
            if ("Photo" === firstItem.MediaType)

**Comment by LukePulverenti** [comment]
Resolved for next release, thanks.
