### ISSUE TITLE
Emby allows remote public internet anonymous access to your server and settings by default

### ISSUE THREAD

**Issue by rhazor** [MediaBrowser/Emby#3042]
I don't get it. I've been reading documentation and forums and disabled DLNA uPNP servers and everything else, no matter what my Emby is accessible over the internet, I tested on Tor browser and curling on some SSH remote server the http://my_external_ip:8096/web/home.html address is always accessible. It loads all the content and is available for anonymous. How do I block external IP access?

![emby](https://user-images.githubusercontent.com/22996586/33243714-ea84eee2-d2f3-11e7-8ef9-8c47f231fdfe.jpg)

I switched from Plex to Emby and Plex didn't have such trouble. All I want is to make it internal only and block/disable external.

So how to achieve that?

UPDATE: So far we learned when installing Emby it creates uPNP rules in your router itself for internal and external remote (WAN) access with no warning and makes your server accessible over the internet for anonymous, including dashboard witch is major security breach.

Disabling DLNA/UPNP inside Emby server doesn't solve anything, because the port forwarding rules were already created when installing Emby, so those solutions are useless.

Since my Technicolor router doesn't have a setting to delete Emby rules I have contacted my ISP for support, because they provided the router, I will update tomorrow. Uninstalling Emby does not remove it.

**Comment by rhazor** [comment]
Even settings dashboard is available for everyone http://my_external_ip:8096/web/dashboard.html lol, everyone can do whatever they want with my server.

Yeah I don't think this is working right.

**Comment by rhazor** [comment]
I unticked Enable automatic port mapping and Enable DLNA server and restarted.

**Comment by rhazor** [comment]
In my router settings uPNP is toggled OFF but there are 2 Emby rules added already and there is no option to delete it.

**Comment by LukePulverenti** [comment]
You'll have to figure out how to delete them from your router. If there isn't a way, then you'll have to wait for them to expire.

**Comment by rhazor** [comment]
Okay, but what about common sense, why is Emby available to public by default after you install it, all access to media and even configuration dashboard is enabled and available for anonymous to access from all around the world?

**Comment by LukePulverenti** [comment]
I think this is an area we can improve upon by asking people up front what they prefer.

**Comment by rhazor** [comment]
You don't even warn people before or after installation about this. Jesus Christ do you have any idea what kind of security hole and breach this is? Literally everyone in the world can access dashboard by default and delete all your shit or do whatever and you think this is normal and maybe it might just need some 'improvement'?

Okay.

**Comment by LukePulverenti** [comment]
Our single largest point of troubleshooting every single day is always about setting up remote access, so the system is designed to be as easy as possible. I think some up-front questions as part of the setup wizard are a simple solution that will appease your concerns. Thanks.

**Comment by rhazor** [comment]
So what you are saying it is completely fine that people can access your server over the internet and change your dashboard settings anonymously? This is completely fine?

**Comment by LukePulverenti** [comment]
No, I am saying that there is still more work to be done.

**Comment by rofrantz** [comment]
Enabling this by default means you've already done some "work" and @rhazor discovery could f%$/€-up your project.
And when I think that some people have the generous offer to even pay for this.
Uninstalling !

This info should go public !

**Comment by jonretting** [comment]
You could implement a local firewall policies to block public all incoming public connection, and allow for internal subnet.

**Comment by luigixp** [comment]
This is strange, is this on a windows server? I recently installed Emby and not seeing this behavior. How can it get access to your router to make those changes?

**Comment by rhazor** [comment]
Don't care anymore, uninstalled long ago. Devs don'g give a shit.

**Comment by luigixp** [comment]
Oh I see, uPNP is how. My router has that disabled by default, Not secure. Are you using Plex not. I had to switch to Emby because Plex has gotten bad this year.

**Comment by LukePulverenti** [comment]
The next release of Emby Server will have explicit settings in the startup wizard to:

- Enable or disable remote access
- Enable or disable the automatic port mapping feature with UPNP.

These settings are also available after the startup wizard in the Advanced section.  Thanks for the feedback guys.
