### ISSUE TITLE
[Feature Request] Volume button support on mobile devices, when using chromecast

### ISSUE THREAD

**Issue by BloodyIron** [MediaBrowser/Emby#3043]
Hey Folks!,

I use my phone with Emby to send to my chromecast alllllll the time. Unfortunately, the volume buttons on my phone do not control the audio for Emby to my Chromecast. Since almost every other chromecast app out there supports volume buttons on mobile devices, I really want to see this in Emby too!

As such, can we please get volume button support for Emby when interfacing with Chromecast? :)

**Comment by BloodyIron** [comment]
Any chance we can get this tied to a milestone or something? :) I'm itching for this!

**Comment by capitaineflam25** [comment]
I would love this feature to😍😋

**Comment by LukePulverenti** [comment]
This will be in the next release of the app, thanks.

**Comment by BloodyIron** [comment]
AWWW YEAH!!!

**Comment by capitaineflam25** [comment]
Thanks a lot !
