### ISSUE TITLE
Library Scans Fail - "String was not recognized as a valid DateTime."

### ISSUE THREAD

**Issue by DncrJim** [MediaBrowser/Emby#3044]
Version:  3.2.40.0
SBC: RPi 3 B
DietPi: V158

The alert says:
Scan media library failed.
String was not recognized as a valid DateTime.

Error first occurred on the initial "Scan All Libraries" near the end of the first library. I was able to scan some other library folders by selecting them individually, however, all folders seem to have developed the same error before scanning all of the media in them. Error occurs on all library scans, as well as on individual library scans. Notification is only given upon failure of the 'scan all' option.

I am able to add items not in the library by going to the folder view and refreshing metadata, but with the scale of the library and the wish for the system to automatically add new items, this is not really a viable solution.

Seemingly Related Topic from 2016: 
https://emby.media/community/index.php?/topic/35823-scan-media-library-failed/

This was a fresh from scratch install, and after reading the above post and discovering the the problem may be intermittent, I wiped everything and started again, and I am experiencing the same error and issues for a second time.

Thanks in advance...

[2017.11.27 12.19.35 Emby Server Log.txt](https://github.com/MediaBrowser/Emby/files/1506875/2017.11.27.12.19.35.Emby.Server.Log.txt)

**Comment by LukePulverenti** [comment]
Hi, I notice you've updated to the mono runtime 5.4. Our highest supported version is 4.8.1. Can you roll that back? It is likely related to this. Thanks.

**Comment by DncrJim** [comment]
Since your comment:
-I have been unable to roll back to the mono install on two different installs (was using dietpi installer for emby)
-I have also tried installing mono of the correct version, locking it and then using the dietpi installer, which doesn't work and breaks mono.
-So my next step was to install using the Debian 8.0 official instructions, which results in this:
```
emby-server : Depends: libembysqlite3-0 but it is not installable
              Depends: embymagick but it is not installable
```
which exists elsewhere on this forum:
https://emby.media/community/index.php?/topic/42011-problems-reinstalling-emby-on-raspberry/
https://emby.media/community/index.php?/topic/19415-debian/page-10#entry390662

and on diet-pi's:
https://github.com/Fourdee/DietPi/issues/1150

I'm pretty sure I've figured out the concept of manually downloading files and installing them with dpkg, but I can't for the life of me figure out how to form the url so I end up with the files I need and no one seems to have written a beginners version of the instructions. If someone could either point out the obvious explanation that I'm missing or write out the links or code I would really appreciate it. 

Just fyi, this was the best I came up with and it had no effect. 
```
wget ftp.de.debian.org/debian/pool/main/libj/libjpeg8/libjpeg-progs_8d-1+deb7u1_armhf.deb
dpkg -i libjpeg-progs_8d-1+deb7u1_armhf.deb.1
```
This appears to be a running issue that has to be re-addressed periodically. Does a note need to be added on the install instructions page that warns of these potentially missing files and points to somewhere with instructions? 

Thanks again, I love it when it works!

**Comment by LukePulverenti** [comment]
Ok, if you look at your x64 instructions and how nice and elegant they are, the good news is that we'll soon have similar for armhf. And once we have that there'll be no more mono runtime at all, and the entire installation will all be self-contained. Hopefully that will be any day now that we'll have that available for testing.

**Comment by DncrJim** [comment]
Fabulous. When the .net core was marked as having gone stable, I assumed that the mono processes that still remained were permanent. Have I made it obvious yet that I don't know what I'm talking about? I presume from your response that I should just abandon this server for a few weeks and then come back once the next round of items have been completed instead of even worrying about this?

**Comment by LukePulverenti** [comment]
Yes you can also try out the Docker image that is available for testing: https://emby.media/community/index.php?/topic/50012-emby-server-for-net-core/

Otherwise apart from that you'll just need to wait for our new arm packages, which should be ready any day now. Thanks.

**Comment by LukePulverenti** [comment]
Now available for testing:
https://emby.media/community/index.php?/topic/50012-emby-server-for-net-core

Thanks !

**Comment by quickmic** [comment]
Same problem here. btw, it's not the mono version.
The date issue comes in my case from invalid data in the "PremiereDate" field in the "TypedBaseItems" table. Here the dataset (unfortunately no header) 

 
"140253"	"}hk*{W�4�? ��"	"MediaBrowser.Controller.Entities.TV.Season"	"NULL"	"���6(\����ſ-~�5"	"/mnt/storage1/series/A/Abalone Wars/S04"	"NULL"	"NULL"	"NULL"	"NULL"	"NULL"	"NULL"	"NULL"	"NULL"	"4"	"0"	"Season 4"	"NULL"	"NULL"	"NULL"	"NULL"	"9999-12-31 23:59:59.9999999Z"	"9999"	"NULL"	"0004"	"NULL"	"NULL"	"NULL"	"2017-01-11 12:53:09Z"	"0001-01-01 00:00:00Z"	"NULL"	"NULL"	"NULL"	"NULL"	"NULL"	"NULL"	"NULL"	"NULL"	"NULL"	"NULL"	"2017-12-28 11:36:16.223718Z"	"2017-12-28 11:36:16.225191Z"	"0"	"NULL"	"NULL"	"NULL"	"NULL"	"NULL"	"1"	"0"	"Series"	"26b6ad4903f9e0463dd97af1324ab8b5"	"NULL"	"NULL"	"season 4"	"36999af65c28adbbb2eac5bf2d7ef235-004"	"NULL"	"NULL"	"NULL"	"NULL"	"0"	"Abalone Wars"	"264436004"	"NULL"	"NULL"	"���6(\����ſ-~�5"	"NULL"	"NULL"	"NULL"	"NULL"	"NULL"	"NULL"	"NULL"	"NULL"	"NULL"	"NULL"	"NULL"	"NULL"	"36999af65c28adbbb2eac5bf2d7ef235"	"NULL"	"NULL"



Check out the "9999-12-31 23:59:59.9999999Z", here is the issue. And it happened when I scanned the lib manually with option "search for missing metadata".

I assume the scanned file was:
'/mnt/storage1/series/A/Abalone Wars/S04/S04E01.mkv'

I try to reproduce the issue and give you an update when I have more information.

**Comment by quickmic** [comment]
Update:
The issue is easy to reproduce and it's not the only file which causes problems.
"Airplane Repo" Season 2 has the same problems.

**Comment by LukePulverenti** [comment]
If you're running pre-release then please make sure to stay on top of the latest versions. thank you for being a part of the testing team.

**Comment by quickmic** [comment]
Sorry, I updated to newest beta and seems good now. The complete scan will take very long, but some of the affected files are already passed. :)

**Comment by quickmic** [comment]
I checked again. The database still has with those weird dates, but seems it not a showstopper for emby.
I don't know what's your approach to fix it. Just ignore invalid entries or fix the dates itself.
/mnt/storage1/series/A/Abalone Wars/S04/season.nfo (DB according to filedata):


[season.nfo.txt](https://github.com/MediaBrowser/Emby/files/1594334/season.nfo.txt)
