### ISSUE TITLE
local devices being limited by optional per-stream bitrate limit for all out of network devices

### ISSUE THREAD

**Issue by hooray4me** [MediaBrowser/Emby#3046]
Devices on the same local network segment are being limited to my 4 mbps setting for out of network devices.
These episodes used to direct stream
![image](https://user-images.githubusercontent.com/12399138/33352150-2b89f700-d46d-11e7-8625-7f0fbf74a343.png)
![image](https://user-images.githubusercontent.com/12399138/33352160-335d90f4-d46d-11e7-8d56-df94f496a0b1.png)
![image](https://user-images.githubusercontent.com/12399138/33352162-36759cc8-d46d-11e7-9bdd-bc5007c3de07.png)

**Comment by hooray4me** [comment]
and in case its relevant, I am using the beta firestick version 1.5.12a

**Comment by LukePulverenti** [comment]
Closing due to abandonment. Please feel free to reopen with the requested information. Thanks.

**Comment by hooray4me** [comment]
I downloaded the server log from yesterday which had a time span of 9am to 5pm... it is over 7GB... I can't even find a client to open the file... I noticed that ALL epg update info is written to this log, which is a lot.
