### ISSUE TITLE
[Bug] Spacebar goes... back?

### ISSUE THREAD

**Issue by BloodyIron** [MediaBrowser/Emby#3052]
Sometimes when I'm watching a video, I press spacebar to pause it and it... goes back in the GUI. As in, it looks a lot like the video quits and goes back to video selection.

However, the GUI only seems to partly draw, so I don't think this is quite the same function being called.

I think this may be due to focus shifting, as I have multiple monitors, and it may be due to mousing away and back to the video.

Also, it seems to happen often when the video is fullscreen, but I'm not entirely sure if this is the only time it happens.

I'm not sure how to reliably reproduce it just yet, but this has been happening for a few weeks now. I'm not sure if a specific version introduced this issue.

Emby version : 3.2.40.0

**Comment by LukePulverenti** [comment]
I'm not able to reproduce this. Are you still seeing this on the latest version of Emby Server? thanks.

**Comment by BloodyIron** [comment]
I'm on 3.2.50.0, and this happens when I'm using a desktop browser to watch stuff. It seems to happen quite frequently really!

**Comment by LukePulverenti** [comment]
I can't reproduce it,  not even if I mash the spacebar repeatedly.

**Comment by BloodyIron** [comment]
I just reproduced it on first try. Steps taken

1. Load a video (in this case "How it's made")
2. Mouse to window on other monitor (switching focus)
3. Mouse back to window running emby
4. Press space to try and pause it, it then immediately takes me back to the media selection window, with some elements missing (only showing Next Up, not Continue Watching, but I have the controls along hte top).

I think this is about focus switching.

**Comment by LukePulverenti** [comment]
if you do this outside of video playback does it navigate backwards?

**Comment by BloodyIron** [comment]
Performing the same steps, except not having a video playing, seems to cause the page to scroll down, and when it hits the bottom, it goes to the "Next Up" section (only showing that).

It looks like they may be related... not sure...

**Comment by Firerouge** [comment]
It actually looks like spacebar maps to whatever the previous button that was clicked in the web ui. 

So if you click the fullscreen button, then press space, it'll exit fullscreen, click space again and it'll go fullscreen again.


To replicate space going back, all you should have to do is click the back button once, then space will continue to go back until you click another button in the UI.

**Comment by BloodyIron** [comment]
But that doesn't explain why pressing space makes me go back, when I had not hit back before hand. I understand what you're referring to here, and I really don't believe that's what's going on here. The previous actions taken don't involve clicking on a back button, they involve playing a video, and maybe hitting fullscreen. So those are the functions that might be called if what I was experiencing, was as you described, but those aren't the functions that are happening when I hit space in these cases.

**Comment by BloodyIron** [comment]
Yeah this is seriously still happening to me almost every time I press space, it just goes "back". It's at the point where I curse myself every time I press space now, because it's like Russian roulette, except almost every chamber has a bullet.

**Comment by LukePulverenti** [comment]
It's natural behavior of the browser to activate a button if the spacebar is pressed while it has focus. So somehow there must be a certain combination of factors causing the back button to gain focus.

**Comment by BloodyIron** [comment]
@LukePulverenti that seems very probable, but I am not yet seeing how, hmmm.

**Comment by LukePulverenti** [comment]
Are you still experiencing this?

**Comment by BloodyIron** [comment]
Occasionally, but I've been playing media mostly through Chromecast anyways, so I haven't tried it a lot in a browser recently.

**Comment by BloodyIron** [comment]
Just happened to me again. Argh! :P

**Comment by LukePulverenti** [comment]
Are you still seeing this?

**Comment by BloodyIron** [comment]
Yeah it still happens. Same as before. I'm not sure what to do about it at this point...

**Comment by BloodyIron** [comment]
Just upgraded the Ubuntu install to 18.04, from 16.04, and this re-did how .NET core is setup, probably for the better. So far, I think spacebar may be working as intended.

But I'm going to test further before I can be sure...

Am I the only one experiencing this?

**Comment by LukePulverenti** [comment]
Thanks for the info.

**Comment by BloodyIron** [comment]
Just upgraded to 3.5.0.0, and pressing space takes me back again. :(

I don't think this is a regression, but it does seem to be present.

That being said, 3.5.0.0 has made moving through the web interface SOOOOOOO much faster now!

**Comment by LukePulverenti** [comment]
It's not that we're going back on space, it's that somehow i think the back button is gaining focus, and as you're aware, clicking space on a focused button will invoke it.

**Comment by LukePulverenti** [comment]
Do you have Emby Premiere?

**Comment by BloodyIron** [comment]
@LukePulverenti I most certainly do! You guys deserve my money, so I give it willing ;)

Why do you ask?

**Comment by LukePulverenti** [comment]
In that case please try this on http://tv.emby.media

See if it happens there. The back button there has set tabindex="-1" to help avoid it being keyboard focused. I can do the same for the web app.

**Comment by BloodyIron** [comment]
@LukePulverenti if you're talking about the EmbyConnect, online SSO/Federated auth, I don't use that. The first reason I use Emby instead of Plex, is because I only want internal auth, not online, for privacy reasons ;)

That is, unless I'm missing the point here?

**Comment by LukePulverenti** [comment]
Please just click the link, thanks.

**Comment by BloodyIron** [comment]
Um, when I click that link and press space, it proceeds to the next steps for setting it up, then generate pin. Is that what you wanted me to test?

I didn't have it connect to my Emby setup, just to be clear on that.

**Comment by LukePulverenti** [comment]
there's a button you can click to manually enter server info.

**Comment by BloodyIron** [comment]
@LukePulverenti I don't think you understand my privacy concerns around doing that. I'm not comfortable doing that.

**Comment by LukePulverenti** [comment]
All connections are direct from your browser to your server.

**Comment by BloodyIron** [comment]
@LukePulverenti I thought this service was a federated/SSO external service provided by the biz behind Emby? If it is _only_ going from my browser, to my server, directly, then I will try it out.

Is there any facet of that tv.emby.media service that ever exits my premises, apart from the initial DNS resolution and page load?

**Comment by LukePulverenti** [comment]
Only Emby Connect, if you use that, and then Emby Premiere validation. That's it.

**Comment by BloodyIron** [comment]
@LukePulverenti thanks for clarifying! :) I appreciate you respectfully working through this with me.

I've tried two videos with tv.emby.media, and it seems that spacebar defaults to the play/pause button thus-far, and does not switch to the back function.

I also want to mention, in my earlier testing when it went "back", the way it went back was wonky. In that, the "back" page only partly loaded, and sometimes elements wouldn't load (like the background might be white sometimes), so I'm not sure if it's using the same function call as the back button itself. Despite the recent observations we've seen.

How many samples do you want me to gather for you?

**Comment by LukePulverenti** [comment]
That's all i need, thanks. Just wanted to confirm that what we already have in Theater will be the solution. Thanks !

**Comment by BloodyIron** [comment]
@LukePulverenti it looks like it!

BTW in Theater it doesn't seem to have music song queue manipulation ;)

Anything else you need from me at this time? Or wait to hear back on your end?

**Comment by LukePulverenti** [comment]
We're good for now, thanks.

**Comment by LukePulverenti** [comment]
Resolved for 3.6. Thanks.

**Comment by BloodyIron** [comment]
@LukePulverenti can't wait ;)
