### ISSUE TITLE
Sample files appear in library after update to 3.2.50.0

### ISSUE THREAD

**Issue by Phanx** [MediaBrowser/Emby#3060]
After updating Emby to version 3.2.50.0, sample video files (with ".sample" in the filename) are now appearing in my libraries. Previously, these files were ignored.

The cause is [this commit](https://github.com/MediaBrowser/Emby/commit/fee256ad18237654dc6e33c4bbc48a92ea7acd8f) with the note "update rules for samples", but it seems to just **remove** the detection rules, not update them. Was there supposed to be more to that commit?

If the removal of sample file detection was really intended, is there some replacement functionality in the works? (I've seen issue #1139 but the last activity there was 2 years ago.) If not, please consider reverting this change. I have hundreds of "sample" files, exactly zero of which I want showing up in Emby.

I already tried reverting to 3.2.40.0, but that caused all of my media to disappear, and I had to upgrade again to see anything (rescanning my libraries didn't fix it) so this doesn't seem like a viable option (I don't want to lose all my metadata, watched status, etc. by starting from scratch).

**Comment by LukePulverenti** [comment]
Hi, can you discuss some examples? thanks.

**Comment by LukePulverenti** [comment]
I'd like to resolve this, so if you can get me some examples that would be great, thanks.

**Comment by Phanx** [comment]
Here are some examples:

- `/media/Movies/Movies/Movie Title (2010)/RELEASEGROUP.TLD.sample.mp4` (1-2 MB)
- `/media/Movies/Movies/Movie Title (2005)/scene-name.sample.mkv` (various sizes)
- `/media/Movies/Movies/Movie Title (2016)/movie.title.sample.mt2s` (4+ GB)

Most of the problem files are in the first format, but I also have some specific scenes cut out as separate files, and a few movies where I have multiple formats but only want one to show up in Emby (I primarily use Emby with my Chromecast, so I don't need it to show formats the Chromecast can't handle when I already have one it can).

If you want an actual file to examine, let me know.

**Comment by LukePulverenti** [comment]
For that first example, can you confirm the file name of the non-sample media? thanks.

**Comment by Phanx** [comment]
That specific one is `Movie.Title.2010.1080p.BluRay.H264.AAC-RELEASEGROUP.mp4` in the same folder; the others are all similar -- in the same folder, movie title in the file name, nothing resembling "sample" in the file name.

**Comment by LukePulverenti** [comment]
Can you give an exact example rather than movie title? i would like to see an exact example of both the original movie file name as well as the sample file name. thanks !

**Comment by Phanx** [comment]
For that one: `Meskada.2010.1080p.BluRay.H264.AAC-RARBG.mp4` vs `RARBG.COM.sample.mp4`. None of the affected movies have the word "sample" in their title or filename.

**Comment by LukePulverenti** [comment]
This is resolved for the next release, thanks.
