### ISSUE TITLE
DLNA problem to launch movie since update to 3.2.50

### ISSUE THREAD

**Issue by Krikroff77** [MediaBrowser/Emby#3067]
Hello,

Since the 3.2.50 update when I launch a movie from a DLNA player it's still the first movie present in the folder that is launched. It worked perfectly in 3.2.40

Tested on 2 servers: WHS2011 and Windows 2012 R2 Standard

_**Edit**: tried with 3.2.50.5 beta with the same results_

Best regards

**Comment by LukePulverenti** [comment]
What dlna player?

**Comment by Krikroff77** [comment]
Hello, dlna player used is a Freebox Player V6
https://emby.media/community/index.php?/topic/41213-dossiers-vides-sur-freebox-player-v6/?p=384400

Edit: tried with 3.2.50.6 beta with the same results

Note: i reinstall servio on one of the servers to test and it works fine

**Comment by Krikroff77** [comment]
Hi,
I just tried with the latest beta (v3.2.50.9) and the result is the same ...
I did some tests to be certain that the problem is from the Emby version:

**Tested with the same DLNA Player (Freebox player) and on the same file tree**

**Test 1** - Emby (WHS2011): Worked before no longer working since 3.2.50
**Test 2** - Emby (Windows Server 2012 R2 STD): Worked before no longer working since 3.2.50
**Test 3** - Plex (ReadyNAS312): Everything works very well
**Test 4** - Serviio (WHS2011): Everything works very well (Note: installed just for testing)

I see the same problem for reading music files too, If I select for example the track 5 of a CD, it is always the first one that is played :(

I know it's typically the kind of complicated problem to reproduce since it's inherently inherent in setup, how can I help you, I like to use Emby and I do not want to use anything else.

Best regards,

**Comment by Krikroff77** [comment]
I confirm, i tested on Xbox one with the default application and there are no problems. It seems there is a regression only with the freeplayer :(

To go deeper: i have also on my WHS2011 one LMS to share music and i can play tracks w/o problems with my freeplayer...

**Comment by LukePulverenti** [comment]
Where can I find this freebox? is it an app or a separate device?

**Comment by Krikroff77** [comment]
Yes it is a separate device, Free SAS is a French ISP who offers to users the freebox player (the most advanced IPTV device w. DLNA player, Blu Ray disc, BT etc. on French ISP market w. 8 Millions subscribers).
https://www.freenews.fr/wp-content/uploads/2014/11/Freebox-R%C3%A9volution.jpg

**Comment by Krikroff77** [comment]
Problem solved with last beta 3.2.70.11. 

Best regards

**Comment by LukePulverenti** [comment]
Thanks for the info !
