### ISSUE TITLE
Need help with Metadata Editing

### ISSUE THREAD

**Issue by CaiB** [MediaBrowser/Emby#3070]
Hello,

I've been trying out Emby for a bit now, even bought the premium version for the live TV functionality, but I haven't been able to get a few things figured out yet, so I thought I'd ask here:

A lot of the time, Emby won't get metadata import 100% right. Sometimes it needs help finding a show, other times it misses a few episodes, and sometimes it labels episodes wrong. This is mostly on much less popular shows, so I don't expect it to get everything.

I can't figure out how to properly edit the metadata myself though. After it's done its best attempt, I'd like to go in and fix everything up to be up to my standards. Here's a few things I need help with:

- How do I add a season? If I set an episode to a season that doesn't exist, that episode just vanishes, never to be seen again.
- How do I remove a season? I had it create an "Unknown" season. I moved the contents to the correct season, and now the "Unknown" one is empty, yet I can't figure out how to get rid of it.
- Is there a way to bulk-edit some fields? I've had instances where it got the season wrong for all episodes, and I couldn't get it to apply the correct number to all of them without me doing it on each one individually.
- If Emby couldn't figure out what a show/season/episode was, but I manually find it on one of the supported metadata sources, how can I get it to grab the info based on that info? I've tried entering the ID in the corresponding field, then clicking "refresh metadata". All that does is get rid of the ID I entered...
- Can I set a library to only use info from a certain metadata source? I've seen poor data several times from some sources, so I'd like to remove that as a potential source for one library, while keeping it in other libraries where it does a good job.

Also,
Are there plans to improve the subtitle handling? Right now, subtitle animations are very choppy, custom fonts don't seem to work, text effects don't appear to work, and updating seems pretty slow. I can post an example if necessary.

Finally,
Is there a good place where I can find info about developing a plugin? I'd like to make one to add a new metadata source specialized towards what I watch, and there currently aren't any plugins that support the site. I'm pretty familiar with C#, I just don't know where to get started working on a plugin for Emby. The wiki here seems really light on info.

**Comment by LukePulverenti** [comment]
HI there. If something is not being recognized, then please discuss an example and attach the information requested in how to report a problem:

https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/

Please check out our TV naming guide:
https://github.com/MediaBrowser/Wiki/wiki/TV%20naming

The easiest way to manage seasons is to use season sub-folders. This is the recommended approach, although we do also support episode files directly under the series folder. Please see the supported naming conventions for files that will allow you to assign season and episode numbers.

You cannot configure a metadata source per each library but this is planned for the future. You can however turn off internet metadata entirely for a library if that's what you'd like to do.

If you're having an issue with subtitle playback, please discuss an example and attach the information requested in how to report a media playback issue:
https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/

Thanks.

**Comment by CaiB** [comment]
Hi Luke,

Thanks for the reply, you've cleared up a few of the questions.

It seems like I was going about it a bit wrong. I'm trying to get Emby to deal with my current library format, and am cleaning up data in Emby afterwards, when I should be standardizing my library first.

I don't think you addressed these though:
- Is there a way to bulk-edit some fields in the metadata manager?
- If Emby couldn't figure out what a show/season/episode was, but I manually find it on one of the supported metadata sources, how can I get it to grab the info based on that info? I've tried entering the ID in the corresponding field, then clicking "refresh metadata". All that does is get rid of the ID I entered...
- Is there a good place where I can find info about developing a plugin? I'd like to make one to add a new metadata source specialized towards what I watch, and there currently aren't any plugins that support the site. I'm pretty familiar with C#, I just don't know where to get started working on a plugin for Emby. The wiki here seems really light on info.

Thanks!

**Comment by Firerouge** [comment]
> Is there a good place where I can find info about developing a plugin?

The wiki has decent documentation on plugin development. Check out the [getting started page](https://github.com/MediaBrowser/Emby/wiki/How-to-build-a-Server-Plugin), and read the rest of the wiki. 

Your C# knowledge won't be of much use, the language used by Emby is .NET and Mono.

**Comment by LukePulverenti** [comment]
Yes @Firerouge answered this pretty well. We'd like to be able to accommodate a mish-mash style folder structure in the future. Thanks !

**Comment by LukePulverenti** [comment]
What kind of plugin are you looking to build?

**Comment by CaiB** [comment]
Hi Luke,

Sorry for the delay, GitHub didn't send me a notification for some reason.

I'm looking into building a plugin that will grab metadata from MyAnimeList.net, as their database is pretty complete and thorough. I also pretty much exclusively use the user ratings on there as reference (currently, a lot of shows/episodes are just 10s from the built in metadata sources, which is kinda useless).

Eventually once I get that working, I also want to extend the plugin to automatically set an episode as watched on my MyAnimeList.net profile when I watch that episode in Emby.

**Comment by LukePulverenti** [comment]
Sounds good. So you just need to setup a plugin skeleton and then add metadata provider implementations just like what you see here:
https://github.com/MediaBrowser/Emby/tree/master/MediaBrowser.Providers/TV/TheTVDB
Thanks.

**Comment by LukePulverenti** [comment]
Closing. Please let us know if you need anything else, thanks.
