### ISSUE TITLE
"Edit subtitles" only with "Allow user to manager server"

### ISSUE THREAD

**Issue by rbrtribeiro** [MediaBrowser/Emby#3071]
Hi,

The listing of multiple subtitle versions is a crucial feature and in Emby is only available by the "Edit subtitles" menu, which is only available to the user with the option "Allow user to manager server" activated.

Is this the expected behaviour? If so, is there any particular reason for that?

Thank you and thanks for all the work done.

**Comment by LukePulverenti** [comment]
Yes currently, it's always possible to change, but behind that menu is the ability to download and delete subtitles so that's why it requires admin rights.

**Comment by rbrtribeiro** [comment]
Thanks for the reply Luke.

Not sure what you mean by "it's always possible to change" but let me try to argue why that is an inhibitor for me and potentially multiple other users. 

Most of the media watched by me and by my media sharing small community is in a foreign language (we are from Portugal), which requires subtitles. Now, as you know, there multiple subtitle versions for the same language for the same media ( and even in that scenario some of them may not be synced which is another issue).

Obviously, I'm not willing to go through my entire media and handpick the correct subtitle version, so my friends need some way to download and select the correct subtitle for the specific media that they are watching. That is possible with that interface, however, I'm not willing to give admin access to all my friends, ergo, unfortunately, this issue becomes an inhibitor for me to use Emby.

With this in mind, my question is how feasible is this change?

**Comment by waldyrious** [comment]
>  it's always possible to change

I'm also confused by this. Could you clarify what you mean?

**Comment by LukePulverenti** [comment]
I just meant that while I was explaining our original thinking, we are open to changing and improving it.

**Comment by waldyrious** [comment]
Thanks for the clarification. I think it would make sense to allow users the permission to edit subtitles without giving them full admin access. Do you have any pointers regarding what would be the right way to implement this feature? If it's not too complex perhaps we could submit a PR :)

**Comment by rbrtribeiro** [comment]
Thanks for the clarification Luke. 

I took a quick look at the code and removed the canEdit blocking var for the Edit subtitles when building the item context menu in itemcontextmenu.js. It works for me but not sure if it's the proper way to it...

Thanks

**Comment by LukePulverenti** [comment]
Well that's actually not good. That should be getting blocked at the api level if the user doesn't have permission. I think a per-library permission might make sense, similar to what we did with the delete permissions.

**Comment by thejacer87** [comment]
just want to put in a plus+ for this feature. i make my wife use her own user so i dont get her "suggested" and "next up"

but for w/e reason not all the shows get the subtitles d/l by the time she watches. so it would be nice for ME if she could download them herself

**Comment by LukePulverenti** [comment]
This will be in Emby Server 3.6. Thanks !

**Comment by ddurdle** [comment]
Is it in the emby 3.6 beta already?

**Comment by LukePulverenti** [comment]
Yes it is, but all of the native apps will require updates to respect the new options. Thanks.
