### ISSUE TITLE
[Bug] VA API transcode without B-frames

### ISSUE THREAD

**Issue by optlink** [MediaBrowser/Emby#3072]
I just added an AMD GPU to my server and wanted to try out video transcoding. Whenever I try it I get this error:
```
...
[libx264 @ 0x56095466b580] using SAR=1/1
[h264_vaapi @ 0x55721c56fde0] B frames are not supported (0x1).
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[libx264 @ 0x56095466b580] using cpu capabilities: MMX2 SSE2Fast LZCNT
Conversion failed!
...
```
and then it seems to fall back to CPU encoding? Adding `-bf 0` to the ffmpeg command in the logs and then running it in the shell seems to work fine. So, is this there anything that can be done about this? The GPU is a Radeon Pro WX 2100 and I'm pretty sure it's based on Polaris which is why B-frame support is missing.

By the way, thank you for your work on this project, I subscribed to Premier just a few weeks ago. It's nice to see an open alternative to Plex.

**Comment by optlink** [comment]
Alright, so Mesa 17.3 seems to have fixed the `-bf 0` requirement for the constrained baseline profile. I figure I can get transcoding working if I patch Emby to use only constrained baseline since attempting to encode higher profiles without B-frames results in garbage. I'm going to start looking here: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Any input would be appreciated.

**Comment by optlink** [comment]
Checking for VAAPI and then adding the baseline profile param around line 700 should do it but I am blocked by #3064.

**Comment by LukePulverenti** [comment]
We'll add -profile:v 578 for the next release, thanks.

**Comment by LukePulverenti** [comment]
Please try release 3.2.60, thanks.

**Comment by optlink** [comment]
@LukePulverenti will do over the weekend, thanks again for your work.

**Comment by LukePulverenti** [comment]
Closing. Please re-open if there's still an issue. Thanks.
