### ISSUE TITLE
[Request] API Endpoint for when music is added for a specific artist

### ISSUE THREAD

**Issue by Qstick** [MediaBrowser/Emby#3079]
Something similar to:

https://github.com/MediaBrowser/Emby/blob/50b88c5ac0e5a633d2d9aa01b446b252a6b0cb10/MediaBrowser.Api/Library/LibraryService.cs#L235-L255

Should accept musicbrainz Id for artist as parameter

**Comment by LukePulverenti** [comment]
Truthfully i don't like the way the current endpoints are done, but i did them the way that the sickbeard developers wanted for tv, and then later movies was done exactly the same way.

What happens if this is music that doesn't exist on musicbrianz, or if for some reason we don't have the musicbrainz id? For this reason I would actually prefer that you instead send the path to actual media file that was updated.

In fact, I would actually like to just redo these endpoints into a single generic one along those same lines. You provide a media path to updated media and also an indication of what action was taken, e.g. file added, updated, deleted, etc.

Will this work?

**Comment by Qstick** [comment]
Works for us. This is sort of how kodi is interfaced, basically we look for a library item with the same path and update it if found, if not found we run a full scan. If you handle that on Emby side... even better.

**Comment by LukePulverenti** [comment]
Ok thanks. I'll get this added soon.

**Comment by LukePulverenti** [comment]
I will try to write some documentation soon but hopefully you can get the gist of it here:
https://github.com/MediaBrowser/Emby/blob/dev/MediaBrowser.Api/Library/LibraryService.cs#L256-L270

The request body will be a json payload with an Updates property, and that property is a list of updates. Each update contains a media path and an UpdateType. Even though we could probably figure out the UpdateType if we wanted to, it should be easy enough for you to supply. Thanks.

**Comment by LukePulverenti** [comment]
This is in the new stable release. Please let me know if there are any issues, thanks.

**Comment by Qstick** [comment]
Thanks @LukePulverenti. will do

**Comment by Qstick** [comment]
@LukePulverenti 

Following up on Github Issue 3079 https://github.com/MediaBrowser/Emby/issues/3079. We are now using `Library/MediaFolders` endpoint to pull the path for the music related collections. We then send that to Emby as a POST using the new `Library/Media/Updated`

My question is how can we tell if this is working? There is no response other than a 204 status code, and I don't see anything start scanning in the server dashboard. Here is relevant log where the request was received and processed:

```
2018-04-02 02:27:25.081 Info HttpServer: HTTP POST http://192.168.1.XXX:8096/mediabrowser/Library/Media/Updated. UserAgent: Lidarr/10.0.0.37729 (windows 10.0.16299.0)
2018-04-02 02:27:25.083 Info HttpServer: HTTP Response 204 to 192.168.1.110. Time: 2ms. http://192.168.1.XXX:8096/mediabrowser/Library/Media/Updated
```
We are sending a JSON array like so:


```
{
"Updates": [{
               "Path":"/config/root/default/Music",
               "UpdateType":"Modified"
       }]
}
```

Should we be using the `Library/PhysicalPaths` endpoint in order to find the correct path to update? If so, how do we know which physical path is mapped to which collection type as the `Library/MediaFolders` endpoint doesn't return the actual physical path (`/mnt/user/Music`) and the PhysicalPaths endpoint doesn't return collection mapping?

**Comment by LukePulverenti** [comment]
Ok, I hadn't thought of that, so let's first take this one step at a time. First I would test this by supplying a path that exactly matches a library folder in Emby library setup. So for example, if you setup a music library with 
\\myserver\share\music
Then you could use the api to notify a song was downloaded to:
\\myserver\share\music\artist\album\song.mp3
(Or whatever the path might be).
Within 1-2 minutes you should see a logging statement that says something like
{Title} (\\myserver\share\music\artist) will be refreshed.

Once you've verified this, then from there we can talk about path mapping. Thanks !

**Comment by Qstick** [comment]
Confirmed that part is working if I pass a known Emby path, I see log entry for `xxx will be refreshed`. I think the mapping is the main issue here, especially between docker containers, etc.

**Comment by LukePulverenti** [comment]
Ok thanks for verifying. If we want to minimize work on your part, then here's what i can do to increase the likelihood that this will work out of box.

When users setup their library folders, they can optionally correlate a shared network folder with the local library folder that they add. This allows the server to use the local folder for internal access, and client apps use the shared network folder. 

What I can do is take the path you supply with the api and try to match it against both. While this won't be bulletproof, it should be sufficient if you add some help text when they setup the notification mechanism. Is this good enough?

If you want it bulletproof, then you might want to support a path substitution mechanism on your side where you can do a string replacement on the path before it gets sent to the emby api. This would allow the user to correlate a path that is configured in your app, with a path that is configured in ours. Let me know what you think. Thanks.
