### ISSUE TITLE
Subtitles in strm files not working anymore

### ISSUE THREAD

**Issue by maximilianh75** [MediaBrowser/Emby#3090]
They are detected but not working in the movie

**Comment by LukePulverenti** [comment]
Hi, I just tested, no problem found. Please discuss an example and attach the information requested in how to report a media playback issue:
https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/

Thanks.

**Comment by maximilianh75** [comment]
I solved. If i deselect the option allow reproduce videos that require conversion without transcode work, for some reason the subtitle works remuxing it with the video and the video continue be direct play

**Comment by LukePulverenti** [comment]
Closing as this was answered in the community. Thanks.
