### ISSUE TITLE
Library Folder missing when renaming Library

### ISSUE THREAD

**Issue by djamp42** [MediaBrowser/Emby#3095]
Steps to recreate.

Create a Library and add 1 folder
Rename Library to new name. (Keep note of original name)
Add a 2nd folder to the library
Now rename the library to the original name.
When you click manage folders, only the original folder will show up. You must rename to something different to see both folders. 

This only appears to happen when you use the original library name.

**Comment by RaymondSchnyder** [comment]
I can confirm this bug. It happens in my setup too.

**Comment by LukePulverenti** [comment]
This is resolved for the next release, thanks.
