### ISSUE TITLE
Music not matching properly

### ISSUE THREAD

**Issue by Duffyx** [MediaBrowser/Emby#3096]
Comming from Plex on FreeBSD I have a nice folder structure/layout for my media files.
However, I have noticed that I have a about 100+ albums not matching/downloading metadata...
Movies and series have no such problems ... why is this? Is the folder structure not utilized properly?

**Comment by LukePulverenti** [comment]
Hi there, welcome. Can you please discuss some examples and attach the information requested in how to report a problem:
https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/

Thanks !

**Comment by Duffyx** [comment]
![capture](https://user-images.githubusercontent.com/32487486/34441198-67aedc4a-ecba-11e7-84c3-8bef7e90e077.PNG)
In the above screenshot you can see that 25 albums out of the first 40 of my collection havent been matched. I'm not exactly sure what logs I should provide... as this occured at the install of emby-server.

My directory structure is as follows:
music/
         artist - album name/
                                         songs.mp3

**Comment by LukePulverenti** [comment]
How are you determining matched? Is that just by the presence of the image?

**Comment by Duffyx** [comment]
Yea, I guess so ... :) Technically this will probably not be correct.

**Comment by LukePulverenti** [comment]
Ok, this actually isn't a matching issue. By default we only use local images in your music folders + embedded images in your audio files. If you want images to be downloaded you'll have to turn on audiodb fetching under Library -> Metadata, and then you'll have to manually refresh your music library.

**Comment by LukePulverenti** [comment]
Hi, has this answered your question?

**Comment by Duffyx** [comment]
I haven't been able to fix this. I turned on every source and "picture" it should and can fetch but its not helping. I did do a refresh metadata on my music library. Any other suggestionns?

**Comment by LukePulverenti** [comment]
Can you discuss a specific example? thanks.

**Comment by Duffyx** [comment]
So I went to Library -> Metadata -> "customize for media type" (selected music artists) -> Toggled all metadata downloaders and image fetchers as well as toggled on all image settings (fetch images).
I did this for music artists, music albums and music videos under the "customize for media type" dropdown menu. Is this not what you meant by enabling audiodb fetching under library -> metadata?

**Comment by LukePulverenti** [comment]
did you click save on all three after making those changes?

**Comment by Duffyx** [comment]
Ok, saved three times just to be sure, settings did get remembered when quiting and logging back in so not sure if that indicates that I specifically saved them. Refreshing library as we speak. Will get back to you. Thanks

**Comment by Duffyx** [comment]
Hmm my music library has finished refreshing and the exact same albums are still not showing the "primary image". In other words it didn't help, same albums as the first screenshot are still "unmatched".

**Comment by LukePulverenti** [comment]
Do they have musicbrainz id's? that is what we use to download from audiodb.

**Comment by Duffyx** [comment]
Where could I check that they contain them or not?

**Comment by LukePulverenti** [comment]
Try using the Identify feature for one of those albums or artists.

**Comment by Duffyx** [comment]
I'll try this when I'm home tonight. Will I have to do this for every album if it works?

**Comment by Duffyx** [comment]
When trying to match on name ABBA, found albums show no image asswel?
![image](https://user-images.githubusercontent.com/32487486/35454387-20cd7352-02ce-11e8-8ff4-f8e146c528a3.png)

**Comment by LukePulverenti** [comment]
That's ok, musicbrainz search does not include images. So did you go through the identification process?

**Comment by Duffyx** [comment]
Yea, I did it for one album and it worked, CFR the EDIT of my previous post.

**Comment by LukePulverenti** [comment]
Ok, now let's look at why this didn't happen automatically. can you pick another artist, and do a manual refresh of that artist. Then please attach the emby server log. thanks !

**Comment by LukePulverenti** [comment]
Did you have a chance to try this?

**Comment by Duffyx** [comment]
[Log.txt](https://github.com/MediaBrowser/Emby/files/1692896/Log.txt)
Ok so, I did a manual refresh of a few artits/albums.
I did manual refreshes of 2-3 albums and 2 music artits who also didn't get matched.
Manual refreshed start here in the log:
2018-02-04 15:18:51.680 Debug App: Running AlbumNfoProvider for /storage/media/music/ABBA - ABBA

**Comment by LukePulverenti** [comment]
Hi, please try the new release of Emby Server and let us know if there is still an issue. Thanks !

**Comment by LukePulverenti** [comment]
I figured out why it was not getting the metadata on the first try, but was succeeding with a refresh. It is resolved for the next release. Thanks.

**Comment by Duffyx** [comment]
I've taken another shot at trying emby.
I'm determined to switch over as support in FBSD is dropping for Plex.
I'm still dealing with this issue and have no clue why its happening with only my music collection.
I have also transitioned to the recommended library directory structure for music to be found on the wiki of Emby. Does emby even look at the directory structure to figure out to what artits an album belongs?
I have no mp3 tags for my songs and my libraries are read/execute only. (altough don't think this is the issue as movies/series don't have this and are also read/execute only).

**Comment by Duffyx** [comment]
Can this ticket be reopened?
