### ISSUE TITLE
Multi version Drop down

### ISSUE THREAD

**Issue by thejacer87** [MediaBrowser/Emby#3106]
very minor thing, but i don't like how the drop down for the version selector uses the entire file name. can get ridiculous with long movie titles:
![image](https://user-images.githubusercontent.com/6412919/34470531-0678cdf2-eee8-11e7-869c-3b5b333206ae.png)

im thinking the dropdown should only display the text used after the ` - ` and "Default" for the one without any modifier

**Comment by LukePulverenti** [comment]
This will be in the next release, thanks.
