### ISSUE TITLE
[REQUEST] Officially link to emby-unlocked

### ISSUE THREAD

**Issue by HaoZeke** [MediaBrowser/Emby#3108]
Hey, as this is technically open sourced but y'all seem to be monetizing this for all it's worth...

You might want to at least link to [emby-unlocked](https://github.com/nvllsvm/emby-unlocked)

**Comment by dcrdev** [comment]
Why would they do this? It's not in there interest to do so...

They have every right to monetise their own software - the GPL even recommends it. The only thing they have to do under the GPL is keep the source code free/public.

**Comment by RaymondSchnyder** [comment]
Is this issue a joke? Holy sh*t. Please stop trolling @HaoZeke

**Comment by HaoZeke** [comment]
@RaymondSchnyder and I see that you are neither :- 
a) A contributer to this project.
b) Someone with anything relevant to my issue.

Perhaps you have mistaken github issues as your favorite forum.

**Comment by LukePulverenti** [comment]
The pre-playback advertisement will be gone in the next release anyway.
