### ISSUE TITLE
[Android, Bug] Audio stutters horribly when "minimized"

### ISSUE THREAD

**Issue by BloodyIron** [MediaBrowser/Emby#3115]
Testing more music on Emby on my Android phone. I play an album, but then I hit home and switch to other stuff, then the sounds starts stuttering horribly...

It fixes after a second or two of switching back to Emby being in focus.

Android 7.1, Samsung Galaxy S4 (Hack the planet!)

**Comment by LukePulverenti** [comment]
Can you please try this version? 
https://emby.media/community/index.php?/topic/53753-emby-for-android-libmpv-testing/
Thanks.

**Comment by BloodyIron** [comment]
Yeah I'll try it out! :D

**Comment by BloodyIron** [comment]
Music playback seems to be stable with this build. Tried to break it a few ways, and it played just fine!

**Comment by LukePulverenti** [comment]
Thanks for the feedback.
