### ISSUE TITLE
[bug] Renaming Library throws errors in server log

### ISSUE THREAD

**Issue by BloodyIron** [MediaBrowser/Emby#3116]
v3.2.60.0 on Ubuntu Linux

Tried to rename a Library from "TV" to "Syndications/TV" and a bunch of errors are thrown.

I am PMing Luke a link to the logs as it contains sensitive information and is a massive log (I'M NOT SANITIZING 19MB OF LOGS).

**Comment by LukePulverenti** [comment]
You're saying you put a slash in the name? If so that's not allowed. We'll have to catch and handle that and show an error message.

**Comment by BloodyIron** [comment]
Yeah I put a slash in the game. What are the acceptable characters?

**Comment by LukePulverenti** [comment]
As of right now pretty basic. Alpha numerics along with some additional characters like dashes, underscores, etc. Basically what would be acceptable in a windows folder name.
