### ISSUE TITLE
[Android, bug] "Play all from here" spins wheels

### ISSUE THREAD

**Issue by BloodyIron** [MediaBrowser/Emby#3119]
Synced an album to my phone (Android 7.1), and when I tell it to "Play all from here", the loading circle just keeps happening non-stop.

Watched the logs, nothing comes up. But since this is intended to be offline, I then realised the logs (server) would be irrelevant.

I'm using the build that Luke pointed me to ( https://emby.media/community/index.php?/topic/53753-emby-for-android-libmpv-testing/ ).

**Comment by LukePulverenti** [comment]
Resolved for next app update, thanks.

**Comment by BloodyIron** [comment]
W00t!
