### ISSUE TITLE
Sync album, doesn't get presented as album, but individual songs

### ISSUE THREAD

**Issue by BloodyIron** [MediaBrowser/Emby#3120]
When I sync an album to my phone, I only see the individual songs, instead of the Album grouping I am used to. This will make it a pain to manage large amounts of music to be synced to my phone.

Android 7.1

**Comment by LukePulverenti** [comment]
Resolved for next release of the app, thanks.

**Comment by BloodyIron** [comment]
Sweet!

**Comment by LukePulverenti** [comment]
Hopefully soon.
