### ISSUE TITLE
Playback fails for MKV files with audio track delay

### ISSUE THREAD

**Issue by schoerg** [MediaBrowser/Emby#3133]
Emby version: 3.2.70.0

I have a mkv file with 3 audiotracks, one of them is delayed by 17 seconds relative to video. This is for lip-sync purposes. 

```
Audio #2
ID                                       : 3
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Mode                                     : 16
Format settings, Endianness              : Big
Codec ID                                 : A_DTS
Duration                                 : 1 h 42 min
Bit rate mode                            : Constant
Bit rate                                 : 1 509 kb/s
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 spf)
Bit depth                                : 16 bits
Compression mode                         : Lossy
Delay relative to video                  : 17 s 163 ms
Stream size                              : 1.08 GiB (7%)
Title                                    : DTS Ger
Language                                 : German
Default                                  : No
Forced                                   : No

```

Trying to play the file results in:

`No compatible streams are currently available. Please try again later or contact your system administrator for details.`

Using the other audio tracks works fine.

Console error with Firefox 57:

```
Requesting url without automatic networking: https://192.168.0.9:8920/emby/Sessions/Playing/Progress
apiclient.js:1:11287
HLS Error: Type: networkError Details: fragLoadError Fatal: false
htmlmediahelper.js:1:4471
hls.js response error code: 500
htmlmediahelper.js:1:4688
playbackmanager playback error type: mediadecodeerror
playbackmanager.js:2:4034
Requesting url without automatic networking: https://192.168.0.9:8920/emby/Sessions/Playing/Stopped
```

Is this a solveable issue? I would like to avoid changing the DTS file.

**Comment by LukePulverenti** [comment]
Hi, can you provide a sample video for testing? thanks.

**Comment by schoerg** [comment]
yes, do you have a server where I could upload it or shall I host it?

**Comment by schoerg** [comment]
@LukePulverenti I sent you a link to the video on emby.media as private message.

**Comment by LukePulverenti** [comment]
Hi, this plays just fine for me in firefox (and chrome). I tested by pre-selecting each of the audio tracks in both browsers. In case it might matter, I'm on firefox 58.

**Comment by schoerg** [comment]
Do you have audio on the german track?

**Comment by LukePulverenti** [comment]
No, I didn't have audio, sorry. So that's the open issue.

**Comment by schoerg** [comment]
I will try some other filesizes again. Maybe the playback issue is only with bigger file sizes.

**Comment by LukePulverenti** [comment]
Do you have microsoft edge to test with? or android chrome on a mobile device? I'm curious if it happens with either of those. Thanks.

**Comment by schoerg** [comment]
playback starts with Edge, but no audio

**Comment by LukePulverenti** [comment]
Ok. I guess we need to see if there's a transcoding adjustment we can make to account for this, maybe by shifting timestamps. I'm not quite sure yet.

**Comment by schoerg** [comment]
Ah I totally forgot about to test with a bigger file and send it to you.

**Comment by LukePulverenti** [comment]
Can you provide a sample again? I think I may have misplaced it. Thanks.

**Comment by LukePulverenti** [comment]
What is your name in the Emby community? I thought you sent the file to me over PM, maybe the link is still valid but i can't find our conversation. Thanks.

**Comment by LukePulverenti** [comment]
I'm happy to look into getting these files to work in all apps, but due to inactivity I'm going to have to close this topic. Please feel free to re-open with the requested information. Thanks.
