### ISSUE TITLE
Hebrew subtitles Punctuation problem in iOS & tvOS.

### ISSUE THREAD

**Issue by BuSHari** [MediaBrowser/Emby#3137]
Hello,

In the Hebrew subtitles the punctuation are displayed reversed, for example:

Hebrew
Correct: ?שלום, מה שלומך
Wrong: שלום, מה שלומך?

English
Correct: Hello, how are you?
Worng: ?Hello, how are

Wrong punctuation location:
![image](https://user-images.githubusercontent.com/1271474/35186213-4e4575be-fe19-11e7-8910-0f96f8568c3d.png)

Correct punctuation location:
![image](https://user-images.githubusercontent.com/1271474/35186220-5889c2a0-fe19-11e7-8cde-aee681e138ac.png)

This issue happens when in external srt files (with and without .heb in the filename) and also in embedded subtitles in mkv file.
When i try to burn the subtitles with the options "Only image" & "All complex" formats the subtitles are out of sync.

All the Hebrew subtitles files are getting fixed by reversing them to RTL to be able to play them in all Players, this is the way to support all players, but only Emby & Plex doesn’t follow that way and i think that for the Hebrew language it tries to reverse it to “fix” the Hebrew RTL problem.

![image](https://user-images.githubusercontent.com/1271474/35186334-16f9e368-fe1b-11e7-85b0-8aff639bf889.png)

Can you please fix that?
I think that you need to add an option to reverse RTL languages that the user can activate, so that we can control when the subtitle file is not reversed.

Thanks,
Idan

**Comment by LukePulverenti** [comment]
Hi there, do they appear correctly in the web app?

**Comment by BuSHari** [comment]
@LukePulverenti yes

**Comment by LukePulverenti** [comment]
Can you please zip up some sample subtitles and attach them here? We will need to test and see if this might be a platform defect. Thanks.

**Comment by BuSHari** [comment]
Here you go...
[Emby Subs.zip](https://github.com/MediaBrowser/Emby/files/1675338/Emby.Subs.zip)

Thank you for your help!

**Comment by LukePulverenti** [comment]
Ok we've tested this and it looks like a platform defect as far as we can tell.

**Comment by BuSHari** [comment]
In the app ‘Infuse’ it’s working fine

**Comment by LukePulverenti** [comment]
That app has it's own embedded video player with custom subtitle rendering i would imagine. We are using the apple video player libraries, and therefore, platform defects become our defects as well.

**Comment by BuSHari** [comment]
ok understood, hope that you can fix it soon...

**Comment by LukePulverenti** [comment]
Hi, if you'd like to join the iOS beta it may be resolved here: https://emby.media/community/index.php?/topic/57242-150-new-video-player/

Thanks.

**Comment by LukePulverenti** [comment]
Resolved for our next app releases with the new video player, thanks.

**Comment by BuSHari** [comment]
Thank you, can you tell me when it will be released?
