### ISSUE TITLE
Unable to run this on docker

### ISSUE THREAD

**Issue by hrshadhin** [MediaBrowser/Emby#3139]
Hi, I'm using ubuntu 16.04 and Docker version 17.12.0-ce, build c97c6d6 and i can't run the container
using this command
`docker run -it --rm -v /usr/local/bin:/target emby/embyserver_netcore instl`
The out put of this command is:
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
ifelse: fatal: unable to exec instl: No such file or directory
[cmd] instl exited 111
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.`

**Comment by LukePulverenti** [comment]
Hi, please try the emby/embyserver docker instead of emby/embyserver_netcore

Let us know if the issue persists. Thanks !

**Comment by hrshadhin** [comment]
Thanks. problem solved. By following docker hub installation instructions. 
`instl` this command causes my posted error messages.
