### ISSUE TITLE
Emby server (Windows) version 3.2.70 Emby.Server.Implementations.dll issue

### ISSUE THREAD

**Issue by matt949** [MediaBrowser/Emby#3141]
I have made some minor changes to the M3U parser that I have been using for a long time. This file in the source has not changed for some time. No other files are changed.

I may not be explaining this very well, but here goes:

Every time there is a new update to the server, I just simply pull the master from here, then recompile with my changes, then replace the "Emby.Server.Implementations.dll" with my recompiled version on my server.  Always worked until recently but not now as of 3.2.70

I can compile it fine, but the compiled "Emby.Server.Implementations.dll" is about 2.7mb (as it has been in previous versions), but the downloaded distribution version (normal or portable) of "Emby.Server.Implementations.dll" is 4.7mb, and if I replace it with my version, the server will not even start. 

Note: Compiling it with the stock code with no changes has this problem too. I've even compiled the entire thing (all projects in the solution) and the result is the same. .NET framework is targetting 4.6.

Is there now something embedded in that DLL that it needs? The version numbers match up (3.2.70). I've tried it with the beta too (3.2.70.3) without success. The only thing I noticed is the distribution version of the file is marked version 1.0 and my compiled one is marked 3.2.70.x

What am I doing wrong? Thank you!

**Comment by LukePulverenti** [comment]
Answered in community, thanks.
