### ISSUE TITLE
Emby v3.2.70.0 (2018/01/18) not recognizing Hauppauge Win TV-HvR2255

### ISSUE THREAD

**Issue by sestahl** [MediaBrowser/Emby#3144]
1) Emby v3.2.70.0 (2018/01/18) is not recognizing Hauppauge Win TV-HVR2255. I am running Windows 10 Pro 64 bit. I would like to run in natively versus Next PVR hoping for better integration. 2)Also, does it support Hauppauge HD PVR which captures via component video and uses ir blaster or USB UIRT?

**Comment by LukePulverenti** [comment]
Hi, can you try going here: http://www.hauppauge.com/site/support/support.html

And installing the latest windows 10 hauppauge software? thanks.

**Comment by sestahl** [comment]
I did install the latest windows drivers for Win TV-HVR2255, Win TV-HVR950Q, and HD PVR Gen 1 and still does not detect when I select haupauge. Do I need to install software other than the drivers?

**Comment by sestahl** [comment]
Hi Luke, so it does see my HD Home Run Prime Tuner but not my Hauppauge Tuners(Win TV-HVR2255, Win TV-HVR955Q, and HD PVR) when I select Hauppauge and click detect tuners. I did insure that the latest Windows 10 Drivers were installed. Also, the tuners are on the same PC as the Emby Server. Any suggestions? Thank You In Advance!

**Comment by LukePulverenti** [comment]
Did you install the WinTV software?

**Comment by LukePulverenti** [comment]
Closing, but please feel free to re-open with the requested information. Thanks.
