### ISSUE TITLE
nothing provides libcurl.so.4(CURL_OPENSSL_3)

### ISSUE THREAD

**Issue by tareefdev** [MediaBrowser/Emby#3145]
I just downloaded the `emby-server-rpm_3.2.70.0_armv7hl.rpm` package on my raspberry pi 3 (which runs with Fedora 27), and when I tried to install it via (sudo dnf install ....) I got this message:

```
Problem: conflicting requests
  - nothing provides libcurl.so.4(CURL_OPENSSL_3) needed by emby-server-3.2.70.0-1.armv7hl
```

**Comment by tareefdev** [comment]
I installed the rpm package with nodeps:
`rpm -ivh --nodeps emby-server-rpm_3.2.70.0_armv7hl.rpm`
 and it works fine.

**Comment by alucryd** [comment]
Apparently the dotnet runtime expects curl to be built with openssl instead of gnutls, and I'm using the latter, I gues that's why it's not happy. I guess I have no choice but to switch to openssl :(

**Comment by tareefdev** [comment]
Thanks! so maybe the library will change in the next version?

**Comment by LukePulverenti** [comment]
Yes, it's already in the beta release if you want to grab that from the website.

**Comment by tareefdev** [comment]
Ok cool... thanks

**Comment by alucryd** [comment]
Had time to try on the rpi 3, building curl against openssl instead of gnutls didn't help. I'll need to look further into it.

**Comment by alucryd** [comment]
Ok, I get it now. The dotnet runtime expects curl abi 3, not abi 4 on armhf. I'll have to either disable versioned symbols, which I'd prefer but expect not to work, or ship a very old curl version, which contains all those nice vulnerabilities: https://curl.haxx.se/docs/vuln-7.15.5.html

**Comment by alucryd** [comment]
Found a better way, rpmbuild can be overriden to ignore certain false positives regarding dependencies. The next beta and stable arm releases will install without complaining about this.

**Comment by tareefdev** [comment]
Do I need to grab the new rpm file every time I want to update emby on my server?

**Comment by alucryd** [comment]
The rpm doesn't come from a repository so you need to download it and install it manually.
