### ISSUE TITLE
Media transcoding

### ISSUE THREAD

**Issue by CordlessWool** [MediaBrowser/Emby#3147]
I tested emby as premium member in december, because of transcoding features, at same time I try plex server for a while. All in all I like emby more, but the transcoding features in plex are much better (as no premium member).

1. When I transcoding movies, there is only one language used and no subtitles. I experiment a little bit with ffmpeg and get it work with all subtitle and languages. 
 Command should be: ffmpeg -i movie.mkv -b:v 1M -maxrate 1M -bufsize 2M -map 0  -c:s dvd_subtitle  test2.mp4

(I did this some month before and write down 4 commands, but I think this one above should be the best one)

2. Transcoded files are saved as an backup to an other folder.... that itself is not the problem, but how to get the transcoded version togetter with the original version? Only way I found, was to include the folder with trancoded files, but then the movies was detected as new movie, so I saw each movie I transcoded twice, but in my mind emby should select the best version on is own needs. Did I miss something in configuration?

**Comment by LukePulverenti** [comment]
Hi, are you asking about the folder sync feature?

**Comment by CordlessWool** [comment]
Yes, it is folder sync and transcoding in once, isn't it?

**Comment by LukePulverenti** [comment]
The next release of Emby Server will expand on these features:
https://emby.media/community/index.php?/topic/58172-33120-convert-media/
Thanks.

**Comment by LukePulverenti** [comment]
Closing. Please feel free to ask additional questions. Thanks.

**Comment by CordlessWool** [comment]
I tried it now, but it still displays two tiles, each for the converted and the original file and the converted version has still only one language
