### ISSUE TITLE
Error initializing output stream 0:0 -

### ISSUE THREAD

**Issue by scanbiz** [MediaBrowser/Emby#3150]
Hi.
I'm having issues with transcoding. Can someone please help me? Here is the log:

2018-02-02 08:21:43.282
Application version: 3.2.70.0

http://192.168.1.118:8096/emby/videos/9dc6c00949a61ea1d4d5b9001060ecc2/hls1/main/13.ts?DeviceId=5D12E05A-E722-4122-9DD5-47DED62BD825&MediaSourceId=9dc6c00949a61ea1d4d5b9001060ecc2&VideoCodec=h264&AudioCodec=mp3,aac&AudioStreamIndex=1&VideoBitrate=139872000&AudioBitrate=128000&PlaySessionId=3faccbff30be42a2957ad86a921b543b&api_key=052ec6adde1946b7aad2c3490a7b136c&CopyTimestamps=false&TranscodingMaxAudioChannels=2&EnableSubtitlesInManifest=false&Tag=9b9bc5b9a8ac88ba00ae62017180f47b&RequireAvc=true&RequireNonAnamorphic=false&SegmentContainer=ts&MinSegments=2&BreakOnNonKeyFrames=True&TranscodeReasons=ContainerNotSupported,VideoCodecNotSupported,AudioCodecNotSupported&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&h264-deinterlace=true

{"Protocol":"File","Id":"9dc6c00949a61ea1d4d5b9001060ecc2","Path":"/media/lager01/Film/test.movie/test.movie.avi","Type":"Default","Container":"avi","Name":"test.movie.avi","IsRemote":false,"ETag":"9b9bc5b9a8ac88ba00ae62017180f47b","RunTimeTicks":69690728448,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":true,"VideoType":"VideoFile","MediaStreams":[{"Codec":"mpeg4","CodecTag":"XVID","TimeBase":"1000/29747","CodecTimeBase":"1000/29747","DisplayTitle":"480P MPEG4","IsInterlaced":false,"BitRate":1564559,"RefFrames":1,"IsDefault":false,"IsForced":false,"Height":400,"Width":720,"AverageFrameRate":29.747,"RealFrameRate":29.747,"Profile":"Advanced Simple Profile","Type":"Video","AspectRatio":"16:9","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p","Level":5,"IsAnamorphic":false},{"Codec":"ac3","TimeBase":"4/125","CodecTimeBase":"1/48000","DisplayTitle":"Dolby Digital stereo","IsInterlaced":false,"ChannelLayout":"stereo","BitRate":128000,"Channels":2,"SampleRate":48000,"IsDefault":false,"IsForced":false,"Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0,"IsAnamorphic":false}],"Formats":[],"Bitrate":1704141,"RequiredHttpHeaders":{}}

User policy for Christian: EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True

/opt/emby-server/bin/ffmpeg -ss 00:00:39.000 -i file:"/media/lager01/Film/test.movie/test.movie.avi" -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -vf "scale=trunc(min(max(iw\,ih*dar)\,1280)/2)*2:trunc(ow/dar/2)*2" -pix_fmt yuv420p -preset veryfast -crf 23 -maxrate 3911398 -bufsize 7822796 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames "expr:if(isnan(prev_forced_t),eq(t,t),gte(t,prev_forced_t+3))" -copyts -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 128000  -f segment -max_delay 5000000 -avoid_negative_ts disabled -map_metadata -1 -map_chapters -1 -start_at_zero -segment_time 3 -segment_time_delta -39 -individual_header_trailer 0 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 13 -segment_list "/media/lager01/cache/transcoding-temp/5a8ea0e1310b9bc39cddfbafabb7fd61.m3u8" -y "/media/lager01/cache/transcoding-temp/5a8ea0e1310b9bc39cddfbafabb7fd61%d.ts"

ffmpeg version 3.4.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.0 (crosstool-NG crosstool-ng-1.23.0)
  configuration: --enable-cross-compile --cross-prefix=x86_64-pc-linux-gnu- --arch=x86_64 --target-os=linux --prefix=/srv/buildbot/x64/ffmpeg-x64/staging --pkg-config=pkg-config --disable-static --disable-cuda --disable-cuvid --disable-iconv --disable-nvenc --disable-doc --disable-ffplay --disable-ffserver --disable-xlib --enable-shared --enable-fontconfig --enable-gnutls --enable-gpl --enable-libass --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libsmbclient --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libx264 --enable-libzvbi --enable-vaapi --enable-version3 --extra-libs='-laddns-samba4 -lasn1util-samba4 -lauthkrb5-samba4 -lCHARSET3-samba4 -lcliauth-samba4 -lcli-cldap-samba4 -lcli-ldap-common-samba4 -lcli-nbt-samba4 -lcli-smb-common-samba4 -lcom_err -lcommon-auth-samba4 -ldbwrap-samba4 -ldcerpc-binding -ldcerpc-samba-samba4 -ldl -ldrm -lexpat -lflag-mapping-samba4 -lfreetype -lfribidi -lfontconfig -lgenrand-samba4 -lgensec-samba4 -lgmp -lgse-samba4 -lgssapi_krb5 -lhogweed -llibcli-lsa3-samba4 -llibsmb-samba4 -linterfaces-samba4 -liov-buf-samba4 -lk5crypto -lkrb5 -lkrb5samba-samba4 -lkrb5support -lldb -lldbsamba-samba4 -lmessages-dgm-samba4 -lmessages-util-samba4 -lmsghdr-samba4 -lmsrpc3-samba4 -lndr -lndr-krb5pac -lndr-nbt -lndr-samba-samba4 -lndr-standard -lnettle -lpng -lreplace-samba4 -lsamba-cluster-support-samba4 -lsamba-credentials -lsamba-debug-samba4 -lsamba-errors -lsamba-hostconfig -lsamba-modules-samba4 -lsamba-security-samba4 -lsamba-sockets-samba4 -lsamba-util -lsamba3-util-samba4 -lsamdb -lsamdb-common-samba4 -lsecrets3-samba4 -lserver-id-db-samba4 -lserver-role-samba4 -lsmbconf -lsmbd-shim-samba4 -lsmb-transport-samba4 -lsocket-blocking-samba4 -lsys-rw-samba4 -ltalloc -ltalloc-report-samba4 -ltdb -ltdb-wrap-samba4 -ltevent -ltevent-util -ltime-basic-samba4 -lutil-cmdline-samba4 -lutil-reg-samba4 -lutil-setid-samba4 -lutil-tdb-samba4 -lwbclient -lwinbind-client-samba4'
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, avi, from 'file:/media/lager01/Film/test.movie/test.movie.avi':
  Duration: 01:56:09.07, start: 0.000000, bitrate: 1704 kb/s
    Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 720x400 [SAR 1:1 DAR 9:5], 1564 kb/s, 29.75 fps, 29.75 tbr, 29.75 tbn, 29.75 tbc
    Stream #0:1: Audio: ac3 ([0] [0][0] / 0x2000), 48000 Hz, stereo, fltp, 128 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg4 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (ac3 (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
[mpeg4 @ 0x1c14aa0] Video uses a non-standard and wasteful way to store B-frames ('packed B-frames'). Consider using the mpeg4_unpack_bframes bitstream filter without encoding but stream copy to fix it.
[libx264 @ 0x1c0abe0] using SAR=1/1
[libx264 @ 0x1c0abe0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x1c0abe0] profile Main, level 4.1
[libx264 @ 0x1c0abe0] 264 - core 152 r2851+3 e9a5903 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=1 ref=1 deblock=1:0:0 analyse=0x1:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=4 chroma_me=0 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=10 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 vbv_maxrate=3911 vbv_bufsize=7822 crf_max=0.0 nal_hrd=none filler=0 ip_ratio=1.40 aq=1:1.00
[segment @ 0x1bea780] Opening '/media/lager01/cache/transcoding-temp/5a8ea0e1310b9bc39cddfbafabb7fd6113.ts' for writing
[segment @ 0x1bea780] Failed to open segment '/media/lager01/cache/transcoding-temp/5a8ea0e1310b9bc39cddfbafabb7fd6113.ts'
Could not write header for output file #0 (incorrect codec parameters ?): Permission denied
Error initializing output stream 0:0 -- 
[libmp3lame @ 0x1c0c080] 4 frames left in the queue on closing
Conversion failed!
ffmpeg version 3.4.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.0 (crosstool-NG crosstool-ng-1.23.0)
  configuration: --enable-cross-compile --cross-prefix=x86_64-pc-linux-gnu- --arch=x86_64 --target-os=linux --prefix=/srv/buildbot/x64/ffmpeg-x64/staging --pkg-config=pkg-config --disable-static --disable-cuda --disable-cuvid --disable-iconv --disable-nvenc --disable-doc --disable-ffplay --disable-ffserver --disable-xlib --enable-shared --enable-fontconfig --enable-gnutls --enable-gpl --enable-libass --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libsmbclient --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libx264 --enable-libzvbi --enable-vaapi --enable-version3 --extra-libs='-laddns-samba4 -lasn1util-samba4 -lauthkrb5-samba4 -lCHARSET3-samba4 -lcliauth-samba4 -lcli-cldap-samba4 -lcli-ldap-common-samba4 -lcli-nbt-samba4 -lcli-smb-common-samba4 -lcom_err -lcommon-auth-samba4 -ldbwrap-samba4 -ldcerpc-binding -ldcerpc-samba-samba4 -ldl -ldrm -lexpat -lflag-mapping-samba4 -lfreetype -lfribidi -lfontconfig -lgenrand-samba4 -lgensec-samba4 -lgmp -lgse-samba4 -lgssapi_krb5 -lhogweed -llibcli-lsa3-samba4 -llibsmb-samba4 -linterfaces-samba4 -liov-buf-samba4 -lk5crypto -lkrb5 -lkrb5samba-samba4 -lkrb5support -lldb -lldbsamba-samba4 -lmessages-dgm-samba4 -lmessages-util-samba4 -lmsghdr-samba4 -lmsrpc3-samba4 -lndr -lndr-krb5pac -lndr-nbt -lndr-samba-samba4 -lndr-standard -lnettle -lpng -lreplace-samba4 -lsamba-cluster-support-samba4 -lsamba-credentials -lsamba-debug-samba4 -lsamba-errors -lsamba-hostconfig -lsamba-modules-samba4 -lsamba-security-samba4 -lsamba-sockets-samba4 -lsamba-util -lsamba3-util-samba4 -lsamdb -lsamdb-common-samba4 -lsecrets3-samba4 -lserver-id-db-samba4 -lserver-role-samba4 -lsmbconf -lsmbd-shim-samba4 -lsmb-transport-samba4 -lsocket-blocking-samba4 -lsys-rw-samba4 -ltalloc -ltalloc-report-samba4 -ltdb -ltdb-wrap-samba4 -ltevent -ltevent-util -ltime-basic-samba4 -lutil-cmdline-samba4 -lutil-reg-samba4 -lutil-setid-samba4 -lutil-tdb-samba4 -lwbclient -lwinbind-client-samba4'
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, avi, from 'file:/media/lager01/Film/test.movie/test.movie.avi':
  Duration: 01:56:09.07, start: 0.000000, bitrate: 1704 kb/s
    Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 720x400 [SAR 1:1 DAR 9:5], 1564 kb/s, 29.75 fps, 29.75 tbr, 29.75 tbn, 29.75 tbc
    Stream #0:1: Audio: ac3 ([0] [0][0] / 0x2000), 48000 Hz, stereo, fltp, 128 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg4 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (ac3 (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
[mpeg4 @ 0x2406aa0] Video uses a non-standard and wasteful way to store B-frames ('packed B-frames'). Consider using the mpeg4_unpack_bframes bitstream filter without encoding but stream copy to fix it.
[libx264 @ 0x23fcbe0] using SAR=1/1
[libx264 @ 0x23fcbe0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x23fcbe0] profile Main, level 4.1
[libx264 @ 0x23fcbe0] 264 - core 152 r2851+3 e9a5903 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=1 ref=1 deblock=1:0:0 analyse=0x1:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=4 chroma_me=0 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=10 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 vbv_maxrate=3911 vbv_bufsize=7822 crf_max=0.0 nal_hrd=none filler=0 ip_ratio=1.40 aq=1:1.00
[segment @ 0x23dc780] Opening '/media/lager01/cache/transcoding-temp/5a8ea0e1310b9bc39cddfbafabb7fd6113.ts' for writing
[segment @ 0x23dc780] Failed to open segment '/media/lager01/cache/transcoding-temp/5a8ea0e1310b9bc39cddfbafabb7fd6113.ts'
Could not write header for output file #0 (incorrect codec parameters ?): Permission denied
Error initializing output stream 0:0 -- 
[libmp3lame @ 0x23fe080] 4 frames left in the queue on closing
Conversion failed!

**Comment by LukePulverenti** [comment]
Hi, did you customize the server's transcoding temporary folder?

**Comment by LukePulverenti** [comment]
Hi, any news? Thanks.

**Comment by LukePulverenti** [comment]
Closing due to abandonment, but please feel free to provide the requested information and re-open. Thanks.
