### ISSUE TITLE
Allow overriding remote wan address

### ISSUE THREAD

**Issue by danpowell88** [MediaBrowser/Emby#3153]
Currently I'm using nginx to forward https traffic to emby over http

```
    location /emby {
        rewrite /emby/(.*) /$1 break;
        proxy_pass http://192.168.1.1:8096;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $remote_addr;
        proxy_set_header X-Forwarded-Protocol $scheme;
        auth_basic "Restricted";

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";		
    }
```

This works great in web browsers but I cannot get any of the mobile clients to connect.

I've tried setting 
```
<EnableHttps>true</EnableHttps>
<IsBehindProxy>true</IsBehindProxy>
<WanDdns>home.mydomain.net/emby</WanDdns>
<PublicPort>80</PublicPort>
<PublicHttpsPort>443</PublicHttpsPort>
<HttpServerPortNumber>8096</HttpServerPortNumber>
<HttpsPortNumber>8920</HttpsPortNumber>
<RequireHttps>false</RequireHttps>

```
but this ends up setting my remote wan address to https://home.mydomain.net/emby:443

Is it possible to allow the external domain to either 

- completly override the address if provided
- parse the entered domain and determine the host and rebulid with the port at the correct part (would think .nets URI class should handle that pretty easily)
- allow a custom field for the base subdirectory when a wan dns is supplied

I can't do anything with the rest of the domain as its already being used by other services so I'm stuck with subfolders for my applications so it'd be great if something here could be supported.

**Comment by danpowell88** [comment]
I could probably create a PR for the 2nd option if someone can point me in the direction of the code that determines that part

**Comment by anoma** [comment]
Can we extend this ticket to allow defining a different or extra internal address please. When using docker in bridged mode the internal IP is shown as 172.*.*.* whilst the clients see the docker host private IP instead which by definition is a different subnet.

**Comment by smoebody** [comment]
@anoma until this is addressed you can use this workaround:
In *Expoert->Advanced->Bind to local network address* you can insert the IP of your Docker-Host. Next you have to bind the http-port e.g. `-p 8096:8096`. This changes the LAN access url to <Docker-Host-IP>:8096 and should therefore be accessable by Chromecast. It doesn't matter to emby that the IP is not available on any interface within the container. It just binds to the available. But the provided IP is used to publish the LAN address to chromecast and other clients i guess.

**Comment by LukePulverenti** [comment]
HI, just use this as your wan address in settings
home.mydomain.net

You don't need to add /emby, the apps will handle that automatically.

**Comment by nomandera** [comment]
I dont profess to fully understand Emby setup in every detail but most home routers dont support split horizon DNS so if you use your WAN DNS address it will resolve to a public IP and not the private one.

Best case scenario this causes all traffic to route into and out of the edge firewall but more likely it just wont work.

I have a working setup here so I dont need support but I would suggest that these settings, especially for new docker users, would benefit for a deeper review, clarification and perhaps simplification.

**Comment by LukePulverenti** [comment]
The answer to the original question here is remove the /emby from the wanddns field as that should be a domain name only. We'll look into adding validation for this in the UI. Thanks.
