### ISSUE TITLE
[Feature request] Whitelist tags in Parental Controls

### ISSUE THREAD

**Issue by Deinara** [MediaBrowser/Emby#3156]
The 'Parental Control' section of the user administration page currently has an option to blacklist all movies with certain tags. I would like to also have an option to only whitelist certain tags. This way, I can create a tag 'parents' for example, so they only see the few movies they are interested in. 
I know I could create a separate library for them, but that would mean that a few of my movies would be in a different library, which isn't ideal.

It's been asked on the forums already:
https://emby.media/community/index.php?/topic/16938-only-allow-certain-tag-feature/
https://emby.media/community/index.php?/topic/25721-parental-controls-tag-whitelist/
https://emby.media/community/index.php?/topic/51529-parental-control-tag-whitelist/

**Comment by LukePulverenti** [comment]
This will be in Emby Server 4.2:

https://emby.media/community/index.php?/topic/72742-4200-restrict-by-tags/

Thanks.
