### ISSUE TITLE
[Feature Request] A simple file browser

### ISSUE THREAD

**Issue by RUSshy** [MediaBrowser/Emby#3159]
Hi,

I don't care about the collections stuff, i have mixed content in my drive, i want to be able to watch what i want without having to browse 4545 different menus

Please give us a simple file browser that list files/folders in a list

Is it that hard to implement ? 

Why all these applications can't provide that simple feature, world of UX is fucked up c'mon

**Comment by RUSshy** [comment]
i have to select a folder to know the name, this is so fucking horible UX experience

GIVE SIMPLE LIST VIEW OMG

**Comment by nicolahinssen** [comment]
Damn dude, show a little respect to the devs.

**Comment by LukePulverenti** [comment]
Closing due to profanity. Please feel free to edit your postings to be a little more civil and polite, and then you can re-open the issue. Thanks.

**Comment by RUSshy** [comment]
ok i was a bit rude, sorry about it, but it was last night i installed on android tv and got mad coz i manage my movies in folders, and emby listed anything like netflix wich sucks
