### ISSUE TITLE
Emby connecting to mb3admin.com continouslty until it crash

### ISSUE THREAD

**Issue by shyne99** [MediaBrowser/Emby#3161]
Hello,
I've noticed that I have to run restart emby every day because it crashed. After looking at the logs, I see that it is spamming mb3admin.com address, like trying to connect to it and posting data 10 times per seconds !!! This behaviour result in my server being freaking slow, and also in emby being very unstable as it crash on its own after a while ( a couple of hours after startup). I only use the web app as a client. 

System : Debain 9 64 bit
Emby-server : 3.2.70.0 installed via the deb file you provide.
I also disabled ipv6 on this server, but i checked using wireshark and it try to connect to the ipv4 of the mothership, so I don't think it is related. 

See the pastebin of the last logs : https://pastebin.com/raw/pmuJYYqi

Thank you.

**Comment by LukePulverenti** [comment]
Resolved for next release, thanks.

**Comment by rofrantz** [comment]
Thanks for "fixing" it @LukePulverenti. Would u mind sharing the kind of data u transpired to that server ?

**Comment by shyne99** [comment]
Thank you for the prompt reply. Do you have an ETA on when does this release will be available ? Or point me to the commit that resolved this issue and I'll apply the patch myself (as I already tried few things that I thought were responsible of this, so I have everything set up to recompile this). 

@rofrantz  as I understand, the data sent out are here to check if the server is "rmby premiere capable", and activate more features if so, like DVR and other things.

**Comment by LukePulverenti** [comment]
It's isolated to the trailer plugin. you can just uninstall that for now.
