### ISSUE TITLE
Zero size folders ignored

### ISSUE THREAD

**Issue by designgears** [MediaBrowser/Emby#3163]
Folders with a size of 0 seem to be ignored, I use plexdrive to mount my google drive to a folder and emby can't see any of it. If I mirror the directory structure to another folder and use unionfs to merge them I can get emby to see and play everything and the only difference I can see is the folder size going from 0 to 4096.

I initially thought it was permissions issue, but after discovering that little workaround that doesn't make sense.

**Comment by LukePulverenti** [comment]
Hi, this isn't true. We don't ignore these. There must be another explanation.

**Comment by designgears** [comment]
Is there any data I can grab that might help with why emby can't see the files in that mount?

**Comment by designgears** [comment]
Closing this, it looks like the project I started helping with was using and older version of plexdrive... all sorted out now, sorry for wasting your time.

**Comment by LukePulverenti** [comment]
No problem, glad you sorted it out.
