### ISSUE TITLE
Snap Support

### ISSUE THREAD

**Issue by BearzRobotics** [MediaBrowser/Emby#3167]
I was wondering if there are any plans to support Ubuntu's snap packaging system?

**Comment by LukePulverenti** [comment]
Hi, it's possible for the future but we already have a Docker image. Have you tried that?

**Comment by jaredallard** [comment]
@BearzRobotics Interested in what you're using snap for? Is this a server setup for something like enabling kubernetes on Ubuntu Server? (Haven't heard of snap being used for anything other than conjure-up to be honest...)

**Comment by BearzRobotics** [comment]
I'm on solus and didn't want to compile from source. I got the docker image to work so I guess I don't need the snap. 

As far as in general, i use snaps for brave, freecad, Plex (had a snap so setting up on solus was a breeze). As far as emby goes I'll be using the docker image for now, but to be honest the reason I wanted the snap was easy setup for a home server.

**Comment by ABotelho23** [comment]
I'm also in support of this.

It would also solve hosting, dependency, and updating issues the Linux builds are currently facing.

**Comment by LukePulverenti** [comment]
What dependency issues? Our new linux packages have no external dependencies that are required.

**Comment by szaimen** [comment]
+1 for snap support

**Comment by LukePulverenti** [comment]
Emby Server Snap packages now available for testing:
https://emby.media/community/index.php?/topic/83274-emby-server-snap-packages/
Thanks !
