### ISSUE TITLE
Unable to disable DNLA

### ISSUE THREAD

**Issue by quentinus95** [MediaBrowser/Emby#3173]
I'm facing the exact same issue as in https://github.com/MediaBrowser/Emby/issues/1578 with v. 3.3.0.0.

**Comment by LukePulverenti** [comment]
Why do you feel that you can't disable DLNA?

**Comment by LukePulverenti** [comment]
Just to clarify, you can disable all of the DLNA features, but since there are other components that depend on network device discovery, there is currently no setting to disable that.

**Comment by quentinus95** [comment]
I would like to be able to disable Emby sending SSDP packets every X seconds to the whole subnet.

**Comment by LukePulverenti** [comment]
Ok, what we can do for the next release is delay starting the device discovery component until another part of the server requests it. This way if you disable both dlna as well as the automatic port mapper, then it will never be requested.

**Comment by LukePulverenti** [comment]
Added for next release, already in the beta. Thanks.

**Comment by quentinus95** [comment]
Thanks a lot !
