### ISSUE TITLE
alexa skill can't recognize word emby

### ISSUE THREAD

**Issue by mark-hahn** [MediaBrowser/Emby#3178]
I really really want to use the amazon alexa emby skill to control emby with my voice.  I find it unusable because the word "emby"  is too hard for alexa to hear.  I did the suggested voice training and now it never understands it.  Before it would work about half the time.

Please please change the word.

**Comment by LukePulverenti** [comment]
Are you still having trouble with this?

**Comment by mark-hahn** [comment]
I gave up some time ago and returned alexa and google.   I had to return
them before the time ran out.  I was also not impressed with the overall
functionality.  Using old fashioned smart phones are fine for me.  My phone
is always close.

**Comment by LukePulverenti** [comment]
https://emby.media/community/index.php?/topic/59558-beta-amazon-alexa/
