### ISSUE TITLE
Offline Sync for external subtitles.

### ISSUE THREAD

**Issue by DisasteR** [MediaBrowser/Emby#3182]
New External subtitles are not synced to device when device has already synced video file.

**Comment by gerrit507** [comment]
Can you please provide more details? What do you mean by device, a device running an emby app or the emby server?

**Comment by DisasteR** [comment]
by device i mean my phone running emby app.
got some show configured for offline sync. when new ep arrive it is synced on my phone.
if the show already have subs when the sync start they are synced a the same time but if the sub comme later it is never synced.

issue seams to be old regarding forum posts
https://emby.media/community/index.php?/topic/44874-subtitles-w-synced-movie-copies/

didn't found it here on github so created this issue.

**Comment by LukePulverenti** [comment]
This is resolved for the next update to the app. Thanks.
