### ISSUE TITLE
"ERR_EMPTY_RESPONSE" with new Emby 3.3.1.0 install on QNAP

### ISSUE THREAD

**Issue by AlexMihe** [MediaBrowser/Emby#3192]
Hello,

I used to have Emby installed from the "QNAP Club" repo. But I wanted to install the package downloaded directly from Emby Github.

I have backed-up, then uninstall the old Emby package from my qnap. I then installed the new package from Github and fowarded the 8920 port.
But when trying to open the page I get the error "ERR_EMPTY_RESPONSE", tried from different browsers, tried directly from the IP of my QNAP, but still the same issue.

Would anyone have an idea of the problem ?

Thank you !!! :-)

**Comment by LukePulverenti** [comment]
Hi, what you should do is first visit the plain http page using port 8096. From there you can setup SSL support which will allow you to use port 8920. Thanks.

**Comment by LukePulverenti** [comment]
Hi, did this help?

**Comment by AlexMihe** [comment]
Hello, yes it does work ! Thank you so much :-)
