### ISSUE TITLE
Ambiguous Binaries

### ISSUE THREAD

**Issue by nvllsvm** [MediaBrowser/Emby#3195]
Why does the main repo have blobs? Are they GPL2 or proprietary?
- Emby.Naming.dll
- Emby.Server.CinemaMode.dll
- Emby.Server.Connect.dll
- Emby.Server.MediaEncoding.dll
- Emby.Server.Sync.dll

The files I am referring to are in this location in the Emby repo: https://github.com/MediaBrowser/Emby/tree/master/ThirdParty/emby

**Comment by LukePulverenti** [comment]
These assemblies are proprietary. Well, except for Naming. It's mostly just added that way out of convenience.

**Comment by nvllsvm** [comment]
Thanks for a prompt and clear response. I honestly really appreciate it (no sarcasm).
