### ISSUE TITLE
Some music folders containing nested folders are erroneosly considered as albums

### ISSUE THREAD

**Issue by dbogdanov** [MediaBrowser/Emby#3199]
Indexing my library by Emby,  some folders that contain inner album folders are themselves considered as albums.

For example: 
```
ls -lh /mnt/home/dbogdanov/_music/_music/_lib/_releases/_drum\ \&\ bass\,\ jungle/
total 60M
drwxrwxrwx 1 dbogdanov dbogdanov 4,0K jul 13  2015 4hero - Parallel Universe [RIVET CD 004] (1995, Reinforced Records)
drwxrwxrwx 1 dbogdanov dbogdanov 4,0K abr 24  2016 4 Hero - Two Pages (1998, Talkin' Loud) [568 879-1] #vinyl-24-96
drwxrwxrwx 1 dbogdanov dbogdanov 4,0K jul 16  2011 Adam F - Colours [7243 8 21725 2 9, 821 7252] (1997, Positiva, Positiva)
drwxrwxrwx 1 dbogdanov dbogdanov 4,0K jul 14  2015 Andy C - Drum & Bass Arena [REACT CD 201] (2001, React)
drwxrwxrwx 1 dbogdanov dbogdanov 4,0K ago 21  2011 Art of Noise - The Drum and Bass Collection [77056] (1996, Discovery Records)
drwxrwxrwx 1 dbogdanov dbogdanov 4,0K jul 14  2015 Bad Company UK - Inside the Machine [VDBCRCD 001] (2000, BC Recordings)
...
```

The ```_drum\ \&\ bass\,\ jungle/``` folder is considered as an album containing all tracks in its nested folders. It is furthermore recognized as one of the albums in its sub-folders ("4hero - Parallel Universe").

I attach screenshots demonstrating the error:

![example_1](https://user-images.githubusercontent.com/409668/37351324-1c0a0c3c-26db-11e8-80d5-6307dbe5edd0.png)
![example_2](https://user-images.githubusercontent.com/409668/37351330-1efbfc7a-26db-11e8-8234-39271240d169.png)

**Comment by LukePulverenti** [comment]
Hi, thanks for this investigation. We currently require some folder structure but this is something we plant o remedy and move to a media-driven model that will accommodate any folder structure.

I've created a new ticket to track this and I'll merge this into that:
https://github.com/MediaBrowser/Emby/issues/3207

Thanks.
