### ISSUE TITLE
Add an option to use images found within music album folders as coverart

### ISSUE THREAD

**Issue by dbogdanov** [MediaBrowser/Emby#3200]
It will be beneficial to add an option to use images found inside album folders as album coverart. This is especially useful for music albums for which no coverart could be retrieved from online providers.

**Comment by LukePulverenti** [comment]
Hi, we should already be doing this. In fact, the local images are given priority over internet images. How are your images named?

**Comment by dbogdanov** [comment]
Oh, that's great. What are the expected image filenames?

I do not have a consistent naming. Some images are downloaded from Discogs with the naming as on their web. Those aren't picked up. I'll post examples later tonight.

**Comment by LukePulverenti** [comment]
A few are supported. They are listed in our music wiki:
https://github.com/MediaBrowser/Wiki/wiki/Music%20naming

folder.ext is the most common.

**Comment by dbogdanov** [comment]
Thank you. In the case of different naming of images, what about having an option to use whatever image found first in a folder as Primary? Preference could be given to square images as they would look better.

**Comment by LukePulverenti** [comment]
Just curious, what are your file names?

**Comment by dbogdanov** [comment]
Here is an example of a folder with no images being retrieved:

```
-rwxrwxrwx  1 dbogdanov  staff   5,6M 18 dic  2015 01 Elevator.mp3
-rwxrwxrwx  1 dbogdanov  staff    10M 18 dic  2015 02 Gonadotropic Synthesis.mp3
-rwxrwxrwx  1 dbogdanov  staff   6,9M 18 dic  2015 03 Subway 49.mp3
-rwxrwxrwx  1 dbogdanov  staff   6,4M 18 dic  2015 04 Communication Off.mp3
-rwxrwxrwx  1 dbogdanov  staff   7,4M 18 dic  2015 05 Approach On Tokyo.mp3
-rwxrwxrwx  1 dbogdanov  staff   8,3M 18 dic  2015 06 Digital Delight.mp3
-rwxrwxrwx  1 dbogdanov  staff   7,2M 18 dic  2015 07 Model Type A.mp3
-rwxrwxrwx  1 dbogdanov  staff   7,6M 18 dic  2015 08 Radioactive Mist.mp3
-rwxrwxrwx  1 dbogdanov  staff    80K 18 dic  2015 R-592113-1135831984.jpeg
-rwxrwxrwx  1 dbogdanov  staff    61K 18 dic  2015 R-592113-1175257387.jpeg
-rwxrwxrwx  1 dbogdanov  staff    63K 18 dic  2015 R-592113-1175257421.jpeg
-rwxrwxrwx  1 dbogdanov  staff   8,0K 18 dic  2015 Thumbs.db
-rwxrwxrwx  1 dbogdanov  staff   868K 18 dic  2015 iko-83-a.jpg
-rwxrwxrwx  1 dbogdanov  staff   839K 18 dic  2015 iko-83-b.jpg
```

**Comment by LukePulverenti** [comment]
What happens if we pick the first image out of the five and then you come back and say you'd prefer it was a different one? Why not just quickly rename one to folder.jpg?

**Comment by dbogdanov** [comment]
I guess showing a random image is better than not showing any image. The ``folder.jpg`` file should have a priority over non-standard filenames, but manually renaming those would be tedious for a large collection. If a user wants a different image from the one picked randomly (or alphabetically), she/he can rename it later, but at least some image will be shown.

While picking a random image it can make sense to give priority to the ones that have a proper size.

**Comment by LukePulverenti** [comment]
I never like to reject feature requests outright but at the very least I see this one sitting open for a long time so I would suggest just using a rename utility to create folder.jpg files from your existing images.

**Comment by dbogdanov** [comment]
Agreed, I am considering writing a script that would create folder.jpg selecting a random image in each folder.

**Comment by LukePulverenti** [comment]
Thanks. I'm going to go ahead and close this as I think that would be the best approach. Thanks.
