### ISSUE TITLE
Folders view do not allow to access to folders anymore

### ISSUE THREAD

**Issue by glatigny** [MediaBrowser/Emby#3209]
By activating the setting "Display a folder view to show plain media folders", there is a "Folders" available in the media list.

Via that "Folders", it was possible to browse the different media by their folder structure.
But since a few releases, the links in that "Folders" are pointing to the "tv" or "movies" listings.

It is still possible to access to that listing, but manually.
Going in the "Folders", clicking on one item and getting the ID from the URL.
`/movies.html?topParentId=XXXX`
Then going back in "Folders" and replacing the parentId with the folder that we want to browse (and keep the serverId variable in the URL)
`/list.html?parentId=XXXXX&serverId=YYYYY`

I think that the issue is related to the data attribute `data-collectiontype` which is set with the type of the collection and the JS do not let the user in the "list.html" context but switch to the collectiontype of the element (so movies.html, tv.html, etc).
By editing the DOM dynamically and removing that collectiontype, the links are then working as before.

**Comment by LukePulverenti** [comment]
Hi, it's resolved for the next release, thanks.
