### ISSUE TITLE
App Request

### ISSUE THREAD

**Issue by 12nick12** [MediaBrowser/Emby#3214]
Not sure if this is the correct place to make a request, but I would love a dedicated LiveTV app for Roku or a dedicated LiveTV OS for rPi. Thank you for your the awesome program I just also wish we could limit who could use Emby Premier license per user.

**Comment by LukePulverenti** [comment]
Thanks for the feedback. You're saying you want a separate app from the apps we already have?

**Comment by 12nick12** [comment]
Yeah, the app works well, but it'd be nice to have a dedicated app that automatically opens to the LiveTV Guide. Or even just add a setting in the app to auto launch the LiveTV Guide.

**Comment by LukePulverenti** [comment]
I don't think dedicated apps are realistic for us, but if you check out our recent Android TV update, we're able to put content right on your device home screen:
https://emby.media/emby-for-android-tv-oreo-ready.html

This can allow you to get to what you want with a reduced number of clicks.

We are going to be doing this sort of things on all platforms where it is possible to do so. Please let me know if you have additional questions. Thanks.

**Comment by LukePulverenti** [comment]
I'm going to close this, however we are happy to hear your feedback on our existing apps and what we can do to make them better for you. Thanks !
