### ISSUE TITLE
Metadata path (relative vs absolute)

### ISSUE THREAD

**Issue by fithwith** [MediaBrowser/Emby#3217]
I already started a discussion about this issue in the forum
here the link : https://emby.media/community/index.php?/topic/57522-path-changed-on-emby-portable-version/

the main issue is : 
I'm using emby the portable version, all my libraries are configured on it and its working fine.
few days ago I changed the whole emby folder to another location.
then I discovered that all the libraries are empty, the libraries are there but no media inside it.
after trying to investigate and searching on the forum I found through Metadata Manager that all the libraries are pointing to the old path.
I tried to change it the new path but its not possible.

actually I found on many config files the absolute path of many stuff is stored, libraries, metadata, cache, everything is stored with absolute path, so why not using relative path, specially with the portable version, since everything is under the same folder, data, app, cache, everything.

I discovered another strange behavior, if I keep emby app folder on the new location and try to scan one of the libraries, it does nothing, its not loading and no media come up, but if I return it back to the old location and try to scan one library the media start coming.

for sure the main idea is not to re-scan every time we change the folder but to use relative path specially for the metadata.

the good trick is that there is no issue with the app, its independent with any external file system, in our case the problem is pretty simple, don't use an absolute path for something which is already under your app folder, why you start the path from c:\ while all the files are under your root  which is  ./emby/...

**Comment by Happy2Play** [comment]
For a default installation with no customized path I would agree.  But lots of users relocate metadata, cache and transcode- temp folders to other places or even drives.

**Comment by fithwith** [comment]
if its customized its fine, it goes under the responsibility of the user himself but in this case its the portable version and everything is stored under the app folder, which is the default behavior.

**Comment by LukePulverenti** [comment]
Other than metadata where did you find absolute paths?

**Comment by fithwith** [comment]
all of them are related to metadata.

**Comment by LukePulverenti** [comment]
They'll be saved with tokens for the next release, or two releases from now most likely.
