### ISSUE TITLE
[Bug?] Video "length" increases as buffer increases

### ISSUE THREAD

**Issue by BloodyIron** [MediaBrowser/Emby#3222]
As I start watching a video (h264 in this case), the buffer grows, naturally. However, I look at the time in the video I'm watching, and the length of the video (mm:ss) grows as the video buffers further. I think it's showing the duration of the buffer, not the video itself. This is using Vivaldi to watch (effectively Chrome) on Linux.

v3.3.1.0

**Comment by LukePulverenti** [comment]
server/ffmpeg log?

**Comment by LukePulverenti** [comment]
Closing due to abandonment. Please feel free to re-open with the requested information. Thanks.

**Comment by BloodyIron** [comment]
Sorry, the issue didn't come back. I will come back with actually useful info if I see it again.
