### ISSUE TITLE
Can you please include a folder view for movies.

### ISSUE THREAD

**Issue by micropet** [MediaBrowser/Emby#3223]
For a large collection of films, the presentation of the server is not useful.

Can you please integrate a simple presentation sorted by directories?

Peter

**Comment by LukePulverenti** [comment]
Hi, in the server dashboard under library -> display, you can turn on the folder view option.  In the current release version it won't display perfectly as folders, but it's resolved for the next release, thanks.

**Comment by micropet** [comment]
Thanks for the answer.

That does not look better either.
I thought of a very simple and clear presentation. As Kodi does:
![20180402_102527](https://user-images.githubusercontent.com/2838584/38189541-08cad9fe-3661-11e8-8f73-92d45fbcf0f8.jpg)
![20180402_102553](https://user-images.githubusercontent.com/2838584/38189553-0feb680c-3661-11e8-874c-0f56fd55c510.jpg)
![20180402_102637](https://user-images.githubusercontent.com/2838584/38189555-1368d686-3661-11e8-9661-6b9e8f071a8b.jpg)

**Comment by LukePulverenti** [comment]
Why doesn't it look better?

**Comment by micropet** [comment]
On the TV it looks OK. In the browser I do not get a reasonable representation of directories.
It looks e.g. like this:

![emby01](https://user-images.githubusercontent.com/2838584/38265830-403dcae2-3777-11e8-8a1f-a09f11f26ad3.PNG)

**Comment by LukePulverenti** [comment]
Right, that's not the folder view i was talking about. I would just wait and try again with the next release of Emby Server. Thanks.

**Comment by micropet** [comment]
OK, i do. Thank you.
