### ISSUE TITLE
GetSearchHintsAsync seems to ignore the IncludeItemTypes array in SearchQuery

### ISSUE THREAD

**Issue by tanathos** [MediaBrowser/Emby#3229]
As for the title: I'm building a search query via the C# client that looks like this:

```
SearchQuery searchQuery = new SearchQuery();
searchQuery.UserId = client.CurrentUserId;
searchQuery.IncludeArtists = false;
searchQuery.IncludeGenres = false;
searchQuery.IncludePeople = false;
searchQuery.IncludeStudios = false;
searchQuery.IncludeMedia = true;
searchQuery.SearchTerm = "Iron";
searchQuery.IncludeItemTypes = new string[] { "MusicAlbum" };
searchQuery.Limit = 24;

var res = await client.GetSearchHintsAsync(searchQuery);
```

But in the SearchHints results I don't only have music albums with the search term "Iron", but also songs.

I'm trying different configurations of the query, also with the ExcludeItemTypes, but I always get items of all types...

**Comment by LukePulverenti** [comment]
Hi, since you've opened a topic in the ApiClient repo, we'll continue the discussion there:
https://github.com/MediaBrowser/Emby.ApiClient/issues/41

Thanks !
