### ISSUE TITLE
Reading channels and programs from large XML EPG files runs slowly when rebuilding guide.

### ISSUE THREAD

**Issue by mak0t0san** [MediaBrowser/Emby#3230]
One issue around this performance issue is the use of Lists and utilizing LINQ expressions to query it (List.FirstOrDefault(i=> i.Id == channelId).  This would perform better using a Dictionary ( Dictionary[channelId] ).  

Another issue is that the XML file is repeatedly parsed and read from, causing heavy amounts of IO. In particular, in `XmlTvProvider.GetProgramsAsync`, it runs this code:
```
 return new XmlTvReader(path, GetLanguage(info))
                .GetProgrammes(channelId, startDateUtc, endDateUtc, cancellationToken)
                .Select(p => GetProgramInfo(p, info)
```

For every channel (which there are thousands), it reads from the XML file and looks for an entry.

Perhaps instead, the EPG can be copied into a SQLite DB, and then query the SQLite db instead of reading from the XML file.  This should improve performance when building the guide.

**Comment by LukePulverenti** [comment]
Thanks, this will be resolved two releases from now, not in the upcoming stable, but in the release after that.
