### ISSUE TITLE
Inconsistent WebSocketState throwing warnings

### ISSUE THREAD

**Issue by BJamin99** [MediaBrowser/Emby#3234]
WebSocketState is defined in two places: MediaBrowser.Model.Net.WebSocketState and SocketHttpListener.WebSocketState.  These two definitions differ.

`MediaBrowser.Model.Net.WebSocketState contains { None, Connecting, Open, CloseSent, CloseReceived, Closed, Aborted }`
`SocketHttpListener.WebSocketState contains { Connecting, Open, Closing, Closed }`

"None" and "Aborted" have no correstponding states in SocketHttpListener.WebSocketState and "CloseSent" and "CloseReceived" have been combined into a single "Closing".

Emby/Emby.Server.Implementations/HttpServer/SocketSharp/SharpWebSocket.cs indirectly uses both of these definitions in its public WebSocketState State variable's getter.  State is of type MediaBrowser.Model.Net.WebSocketState and WebSocket.ReadyState is of type SocketHttpListener.WebSocketState.  So when the following is called:

`if (!Enum.TryParse(WebSocket.ReadyState.ToString(), true, out commonState))`

when WebSocket.ReadyState has the value "Closing", the TryParse fails, setting commonState to the "default" value (I believe that would be "None" in this case), and then outputting a warning to the log file.

More critically, the getter of the SharpWebSocket.State has received an invalid value (and doesn't know it).  This can cause further error for any decisions made based on that value.

**Comment by LukePulverenti** [comment]
Resolved for next release, thanks !
