### ISSUE TITLE
Calling RefreshMetadata add to library with no parent

### ISSUE THREAD

**Issue by PoppyPop** [MediaBrowser/Emby#3241]
Has seen in MediaBrowser/Emby.AutoOrganize#8, in the AutoOrganize plugin, i noticed that the series.RefreshMetadata(....) add the media to the library, but the parentId is missing.

When we scan the library, the process does not handle the orphan item and add a new item, this time with correct parenting info.

The orphan is not visible in any way, but can cause trouble with all process that search for an item with the name.

**Comment by LukePulverenti** [comment]
Stop using the AddChild method. Just copy the files and let the regular library scan take it from there.

**Comment by PoppyPop** [comment]
I don't understand, you says in MediaBrowser/Emby.AutoOrganize#10 to open a bug report.
Can we continue the discussion in the PR ? an find a good alternative for the plugin users ?

**Comment by LukePulverenti** [comment]
When I look at the auto-organize code from a few weeks ago, there were no calls to folder.AddChild. I see that you have added this to both TV and Movies, but it's not a good thing to be doing. Remember what I said that the plugin should be only be an automated alternative to manually copying the files.

If you copy the files in manually, the next step is running a library scan or waiting for the realtime monitor to pick up the changes, and that's exactly what the plugin should do. Just copy the files without using AddChild.

**Comment by LukePulverenti** [comment]
Yes, we can continue in the PR.
