### ISSUE TITLE
TV Series Meta Data not being gathered automatically

### ISSUE THREAD

**Issue by Jab2870** [MediaBrowser/Emby#3249]
Hi,
I have my episodes inside a TV directory in the following format:

```
The Big Bang Theory/
├── Season 1
│   ├── The Big Bang Theory SE01E01.mp4
│   ├── The Big Bang Theory SE01E02.mp4
│   ├── The Big Bang Theory SE01E03.mp4
│   ├── .......
```

I have also tried without the "The Big Bang Theory" in the file names. For some reason the Meta data is not being automatically picked up. After I add the IDs for thetvdb and IMDB then refresh metadata then I get all of the artwork and actors / actresses and episode names.

Shouldn't this be automatic? Am I naming my files correctly?

**Comment by LukePulverenti** [comment]
Hi, your files look fine. It is automatic. Maybe you had pre-existing metadata files, in which case that would be the metadata source. Or maybe there was a tvdb outage or other kind of download failure at the time. Please attach the information requested in how to report a problem:
https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/
Thanks.

**Comment by Penkethboy** [comment]
you have SE01E01 - change it to S01E01

**Comment by LukePulverenti** [comment]
Ah yes I completely missed that, thanks @Penkethboy

**Comment by Jab2870** [comment]
Thanks, my bad. That has fixed it.
