### ISSUE TITLE
Matroska causes UI and system stutter on Android

### ISSUE THREAD

**Issue by sauerj** [MediaBrowser/Emby#3254]
When playing a Matroska video on the Android 2.9.92 client, the UI immediately begins to stutter and Android reports the Emby App as not responding.
Same video settings but as MPEG-4 container, play without any problems.
Both videos are direct played.

Video settings: H.264 Profile: High Level: 4.1 CRF: 22
Emby for Android 2.9.92 on Android 8.0

**Comment by sauerj** [comment]
Tried again with Main and High Level 4.0. Main video starts with slight less stutter, but after a few seconds same issue. When I copy the files onto the device, VLC plays them without any problems.

**Comment by LukePulverenti** [comment]
What device?

**Comment by sauerj** [comment]
Huawei P10 Android 8

Luke <notifications@github.com> schrieb am Do., 24. Mai 2018, 19:15:

**Comment by LukePulverenti** [comment]
Resolved for next app update, thanks.
