### ISSUE TITLE
Subtitle not appear in Apple TV4

### ISSUE THREAD

**Issue by BuSHari** [MediaBrowser/Emby#3259]
Hi,

When try to watch a video (TV show or Movie) and i check that the correct subtitle is selected, the subtitle is appear in the video when played.
The subtitle menu isnt appear during the play (only Info & Audio).

The Subtitle is external and use the same mame of the video, i checked that the correct subtitle is marked before playing and i activated the Closed Caption in Apple settings.

Can you please check for a fix?

**Comment by LukePulverenti** [comment]
Please discuss an example and attach the information requested in how to report a problem:
https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/

Thanks.

**Comment by BuSHari** [comment]
I've created a new topic in the communnity
https://emby.media/community/index.php?/topic/58758-subtitles-not-appear-in-apple-tv4/

**Comment by LukePulverenti** [comment]
Ok, we'll continue in the community thread. Thanks.
