### ISSUE TITLE
no more https redirect

### ISSUE THREAD

**Issue by mgherghi** [MediaBrowser/Emby#3261]
Not sure if this was missed, but emby 3.4 for armhf no longer has the redirect to https (force https) , ive tried other ways of having it redirect from the server app but http always works

**Comment by LukePulverenti** [comment]
Hi, try configuring the secure connections mode setting.

**Comment by LukePulverenti** [comment]
Since you opened a topic in the Emby community as well, we can continue the conversation there. Thanks !
