### ISSUE TITLE
Second line in header on small full hd screen

### ISSUE THREAD

**Issue by Haxy89** [MediaBrowser/Emby#3262]
![image](https://user-images.githubusercontent.com/37550896/39661848-383b7ec0-5059-11e8-86e0-09dede360413.png)

My screen is 11cal and 1920x1080, I get second line in header for "Start" and "Favourites".
I need to change zoom level to 90% in chrome to get proper header:

![image](https://user-images.githubusercontent.com/37550896/39661871-810f01b2-5059-11e8-8269-9e2f9520330b.png)

**Comment by LukePulverenti** [comment]
Hi, this isn't a problem. At various sizes, it will either be one line or two lines. Nothing to worry about.

**Comment by Haxy89** [comment]
But I don't want two lines, it is a waste of space above.
![image](https://user-images.githubusercontent.com/37550896/39664128-10e95858-507f-11e8-82cf-c2cb5233d123.png)

How to fix .css to move "Start" and "Favourites" to first line always?

**Comment by LukePulverenti** [comment]
I'm closing this sorry. It's a very simple responsive css. At X resolution one line, Y resolution two lines.
