### ISSUE TITLE
Google Analytics. Simplification of wording, opt out or complete removal

### ISSUE THREAD

**Issue by anoma** [MediaBrowser/Emby#3266]
Can I request the inclusion of options that allow Emby sysadmins to control in one central location all Emby uses of advanced metric reporting, aka Google analytics or alternatively that user data logging be removed from the project completely.

I have carefully worded this request to include all Emby uses of advanced metric reporting but my primary exposure to this has been surrounding the setting in the `Emby for Kodi Sync Add-On` https://emby.media/emby-for-kodi.html

As it stands each of my users are required to navigate to `Kodi > Addons > Emby > Configure > Advanced`  and disable "analytics metrics logging" on each of their profiles on each of their devices. This is impractical in general and impossible given the metrics are being collected are against my children who are all too young to understand any of this.

I would also like to request this setting be altered to use clearer wording explaining what it is as in my opinion the current wording does not naturally lend itself to informing users that data is being uploaded to the cloud for analysis.

Alternatively you may find it beneficial to consider removing all user data collection as you may not be aware of recent regulation changes covering to the collection of EU citizen data by any party worldwide. These changes are far reaching and amongst other things clear up the previous grey area of data being uploaded outside of the EU by non EU parties. This FAQ should help https://www.eugdpr.org/gdpr-faqs.htm and I would strongly recommend Emby LLC review this and instruct their authorised partners to do so too as compliance is mandatory and it has special regulations for children you will need to follow without delay.

Note: I seriously considered not raising this ticket in fear of it becoming some flag for nay sayers to rally behind. I would ask that people do not jump on this for anything other than technical or legal compliance as *Emby LLC and their authorised partners are absolutely within their rights to collect data* they just need to do it in the right way which unfortunately in a post GDPR world is a very complex and time-consuming task.

**Comment by LukePulverenti** [comment]
Hi, please open this in the Emby for Kodi repository:
https://github.com/MediaBrowser/plugin.video.emby
Thanks.
