### ISSUE TITLE
"Enable real time monitoring" broken in Version 3.4.1.0

### ISSUE THREAD

**Issue by yuriw** [MediaBrowser/Emby#3268]
Steps:

Select  "Enable real time monitoring" in Manage Folders
Download new video
Wait for update, see errors below.
Note: manual library scan works fine.

Snippet from the log:

> 2018-05-10 08:12:06.002 Error LibraryMonitor: Error in Directory watcher for: /media/seagatecentral/Public/Videos
>     *** Error Report ***
>     Version: 3.4.1.0
>     Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
>     Operating system: Unix 4.13.0.39
>     64-Bit OS: True
>     64-Bit Process: True
>     User Interactive: True
>     Processor count: 4
>     Program data path: /var/lib/emby
>     Application directory: /opt/emby-server/system
>     System.IO.FileNotFoundException: Could not find file '/xxx/movie.yyy'.
>     File name: '/media/seagatecentral/Public/Videos/xxx/movie.yyy'
>     System.IO.FileNotFoundException
>     No Stack Trace Available

see more
[https://emby.media/community/index.php?/topic/58197-script-to-scan-library/page-2](url)

**Comment by Penkethboy** [comment]
Real-time monitoring only works on some OS's - limitation of the library used IIRC

**Comment by yuriw** [comment]
I am on ubuuntu 16.04 serve and it i supported on it

**Comment by LukePulverenti** [comment]
It could be permissions. It could also be a defect in the 2.07 version of the .NET core runtime, which the 3.4.1 release updated to. The error is coming from the runtime itself so there's not much we're going to be able to do about it. The next release will be updating to the 2.1 version of the runtime so perhaps that will resolve it.

**Comment by yuriw** [comment]
@Penkethboy thanks for suggestion! @LukePulverenti already confirmed that this is a new problem, so this is a issue tracker for it

**Comment by LukePulverenti** [comment]
Closing as there isn't really anything for us to do here. Please try again with the next release and the updated .net core runtime. Thanks.
