### ISSUE TITLE
[Feature Request] Auto-Merge Movies/TV Shows

### ISSUE THREAD

**Issue by jaketame** [MediaBrowser/Emby#3272]
I would like to request for the auto-merge of Movies and TV show Episodes

**Comment by jaketame** [comment]
To expand on this;

Movies;
Relax the naming convention requirement.
Span multiple root folders
   /data/movies/
   /data/movies4k/
If a user transcodes then default selecting 1080p to transcode rather than a 4K version

TV Shows;
Merge TV shows
Merge TV episodes into a single episode
Allow to choose best version
Allow multiple root folders
  /data/tvshows/
  /data/tvshows4k/
If user trancodes then default to transcode 1080p version rather than 4K version.

**Comment by LukePulverenti** [comment]
Closing based on your comment in #2431
