### ISSUE TITLE
Bug in audio language selection

### ISSUE THREAD

**Issue by paulogeneses** [MediaBrowser/Emby#3273]
There is a bug in the [line 369](https://github.com/MediaBrowser/Emby/blob/e4f1a16550f7d497968d19683812e594785fbcd9/Emby.Server.Implementations/Library/MediaSourceManager.cs#L369) of MediaSourceManager.cs, as you can see below:

![2018-05-14 23_09_38-emby server implementations_library_mediasourcemanager cs_ 7aa573d - tortoisegit](https://user-images.githubusercontent.com/12234915/40033633-9941d048-57cf-11e8-8b7a-ddc38cc45f63.png)

This causes issues with dual audio videos when the desired audio language is not the default track set in the video file, since the player always chooses the track that is marked as default, forcing the user to manually change the audio language every time.

**Comment by LukePulverenti** [comment]
It's resolved for the next release, thanks.
