### ISSUE TITLE
[windows 10] Emby server updater is creating many .log files in random directory

### ISSUE THREAD

**Issue by Zerqz** [MediaBrowser/Emby#3276]
Hello, 

It's been bothering me for awhile and finally today I decided to track down what was making these weird log files in the root of my D:\ directory, and it turns out it's the emby-server-updater. 

I know it's emby making this file because I ran ProcessMon and waited for a new log to be created as seen here: [imgur-screenshot](https://imgur.com/a/1clCLsB)

It's very weird because, 
A) that isn't where Emby server is installed. 
B) There's no identifiable information as to what the log is referring to or where it came from. 
C) It's the same directory as where the location of the library is, but not where anything has been installed.

I went through all of the server settings and any mention of logging is `disabled` so I don't know why all these files are being created here.

The files are named something along the lines of `0fe0dac6-c1d3-4671-9df9-38e0bf89e86a.log` but change along the same format for each file, and after about a week I'll get 30 of them in this directory, which gets rather annoying.

All that's in the file is:
`Error performing update. Could not load file or assembly 'System.Memory, Version=4.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.`

Which doesn't make sense, because if I go to the emby dashboard, the server is successfully being updated.

**Comment by LukePulverenti** [comment]
It's resolved for the next release, thanks.

**Comment by hirenshah** [comment]
I am using Version 3.6.0.2 beta and it is still happening for me...
