### ISSUE TITLE
Feature Request: Support for HTTP/2

### ISSUE THREAD

**Issue by sydlexius** [MediaBrowser/Emby#3277]
I'm interested in seeing if Emby can be enhanced to support the HTTP/2 protocol.  There are three applicable features that I believe would improve Emby, especially for mobile use.  HTTPS connections with HTTP/2 requires TLS 1.2 (or newer).   When combined with TLS 1.3 and HTTP/2 Server Push, it is possible to opportunistically encrypt outside, unencrypted sources of data.  Additionally, with improved pipelining support and the introduction of multiplexing, the endpoint performance should be demonstrably better.

For reference, I am providing a wiki link to HTTP/2 [here](https://en.wikipedia.org/wiki/HTTP/2).  There is a github project for an MIT-License C# server and client implementation that can be found [here](https://github.com/Matthias247/http2dotnet).

**Comment by LukePulverenti** [comment]
Once it gets added to Microsoft's kestrel library then we'll adopt that implementation. Looks like they have an open ticket about it:
https://github.com/aspnet/KestrelHttpServer/issues/73
Thanks.

**Comment by sydlexius** [comment]
Looks promising.  Hopefully it'll be easy to implement once Kestrel supports it.

**Comment by BowlesCR** [comment]
I'd love to see this too.
Alternatively, it should be possible to throw a reverse proxy in front of Emby to achieve the same ends.

**Comment by artorius** [comment]
I have an Apache front-end server that is doing both SSL (with LetsEncrypt) and using HTTP/2.  My Emby server sits behind this, and I use it just fine.  I understand that this request is to have this built into Emby, but just to put it out there, I am running this behind an Apache proxy with no issues on HTTP/2.

**Comment by emosterd** [comment]
@artorius:

Sorry to threadjack, but would you mind sharing your you emby.conf—or whatever you call it—from your sites-enabled?  I’ve been trying to get something like mydomain.com/emby to forward to Emby, just to have a nice, easy-to-remember URL, but have been unable to do so.

**Comment by artorius** [comment]
@emosterd 

I'll likely put together a write-up on how I do this sort of thing.  I'll post it to the forum when I'm done.  Give me a day or so to get something together.

**Comment by KristupasSavickas** [comment]
I have a similar setup using [nginx-proxy](https://github.com/jwilder/nginx-proxy) and letsencrypt-nginx-proxy-companion[](https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion/).

**Comment by emosterd** [comment]
@artorius & @KristupasSavickas 

Thanks!  I've tried at least configs from Emby's forum, but I've not been able to get them to work.  Strangely, I have no problem getting the reverse proxy to work with Subsonic.

One small victory was that I was able to get my existing LE certificate to work with Emby, but I'd really just like to be able to have something like myserver.com/videos go to Emby on port 8920, like I have Subsonic to for /music, where it also works with LE.

**Comment by artorius** [comment]
I posted a short Apache setup howto here:  [https://emby.media/community/index.php?/topic/61549-apache-proxy-frontend-for-emby/](url)

**Comment by emosterd** [comment]
@artorius 

Thanks!  I posted a follow-up question there, just so others could see it if they are having the same problem as I am.  I figured it'd be more visible there than here.

**Comment by cslawrence-uiowa** [comment]
It appears the HTTP/2 might have been added as of December by Microsoft.

**Comment by squawkingVFR** [comment]
@LukePulverenti It appears the HTTP/2 might have been added as of December by Microsoft.

https://github.com/aspnet/AspNetCore/issues/4782

**Comment by LukePulverenti** [comment]
I think it will make sense to explore this once .net core 3.0 is released, which is coming sometime this year.

**Comment by scalablecory** [comment]
Preview 7 is out and go-live. Good time to start on this!

**Comment by LukePulverenti** [comment]
Yes now that we've released 4.2 today, once we're able to put 4.2 behind us I can allocate a little time to start playing with .net core 3.0.

**Comment by LukePulverenti** [comment]
This will be in Emby Server 4.4 for Windows and most Linux distros. Remember that in order to test you'll need to setup https with TLS 1.2+.
