### ISSUE TITLE
Latest release

### ISSUE THREAD

**Issue by MurkBRA** [MediaBrowser/Emby#3279]
embyserver-win-x64-3.4.1.0
`MediaBrowser.ServerApplication.exe` is missing

**Comment by LukePulverenti** [comment]
Hi, please use EmbyServer.exe. If you are intending to run as a windows service, instructions for that can be found here:
https://github.com/MediaBrowser/Wiki/wiki/Running%20Emby%20Server%20as%20a%20Windows%20Service
Thanks.

**Comment by LukePulverenti** [comment]
Please let us know if you have additional questions. Thanks !
