### ISSUE TITLE
Subtitles do not scale or re-position when window size changes

### ISSUE THREAD

**Issue by KD0BPV** [MediaBrowser/Emby#3280]
Server operating system: Arch Linux x86_64
Emby server version: 3.4.1.0
Client operating system: Gentoo Linux x86_64
Client agent: Firefox v60.0 x86_64

Starting video with full-size browser window, then shrinking it:
![screenshot_20180519_085713](https://user-images.githubusercontent.com/4677549/40269458-8aee00de-5b44-11e8-8002-380a87d9c215.png)

Starting video with half-width window, then expanding it:
![screenshot_20180519_090259](https://user-images.githubusercontent.com/4677549/40269463-9ca4ac7e-5b44-11e8-839d-63c116d56f5c.png)

The video being played is in an MKV container. Here's the subtitle track metadata:
![screenshot_20180519_092152](https://user-images.githubusercontent.com/4677549/40269600-4cd9009e-5b46-11e8-895e-0b126cb16913.png)

User subtitle settings:
![screenshot_20180519_092541](https://user-images.githubusercontent.com/4677549/40269631-bc986b68-5b46-11e8-9142-93d08d7d1052.png)

**Comment by LukePulverenti** [comment]
Can you try another browser? I can't reproduce this, however occasionally i have heard users on gentoo mention this.

**Comment by KD0BPV** [comment]
Hm. Curious. I tried doing the same things in Chrome, and it works as expected. That got me thinking... I looked at the use flags for my firefox install. The Harfbuzz use flag is disabled, so firefox is using a bundled version. I'll try recompiling, linking to the system harfbuzz install, and get back to you.

**Comment by KD0BPV** [comment]
No luck.

**Comment by LukePulverenti** [comment]
I was able to reproduce in firefox on windows. It's resolved for the next release, thanks.
