### ISSUE TITLE
Improper mapping of GenreItems when using fields

### ISSUE THREAD

**Issue by kdschlosser** [MediaBrowser/Emby#3282]
I am not sure if this is by intentional design. But using the Genre field parameter there are 2 additional objects added to the returned JSON. GenreItems and Genres. I do not know if there are additional parameters that do the same thing. There is a list of available objects that can be returned (i do not believe it is a complete list). but i have not been able to locate a list of available field items. and since the mapping of field items to returned JSON object name is not direct this adds some extra complexity.

This list of items are what I have used in the fields parameter and do not get a matching returned json object. This is when I query the database for a movie. In the Wiki it states that if an id is used directly instead of an enumeration the returned JSON for that query will have a returned JSON object including all available database entries for that id. I have found that this is not the case. There are things that are not returned unless they are specifically added to the fields parameter of the query.

AspectRatio
CriticRatingSummary
CumulativeRunTimeTicks
Is3D
IsHD
IsoType
Language
OriginalPrimaryImageAspectRatio
OverviewHtml
PlayedPercentage
SpecialFeatureCount
Status
Video3DFormat

I am not sure if the way the API is set up is if there is no information on that item then it doesn't get returned. I would think that it would return the field with a value of null.

It would be awesome if there is a complete JSON layout of the API. As an example of what I think would be easy to follow.

before the name of the returned value would be the name used in the fields parameter and also what media types it can get returned for. followed by the actual name of value. and after that would be the contents data type with a brief description of what it is and if needed a description of what the use would be if it is not obvious (RunTimeTicks as an example).

I only included the fields and mediatypes example for the first few items simply to show what the layout would be.

      {
        (fields=Genres, mediatypes=Movie, TV) "Genres": [
            string(genre name),
        ],
        "Container": string(file extension),
        "LocationType": string(file location),
        (fields=OfficialRating, mediatypes=Movie, TV) "OfficialRating": string(parental rating = PG, TV-PG, NC-17),
        "RemoteTrailers": [
            {
                "Url": string(),
                "Name": String(trailer name)
            }
        ],
        "ServerId": string(server id),
        "ProductionLocations": [
            string(location)
        ],
        "SortName": string(),
        "Tags": [],
        "Type": string(media type),
        "IsFolder": boolean(),
        "CriticRating": integer(),
        "ProviderIds": {
            string(metadata provider name): string(metadata provider id),
        },
        "PremiereDate": string(iso8601 first showing),
        "ProductionYear": integer(year released),
        "Path": string(media loaction),
        "LocalTrailerCount": integer(),
        "BackdropImageTags": [
            string(image id),
        ],
        "Name": string(name/title),
        "MediaType": string(),
        "Taglines": [
            string()
        ],
        "ParentId": string(parent container id),
        "PrimaryImageAspectRatio": integer(),
        "MediaSources": [
            {
                "SupportsDirectStream": boolean(),
                "Container": string(file extension),
                "RequiresClosing": boolean(),
                "IgnoreDts": boolean(),
                "IgnoreIndex": boolean(),
                "SupportsDirectPlay": boolean(),
                "MediaStreams": [
                    {
                        "IsInterlaced": boolean(),
                        "Index": integer(),
                        "AverageFrameRate": integer(frames (images) per second),
                        "Width": integer(vertical line count),
                        "VideoRange": string(),
                        "Codec": string(codec),
                        "IsForced": boolean(),
                        "AspectRatio": string(aspect ratio),
                        "Type": string(media type),
                        "IsTextSubtitleStream": boolean(),
                        "Profile": string(),
                        "DisplayTitle": string(video encoding),
                        "SupportsExternalStream": boolean(),
                        "CodecTimeBase": string(),
                        "RealFrameRate": integer(),
                        "CodecTag": string(codec name),
                        "Level": integer(),
                        "RefFrames": integer(),
                        "TimeBase": string(),
                        "BitRate": integer(bitrate kbps),
                        "IsDefault": boolean(),
                        "IsAnamorphic": boolean(),
                        "Height": integer(horizontal line count),
                        "PixelFormat": string(),
                        "IsExternal": boolean()
                    },
                    {
                        "IsAnamorphic": boolean(),
                        "IsInterlaced": boolean(),
                        "DisplayTitle": string(sound encoding),
                        "SupportsExternalStream": boolean(),
                        "ChannelLayout": string(audio output),
                        "Title": string(audio track name),
                        "Index": integer(),
                        "Type": string(),
                        "IsForced": boolean(),
                        "Level": integer(),
                        "Channels": integer(number of audio channels),
                        "Codec": string(encoder),
                        "CodecTimeBase": string(),
                        "TimeBase": string(),
                        "SampleRate": integer(sample rate Hz),
                        "BitRate": integer(bitrate kbps),
                        "IsTextSubtitleStream": boolean(),
                        "IsDefault": boolean(),
                        "IsExternal": boolean()
                    }
                ],
                "Type": string(),
                "ReadAtNativeFramerate": boolean(),
                "RequiresLooping": boolean(),
                "Path": string(media location),
                "RequiresOpening": boolean(),
                "Bitrate": integer(bitrate kbps),
                "IsRemote": boolean(),
                "Name": string( filename without extension),
                "RequiredHttpHeaders": {},
                "SupportsTranscoding": boolean(),
                "Formats": [],
                "Protocol": string(),
                "IsInfiniteStream": boolean(),
                "GenPtsInput": boolean(),
                "VideoType": string(),
                "ETag": string(),
                "RunTimeTicks": integer(media duration) / 10000000 = seconds,
                "SupportsProbing": boolean(),
                "Id": string()
            }
        ],
        "CommunityRating": 6.4,
        "Studios": [
            {
                "Name": string(studio name),
                "Id": string()
            },
        ],
        "People": [
            {
                "Type": string(job description),
                "PrimaryImageTag": string(image id),
                "Role": string(role),
                "Name": string(person name),
                "Id": string()
            },
        ],
        "Overview": string(synopsis)
        "Chapters": [
            {
                "Name": string(chapter name),
                "StartPositionTicks": integer(chapter location) / 10000000 = location in seconds
            },
        ],
        "DateCreated": string(iso8601 database entry creation),
        "VideoType": string(),
        "ImageTags": {
            "Logo": string(image id),
            "Primary": string(image id),
            "Thumb": string(image id)
        },
        "HomePageUrl": string(official media website),
        "RunTimeTicks": integer(media duration) / 10000000 = seconds,
        "GenreItems": [
            {
                "Name": string(genre name),
                "Id": string()
            },
        ],
        "Id": string()
     }

    iso8601 = date format YYYY-MM-DDThh:mm:ss.sZ
              YYYY=4 digit year
              MM=2 digit month
              DD=2 digit day of month
              T=Start of time designation (delimiter)
              hh=2 digit hour (24 hour clock)
              mm=2 digit minute
              ss.s=seconds.fraction of a second
              Z=UTC (timestamp is for GMT timezone +-0 hours)

I would imagine that the items added to the fields parameter are the actual database object names if that is the case then writing a script to collect a good portion of the information from the database i would imagine shouldn't be to difficult. 

I would be willing to create this formatted structure representation of the JSON returned by the API if one does not exist. But I would need a point in a general direction as to where to look to start collecting this information. I browsed through the code some and bits and pieces here and there. But due to the large number of files it would take me a very long time to read each and every single file in search of the information. 

Also is there a complete list available for the parameters that can be used in a query and what types of queries the parameters can be used with?

I am sorry for this being long winded but a believe that a complete API layout written for programmers is something that needs to be done. it should be only a 2 page document. one for the API calls. and one for the returned data structure. But both should be complete, and it is also a good reference for the writers as well, if a change is made to the API you can make sure that all pieces have been accounted for. I would imagine that with an API this large and complex that something can get forgotten.

**Comment by kdschlosser** [comment]
OK so I was a little bored today. and I started mapping out the JSON structure from the API and this is what I have come up with thus far.

I set it up as explained above. I have not yet added any examples of use for anything.

before each element name I have placed the conditions that have to be met before that element will be returned. If there is a Type= in the condition this simply means this is the media type(s) you need to query for whether it be an enumeration request or a direct request. if you need to supply a field name in the Fields parameter as wee that is also noted in it. If there are any other conditions they have to be fulfilled as well. I did fond out that the API for the most part is set up so that if an object does not exist for that element it will not add the element to the returned data. There are exceptions to this but not many and those will return a null if the object does not exist. I also included the data type for the object that is returned for that element. The structure will be exactly as you see it. the nesting specifically. If you do not meet the conditions of an element that element will not be in the returned JSON data structure.

Enumerations are pretty much the same thing as this whole structure with a condensed amount of information in it and there can be multiple structures in an enumeration array.

This is still not complete and I am continuing to read through the code to try and locate more elements that need to be added. If there is something missing and or incorrect please let me know. I am not all that proficient in c#, but I'm learning.

        {
          'EndDate': str(ISO8601),
          'BackdropImageTags': array([str(), str()]),
          'ImageTags': array([{}, {}])
          'Id': str(),
          'IndexNumber': int(),
          'ParentIndexNumber': int(),
          'MediaType': str(),
          (not Type=LiveTvProgram) 'LocationType': str(),
          (IsHd) 'IsHD': bool(),
          'Audio': str(Mono, Stereo, Dolby, DolbyDigital, Thx, Atmos),
          'CriticRating': float(),
          (Trailers) 'LocalTrailerCount': int(),
          (DisplayOrder) 'DisplayOrder': str(),
          (CollectionType) 'CollectionType': str(),
          'Name': str(),
          'OfficialRating': str(),
          'PremiereDate': str(ISO8601),
          'ProductionYear': int(),
          'RunTimeTicks': int(),
          'Type': str(),
          (CommunityRating) 'CommunityRating': float(),
          (IsPlaceHolder) 'IsPlaceHolder': bool(),
          (Fields=DateCreated) 'DateCreated': str(ISO8601),
          (Fields=Settings) 'LockedFields': ??? Cast, Genres, ProductionLocations, Studios, Tags, Name, Overview, Runtime, OfficialRating
          (Fields=Settings) 'LockData': bool(),
          (Fields=Settings) 'ForcedSortName': str(),
          (Fields=Container) 'Container': str(),
          (Fields=HomePageUrl) 'HomePageUrl': str(),
          (Fields=ExternalUrl) 'ExternalUrls': array([str(), str()]),
          (Fields=Tags) 'Tags': array([str(), str()]),
          (Fields=AspectRatio) 'AspectRatio': str(),
          (Fields=ScreenshotImageTags) 'ScreenshotImageTags': array([str(), str()]),
          (Fields=Genres) 'Genres': array([str(), str()]),
          (Fields=Genres ) 'GenreItems': array([
              {
                  'Name': str(),
                  'Id': str()
              }
          ]),
          (Fields=IsFolder) 'IsFolder': bool(),
          (EnableUserData=True) 'UserData': {
              'IsFavorite': bool(),
              'Likes': bool(),
              'PlaybackPositionTicks', int(),
              'Rating': float(),
              'Played': bool(),
              'LastPlayedDate' : str(iso8601),
              'Key': ???
          },
          (if Type=Library and ((MusicAlbum or Season) or ChildCount)) 'ChildCount': int(),
          (Fields=CumulativeRunTimeTicks) 'CumulativeRunTimeTicks': int(),
          (Fields=DateLastMediaAdded) 'DateLastMediaAdded': str(ISO8601),
          (Fields=PlayAccess) 'PlayAccess': ???,
          (Fields=BasicSyncInfo or SyncInfo) 'SupportsSync'
          (Fields=Settings) 'PreferredMetadataCountryCode': str(),
          (Fields=Settings) 'PreferredMetadataLanguage': str(),
          (Fields=RemoteTrailers) 'RemoteTrailers': array([
              {},
              {}
          ]),
          (Fields=Overview) 'Overview': str(),
          (Fields=OriginalTitle) 'OriginalTitle': str(),
          (Fields=ParentId) 'ParentId': str(),
          (Fields=Path) 'Path': str(),
          (Fields=EnableMediaSourceDisplay) 'EnableMediaSourceDisplay': bool(),
          (Fields=ProviderIds) 'ProviderIds': array([
              {str(metadata provider name): str(metadata provider id)},
              {str(metadata provider name): str(metadata provider id)}
          ]),
          (Fields=SortName) 'SortName': str(),
          (Fields=CustomRating) 'CustomRating': str(),
          (Fields=Taglines) 'Taglines': array([str(), str()]),
          (Fields=ProductionLocations) 'ProductionLocations': array([str(), str()]),
          (Type=Channel and ChannelId) 'ChannelId': str(),
          (Type=Channel and ChannelId) 'ChannelName': str(),
          (Type=Channel) 'SourceType': int(0=Library, 1=Channel, 2=LiveTV),
          (Fields=People) 'People': array([
              {
                  "Type": str(Actor or GuestStar or Director or Writer or Producer or Composer)
                  "Role": str()
                  "Name": str()
                  "PrimaryImageTag": str()
              },
              {
                  "Type": str(Actor or GuestStar or Director or Writer or Producer or Composer)
                  "Role": str()
                  "Name": str()
                  "PrimaryImageTag": str()
              }
          ]),
          (Fields=PrimaryImageAspectRatio) 'PrimaryImageAspectRatio': str(),
          (Fields=DisplayPreferencesId) 'DisplayPreferencesId': str(),
          (Fields=Studios) 'Studios': array([
              {
                  'Name': str(),
                  'Id': str()
              },
              {
                  'Name': str(),
                  'Id': str()
              }
          ]),
          (Fields=CanDelete) 'CanDelete': bool()
          (Fields=CanDownload) 'CanDownload': bool()
          (Fields=Etag) 'Etag': str(),
          (Fields=) 'Type': str()
          (Type=Book or (Recording and SeriesName)) 'EpisodeTitle': str()
          (Type=Photo) 'Width': int(),
          (Type=Photo) 'Height': int(),
          (Type=Photo) 'CameraMake': str(),
          (Type=Photo) 'CameraModel': str(),
          (Type=Photo) 'Software': str(),
          (Type=Photo) 'ExposureTime': double(),
          (Type=Photo) 'FocalLength': double(),
          (Type=Photo) 'ImageOrientation': str(),
          (Type=Photo) 'Aperture': double(),
          (Type=Photo) 'ShutterSpeed': double(),
          (Type=Photo and Album) or Type=MusicVideo) 'Album': str(),
          (Type=Photo and Album) or Type=MusicVideo) 'AlbumId': str(),
          (Type=Photo) 'Latitude': double(),
          (Type=Photo) 'Longitude': double(),
          (Type=Photo) 'Altitude': double(),
          (Type=Photo) 'IsoSpeedRating': int(),
          (Type=MusicVideo) 'MusicVideoCount': int(),
          (Type=Album) 'SongCount': int(),
          (Type=GameSystem) 'GameCount': int(),
          (Type=Album, Audio) 'ArtistCount': int(),
          (Type=Audio) 'AlbumCount': int(),
          (Type=Series) 'EpisodeCount': int(),
          (Type=Movie) 'MovieCount': int(),
          (if Trailers) 'TrailerCount': int(),
          (Type=Season) 'SeriesCount': int(),
          (Type=Channel) 'ProgramCount': int(),
          (Fields=Logo) 'ParentLogoItemId': str(),
          (Fields=Logo) 'ParentLogoImageTag': str(),
          (Fields=Art) 'ParentArtItemId': str(),
          (Fields=Art) 'ParentArtImageTag': str(),
          (Fields=Thumb) 'ParentThumbItemId': str(),
          (Fields=Thumb) 'ParentThumbImageTag': str(),
          (Type=Audio) "Album", str(),
          (Type=Audio, Video and ExtraType) "ExtraType": str(),
          (Tye=Audio and AlbumParent) "AlbumId": str(),
          (Type=Audio and AlbumParent) "AlbumPrimaryImageTag": str(),
          (Type=Audio and AlbumArtist)"AlbumArtists" array([
              {
                  "Name": str(),
                  "Id": str()
              },
              {
                  "Name": str(),
                  "Id": str()
              }
          ]),
          (Type=Audio and AlbumArtist) "AlbumArtist": str(),
          (Type=Audio and Artist) "Artists": array([str(), str()]),
          (Type=Audio and Artist) "ArtistItems" array([
              {
                  "Name": str(),
                  "Id": str()
              },
              {
                  "Name": str(),
                  "Id": str()
              }
          ]),
        
          (Type=Video) 'VideoType': str(),
          (Type=Video) 'Video3DFormat': str(),
          (Type=Video) 'IsoType': str(),
          (Type=Video and HasSubtitles) 'HasSubtitles': bool(),
          (Type=Video and AdditionalParts) 'PartCount': int(),
          (Type=Video and Fields=MediaSourceCount) 'MediaSourceCount': int(),
          (Type=Book, Video and Fields=Chapters) 'Chapters': array([
              {
                  "StartPositionTicks": int(),
                  "Name": str(),
                  (ImageTag) "ImageTag": str(),
              },
              {
                  "StartPositionTicks": int(),
                  "Name": str(),
                  (ImageTag) "ImageTag": str(),
              }
          ]),
          (Fields=MediaStreams, MediaSources) 'MediaSources': array([
              {
                  "SupportsDirectStream": bool(),
                  "Container": str(),
                  "RequiresClosing": bool(),
                  "IgnoreDts": bool(),
                  "IgnoreIndex": bool(),
                  "SupportsDirectPlay": bool(),
                  "MediaStreams": array([
                      {
                          "IsInterlaced", bool(),
                          "Index", int(),
                          "AverageFrameRate", float(),
                          "Width", int(),
                          "VideoRange": str(),
                          "Codec", str(),
                          "IsForced", bool(),
                          "AspectRatio", str(),
                          "Type", str(),
                          "IsTextSubtitleStream": bool(),
                          "Profile", str(),
                          "DisplayTitle": str(),
                          "SupportsExternalStream": bool(),
                          "CodecTimeBase": str(),
                          "RealFrameRate": float(),
                          "CodecTag": str(),
                          "Level": int(),
                          "RefFrames": int(),
                          "TimeBase": str(),
                          "BitRate", int(),
                          "IsDefault", bool(),
                          "IsAnamorphic", bool(),
                          "Height", int(),
                          "PixelFormat", str(),
                          "IsExternal", bool(),
                          "Language", str(),
                          "ChannelLayout", str(),
                          "Path", str(),
                          "Channels", int(),
                          "SampleRate", int(),
                          "Comment", str(),
                          "NalLengthSize", str(),
                          "IsAvc", bool(),
                          "Title", str(),
                          "ColorPrimaries", str(),
                          "ColorSpace", str(),
                          "ColorTransfer" str()
                      }
                  ]),
                  "Type": str(),
                  "ReadAtNativeFramerate": bool(),
                  "RequiresLooping": bool(),
                  "Path": str(),
                  "RequiresOpening": bool(),
                  "Bitrate": int(),
                  "IsRemote": bool(),
                  "Name": str(),
                  "RequiredHttpHeaders": {},
                  "SupportsTranscoding": bool,
                  "Formats": array([]),
                  "Protocol": str(),
                  "IsInfiniteStream": bool(),
                  "GenPtsInput": bool(),
                  "VideoType": str(),
                  "ETag": str(),
                  "RunTimeTicks": int(),
                  "SupportsProbing": bool(),
                  "Id": (str) ,
              }
          ]),
        
          (Type=Video and HasSpecialFeatures) 'SpecialFeatureCount': int(),
          (Type=Episode) 'IndexNumberEnd': int(),
          (Type=Episode) 'SeriesName': str(),
          (Type=Episode and Fields=SpecialEpisodeNumbers) 'AirsAfterSeasonNumber': int(),
          (Type=Episode and Fields=SpecialEpisodeNumbers) 'AirsBeforeEpisodeNumber': int(),
          (Type=Episode and Fields=SpecialEpisodeNumbers) 'AirsBeforeSeasonNumber': int(),
          (Type=Episode and SeasonId) 'SeasonId': str(),
          (Type=Episode. Season) 'SeasonName': str(),
          (Type=Episode, Season and SeriesId) 'SeriesId': str(),
          (Type=Episode, Season and Series) 'SeriesPrimaryImageTag': str(),
          (Type=Episode, Season and Fields=SeriesStudio and Series) 'SeriesStudio': str(),
          (Type=Series) 'AirDays': array([int(0=Sunday, 1=Monday, 2=Tuesday, 3=Wednesday, 4=Thursday, 5=Friday, 6=Saturday)])
          (Type=Series) 'AirTime': str()
          (Type=Series) 'Status': str()
        }

**Comment by LukePulverenti** [comment]
Hi, thanks for the info. Just for some context, Genres came first and there is a field for that. GenreItems was added later so that we could include the GenreId so that apps could query by genre id instead of genre name. We couldn't change the structure of the Genres property without breaking apps so had to just introduce GenreItems. This is just intended to be a substitute for Genres.

**Comment by LukePulverenti** [comment]
Since we've already had this for a couple years now, I'll just make sure the wiki is up to date but I'm not going to make a change at this point, thanks.
