### ISSUE TITLE
latest releases missing from docker hub

### ISSUE THREAD

**Issue by mathroc** [MediaBrowser/Emby#3284]
Hi,

I'm not sure this is the correct repository for this but the releases since 3.4.1.2 are missing here : https://hub.docker.com/r/emby/embyserver/tags/

**Comment by LukePulverenti** [comment]
Docker betas are currently on pause while we work out some changes. Thanks.

**Comment by LukePulverenti** [comment]
Updated docker betas are on the way up. Thanks.

**Comment by mathroc** [comment]
thank you @LukePulverenti !
