### ISSUE TITLE
Preserve music player state between page reloads

### ISSUE THREAD

**Issue by KristupasSavickas** [MediaBrowser/Emby#3289]
Playing music using the "Play On" feature on the web interface and reloading/closing the tab results in a weird situation, where music keeps playing, but playback is impossible to control form the newly opened tab.

My suggestion would be to track "active" players on a per-user basis and display the player on page load if it exists.

**Comment by KristupasSavickas** [comment]
On further investigation this applies to video player as well

**Comment by KristupasSavickas** [comment]
Turns out I was wrong about this, the player state is preserved, I just needed to select the device I used before closing the window.

**Comment by LukePulverenti** [comment]
Thanks for the feedback !
