### ISSUE TITLE
[ANDROID App] Pause button disappears

### ISSUE THREAD

**Issue by ztheoz** [MediaBrowser/Emby#3292]
Hi, 
I've this issue since à long time : when I hit the pause button several times (let's say 3 or 4 times) it disappears. The only way I have to have it back is to start a new video or restart the video.
I have the latest version of emby server and the android app, I'm using Debian stetch and Android 8.0 (oxygen OS) on a One Plus 3.
Here is a screenshot : 
![screenshot_20180526-160316_01_01](https://user-images.githubusercontent.com/32197190/40577025-2490434a-60ff-11e8-937e-906a1ca454f2.jpg)
Thanks!

**Comment by LukePulverenti** [comment]
Thanks for the report. Please try this again with the next update to the app.

**Comment by LukePulverenti** [comment]
Resolved for next app update, thanks.
