### ISSUE TITLE
Added support for WD My Cloud 

### ISSUE THREAD

**Issue by stefaang** [MediaBrowser/Emby#3298]
I added [support](https://github.com/WDCommunity/wdpksrc/releases/tag/emby-v0.01) for WD My Cloud NAS but it's not so easy to unpack the .deb files.
Now I need to get entware tar to be able to unpack an LZMA compressed archive.
See [here](https://github.com/WDCommunity/wdpksrc/blob/master/wdpk/emby/install.sh)

If simpler tarball releases would be available both for x64 and ARM, I could drop the entware requirement for installation.
The install directory for this platform is `/shares/Volume_1/Nas_Prog/emby`.

Any suggestions?

**Comment by LukePulverenti** [comment]
I didn't know there were x64 WD's? I thought they were all armel. It's been a while since I've looked at them all. I assume by arm you mean armel?

**Comment by stefaang** [comment]
The DLxxxx and PRxxxx line is x64, the rest is armhf afaik.
More info [here](https://docs.google.com/spreadsheets/d/1kdgN_Dn58hR8psrTnMHZNmpzxY6BfKERAzWCF6J5XcA/edit#gid=0)
They've also recently launched the My Cloud Home, a new product line with android M... looks like a good candidate for https://emby.media/community/index.php?/topic/53944-emby-server-for-android/

**Comment by alucryd** [comment]
While the arm CPUs from Marvell are indeed armhf capable, the WD firmware is armel and won't run armhf code. Did you try running your package on any of the arm models?

**Comment by stefaang** [comment]
No I don't have an arm model, but the EX models have docker and they are able to run armhf images according to [here](https://community.wd.com/t/installation-of-app-via-ssh-in-wd-my-cloud-ex4100/148667/4) and [here](https://community.wd.com/t/can-sickbeard-be-installed-on-ex4/146879/2).

**Comment by stefaang** [comment]
Thanks for the detailed explanation.
Would it be possible to get around this limitation by adding ld-linux-armhf.so.3 to the WD binary package and load it with LD_LIBRARY_PATH?

**Comment by alucryd** [comment]
Possibly, but that's where the in theory comes in, I already tried on my EX2 Ultra to no avail, the dotnet runtime refused to work even with the right dynamic linker. I should give docker another try though, it's way easier to do the testing with it.

**Comment by alucryd** [comment]
Now that I know there are x64 models, I tried adding wd packages to our builds, but I don't have any x64 wd device at hand. Would you be willing to give them a try?

**Comment by LukePulverenti** [comment]
You can participate in testing here: https://emby.media/community/index.php?/topic/59597-emby-server-for-western-digital-nas/

Thanks guys.

**Comment by LukePulverenti** [comment]
Closing. This will be up on the website soon. Thanks everyone.
