### ISSUE TITLE
Error when playing movie emby 3.4.1.0

### ISSUE THREAD

**Issue by jgomez709** [MediaBrowser/Emby#3300]
Dear:

my problem is the same as the one mentioned here: https://github.com/MediaBrowser/Emby/issues/3103

except that to me you think with several pecliculas and that I have reinstalled and cleaned twice already emby, and it is not solved.

I have the following problem:

Stream mapping:
  Stream # 0: 2 -> # 0: 0 (h264 (native) -> h264 (libx264))
  Stream # 0: 0 -> # 0: 1 (ac3 (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] For help
[libx264 @ 0x12e9bc0] using SAR = 302/303
[libx264 @ 0x12e9bc0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
[libx264 @ 0x12e9bc0] profile Main, level 4.1
[libx264 @ 0x12e9bc0] 264 - core 152 r2851 + 3 e9a5903 - H.264 / MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac = 1 ref = 1 deblock = 1: 0: 0 analyze = 0x1: 0 me = day subme = 0 psy = 1 psy_rd = 1.00: 0.00 mixed_ref = 0 me_range = 4 chroma_me = 0 trellis = 0 8x8dct = 0 cqm = 0 deadzone = 21.11 fast_pskip = 1 chroma_qp_offset = 0 threads = 9 lookahead_threads = 1 sliced_threads = 0 nr = 0 decimate = 1 interlaced = 0 bluray_compat = 0 constrained_intra = 0 bframes = 3 b_pyramid = 2 b_adapt = 1 b_bias = 0 direct = 1 weightb = 1 open_gop = 0 weightp = 1 keyint = 250 keyint_min = 23 scenecut = 40 intra_refresh = 0 rc_lookahead = 10 rc = crf mbtree = 1 crf = 23.0 qcomp = 0.60 qpmin = 0 qpmax = 69 qpstep = 4 vbv_maxrate = 1616 vbv_bufsize = 3232 crf_max = 0.0 nal_hrd = none filler = 0 ip_ratio = 1.40 aq = 1: 1.00
frame = 122 fps = 0.0 q = 0.0 size = N / A time = -577014: 32: 22.77 bitrate = N / A speed = N / A
Too many packets buffered for output stream 0: 0.
[libx264 @ 0x12e9bc0] frame I: 3 Avg QP: 14.77 size: 5109
[libx264 @ 0x12e9bc0] frame P: 36 Avg QP: 19.41 size: 5183
[libx264 @ 0x12e9bc0] frame B: 90 Avg QP: 20.70 size: 2610
[libx264 @ 0x12e9bc0] consecutive B-frames: 3.8% 7.7% 2.3% 86.2%
[libx264 @ 0x12e9bc0] mb I I16.4: 69.1% 0.0% 30.9%
[libx264 @ 0x12e9bc0] mb P I16.4: 34.6% 0.0% 0.0% P16.4: 35.2% 0.0% 0.0% 0.0% 0.0% skip: 30.3%
[libx264 @ 0x12e9bc0] mb B I16..4: 8.5% 0.0% 0.0% B16..8: 22.2% 0.0% 0.0% direct: 7.9% skip: 61.4% L0: 35.7% L1: 42.1% BI: 22.1%
[libx264 @ 0x12e9bc0] coded y, uvDC, uvAC intra: 37.9% 51.8% 12.2% inter: 14.3% 21.8% 0.6%
[libx264 @ 0x12e9bc0] i16 v, h, dc, p: 32% 29% 15% 23%
[libx264 @ 0x12e9bc0] i4 v, h, dc, ddl, ddr, vr, hd, vl, hu: 11% 22% 14% 22% 4% 2% 4% 5% 16%
[libx264 @ 0x12e9bc0] i8c dc, h, v, p: 39% 27% 18% 17%
[libx264 @ 0x12e9bc0] Weighted P-Frames: Y: 27.8% UV: 27.8%
[libx264 @ 0x12e9bc0] kb / s: 649.49
Conversion failed!

the movie that I try to reproduce has the following metadata:

Audio
Title: Dolby Digital Spa 6 ch Default
Language: spa
Codec: AC3
Channels: 6 ch
Sampling frequency: 48000 Hz
Default: Yes
====================================================================================
Audio
Title: Eng DTS 5.1
Language: eng
Codec: DTS
Profile: DTS
Design: 5.1
Channels: 6 ch
Bit rate: 1536 kbps
Sampling frequency: 48000 Hz
Default: No

========================================================
Video
Title: 1080P H264
Codec: H264
AVC: Yes
Profile: High
Level: 41
Resolution: 1920x808
Aspect ratio: 2.40: 1
Anamorphic: No
Interlaced: No
Pictures per second: 23.9759865
Bit rate: 11035 kbps
Bit depth: 8 bit
Pixel format: yuv420p
Reference pictures: 1
NAL: 4

the problem only appears when I select the audio "TitleSpa Dolby Digital 6 ch Default", because when I select the audio "Title: Eng DTS 5.1".

I am using version "Version 3.4.1.0" of emby server in linux Ubuntu 16.04.4 LTS.

Any idea how to fix it?

Here is the link to the movie:
https://mega.nz/#F!xU0XFa4R!TOooO9CL_8JxeOLZmwrOoQ

Greetings.

**Comment by LukePulverenti** [comment]
Thanks, I think you opened a topic in our community so we'll assist you there.

**Comment by LukePulverenti** [comment]
Closing this as we are discussing this in the community. Thanks.
