### ISSUE TITLE
JS source code for the HTML5 frontend

### ISSUE THREAD

**Issue by flaviut** [MediaBrowser/Emby#3301]
Hi, I'm looking to make some changes to the frontend of the application, but all I'm able to find is the minified scripts in `MediaBrowser.WebDashboard/dashboard-ui/`.

Can someone please point me in the right direction to get the unminified versions? It might be a good idea to place a README file in that directory too, so that anyone else who's looking for those scripts knows where to go to modify them.

**Comment by LukePulverenti** [comment]
They currently aren't available. It's just easier for our build process right now to keep the output files in the repository. At some point we will look at reworking this. Thanks.
