### ISSUE TITLE
Ignore .AppleDouble folders in library scan

### ISSUE THREAD

**Issue by flexarts** [MediaBrowser/Emby#3305]
Hi,

Recently I noticed that I started to get a lot of duplicate entries in the Metadata when scanning libraries which have **.AppleDouble** folders with the same filenames as the parent folder.

Unfortunately I have a lot of such folders and it is no solvable using the **.ignore** file feature of Emby because I would need to go through each folder checking for .AppleDouble sub-folders.

Also I am a happy Emby Server user since 4 years and never had that problem before... 
Did something change regarding the folder ignore?

Cheers Dom

**Comment by LukePulverenti** [comment]
This is resolved for the next release, thanks.
