### ISSUE TITLE
https server unreachable

### ISSUE THREAD

**Issue by lapoigne** [MediaBrowser/Emby#3314]
On my Emby server on Synology DS414, in can't connect on https version (port 8920) with web browser.
If I restart Emby it's work, but after some time I can't reconnect.
No problems with http version.

What log can I post to debug that ?

**Comment by LukePulverenti** [comment]
the server log would be good, thanks.

**Comment by lapoigne** [comment]
After 4 day of running good, no https server
[emby.log](https://github.com/MediaBrowser/Emby/files/2096840/emby.log)

**Comment by LukePulverenti** [comment]
Resolved for next release, thanks.
