### ISSUE TITLE
Alternate versions not working if version starts with number

### ISSUE THREAD

**Issue by chowbok** [MediaBrowser/Emby#3317]
Currently running version 3.4.1.14 beta on Arch Linux. I have two versions of _The Phantom of the Opera_, in the directory "The Phantom of the Opera (1925)". If I name them like this, it doesn't recognize them as alternate versions:

- The Phantom of the Opera (1925) - 1925 version.mkv
- The Phantom of the Opera (1925) - 1929 version.mkv

If I change the names thusly, it works fine:

- The Phantom of the Opera (1925) - original.mkv
- The Phantom of the Opera (1925) - rerelease.mkv

I'm assuming it's because the "alternate" string in the former starts with a number, but perhaps it's some other issue.

**Comment by LukePulverenti** [comment]
Dev note: I've created a failing unit test for this in the Emby.Naming project, so ideally all that needs to happen is getting that test to pass, without breaking any others.

**Comment by softworkz** [comment]
Coulldn't find _any_ unit test in that project..

**Comment by LukePulverenti** [comment]
Resolved in Emby Server 3.6.
