### ISSUE TITLE
Playlists with paths containing certain characters are not imported

### ISSUE THREAD

**Issue by amura11** [MediaBrowser/Emby#3320]
When importing m3u playlists that have paths that have the characters `~`, `[`, or `]` in them they are not imported. The paths are correct and other files that don't have these characters are imported correctly. I looked through my logs and I don't see any errors or exceptions regarding these files. The playlists work fine in other applications so it doesn't seem to be an issue with the playlists themselves either.

**Comment by LukePulverenti** [comment]
Resolved for next release, thanks.
