### ISSUE TITLE
Add last.fm as music artist picture provider

### ISSUE THREAD

**Issue by KristupasSavickas** [MediaBrowser/Emby#3323]
The current providers for music artist pictures (FanArt and TheAudioDB) fail to find pictures for many artists, and many are incorrect or vastly outdated. I've seen multiple apps (Shuttle for android comes to mind) that use last.fm for providing artist images and it's seems to be quite accurate.

**Comment by LukePulverenti** [comment]
I've resurrected our old lastfm plugin into a new repository. I will help ensure it is compatible with newer versions of Emby Server, but we will have to depend on community help to ensure it is still compatible with last fm.

The source can be found here:
https://github.com/MediaBrowser/Lastfm

Thanks !

**Comment by LukePulverenti** [comment]
Keep in mind that fanart.tv has the highest quality music images available, and we already have audiodb as a secondary option. I haven't seen too many incorrect ones on those.
