### ISSUE TITLE
Only show albums that the artist is labeled as album artist in the artist's page

### ISSUE THREAD

**Issue by KristupasSavickas** [MediaBrowser/Emby#3324]
Currently albums that the artist if featured on are shown as if they were albums of his own. I think it would be better to separate the albums that the artist is labeled as album artist from the ones the artist is featured on, by putting them in a separate section on the artist's page.

**Comment by LukePulverenti** [comment]
I've resurrected our old lastfm plugin into a new repository. I will help ensure it is compatible with newer versions of Emby Server, but we will have to depend on community help to ensure it is still compatible with last fm.

The source can be found here:
https://github.com/MediaBrowser/Lastfm

Thanks !

**Comment by LukePulverenti** [comment]
Sorry, wrong issue.

**Comment by LukePulverenti** [comment]
This will be in the next release, thanks.
