### ISSUE TITLE
Last.fm plugin

### ISSUE THREAD

**Issue by KristupasSavickas** [MediaBrowser/Emby#3325]
We have a trakt.tv plugin for movies/tv shows, maybe we could have a plugin for music with last.fm?

**Comment by LukePulverenti** [comment]
I've resurrected our old lastfm plugin into a new repository. I will help ensure it is compatible with newer versions of Emby Server, but we will have to depend on community help to ensure it is still compatible with last fm.

The source can be found here:
https://github.com/MediaBrowser/Lastfm

Thanks !
