### ISSUE TITLE
Emby Connect: Cannot use email addresses with "." or "+" in them

### ISSUE THREAD

**Issue by rpatterson** [MediaBrowser/Emby#3326]
I was trying to test out Emby Connect before inviting a friend and was trying to use Gmail `+` aliases, but I never got the Emby Connect invite emails.  The same was true for adding `.` to email addresses.  I confirmed that sending mail to this addresses through other MTAs worked just fine.

Firstly, email addresses with `.` in them should definitely work so that's a definite bug in Emby Connect.  Secondly, using addreses with `+` in them is very useful for testing and/or filtering and should also be supported.

**Comment by ebr11** [comment]
Hi.  Can you tell us exactly what you did and what happened?  Also, did these people already have Connect accounts or no?

Thanks.

**Comment by jaketame** [comment]
Side issue but could be related;

I can no longer add an alias to a user who was invited by emby connect?

**Comment by ebr11** [comment]
> I can no longer add an alias to a user who was invited by emby connect?

I'm not sure what you mean but please ask this different question in the forums.  Thanks.

**Comment by LukePulverenti** [comment]
@rpatterson Can you answer these questions? Thanks !

**Comment by ebr11** [comment]
Hi. I tested an email of "test.account@domain.com" and received the email without issue.

For the "+" one, I believe if you simply omit the "+" it should work as well since Gmail ignores those anyway.

Please let us know if you still have an issue with this and under what specific conditions and we can re-open.  Thanks.
