### ISSUE TITLE
Collections under Movies not separated by library

### ISSUE THREAD

**Issue by LukePulverenti** [MediaBrowser/Emby#3327]

**Comment by Attidudinal** [comment]
Covers half of the issue concerning the presentation of 'sets' within Emby.  The 'other' half of the presentation WITHIN a Library, that of folders, is probably better off relegated to a seperate ticket.
I am relatively new to Emby and was not familiar with submission process - thanks to Luke for the submission of this ticket. Refer to Folders under Movies for the other submission.

**Comment by LukePulverenti** [comment]
Resolved for Emby Server 3.6.
