### ISSUE TITLE
Folders under Movies not represented

### ISSUE THREAD

**Issue by Attidudinal** [MediaBrowser/Emby#3329]
Need the ability to present the folders (directories) underlying (comprising) a given Library WITHIN the Library structure - avoids having to create all kinds of Collections to represent that which already exists.
(Or, in the alternative, to create numerous Libraries to represent each of the sub-sets.)
It also 'frees' the concept of a Collection to be used to make other logical connections within each of the given sub-sets (folders).
Note:  This goes hand-in-hand with the ability to show those Collections that pertain to a given Library which are ONLY members of that Library (Ticket #3327); all in keeping with the concepts of Set Theory.

**Comment by LukePulverenti** [comment]
The libraries will have a folders tab in the next release. thanks.
