### ISSUE TITLE
[Feature Request] Throttle transcoding / remux

### ISSUE THREAD

**Issue by jaketame** [MediaBrowser/Emby#3334]
I can't seem to find anything relating to throttling transcoding / remux?

Problem:
 - 4K Transcoding / Remux - It uses a lot of space thus drives are filling up based on transcoding settings at the moment as Emby is transcoding the whole file, thus with a 4K remux / transcode this could be 60GB and multiple this if you have multiple users.

Remuxing seems to cause problems event when its out remuxing audio / container as it will fill up the disk.

Fix:
- Ability to throttle transcoding to be 5-10 minutes ahead of current time

**Comment by LukePulverenti** [comment]
Added in 3.6:
https://emby.media/community/index.php?/topic/62657-36040-transcode-throttle-is-back/
