### ISSUE TITLE
Change in settings button behaviour from 3.4.1.18 beta onwards

### ISSUE THREAD

**Issue by diegoviso** [MediaBrowser/Emby#3340]
I'm not sure if it is intentional, from 3.4.1.18 the Settings cog/spanner icon on the header tab now directs to user preferences instead of the server dashboard. This seems redundant as the user icon does the same. Hopefully this change can be reverted so the Settings cog icon directs to the dashboard.

The change is found in librarymenu.js, function onSettingsClicked. 

Previous to 3.4.1.18 
function onSettingsClick(e){Dashboard.navigate("dashboard.html")}

From 3.4.1.18 onwards
function onSettingsClick(e){{Dashboard.navigate("mypreferencesmenu.html")}

Thanks

**Comment by LukePulverenti** [comment]
Resolved, thanks.
