### ISSUE TITLE
Transcoding not working on Android Server

### ISSUE THREAD

**Issue by thelittlefireman** [MediaBrowser/Emby#3346]
Transcoding not workings, log always show : 
```[amediaformat` @ 0xead17040] No Java virtual machine has been registered
[hevc_mediacodec @ 0xeac07f80] Failed to create media format
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (hevc_mediacodec) -> h264 (libx264))
  Stream #0:1 -> #0:1 (dts (dca) -> mp3 (libmp3lame))
Error while opening decoder for input stream #0:0 : Generic error in an external library
ffmpeg version 4.0 Copyright (c) 2000-2018 the FFmpeg developers
  built with Android clang version 5.0.300080 (based on LLVM 5.0.300080)```

i try on several format : 

emby logs : [embylogs](https://file.io/8rUzcw)
ffmpeg log : 
[ffmpeg-transcode](https://file.io/KdLv8V)
[ffmpeg-transcode](https://file.io/osj8Uy)
[ffmpeg-transcode](https://file.io/VijbhA)
[ffmpeg-transcode](https://file.io/Gc7hBd)
[ffmpeg-transcode](https://file.io/9mC7qK)

thanks for all

Thomas

**Comment by LukePulverenti** [comment]
Resolved for next update, thanks.
