### ISSUE TITLE
Kodi with emby cinema mode

### ISSUE THREAD

**Issue by bygadd** [MediaBrowser/Emby#3348]
Hi, i use emby server versuion 3.4.1.0  on my QNAP with firmware vrsion 4.3.4.0597 from a while and few days ago, i do subscribeing to emby because i need to use cinema mode on my KODI player.

My problem is, i can't setup the movie trailers to get playback.
The setup in emby addon, is to ask before playback trailer and when i konfirm to play, the error mesage appere "emby error : se log for more info".

I do not have any issues, when i play trailers thrue web player from emby server!

Can you help me to resolve this issue?
I attaching my log:
[kodi.log](https://github.com/MediaBrowser/Emby/files/2166701/kodi.log)

**Comment by LukePulverenti** [comment]
Hi there, welcome. Please open this topic in our Kodi repository:
https://github.com/MediaBrowser/plugin.video.emby
However, since you also posted in our support community, we can just keep the discussion there and respond to you in one place. Thanks.
