### ISSUE TITLE
force audio-transcoding

### ISSUE THREAD

**Issue by smoebody** [MediaBrowser/Emby#3356]
Sorry to bother you again with this issue. I searched a long time and found many threads regarding the emby+chromecast2+crappy-tv setup.

Indeed my TV supports ac3-decoding, but not usable for me. I am actually not using the tv-speakers but the digital-outputplug of the tv to get the sound to my external audio-receiver (only capable of good old stereo input) which receives an ear-smashing audio-noise because appearently it is not able to decode the audio-stream

So here is my request: please make it configurable what is acceptable by the renderer. I think this can prevent a lot of headache for users and developers. Plex is providing profiles for this case. Maybe something similar could be used for emby as well.

**Comment by LukePulverenti** [comment]
This will be handled by #3388 - Add in app settings to indicate support pass-through formats

Thanks !
