### ISSUE TITLE
/opt/emby-server/lib/libsamdb.so.0: invalid ELF header

### ISSUE THREAD

**Issue by scrimpy** [MediaBrowser/Emby#3362]
/opt/emby-server/bin/ffmpeg -i file:"/Yellow Brick Road (2010)/Yellow Brick Road (2010).mkv" -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -vf "scale=trunc(min(max(iw\,ih*dar)\,1920)/2)*2:trunc(ow/dar/2)*2" -pix_fmt yuv420p -preset slow -crf 23 -maxrate 9932262 -bufsize 19864524 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames "expr:if(isnan(prev_forced_t),eq(t,t),gte(t,prev_forced_t+2))" -copyts -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 384000 -af "volume=2" -f segment -max_delay 5000000 -avoid_negative_ts disabled -map_metadata -1 -map_chapters -1 -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 0 -segment_list "/tmp/transcoding-temp/c5fbb33d371a992f53237e565e4badd0.m3u8" -y "/tmp/transcoding-temp/c5fbb33d371a992f53237e565e4badd0%d.ts"

/opt/emby-server/bin/ffmpeg: error while loading shared libraries: /opt/emby-server/lib/libsamdb.so.0: invalid ELF header
/opt/emby-server/bin/ffmpeg: error while loading shared libraries: /opt/emby-server/lib/libsamdb.so.0: invalid ELF header

**Comment by LukePulverenti** [comment]
Please attach the complete ffmpeg log and the emby server log. thanks.

**Comment by scrimpy** [comment]
fixed it by taking my systems libsamdb.so.0

**Comment by LukePulverenti** [comment]
Can you please provide the requested information so that we can learn more about what happened and what you were trying to do? thanks.
