### ISSUE TITLE
Emby does not recognize subtitles of multi version movies

### ISSUE THREAD

**Issue by sauerj** [MediaBrowser/Emby#3364]
This issue is valid for: emby-server 3.4.1.0 and 3.5.0.0

My movies are organized like this:

- LIBRARY/Movie Name/Movie Name - 720p.mkv
- LIBRARY/Movie Name/Movie Name - 1080p.mkv

The SubtitleManger download the subtiltes just for one version and save them as:
- Movie Name - 1080p.lang.srt

Emby now shows only the subtiltes for version "1080p" not for "720p".

It is understandable why emby does this, because only one movie has an exact subtitle file name match. This will lead to manually download the subtitles for the other version. It seems that SubtitleManger only downloads subtitles for the filename which is in the MetadataManager.

Is it possible to enable a lesser strict file name matching for subtitles when a multi version movie is detected?

**Comment by LukePulverenti** [comment]
This is resolved in Emby Server 4.2. The subtitle download scheduled task will download for all versions now. Thanks.
