### ISSUE TITLE
Chromecast streaming is a nightmare!

### ISSUE THREAD

**Issue by graphixillusion** [MediaBrowser/Emby#3370]
Hi there. I would like to report that streaming on chromecast is a real nightmare! The stream stucks very often during play and i need to disconnect and reconnect to make it works again. I'm streaming through emby on android and the server is on Windows 10 machine. Another issue to report is that after the stream freeze, when i try to resume the movie, it always starts from the beginning and it will not resume from the last view. I have those issues since a while right now and it's very annoying! Thank you!

**Comment by LukePulverenti** [comment]
Please attach the information requested in how to report a problem:
https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/
THanks.

**Comment by LukePulverenti** [comment]
Closing this since we are already helping you in the Emby community, and one place is sufficient. Thanks !
