### ISSUE TITLE
3.5.0.0 macOS release?

### ISSUE THREAD

**Issue by brianmorton** [MediaBrowser/Emby#3371]
will there be one? asking as a homebrew maintainer.

**Comment by LukePulverenti** [comment]
What have you been using as the basis for homebrew? Everything has been tagged and done the same way as previous releases.

**Comment by brianmorton** [comment]
the github releases page.

for example our latest binary for you is `3.4.1.0` located here:
```
https://github.com/MediaBrowser/Emby/releases/download/3.4.1.0/embyserver-osx-x64-3.4.1.0.zip
```
however there is no equivalent for `3.5.0.0` on your [releases page](https://github.com/MediaBrowser/Emby/releases), although I do see you have one [linked](https://github.com/MediaBrowser/Emby.Releases/releases/download/3.5.0.0/embyserver-osx-x64-3.5.0.0.zip) from the website.

I suppose the issue was created to wonder whether the releases page would be featuring macOS releases from now on,  or if they would only be available from the website?

**Comment by brianmorton** [comment]
I will switch our stuff over to use your releases repo: https://github.com/MediaBrowser/Emby.releases/releases

Would you agree that is best?

**Comment by LukePulverenti** [comment]
Yes that would be great, thanks !

**Comment by brianmorton** [comment]
Thanks!

**Comment by LukePulverenti** [comment]
Hey, just one to confirm that when installing through ports, does the server end up in the Applications folder similar to our MacOS install instructions on the website? The instructions ask them to drag it into Applications. The server has to be run from there rather than an arbitrary location or it will be denied access by the system to do certain things, such as launch it's embedded ffmpeg. Thanks.

**Comment by brianmorton** [comment]
I don't know anything about what macports does, but most homebrew cask applications work that way. After looking at the [cask file](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/emby-server.rb), I would say this one does as well.

**Comment by LukePulverenti** [comment]
Perfect, thanks.
