### ISSUE TITLE
Add a 'Read More' Tag for synopsis

### ISSUE THREAD

**Issue by jee-r** [MediaBrowser/Emby#3372]
Hello 

Please, would it be possible to add a 'Read More' tag after X lines on the synopsis (description) of an artist and album it would avoid scrolling the whole page to reach the albums/tracklist. 

Eg. Pink Floyd Artist Page : 
![long synopsis emby Artist ](https://user-images.githubusercontent.com/10530469/43000521-0d59e764-8c22-11e8-8804-6d67a02dd1c9.jpg)
Eg. Album Page
![long synopsis emby-album](https://user-images.githubusercontent.com/10530469/43000973-ce786500-8c23-11e8-875c-73747bc7a354.jpg)

Thank you

**Comment by LukePulverenti** [comment]
This will be in Emby Server 4.4. Thanks !
