### ISSUE TITLE
Android app phoning home every ~15mn

### ISSUE THREAD

**Issue by MatMaul** [MediaBrowser/Emby#3382]
The android app seems to call home every 15mn, this is really annoying because it wakes up my HDD on my NAS to write this to the logs.
I guess it also eat a bit of my phone battery too.

Why is it the case, I don't see any feature that would need that ?
Can we at least have an option to disable that ?

Thanks.

**Comment by softworkz** [comment]
> Why is it the case, I don't see any feature that would need that ?
Features:
- Remote Control: The server needs to know which devices are online
- Synchronization: Clients apps need to check regularly if there's some content to synchronize

> Can we at least have an option to disable that ?

We are supporting Wake-On-LAN for local networks where the server may go to sleep (not just a single HD). Some routers are also available that support this and wake up your machine when a request is received on a certain port.

But Emby is a server application and when it is running it requires unconditional access to the file system. This includes the location of its binaries and all locations containing program data or temporary data. It's an incorrect assumption that it would just be some log entries written that are causing the HDD spin-up. Instead, this would be a neverending story: After preventing log entries being written, we would find out, that Emby is reading from the user database that may cause a file operation, then a client wants to check for new sync items to download, the server needs to update the list of active devices and this needs to be written to disk. Even for unsolicited scanning requests, it is inevitable to perform certain file operations.

To really achieve what you want - "running Emby from memory" - we would need to implement some massive changes that would also introduce a number of other drawbacks.

So bear with me - but your case is pretty exotic and does not justify the effort imo.

I would recommend: Put Emby or its data on an ssd or some usb memory. 

You should also consider: HD spinup and spindown may save energy, but it decreases lifetime and reliability on the other side.

**Comment by MatMaul** [comment]
Let's forget about the HD spin-up, as you said it's not really made for HDD staying off. I stopped that battle, Emby is not even the main offender here, a lot of logs from official apps triggers it too. I'll just put some phonic isolation around my NAS :)

It's still a problem for me that Emby app wake up my phone every 15mn. I understand the need of sync for the mentioned functionalities, but since it doesn't use any push mechanism can we have an option to configure the delay ?

**Comment by softworkz** [comment]
Implementing push notifications is planned and will arrive soon. 

Regarding sync in general, introducing a configurable check interval would just add another factor of uncertainty to the story, while we're actually aiming to make it even more reliable.

An option that I could imagine instead would be one to fully disable sync for those who don't want or need it. But I'm just chatting here, that would need to be discussed internally.

**Comment by MatMaul** [comment]
Yes would be nice to have a global option until push arrive. Thanks for the feedback.

**Comment by LukePulverenti** [comment]
This is resolved for the next update to the android app, with Emby Server 4.0+. Thanks !
