### ISSUE TITLE
Transcoding files with multiple languages 

### ISSUE THREAD

**Issue by CordlessWool** [MediaBrowser/Emby#3392]
I opened in the past a issue because of missing transcoding with multiple langues [3147](https://github.com/MediaBrowser/Emby/issues/3147).

I could not reopen the ticket so I will write a new one if it is ok? It was marked as done but I is still not done. I spend again some money to a premium account, because of thinking it was done. But the only thing was changed, is that the files now could save to the same folder. But like syncing files to an other folder the media is shown twice. So the things I am missing are:

- detected media that are converted as once (e.g. same movie) and choose best version at playback.
- transcoding files with all existing languages and sub titles

**Comment by LukePulverenti** [comment]
In Emby Server 4.1 we are looking into preserving all audio tracks when using the conversion and sync features. Thanks.

**Comment by LukePulverenti** [comment]
This will be in Emby Server 4.1, thanks.
