### ISSUE TITLE
Binding to priviledged ports

### ISSUE THREAD

**Issue by xaqq** [MediaBrowser/Emby#3395]
Hello, I've been running Emby on port 80 and 443 by using `cap_net_bind_service+eip` on both `emby-server` and `EmbyServer.dll`. It used to work without issue.

However, when using the latest 3.5.2 version this does not work anymore.
Can anyone point me toward what may have changed that could have broken this ?

The reason i'm using `cap_net_bind_service` instead of NAT etc is because I'm running emby in a container so I wanted to perform as little additional config as possible.

**Comment by LukePulverenti** [comment]
Can you please describe "does not work"? Thanks.

**Comment by LukePulverenti** [comment]
Closing due to abandonment, but please feel free to re-open with the requested information. Thanks !
