### ISSUE TITLE
Hebrew Subtitles - Weird behaviour in multiple devices

### ISSUE THREAD

**Issue by BuSHari** [MediaBrowser/Emby#3399]
Hello,

A few months ago i've opened an issue regarding the punctuation problem in iOS & tvOS for the Hebrew languages, you can see the issue here: https://github.com/MediaBrowser/Emby/issues/3137

In the last Beta version i saw that this issue is partialy resolved, now the punctuation appears in the correct way, but sometimes there is a '-' in the end of the line instead of a dot, see photo for example:
![image](https://user-images.githubusercontent.com/1271474/43773589-dfc5c1c0-9a4e-11e8-833f-421c686c9b82.png)

But when i play the video in the Chrome browser on my Mac i have the punctuation problem, see photo for example:
![image](https://user-images.githubusercontent.com/1271474/43774831-293a8508-9a53-11e8-887f-819c60a21da2.png)

Here is the Subtitles file: 
[Escape Plan 2 Hades 2018 - [Bluray-1080p]-LEGi0N.heb.forced.srt.zip](https://github.com/MediaBrowser/Emby/files/2266241/Escape.Plan.2.Hades.2018.-.Bluray-1080p.-LEGi0N.heb.forced.srt.zip)

Here is Emby Server log file:
[Server_Logs.zip](https://github.com/MediaBrowser/Emby/files/2266261/Server_Logs.zip)

Also posted a new topic in the community:
https://emby.media/community/index.php?/topic/61575-hebrew-subtitles-weird-behaviour-in-multiple-devices/ 

Thanks,
Idan

**Comment by LukePulverenti** [comment]
Please try Emby for iOS 1.7.7. Thanks !

**Comment by alon2df** [comment]
The problem with the 2 Hebrew letters being rendered as squares, as described in #3499, persists as of the latest android version. 

Please note that #3399 and #3499 are quite different, the former having to do with wrong placement of punctuation marks, while the later (and more severe IMHO) with specific letters not being rendered correctly. As far as I can tell, this replacement of the letters with squares is consistent, and happens only for the 2 letters ל and ך. The squares are also consistently followed by a space. Perhaps there is a problem with UTF decoding for these letters?

**Comment by LukePulverenti** [comment]
It is probably just more characters missing from our font file. Can you zip up sample subtitles? what apps are you testing with?

**Comment by alon2df** [comment]
Ok thanks!

Sample subtitle attached as well a screenshot showing the problem.

[sample.zip](https://github.com/MediaBrowser/Emby/files/3253542/sample.zip)

Note that I edited the first subtitle line to include all 27 Hebrew letters (diacritical signs were not included). You can clearly see the missing letters there: Lamed and Final Kaf (unicode values: U+05DC, U+05DA, see [here](https://en.wikipedia.org/wiki/Unicode_and_HTML_for_the_Hebrew_alphabet))

The problem exists on Emby Android app, latest version. I also tested it on Android chrome browser on the same device and there's no problem there.

**Comment by LukePulverenti** [comment]
We'll take a look, thanks.

**Comment by LukePulverenti** [comment]
We've added these characters to our font file. It will be in the next updates for all of our apps. Are there any outstanding issues remaining with Hebrew?

**Comment by LukePulverenti** [comment]
The android and iOS betas both have the updated font. Thanks.

**Comment by LukePulverenti** [comment]
Closing, but please feel free to re-open if there is still an issue. Thanks !
