### ISSUE TITLE
Chromecast - improve transition from photos to videos

### ISSUE THREAD

**Issue by LukePulverenti** [MediaBrowser/Emby#3405]

**Comment by LukePulverenti** [comment]
Resolved.

**Comment by steve-s-71** [comment]
@LukePulverenti I’m afraid it does not work properly. Casting a photo seems to kill the capability to cast a video:

When connecting to Chromecast, then watching a photo, then try to play a video, the video does not start to play. The spinning wheel is spinning forever.

When connecting to Chromecast, then try to play a video (without watching photos before), the video start to play immediately. It also let me select another video, that also play immediately and also the 3rd video and so on. BUT as soon I select a photo and then try to play a video, then the spinning wheel is again spinning forever.
