### ISSUE TITLE
Please let me display more than 100 albums per page in my music library

### ISSUE THREAD

**Issue by Asday** [MediaBrowser/Emby#3409]

**Comment by KristupasSavickas** [comment]
Yes, infinite scroll would be nice.

**Comment by LukePulverenti** [comment]
It's planned for the future. Thanks.

**Comment by Asday** [comment]
Any update on this?  Even just being able to define "yeah dude show me 1000 at once" in preferences or something.

**Comment by LukePulverenti** [comment]
This will be in Emby Server 4.4. Thanks.

**Comment by KristupasSavickas** [comment]
Emby is dead, all hail Jellyfin!
