### ISSUE TITLE
emby release 3.5.2.0 missing assets Emby.Mono.Zip

### ISSUE THREAD

**Issue by userdocs** [MediaBrowser/Emby#3410]
Hi, i had a look and could not see an obvious reason for this. I use this file to update my installation but it is missing from the latest release but is present in all previous.

https://github.com/MediaBrowser/Emby/releases

Is there a reason its not there or was it just an oversight?

**Comment by LukePulverenti** [comment]
Hi, releases are now here:
https://github.com/MediaBrowser/Emby.Releases
Thanks.
