### ISSUE TITLE
Audio selection isn't available in V3.5.2.0 and V3.6.0.2 on FreeNas 11.1

### ISSUE THREAD

**Issue by gasp72** [MediaBrowser/Emby#3415]
Hi to all,

with the last release Version V3.5.2.0 and V3.6.0.2 on FreeNas 11.1 there is a bug with the player on Android and LG OS and during the poster information preview.
With version  3.3.1.0 the problem isn't showed.

The information about the video quality, resolution and the Audio track isn't showed in the preview or during the playing

So isn't impossible to change the audio track or select the subtitle before the play or during the show
Here the log and the screenshot 
[Log.txt](https://github.com/MediaBrowser/Emby/files/2321091/Log.txt)

![android app](https://user-images.githubusercontent.com/33793464/44619469-2cc59e00-a887-11e8-843f-2cf37dd84001.jpg)
![lgos app](https://user-images.githubusercontent.com/33793464/44619470-3222e880-a887-11e8-816d-3cfb32cc8ef3.jpg)
![poster v3_3](https://user-images.githubusercontent.com/33793464/44619483-61395a00-a887-11e8-9174-3981b881c9c6.jpg)
![poster v3_6](https://user-images.githubusercontent.com/33793464/44619485-64cce100-a887-11e8-999d-72b841996d1a.jpg)

**Comment by LukePulverenti** [comment]
Since we helped you in the forum we can keep the conversation there. Thanks.
