### ISSUE TITLE
Detect low disk space and delete transcoded segments

### ISSUE THREAD

**Issue by LukePulverenti** [MediaBrowser/Emby#3418]
https://emby.media/community/index.php?/topic/62109-emby-transcoder-fills-up-32gb-ramdisk-then-stops-playing

**Comment by LukePulverenti** [comment]
Dev note: Only as needed to prevent disk space errors.

**Comment by jaketame** [comment]
Is this resolved in the transcode throttle or do we not delete older chunks?

**Comment by LukePulverenti** [comment]
This will be in the upcoming 4.7 server release.
