### ISSUE TITLE
Volume not synced correctly when using remote control feature

### ISSUE THREAD

**Issue by KristupasSavickas** [MediaBrowser/Emby#3421]
Hello,
setting audio volume using the remote control feature does not work as expected. The new volume is sent to the device correctly, but it's reset to zero after about a second. The change is only visible on the frontend (I can verify this on desktop browser and Android), it's not affecting the device. The remote device I'm using is a Kodi instance running EmbyCon.

**Comment by LukePulverenti** [comment]
Hi, if you use one web app to control another web app, do you see this issue?

**Comment by LukePulverenti** [comment]
I'm going to close this due to lack of response, however, just so you're aware, in all likelihood this is an issue within the app that you're controlling. Thanks.
