### ISSUE TITLE
Dashboard no longer auto-updates on 3.6.0.32 beta

### ISSUE THREAD

**Issue by Lord-Malgus** [MediaBrowser/Emby#3428]
The Emby Server Dashboard no longer auto-updates the "Active Devices" section.  You must keep refreshing the page in order to see the current status.

Tested on, Emby Server 3.6.0.32 beta
Tested using multiple clients - Roku 3.0.97, Edge 3.6.0.32, Chrome 3.6.0.32, Emby Theater 1.1.224.0.

This does not appear to affect all browser when viewing the dashboard however.  The page looks static when viewing via Chrome and Edge browsers..  However using opera,  it does update.

**Comment by LukePulverenti** [comment]
Hi, just tested and confirmed that it's working fine here. Please see how to report a problem: https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/
Thanks.
