### ISSUE TITLE
Android Auto Support

### ISSUE THREAD

**Issue by hughesjs** [MediaBrowser/Emby#3432]
*Feature Request*
Android Auto support for the app.

I'd be happy to work on this if someone could point me to the right repo for the app.

**Comment by mrwebsmith** [comment]
YES.. anything i'd love..wish i could help (other than testing)

-MWS

**Comment by hughesjs** [comment]
Any chance someone could point me towards the repo with the app in?

**Comment by hughesjs** [comment]
@LukePulverenti if you could add me to the repo I'd be happy to help. Unless this is going commercial?

**Comment by andrewrabert** [comment]
@hughesjs The app was once open source. I'm mirroring it at https://github.com/nvllsvm/emby-android

**Comment by KristupasSavickas** [comment]
@nvllsvm So it was licensed under GPL, but not it's proprietary. Same for emby server.  Anything we can do about it?

**Comment by andrewrabert** [comment]
@KristupasSavickas All we can do is fork.

**Comment by KristupasSavickas** [comment]
@nvllsvm the project failed to attract contributors due to various reasons, I don't think a fork could achieve that as well. Especially with all the ecosystem around Emyb.

**Comment by LukePulverenti** [comment]
Now in testing:
https://emby.media/community/index.php?/topic/82319-android-auto-testing/
Thanks !
