### ISSUE TITLE
add podcasts on library  media type

### ISSUE THREAD

**Issue by icf20** [MediaBrowser/Emby#3433]
currently it works if music is selected i wonder if you want add the podcast type on the drop down menu 

my version is 3.5.2.0

**Comment by LukePulverenti** [comment]
Hi, is it necessary? New content types are a lot of work for us. There is music, and the next release will have audio books. I would think one of those two should be close enough, no?

**Comment by icf20** [comment]
well i lose some time using the mixed category, maybe is obvious for you but for me was not, i expected the category to be strict music only, maybe audio can be better i dunno or music/audio/podcast can be better

**Comment by LukePulverenti** [comment]
I would use audiobooks with the next release. I think you will find that close enough to what you are looking for. Thanks.
