### ISSUE TITLE
Bug: can't edit sync settings

### ISSUE THREAD

**Issue by SecondScreenVentures** [MediaBrowser/Emby#3447]
In the Download & Sync screen in the server, TV shows with more than one episode have "..." on the right side, and you can click on the show name and edit the sync settings (like change the quality of the video and such). If a show has only 1 episode, you can't click on it and change the settings. Only way is to remove the TV show and re-sync with new settings. Currently, you can't even see what the settings are.

**Comment by LukePulverenti** [comment]
Hi, this is resolved for the next release, thanks !
