### ISSUE TITLE
Xbox One + rclone video stopping 

### ISSUE THREAD

**Issue by martimarkov** [MediaBrowser/Emby#3448]
So I have been having this issue for ages. I have mount with rclone which is using google, crypt and cache. 

Some files when played make the video to pause for a few seconds and later resume playback. The file never gets transcoded on the server and displays Direct Stream on both the Xbox and the dashboard. This happens on Emby, Ember and DLNA. 

The playback for the same files works fine if played from the local hard drive on the server. But this only happens on Xbox. Playing all those files from the browser always works and no “blocking” happens. 

Interestingly when the block happens and the frame is then dropped (from stats for nerds) the indicator in the player for how much has been buffered on the video disappears and after the video resumes it goes back to the previous value (around 30-40 seconds I guess). 

I can share a magnet link for an actual file if that would be helpful but it’s copyrighted obviously. :D

**Comment by LukePulverenti** [comment]
To me that just sounds like it can't download the data fast enough.

**Comment by martimarkov** [comment]
That’s what I was thinking as well but does not answer the question of why this only happens on the XBoX. Again any other player does not exhibit this behaviour. 

Also the connection between the server and emby is 1Gbps. Emby is also connected to the internet over a 1 Gbps and I,be tested the speed I never get anything under 900Mbps to the internet (both up and down). 

Thanks,
Marti Markov

**Comment by LukePulverenti** [comment]
I would try lowering the in-app quality setting in case the bitrate being delivered might be too high. Thanks.

**Comment by martimarkov** [comment]
I’ll definitely give that a go but I still think that if it was the bitrate it would be felt on the other players. 

Could it be that the mkv files are not “web optimised” so some sectors of meta data are not in the beginning of the file? (Have some vague memory about some issues like that with video files back in the day)


Also maybe if there some buffer on the player that can be configured that would shed some additional info

**Comment by LukePulverenti** [comment]
Did you try this?

**Comment by martimarkov** [comment]
Yes, I did. The issue still persists.

Have you considered adding more options in the xbox app to allow changing the cache?

**Comment by LukePulverenti** [comment]
Hi, can you please try the latest version of the server and the app and let us know how it compares? Thanks !

**Comment by LukePulverenti** [comment]
Please try this with the new Emby Server 4.3 and let us know how that compares. Thanks.

**Comment by LukePulverenti** [comment]
Closing, but please feel free to re-open with the requested information. Thanks.
