### ISSUE TITLE
Forgot password instructions have incorrect link and expiry

### ISSUE THREAD

**Issue by bmjsmith** [MediaBrowser/Emby#3450]
If you forget your password and use the reset functionality a file is created at `/var/lib/emby/passwordreset.txt `

with the content:
```
Use your web browser to visit:

http://192.168.0.1:8096/web/forgotpasswordpin.html

Enter the following pin code:

1234

The pin code will expire at 41
```

This should probably say:

```
Use your web browser to visit:

http://192.168.0.1:8096/web/index.html#!/forgotpasswordpin.html

Enter the following pin code:

1234

The pin code will expire at some actual time like 12:00:00
```
because without the hash routing the page is just a bare template, and the expiry time seems misformatted.

**Comment by LukePulverenti** [comment]
Resolved for Emby Server 3.6. Thanks.
