### ISSUE TITLE
Support for macOS Picture-in-Picture (+ working workaround)

### ISSUE THREAD

**Issue by anohren** [MediaBrowser/Emby#3451]
Just tried `emby-server-deb_3.5.3.0_armhf.deb` web player in Safari 12 for macOS 10.14 (Mojave) and concluded that I couldn't enter the macOS Picture-in-picture mode by right-clicking the video and selecting it in the context menu. 

The slightly irritating part was that I had accidentally right-clicked the video immediately while the web player page was still loading, and could see the PiP option in the menu at that time. After opening the menu a second time, the PiP option had disappeared.

I assumed this was because the video element had been buried below another top-most element, so using Safari's web inspector started to disable elements one by one until I got it working. This was the interfering elements:

```
<div class="backgroundContainer backgroundContainer-transparent __WebInspectorHideElement__"></div>

<div id="videoOsdPage" data-role="page" class="page libraryPage mainAnimatedPage __WebInspectorHideElement__" data-backbutton="true" data-type="video-osd" data-properties="fullscreen">
```

PiP mode seems to work flawlessly after actually entering into it.

**Comment by LukePulverenti** [comment]
Resolved in Emby Server 4.1.
