### ISSUE TITLE
[Bug] Multi-Movie/TV File Resume

### ISSUE THREAD

**Issue by jaketame** [MediaBrowser/Emby#3454]
Issue:
When you have merged TV Shows (Automatically) or Movies (Manually or via script tmdbid) when you need to resume, it shows all versions available

Fix: Show a single poster for all versions and allow option to resume specific version

https://emby.media/community/index.php?/forum/98-feature-requests/

**Comment by LukePulverenti** [comment]
Resolved for next release. Thanks.
