### ISSUE TITLE
Add support for dynamic categories based off group-title in M3U 

### ISSUE THREAD

**Issue by andyleadbetter** [MediaBrowser/Emby#3457]
Most IPTV provides support extra metadata in the M3U file, but do not provide the data in the EPG.

channel-id="Channel Name" group-title="USA NETWORKS|live",Channel Name

It would be really good if Emby would take these group-titles into its EPG and categorise the channel list automatically.

**Comment by LukePulverenti** [comment]
Duplicate/merging with #2646 - Channel groups for LiveTV #2646
