### ISSUE TITLE
Can't scroll at all any more.

### ISSUE THREAD

**Issue by Asday** [MediaBrowser/Emby#3460]
Emby Version 3.2.70.0
Chromium Version 70.0.3538.67 (Official Build) Built on Ubuntu , running on LinuxMint 18 (64-bit)

A scrollbar is visible, but it's full height, and neither dragging it, using the scroll wheel, arrow keys, Home, End, PgUp, PgDown, or even touch-dragging on my touch screen allow me to scroll the page.

Opening the admin allows me to scroll on the left menu pane, but the right main pane is unscrollable.

**Comment by LukePulverenti** [comment]
Please see here:
https://emby.media/community/index.php?/blog/1/entry-423-emby-server-34-released/

**Comment by LukePulverenti** [comment]
Sorry, my mistake. Please see here:
https://emby.media/community/index.php?/blog/1/entry-437-emby-server-353-released/
Thanks.

**Comment by Asday** [comment]
![image](https://user-images.githubusercontent.com/340276/47538931-bf091300-d8c5-11e8-8bf2-81f92a3b5438.png)

Aah this probably isn't helping.
