### ISSUE TITLE
Samsung 2018 Smart TVs - Button Names

### ISSUE THREAD

**Issue by IceBoosteR** [MediaBrowser/Emby#3461]
On 2018 Samsung SMART TV, Version 1.0.29 (latest) every button within the app appears to show its own name, which is very annoying. You can see some like:
"ButtonNextNext" For the button name itself "ButtonName" and then added the text which should be shown to the user "Next".
Thanks,
Ice

**Comment by LukePulverenti** [comment]
It's resolved for the next release of the app, thanks.
