### ISSUE TITLE
Delete recorded (Live TV) video leaves behind directory

### ISSUE THREAD

**Issue by yuriw** [MediaBrowser/Emby#3462]
My Emby server on Ubuntu 16.04 Version 3.5.3.0
Default recording path changed to mount point `/mnt/xxx/emby/recordings`

After a video had been recorded, delete it via `Recordings/.../Delete media`

After this actual media file is deleted but the directory is not.

Expected - directory is deleted as well.

**Comment by LukePulverenti** [comment]
Hi, can you please discuss an example? thanks.

**Comment by yuriw** [comment]
It's odd, but I don't see it's happening anymore.  Will provide details when/if find a reproducible case.

**Comment by LukePulverenti** [comment]
Thanks !
