### ISSUE TITLE
[Feature Request] Permit manual entry/override of "In-Home (LAN) access"

### ISSUE THREAD

**Issue by andrewmiskell** [MediaBrowser/Emby#3464]
In dockerized installations with reverse proxies (specifically Traefik) for external access, the In-Home LAN access is set to the internal docker bridge address assigned to the container and not the actual docker host IP.

This breaks attempting to connect to a Emby server locally via Emby Connect (because the private docker address is given to the Emby App to connect with instead of the docker host). One suggested workaround is to use host networking on the docker container, however this causes issues with reverse proxies and also breaks internal traffic with other dockerized containers which communicate with Emby over the internal docker network (as to not expose that traffic outside of the docker network).

I discussed this in the comments of thread [here](https://emby.media/community/index.php?/topic/56771-chromecast-address) as well. Simply providing an advanced setting to manually set this address would allow for more flexible setup of Emby in dockerized environments. Plex's docker container already supports this using the ADVERTISE_IP environment variable. Emby wouldn't need to support an environment variable but just allow it in the configuration.

**Comment by LukePulverenti** [comment]
Hi there, have you explored advanced server settings?

**Comment by andrewmiskell** [comment]
Yes, I have.. There's no setting for what I'm talking about. If you're referring to the "bind address" area, that doesn't work because the docker host IP isn't available to the container so you can't bind to it.

**Comment by LukePulverenti** [comment]
I'm referring to the lan networks setting.

**Comment by pabloromeo** [comment]
This is also very important for us deploying within Docker Swarm, where we don't use the host network directly and get a virtual ip for the container instead

**Comment by nomandera** [comment]
For what it is worth I have a similar setup but using nginx.

Setting the:

> LAN networks:
> Comma separated list of IP addresses or IP/netmask entries for networks that will be considered on local network when enforcing bandwidth restrictions. If set, all other IP addresses will be considered to be on the external network and will be subject to the external bandwidth restrictions. If left blank, only the server's subnet is considered to be on the local network.

does not appear to ever bypass the user needing authentication.

Perhaps my syntax is incorrect as even taking this to the extreme by adding the entire IANA private IP address space `10.0.0.0/8, 172.0.0.0/8, 192.168.0.0/16` still has no impact.

There is a scenario where users think they are connecting locally but in fact NAT is presenting Emby with the external network IP however I can clearly seen my 10. address in the logs so for sure this isnt my specific issue.

**Comment by lawrencecurtis** [comment]
This really would be super handy

**Comment by lawrencecurtis** [comment]
If you bind to host 0.0.0.0 then it will only display the wan ip/address in the server status. This effectively fixed the issue for me

**Comment by nomandera** [comment]
Can we get this accepted as a bug.

From reading back it appears that the perception is that `lan networks setting` is a working solution but it is not. This does not work in the context of `dockerized installations with reverse proxie` (as documented at least).

**Comment by LukePulverenti** [comment]
I think it might just be misunderstanding of what the settings are.

LAN Networks - Used to help determine if a request from a client device is inside your LAN network or not.

Bind to local address - This will change the LAN address that is reported by the server to other devices.

**Comment by LukePulverenti** [comment]
Closing. Please feel free to reopen or start a new ticket if you still have an issue. Thanks.
