### ISSUE TITLE
VAAPI not used when subtitles need to be burned in

### ISSUE THREAD

**Issue by LukePulverenti** [MediaBrowser/Emby#3467]
https://emby.media/community/index.php?/topic/64893-no-hw-transcode-on-d916-during-subtitle-burn

**Comment by softworkz** [comment]
This is actually resolved now.

**Comment by softworkz** [comment]
Can be closed.

**Comment by LukePulverenti** [comment]
Resolved for Emby Server 3.6. Thanks.
