### ISSUE TITLE
Restore doesn't restore user->library association

### ISSUE THREAD

**Issue by ggzengel** [MediaBrowser/Emby#3469]
Because of #3307 I decided to install a new system and migrated with help of the backup plugin.
After restore the associations between users and libraries are gone. I tried to restore twice but nothing helped.
Only users with access to all libraries still had this flag set.

Edit: I migrated from 3.3.1 to 3.5.3

**Comment by LukePulverenti** [comment]
HI, tested with the latest versions of the server and plugin, and unable to reproduce. I think this was resolved somewhere along the way. Thanks.
