### ISSUE TITLE
Error starting ffmpeg, segment_time_delta out of range

### ISSUE THREAD

**Issue by KD0BPV** [MediaBrowser/Emby#3470]
This bug is blocking testing of #3422

I'm getting the following error from ffmpeg:
```
[segment muxer @ 0x55ad7ef57000] Value -888.000000 for parameter 'segment_time_delta' out of range [0 - 9.22337e+12]
[segment muxer @ 0x55ad7ef57000] Error setting option segment_time_delta to value -888.
Could not write header for output file #0 (incorrect codec parameters ?): Numerical result out of range
Error initializing output stream 0:0 --
[aac @ 0x55ad7eee6740] Qavg: -nan
Conversion failed!
```
The command Emby is giving is: 
```
/usr/bin/ffmpeg -ss 00:14:48.000 -f matroska,webm -i file:"/srv/plex/Shows/Saikin, Imouto no Yousu ga Chotto Okashiinda ga/Season 01/Recently, My Sister Is Unusual - 01 - Mitsuki SOS.mkv" -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -vf "scale=trunc(min(max(iw\,ih*dar)\,640)/2)*2:trunc(ow/dar/2)*2" -pix_fmt yuv420p -preset medium -crf 23 -maxrate 808000 -bufsize 1616000 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames "expr:if(isnan(prev_forced_t),eq(t,t),gte(t,prev_forced_t+3))" -copyts -vsync -1 -codec:a:0 aac -strict experimental -ac 2 -ab 192000  -f segment -max_delay 5000000 -avoid_negative_ts disabled -map_metadata -1 -map_chapters -1 -start_at_zero -segment_time 3 -segment_time_delta -888 -individual_header_trailer 0 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 296 -segment_list "/srv/plex/transcode_tmp/transcoding-temp/e5b786a60106a44d47f29e6c7ec146e3.m3u8" -y "/srv/plex/transcode_tmp/transcoding-temp/e5b786a60106a44d47f29e6c7ec146e3%d.ts"
```
As we can see, Emby is passing a bad value in the call to ffmpeg (`... -segment_time_delta -888 ...`). So far, it seems to happen whenever a new segment begins being transcoded. This does not affect starting a video, only moving to another segment within that video, as starting a video from the beginning does not call ffmpeg with the -segment_time_delta argument.

So far, every file I have tried reproducing this with errors because the delta is negative, while the range `[0;9.22337e+12]` (only positive values allowed).

Versions:
ffmpeg v4.1
emby-server v3.5.3.0

**Comment by softworkz** [comment]
You are using an incorrect version of ffmpeg. Did you install or configure a custom version?

**Comment by LukePulverenti** [comment]
Or if you're on arch linux then you will need to go back to ffmpeg 4.0.2.

**Comment by LukePulverenti** [comment]
From your other topic I see you're on Arch linux. Please see here for more information and the solution:
https://emby.media/community/index.php?/topic/65009-i-think-i-found-a-bug-in-transcoding-when-resuming/
Thanks !

**Comment by KD0BPV** [comment]
@softworkz No. This is the packaged version from the Arch Linux repos.

@LukePulverenti Yup, that was it. I'm really surprised that didn't come up in my search results while I was trouble-shooting this issue. Thanks!
