### ISSUE TITLE
ARW (Sony raw) not showing on deb_3.5.3.0_armhf / Raspbian 9-stretch

### ISSUE THREAD

**Issue by brunoc** [MediaBrowser/Emby#3472]
I am on `emby-server-deb_3.5.3.0_armhf.deb` on raspbian rPi 3B+ and have the same issue as [this one](https://github.com/MediaBrowser/Emby/issues/2335) where ARW (sony) files are not showing and web browser seems to be getting the full original ARW data and is unable to display it or show/generate thumbnails.

Partial log and sample file included. 

~~~
Linux raspberrypi 4.14.71-v7+ #1145 SMP Fri Sep 21 15:38:35 BST 2018 armv7l GNU/Linux
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
~~~

[emby.log](https://github.com/MediaBrowser/Emby/files/2557373/emby.log)

[DSC00656.ARW.zip](https://github.com/MediaBrowser/Emby/files/2557376/DSC00656.ARW.zip)

Cheers!

_Originally posted by @brunoc in https://github.com/MediaBrowser/Emby/issues/2335#issuecomment-436612050_

**Comment by LukePulverenti** [comment]
Hi there, can you please try Emby Server 4.0? Thanks.

**Comment by brunoc** [comment]
Thanks for the follow up. I did but now I am stuck with "Emby Server is upgrading your database. Please try again in a minute or two." (deb_4.0.1.0_armhf installed over deb_3.5.3.0_armhf). Let me know if I should open a separate ticket!

see logs:

[embylogs.tar.gz](https://github.com/MediaBrowser/Emby/files/2800480/embylogs.tar.gz)

**Comment by LukePulverenti** [comment]
That could take a little while. I would just give it some time. Thanks.

**Comment by brunoc** [comment]
All good!

The ARW files are now showing up. I will add more to my library in the next few days and report any further issue.

It took a while on the poor rPi 3B+ to upgrade though, probably about 1h before Emby came back online.

Thanks so much Luke and Team.
