### ISSUE TITLE
Too easy to overwrite primary image of movie or TV episode

### ISSUE THREAD

**Issue by chowbok** [MediaBrowser/Emby#3473]
When adding an additional image to a movie or TV episode, the selection defaults to "primary", and sometimes I forget to change it if I'm adding a different kind of image. This results in my primary image being overwritten with no way to undo it other than restoring from backup. It would be nice if it could prompt me for confirmation when uploading an image would overwrite an existing image.

**Comment by LukePulverenti** [comment]
Hi, the image editor has a new design now. The details are in our 4.6 announcement:
https://emby.media/community/index.php?/blogs/entry/507-emby-server-46-released/

Now all of the available image types are visible as slots and you have to specifically choose one before you can upload a new image or download a new one.

Does this resolve your concern?

**Comment by LukePulverenti** [comment]
Closing, but please feel free to re-open if you'd like to continue this discussion. Thanks.
