### ISSUE TITLE
Add "Identify" option for TV episodes

### ISSUE THREAD

**Issue by chowbok** [MediaBrowser/Emby#3475]
TV episodes should have an "Identify" option as movies do. I realize the fact that it doesn't is a deliberate decision, but I was wondering if it could be revisited. TVDB isn't always correct about episode order.

**Comment by LukePulverenti** [comment]
This won't happen. You identify the series, then all you have to do is make sure the episodes have season and episode numbers. If you want your video file to be a different episode than what's on tvdb, then just rename to a new episode number.

**Comment by chowbok** [comment]
Seems like then I have to duplicate their episode ordering errors if I want otherwise correct metadata on a particular episode. I can live with it, though.
