### ISSUE TITLE
Need ability to search by and/or browse tags

### ISSUE THREAD

**Issue by chowbok** [MediaBrowser/Emby#3477]
I like the "Tags" feature of the UI, but it's pretty limited currently since you can't search for a tag, or click on a tag and have it show you other items with that tag. Would be cool if we had that ability.

**Comment by LukePulverenti** [comment]
Tags will be clickable in Emby Server 4.2. Additionally most list screens offer tags for filtering. Searching is the last thing remaining. Thanks.

**Comment by bigbellyburger** [comment]
It would be nice to also be able to browse a list of all tags, like with collections.

**Comment by LukePulverenti** [comment]
Searching tags will be in Emby Server 4.4.

**Comment by LukePulverenti** [comment]
The last piece of the puzzle, browsing tags, will be in Emby Server 4.6.
