### ISSUE TITLE
Broken images on the latest beta

### ISSUE THREAD

**Issue by KristupasSavickas** [MediaBrowser/Emby#3484]
All types of images (movie and album covers, artist photos) seem to be broken on the latest beta (3.6.0.71). I'm running Arch, so maybe this is related to #3478.

Album cover images are created by an external program (beets) and should be readable. Here's what the directory structure looks like:
```
kristupas@Server ~ % tree /array/media/music/Earl\ Sweatshirt          
/array/media/music/Earl\ Sweatshirt
|-- Doris
|   |-- 01\ Pre.flac
|   |-- 02\ Burgundy.flac
|   |-- 03\ 20\ Wave\ Caps.flac
|   |-- 04\ Sunday.flac
|   |-- 05\ Hive.flac
|   |-- 06\ Chum.flac
|   |-- 07\ Sasquatch.flac
|   |-- 08\ Centurion.flac
|   |-- 09\ 523.flac
|   |-- 10\ Uncle\ Al.flac
|   |-- 11\ Guild.flac
|   |-- 12\ Molasses.flac
|   |-- 13\ Whoa.flac
|   |-- 14\ Hoarse.flac
|   |-- 15\ Knight.flac
|   `-- cover.jpg

```

Here are a few images of what it looks like:
![screenshot_20181126_084251](https://user-images.githubusercontent.com/1362643/48997361-5c22ca00-f158-11e8-8788-ba14a6497480.png)
![screenshot_20181126_084417](https://user-images.githubusercontent.com/1362643/48997362-5c22ca00-f158-11e8-8fd8-b51b3122fa5a.png)
![screenshot_20181126_084431](https://user-images.githubusercontent.com/1362643/48997363-5c22ca00-f158-11e8-9ecd-5c6d6ae69577.png)

The images load sometimes, but instantly disappear/become half white. Android app fails to render images completely, the placeholder icon is shown instead.

**Comment by LukePulverenti** [comment]
Server log?

**Comment by LukePulverenti** [comment]
And also do you have libskiasharp installed on your system, and what version?

**Comment by KristupasSavickas** [comment]
The currently installed version of skiasharp is 1.60.2-1.

I don't see anything out of the ordinary looking at the debug log, would you like me to post a log of me doing a particular thing (library scan, etc.).

**Comment by KristupasSavickas** [comment]
I tried a clean reinstall (by deleting /var/lib/emby), the issue still persists.

**Comment by KristupasSavickas** [comment]
Tried installing 3.5.3.0 - everything works as intended.

**Comment by LukePulverenti** [comment]
The beta channel has rolled back to skiasharp 1.60.0, so that's the version you'll need to have on your system.

**Comment by alucryd** [comment]
FTR, the Arch Linux package uses skia-sharp60 (not skia-sharp), which is at 1.60.0, the logs should display that version during startup. Beta works fine here, images display correctly, both in firefox and in the android app.

**Comment by LukePulverenti** [comment]
Did you have a chance to try this?

**Comment by LukePulverenti** [comment]
This should help you get squared away:
https://emby.media/community/index.php?/topic/66507-small-problem-with-skia-sharp-on-arch-linux/
Thanks.
