### ISSUE TITLE
Api User.Policy.EnabledFolders

### ISSUE THREAD

**Issue by kitten77** [MediaBrowser/Emby#3485]
If user.Policy.EnableAllFolders = True 
it returns a empty list on User.Policy.EnabledFolders

Is this how it should behave or shouldn't it return a complete list of all Folders?

**Comment by LukePulverenti** [comment]
No it shouldn't. This is the user's configuration object, not the actual results. You would use the regular library browsing api to get results.

**Comment by kitten77** [comment]
Thank you :)
