### ISSUE TITLE
card text needs to be wider 3.6.0.74 beta Windows

### ISSUE THREAD

**Issue by francisuk1989** [MediaBrowser/Emby#3486]
The card text columns under **"users"** needs to be wider as for larger names like Francis is only getting the last three FRA, This dos affect last seen aswell. Also try zooming in and out but dosnt help that much.

Dos not affect the login photo, Heres a screenshot of the users currently
https://files.catbox.moe/mxbff9.jpg

Using Windows x64, 3.6.0.74 beta

**Comment by Penkethboy** [comment]
Create a post in the Emby CSS sub forum about this and someone will give you some css to modify the size of the card.

I have users with names longer than francis and they fully display - do you have any css applied already?

**Comment by francisuk1989** [comment]
@Penkethboy will create a forum post later on, Nope no CSS applied only using a theme what looks ok on 3.5.3.0 stable.

**Comment by LukePulverenti** [comment]
It's slightly wider in 4.0, although I still have not gotten to a mouseover tooltip yet.

**Comment by LukePulverenti** [comment]
There will be a tooltip hover in Emby Server 4.1 Thanks.
