### ISSUE TITLE
How to install emby server beta?

### ISSUE THREAD

**Issue by bits1125** [MediaBrowser/Emby#3487]
How to install emby server beta?
What is the beta package repository?

**Comment by LukePulverenti** [comment]
Instructions are on our website:
https://emby.media/download

If there are betas available on your platform, the instructions will be on the page for it. Thanks.

**Comment by bits1125** [comment]
Synology dsm6.2
I found that others used 3.6.x, I only found 3.5.3 in the package repository.
![tim 20181207024829](https://user-images.githubusercontent.com/30818344/49605177-cba37f80-f9ca-11e8-9293-09e3f496a94e.png)

**Comment by LukePulverenti** [comment]
The Synology beta is a closed beta process.  To join you'll have to announce your intention to volunteer for testing in the Synology section of the Emby Community. Thanks.
