### ISSUE TITLE
[Feature request] Synchronize subtitles timing/delay

### ISSUE THREAD

**Issue by rbrtribeiro** [MediaBrowser/Emby#3488]
Hi,

now that non-admin users will be able to download subtitles (thanks for that!), I would like to add this issue to the bowl of the _critically missing features_ :).

As also requested [here](https://emby.media/community/index.php?/topic/30041-adjust-subtitle-delay/), I believe that adjusting the delay (positive or negative) would be an important feature to add. This is simply because several media do not have available synced subtitles (or they are not available right away when the media is released), which promptly rules out using Emby as player. This feature is neatly implemented in Kodi ([Subtitle offset](https://kodi.wiki/view/Video_playback#Subtitles)).

Thank you for all the work done,
Best

**Comment by neolectron** [comment]
I would also love this feature, it is just pain when emby think it is "perfect match" but its not really.

**Comment by GnaXi** [comment]
Yes! This is quite needed, especially for TV shows that sometimes has ads in the middle of an episode, which ends up offsetting the subtitles a lot.

**Comment by YanzheL** [comment]
Yes, this is an important feature that should be placed as the first priority.

**Comment by tbrady85** [comment]
+1

**Comment by 3lsheikh** [comment]
+1

**Comment by ravijagga** [comment]
+1

**Comment by LukePulverenti** [comment]
You'll be able to set the subtitle offset directly in the video player in the upcoming Emby Server 4.5 release.
