### ISSUE TITLE
Sort by Date Played not working

### ISSUE THREAD

**Issue by nickdex** [MediaBrowser/Emby#3489]
When I try to sort by **Date Played** it sorts by Alphabetical order instead.

Using Server Version 3.5.3.0 with HTML5 player

**Comment by LukePulverenti** [comment]
Hi, on what screen?

**Comment by nickdex** [comment]
Anime.
For Movies it is working.

**Comment by LukePulverenti** [comment]
Did you set this up as a TV library?

**Comment by nickdex** [comment]
I used Anime plugin and selected **TV Shows** as content type

**Comment by LukePulverenti** [comment]
Thanks. I see the problem. I'm putting in a fix to resolve this in the upcoming 3.6 release. Thanks !
