### ISSUE TITLE
m3u8 TS stream wont play (infinite buffer)

### ISSUE THREAD

**Issue by rlaphoenix** [MediaBrowser/Emby#3490]
```
#EXTM3U
#EXT-X-MEDIA-SEQUENCE:2099
#EXT-X-ALLOW-CACHE:NO
#EXT-X-VERSION:2
#EXT-X-KEY:METHOD=AES-128,URI="https://www.[redacted]/hls-key/[redacted].bin",IV=0X0da8bbe217ab7b23b7702147aeb31bd5
#EXT-X-TARGETDURATION:8
#EXTINF:8,
../../../hls-live/streams/events/_definst_/[redacted]/[redacted]-720Num2099.ts
#EXTINF:8,
../../../hls-live/streams/events/_definst_/[redacted]/[redacted]-720Num2100.ts
#EXTINF:8,
../../../hls-live/streams/events/_definst_/[redacted]/[redacted]-720Num2101.ts
#EXTINF:8,
../../../hls-live/streams/events/_definst_/[redacted]/[redacted]-720Num2102.ts
#EXTINF:8,
../../../hls-live/streams/events/_definst_/[redacted]/[redacted]-720Num2103.ts
#EXTINF:8,
../../../hls-live/streams/events/_definst_/[redacted]/[redacted]-720Num2104.ts
```
The above is the contents of the m3u8 url.
If I put it in a test m3u8 master list and put it as a tuner, and try play it in the EPG, it will instantly buffer and never load or do anything else, no error, no timeout, nothing.

If I were to do: `streamlink <m3u8 link> best --player-external-http --player-external-http-port 7001`
and then replace the original link in the master list with http://localhost:7001 it would work. So im assuming the AES .bin has something to do with it? (btw it is HTTPS, so that could perhaps be an issue since I am playing from chrome on localhost:8096 (http))

**Comment by rlaphoenix** [comment]
The main m3u8 link is also playable via mpv but not VLC

**Comment by LukePulverenti** [comment]
Hi, does this still happen?
