### ISSUE TITLE
Movies being scraped as #DUPE#

### ISSUE THREAD

**Issue by nomandera** [MediaBrowser/Emby#3491]
As initially reported in the forum.

Somewhere in the identification or metadata scraping process, legitimate ttids are being displayed as #DUPE#, as can be seen:

![Image of Yaktocat](https://i.imgur.com/AMoYvBX.jpg)

I have managed to track down five example of this issue and have constructed a fake data set to easily reproduce.

[sample.zip 4KB](https://github.com/MediaBrowser/Emby/files/2686807/sample.zip)

I have also added a 6th example to the dataset which shows a very similar movie with a similar name which also contains unusual characters but is identified correctly (movie6 acts as a control set).

This data set has been confirmed to replicate the issue on two seperate beta server installs but it appears that this issue may not exist in the last stable (this is harder for me to test but feedback has been that it works OK)

**Comment by LukePulverenti** [comment]
Hi, does this still happen?

**Comment by nomandera** [comment]
Yes I have reconfirmed the sample data set provided above generates the same DUPE entries in both Version 3.6.0.84 beta and Version 4.0.0.0 beta

**Comment by LukePulverenti** [comment]
Ok this is actually bad data coming from Omdb. What I would suggest is making sure that MovieDb is your highest priority metadata provider for each of your Movie libraries.

**Comment by nomandera** [comment]
As far as I can tell this is the way it is currently setup, the default and the way it has always been configured here

![Order](https://i.imgur.com/hH91BCB.jpg)

I am going to guess that since the movie.nfo is a URL type it is using the IMDB ID against OMDB and essentially bypassing TMDB.

**Comment by LukePulverenti** [comment]
What is the Imdb Id?

**Comment by nomandera** [comment]
The ttid for the IMDB movie reference

e.g. http://www.imdb.com/title/**tt3920266**/

Can you replicate the bug with the provided zip file. I have tested it on multiple versions now and had it independently checked as well so I a quite confident it is reproducible with default 4.x install

**Comment by LukePulverenti** [comment]
Ok i tested movie4, and yes i can reproduce but this is a bit of a special case.

Looking up that Imdb Id on Moviedb returns zero results. So then we go to the next movie provider which is Omdb, and it sends back the #DUPE# result. I could have Emby check for #DUPE#, and then treat that the same as no data found, this way you don't end up with junk data in your display.

I think what has happened is the real Imdb Id has changed, and you need to update your nfo with the new value.

**Comment by nomandera** [comment]
I think you have found the source of the problem. It appears that in certain rare cases IMDB will end up with duplicates and in even rarer cases the fixed (i.e. merged) entry will take the later ttid rather than the earlier one.

The earlier ttid is then dropped and on the website the now old ttid URL is redirected to the new ttid.

I have found a thread discussing one of the specific examples I happened to hit. https://getsatisfaction.com/imdb/topics/same-title-is-in-the-imdb-database-twice

I think the path of least resistance would be to detect `#DUPE#` and present the Emby user with some better information.  For example we could name the movie as `#DUPE or IMDB ID removed` (or similar) and perhaps even insert a fuller explanation as the movie synopsis.

Either way thanks for taking the time to debug this. I will leave this open in case you want to discuss this idea further or if you think it is not worth the effort please feel free to close as resolved.

**Comment by LukePulverenti** [comment]
I've pushed Omdb 1.0.4 to resolve this, thanks.
