### ISSUE TITLE
emby don't start

### ISSUE THREAD

**Issue by awaska** [MediaBrowser/Emby#3493]
● emby-server.service - Emby Server is a personal media server with apps on just about every device.
   Loaded: loaded (/usr/lib/systemd/system/emby-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Thu 2018-12-20 19:49:15 GMT; 9s ago
  Process: 3891 ExecStart=/opt/emby-server/bin/emby-server (code=killed, signal=ILL)
 Main PID: 3891 (code=killed, signal=ILL)

Dec 20 19:49:14 raspberrypi systemd[1]: Started Emby Server is a personal media server with apps on just about every device..
Dec 20 19:49:15 raspberrypi systemd[1]: emby-server.service: Main process exited, code=killed, status=4/ILL
Dec 20 19:49:15 raspberrypi systemd[1]: emby-server.service: Unit entered failed state.
Dec 20 19:49:15 raspberrypi systemd[1]: emby-server.service: Failed with result 'signal'.

this is the error

**Comment by LukePulverenti** [comment]
Hi, what version is this? Is any emby server log generated? Thanks.

**Comment by LukePulverenti** [comment]
Anything?

**Comment by awaska** [comment]
how i can discover the version

**Comment by awaska** [comment]
Download emby-server-deb_3.5.3.0_armhf.deb
dpkg -i emby-server-deb_3.5.3.0_armhf.deb
Open a web browser to http://localhost:8096 
i try this guide i'm on raspberry pi

**Comment by LukePulverenti** [comment]
What model RPI?

**Comment by awaska** [comment]
Raspberry pi

Il giorno sab 12 gen 2019 alle 20:38 Luke <notifications@github.com> ha
scritto:

**Comment by awaska** [comment]
version b rever 2

**Comment by LukePulverenti** [comment]
is this the one that you have?
https://www.raspberrypi.org/products/raspberry-pi-1-model-b-plus/

**Comment by awaska** [comment]
No my raspberry is 2012 and have a rca connector 2usb port ethernet hdmi
jack sd i think is 2012 named raspberry pi

Il giorno mar 15 gen 2019 alle 22:53 Luke <notifications@github.com> ha
scritto:

**Comment by LukePulverenti** [comment]
This is a softp cpu, right? I don't think we support this older RPI model right now.
