### ISSUE TITLE
Resuming from midway doesn't work for Anime (TV Shows)

### ISSUE THREAD

**Issue by nickdex** [MediaBrowser/Emby#3494]
How to replicate 
1. Play an episode, let it play for few minutes.
2. Go back
3. Click on play icon in center, on resume button from the episode screen
4. The progress bar will reset and the player will remain stuck at blank screen.

I started using emby a month ago, since then the resume has worked only once (coincidentally today) when I was testing it once last time before creating issue. Subsequent test replicated the bug though

For movies it works fine.

Might be related to #3489

**Comment by LukePulverenti** [comment]
Hi, is this with the web app?

**Comment by nickdex** [comment]
Yes, with web app.
I just tested on android and it doesn't have any problem resuming.

**Comment by LukePulverenti** [comment]
Can you please attach the emby server log, and ffmpeg log if there was one? Thanks !

**Comment by nickdex** [comment]
My latest attempt to play, go back and resume -
[embyserver.txt
12/21/2018 11:20 AM](https://github.com/MediaBrowser/Emby/files/2701674/embyserver.txt)

[ffmpeg-directstream-9e680b5f-ad60-4a3f-bae5-ce06a2ac00c1.txt
12/21/2018 11:20 AM](https://github.com/MediaBrowser/Emby/files/2701675/ffmpeg-directstream-9e680b5f-ad60-4a3f-bae5-ce06a2ac00c1.txt)

[ffmpeg-directstream-23e039a2-ff8d-41ae-b9ce-956bb4f0eb6f.txt
12/21/2018 11:20 AM](https://github.com/MediaBrowser/Emby/files/2701676/ffmpeg-directstream-23e039a2-ff8d-41ae-b9ce-956bb4f0eb6f.txt)

**Comment by VGrol** [comment]
Emby is incompatible with FFMPEG 4.1, please downgrade to any of the 4.0 versions.
There was talk of bundling their own FFMPEG version into the current package, but it that itself is a pretty messy solution.

~~This is a problem on a lot of linux platforms.~~
Apparently just limited to Arch Linux.

That stated, I spoke with the Beta package maintainer of Emby Server on Arch, 
bundling internal packages is a poor solution that doesn't really blend well with Arch philosophy. 
A better alternative would be to require an FFMPEG compat version.

**Comment by LukePulverenti** [comment]
Actually it's not a problem on most linux platforms, only arch linux. On other linux platforms we have already bundled our own ffmpeg. It is only with arch linux that we've been using your system version.

Going forward with 3.6 we'll be shipping our own. For now, he is correct, simply downgrade to ffmpeg 4.0.2. Thanks.
