### ISSUE TITLE
run on aarch64 running void linux with musl library

### ISSUE THREAD

**Issue by guygastineau** [MediaBrowser/Emby#3498]
Hi, I hope this is the right place to ask this.

I am hoping for some guidance on how to compile this for the aarch64 architecture.  I am hoping to get this running on my rpi 3 b plus with void linux.  My musl libs might complicate the process.

Any advice on compiling this server locally would be greatly appreciated

Thank you,
Guy Gastineau

**Comment by LukePulverenti** [comment]
Hi, we have ready built aarch64 packages in beta:
https://emby.media/linux-server.html
Please let us know if this helps. Thanks !

**Comment by guygastineau** [comment]
@LukePulverenti thank you.

I'll try this today.  I am backing my pi up over ssh right now, so I'll wait before trying those binaries.

Should I close this issue in the meantime?

**Comment by guygastineau** [comment]
Also, if I get this working I'll pass info to the void maintainers and see if we can get a package in their xbps repos.

If/when this happens I will give you all the info if you want directions for void on your website.

**Comment by guygastineau** [comment]
So these binaries don't work with the musl libraries on my void r pi 3 b plus.

Is it possible to get some direction for compiling for the aarch64 architecture?

I would really like to use your software on this platform; and I hope to help others do the same.

Thank you for your time

**Comment by LukePulverenti** [comment]
Hi, what exactly do you mean by "don't work"? Thanks.

**Comment by guygastineau** [comment]
I mean, they are compiled against glibc, and my machine uses musl in place of glibc.

That is why I want to compile it myself.

I am sure the binaries I pulled out of the Debian package are functional for an aarch64 system with the more conventional glibc.

**Comment by guygastineau** [comment]
I'm sorry. I believe I am wrong.

Your binaries are compiled from c#?

**Comment by guygastineau** [comment]
Further investigation shows that it still utilizes glibc in system calls.

**Comment by guygastineau** [comment]
Most likely I cannot compile these binaries on my pi either due to the environmental complexity of c# compilation.

Would you like me to close this issue?

**Comment by LukePulverenti** [comment]
Before we can proceed further, we'll need support from .NET Core to run on musl:
https://github.com/dotnet/docs/issues/5731

Thanks.

**Comment by guygastineau** [comment]
Thank you for looking into this.
