### ISSUE TITLE
Unable to scroll people

### ISSUE THREAD

**Issue by IceBoosteR** [MediaBrowser/Emby#3500]
Hi all,

I am using the latest version of Emby Server. I have seen an issue with the XBOX One app and the Samsung TV app. When I click on a person/actor to see in which movies the actor has been in, I am unable to scroll. therefore I can see the photo of the actor and the biography, but I am unable to see the movies he/she has been in.
It is not seen on the Android app or somewhere else.
This problem is reproducable. Thanks

**Comment by LukePulverenti** [comment]
Hi, can you by chance show a screenshot or image of one of these? I have seen this reported before but  haven't reproduced myself. I think it is something that is only observed under certain conditions. Thanks !

**Comment by IceBoosteR** [comment]
Hi,
I have made two screenshot. There is nop possibilty to scroll, I even do not have a "selection/cursor" to move. these are taken from the XBOX version.
https://imgur.com/a/m9BmmQH
You can not even see the movies the actor is in.

**Comment by LukePulverenti** [comment]
This is resolved for the next updates to both of these apps. Thanks.
