### ISSUE TITLE
unable to play video

### ISSUE THREAD

**Issue by icf20** [MediaBrowser/Emby#3502]
freenas Version 3.5.3.0 

the video dont play, there is just a loading gif nothing more

**Comment by LukePulverenti** [comment]
Hi there, please attach the information requested in how to report a media playback issue:
https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/

Thanks !

**Comment by icf20** [comment]
it is exactly this https://emby.media/community/index.php?/topic/64890-error-librarymonitor-heaps-and-heaps-of-error-reports-in-the-server-log/#entry644466

**Comment by LukePulverenti** [comment]
Can you please attach the information anyway so that I can try and help you? There is no way that library monitor errors are going to interfere with playback. Thanks !

**Comment by icf20** [comment]
i installed beta 3.6.0.80 

for now is working OK
