### ISSUE TITLE
Can't omit port in Emby setup on Android TV

### ISSUE THREAD

**Issue by kevin-hanselman** [MediaBrowser/Emby#3503]
I've setup an Emby server on my LAN (remote access disabled) behind a reverse proxy. The Emby server web UI is accessible to any web browser connected to my LAN at http://192.168.1.111/emby/. I installed the Emby Android app on my phone, and connected to the server via IP address (skipping Emby Connect); this worked just fine, and I could stream my media. (I needed to leave the Port field empty.) Here is a snippet from my embyserver.txt log when connecting from my Android phone:

```
2019-01-02 18:13:01.195 Info HttpServer: HTTP Response 200 to 192.168.1.125. Time: 1ms. http://192.168.1.111:8096/emby//emby/system/info/public?format=json 
```

I've also installed the Emby for Android TV app on my Nvidia Shield TV, but I cannot connect to the server via IP address _even when using the same IP/port entries that worked on my Android phone_. Here is the log entry from my Shield TV when it tries to connect to the server:

```
2019-01-02 18:04:33.141 Info HttpServer: HTTP Response 404 to 192.168.1.222. Time: 1ms. http://192.168.1.111:8096/emby/:/emby/system/info/public?format=json 
```

It looks to me like the the port specifier, `:`, is not being properly ignored when said field is empty, thus causing the 404; this is the only significant difference between the two log entries. Furthermore, **there is no notification of any error in the Android TV app; the dialog simply closes and puts me back at the "Emby Connect or Enter IP" screen.** Luckily I know enough to look at the server logs.

**Comment by kevin-hanselman** [comment]
@LukePulverenti, any response?

**Comment by ebr11** [comment]
Hi.  Thanks for the report.  We will take a look at this.

**Comment by ebr11** [comment]
Hi.  This should be fixed in the beta of the app that went up today.

Thanks.
