### ISSUE TITLE
Unable to sign out in web app

### ISSUE THREAD

**Issue by AlphaCzech** [MediaBrowser/Emby#3505]
I'm unable to sign out from Emby web app. The button is simply missing. 

Emby version: 3.5.3.0

Tried clearing cache, different browsers (latest Chrome, edge, firefox), incognito tabs.

![image](https://user-images.githubusercontent.com/18165288/51077513-f5c21e80-16a7-11e9-8dbc-6232f69fd357.png)

**Comment by LukePulverenti** [comment]
If your server only has one user, and if that user does not have a password, then there is no sign out and you're always automatically logged in.

Try giving your user a password, or adding a second user.

**Comment by AlphaCzech** [comment]
I created another user, "test" and the option to Sign out appeared. However, my first user has always had a password set up. It's emby connect user which I used during the initial setup.

When I check password for user AlphaCzech I see only two options: New password and New password confirm. Does it mean I can have two passwords for one user?

EDIT
I tried logging in without password and it let me, then I tried with my actual password and it also let me in, lastly I tried typing some nonsense for the password and it told me I had incorrect credentials.

Is this how it's supposed to work? It doesn't feel right.

**Comment by AlphaCzech** [comment]
I tried logging in without password and it let me, then I tried with my actual password and it also let me in, lastly I tried typing some nonsense for the password and it told me I had incorrect credentials.

Is this how it's supposed to work? It doesn't feel right.

**Comment by LukePulverenti** [comment]
Ok, the problem here is that there is some confusion over local login vs Emby Connect. Yes I would suggest assigning a password to your local Emby user from within your server dashboard.

The Emby Connect feature is something that you would use away from home to make remote access easier, and it has it's own password.

**Comment by AlphaCzech** [comment]
I see Luke, thank you for the explanation. I set password for my local account now.
