### ISSUE TITLE
Chapter information for audiobooks

### ISSUE THREAD

**Issue by yermak** [MediaBrowser/Emby#3506]
Audiobooks (m4b) contain chapter information in metadata availabile for extraction with ffmpeg.
We need to create artificial chapter with chapters based on internal metadata.

Idieally book representation for MP3s with same album name and audiobook should look similar, so use could start playback of the book from any mp3 file or any chapter in m4b.

**Comment by LukePulverenti** [comment]
This will be in the upcoming Emby Server 4.7 release. Thanks !
