### ISSUE TITLE
On pause immidiately update save position on the server

### ISSUE THREAD

**Issue by yermak** [MediaBrowser/Emby#3507]
During listening of dowloaded audiobooks on iOS (m4b) i discovered the following behavior.
If you make media active and properly set media on pause, chances that it saves listening position are quite high.
If you pause media from locked screen or using airpods, if you resume it within minute or so it works ok, but after longer period or if application is closed completely - it seem like media is fallen back to last saved position.
I suggest to sync with server after each pause/resume.

**Comment by LukePulverenti** [comment]
Hi, we already do this in response to any user action. Anytime you do something manually in the video player, it gets reported to the server immediately. We would need to look at a more specific example. Thanks !

**Comment by LukePulverenti** [comment]
Hi there, how does the latest version of the app compare?

**Comment by LukePulverenti** [comment]
Anytime media is paused we immediately report to the server. If you're still seeing an issue please let us know, thanks.
