### ISSUE TITLE
iOS media navigation - minimal units of time change

### ISSUE THREAD

**Issue by yermak** [MediaBrowser/Emby#3508]
on iOS player time bar could only be changed within some minimal unit, e.g. on average film I can rewind for few seconds, however on long media, e.g. 10+ hours, i could only rewind for about 10 mins - that is minimal step. Which make precise navigation difficult.
Can we add a check to keep minimal step at least 1min, if minimal step is calculated on pro-rate with media duration.

**Comment by LukePulverenti** [comment]
Please try the new video OSD in 1.8.3:
https://emby.media/community/index.php?/blog/1/entry-472-emby-for-ios-updated-for-ios-13-and-new-video-osd/
Thanks.

**Comment by LukePulverenti** [comment]
Hi there, are you still having an issue with this?

**Comment by yermak** [comment]
Thanks, Luke.

While precise positioning is not accurate enough, on long audiobook i could get only about 5 mins of accuracy. Having rewind buttons actually resolves the issue. 

What is more important it seems it now saves position of audiobook when pause it (even via airpods) which actually makes issue irrelevant.

However, while restarting audiobook from saved position, which could take a while, if i click play button twice it restart book from the beginning - which could be quite upsetting
