### ISSUE TITLE
add ability to use .actors folder from TinyMediaManager for actor photos

### ISSUE THREAD

**Issue by C4Wiz** [MediaBrowser/Emby#3509]
TinyMediaManager stores actor images in a folder called .actors inside the folder with the movie, can this folder be scraped by emby?
<img width="511" alt="screen shot 2019-01-20 at 2 10 55 pm" src="https://user-images.githubusercontent.com/3883521/51443858-3e3b9680-1cbd-11e9-9f03-be7248d803ef.png">

**Comment by C4Wiz** [comment]
anyone?

**Comment by LukePulverenti** [comment]
It's possible for the future. thanks.

**Comment by LukePulverenti** [comment]
This will be in the upcoming 4.8 server release. Thanks.
