### ISSUE TITLE
FFmpeg Source Code Missing?

### ISSUE THREAD

**Issue by anthonylavado** [MediaBrowser/Emby#3511]
Hi there! :wave:

According to a post by @LukePulverenti on the Emby forums, there have been modifications to FFmpeg in order to allow Transcode Throttling: 
https://emby.media/community/index.php?/topic/62657-36040-transcode-throttle-is-back/page-1

I can’t seem to find the modifications to FFmpeg listed anywhere, nor a copy of the source code that is being distributed. Can anyone point me in the right direction?

Thanks! 😄

**Comment by LukePulverenti** [comment]
We will add the ffmpeg source to our distributions. Thanks.

**Comment by anthonylavado** [comment]
Hi @LukePulverenti! 👋 

Just checking in again as I see a few more releases have come through (even in beta form).

Do you know where I can look for the FFmpeg source?

Thanks 🤠

**Comment by LukePulverenti** [comment]
We will get this added to our distributed packages. Please just give us a little bit of time. Thanks.

**Comment by anthonylavado** [comment]
Okay. Thank you!

**Comment by cactushydrocodone** [comment]
How much time do you need?
when did you plan to do this?
Some transparency on this please, i cannot use my emby premiere production right now because i need the ffmpeg from you, as the official one doesnt work anymore thanks to your modifications.

**Comment by LukePulverenti** [comment]
If you need it immediately you can get it from our arch linux package:
https://www.archlinux.org/packages/community/any/emby-server/
Just click source files, then open the PkgBuild.

Having said that, what problem are you trying to resolve? The server is designed to work both with and without our modified ffmpeg builds. There might be some features missing with a vanilla build, but nothing should break.

**Comment by cactushydrocodone** [comment]
Transcoding with a vanilla 4.1 build isnt possible. Only DirectPlay.
 
The error message says that "look_ahead" is missing from the build.

**Comment by softworkz** [comment]
ffmpeg 4.1 is not supported.

Why don't you simply use the ffmpeg version that is included with the Emby installation package?

**Comment by LukePulverenti** [comment]
Right, we haven't gotten to 4.1 yet. I should clarify what i meant by vanilla ffmpeg - you should at least make sure to match the version we're shipping. Anything else you can assume is untested. Thanks.

**Comment by cactushydrocodone** [comment]
@softworkz Because it is not included in my installation. I use the netcore zip.

**Comment by cactushydrocodone** [comment]
But i will try ffmpeg 4.0.1 now, thanks

**Comment by softworkz** [comment]
On which platform are you?

**Comment by cactushydrocodone** [comment]
Now it works, i havent fully tested it yet (4.0.3 was the build i tested now). Thanks for the help, will document this in my notes for the future

**Comment by softworkz** [comment]
I'm still curious: On which platform are you? Windows, Linux or else?

**Comment by cactushydrocodone** [comment]
@softworkz Sorry didnt saw your message there, im using Alpine Linux

**Comment by LukePulverenti** [comment]
Starting with beta 4.1.0.10, the licenses file contains a link to the ffmpeg source code that was used to build it. As previously mentioned, this is already in the arch linux stable package. Thanks.
