### ISSUE TITLE
Inability to change subtitle size on LG Smart TV (LG C8)

### ISSUE THREAD

**Issue by AdnanHodzic** [MediaBrowser/Emby#3515]
On LG Smart TV (LG C8) app, I do not have functionality to change subtitles size. If I go to user settings, I'm only greeted with few options (Home/Select server/Sign out/Exit). This is a problem as the subtitles size is huge and takes big portion of a screen, which makes it very difficult to watch content on the TV.

In LG Content Store it states that Emby app was last updated on 03/08/2018 and its version is: 1.0.9

If I go to same options in my browser, I'm greeted with many more settings out of which one is "Subtitles". Which allows me to change subtitle size as well as many other subtitle related settings.

**Comment by LukePulverenti** [comment]
Hi, this will be available in the next update to the app. Thanks !

**Comment by AdnanHodzic** [comment]
Great, looking forward to that update! Do you happen to have any indication when the update will be rolled out?

**Comment by LukePulverenti** [comment]
Hopefully in the next few weeks. It will be whenever it gets through the LG review process. Thanks.
