### ISSUE TITLE
Audio books not working

### ISSUE THREAD

**Issue by ArthurKnoep** [MediaBrowser/Emby#3516]
Hello guys,

Since I have updated my server on the latest version (v4.0.1.0), I am not able to access my audio books.

I can navigate the folder, but when I open the last folder (with all my audio files inside), the screen stays empty.

The API call `/Users/<id>/Items` returns that : `{"Items":[],"TotalRecordCount":0}`

Note: I use Emby via the official docker: emby/embyserver

**Comment by LukePulverenti** [comment]
Hi, is it still setup with the Books content type? There is now a dedicated audio books content type. You will need to remove the books library, run a scan, and then add it back as audio books. Please let me know if this resolves it for you. Thanks.

**Comment by ArthurKnoep** [comment]
Hi @LukePulverenti 

Tanks for your help, I have removed my library and recreate it under "Audio book" content type and now it's working again.
But now I have a strange behavior that some books have no metadata (emby displays only the filename instead of the mp3 metadata)
