### ISSUE TITLE
Create collection based on nfo

### ISSUE THREAD

**Issue by hbooo** [MediaBrowser/Emby#3519]
Hello,

I'm currently filling my metadatas with MediaElch to have consistency between emby, plex and kodi.

It works great but collections aren't generated from nfo files despite the fact that node
"set" is filled.

Is it possible to add this to emby?

Thanks in advance

**Comment by Penkethboy** [comment]
They are saved as xml files not NFO's (although format is similar)

see your .\data\collections folder for examples or create one manually via the web interface for testing

**Comment by hbooo** [comment]
Problem is that I won't be able to use them on plex or kodi. Is there any way to define globally the folder, in order to not have it in .\data\collections but in a specified folder? I found how to change for a boxset but not for all

**Comment by LukePulverenti** [comment]
This will be in Emby Server 4.6.
