### ISSUE TITLE
delete permission broken

### ISSUE THREAD

**Issue by joCoutu** [MediaBrowser/Emby#3525]

**Comment by joCoutu** [comment]
I create a user and remove permission to delete content.
I login with this user - add a video to my playlist - delete the playlist and this remove the video

**Comment by LukePulverenti** [comment]
Hi, it isn't that it's broken, it's that playlists and collections can be created by anyone and therefore have their own rules. This is something we'll be revamping in a future update to make it more transparent and configurable. Thanks.

**Comment by joCoutu** [comment]
ok as a workaround, I remove the linux write permission on my media folder
