### ISSUE TITLE
Starting Emby only works once on macOS

### ISSUE THREAD

**Issue by optikfluffel** [MediaBrowser/Emby#3526]
When I stop Emby via the menu bar icon this doesn't seem to stop the EmberServer process, I then have to sign out or reboot my Macbook to be able to start it again.

Apart from that I get a bunch of errors in the Console when starting Emby:

```
11:01:09.917005 +0100	EmbyServer	MacOS error: -25294
11:01:09.921755 +0100	EmbyServer	MacOS error: -25294
11:01:09.937728 +0100	EmbyServer	MacOS error: -25294
11:01:09.945716 +0100	EmbyServer	MacOS error: -25294
11:01:09.979698 +0100	EmbyServer	MacOS error: -25294
11:01:09.985411 +0100	EmbyServer	MacOS error: -25294
11:01:09.988826 +0100	EmbyServer	MacOS error: -25294
11:01:10.011695 +0100	EmbyServer	MacOS error: -25294
11:01:10.015070 +0100	EmbyServer	MacOS error: -25294
11:01:10.018408 +0100	EmbyServer	MacOS error: -25294
11:01:10.020955 +0100	EmbyServer	MacOS error: -25294
11:01:10.032258 +0100	EmbyServer	MacOS error: -25294
11:01:10.035329 +0100	EmbyServer	MacOS error: -25294
11:01:10.038155 +0100	EmbyServer	MacOS error: -25294
11:01:10.044827 +0100	EmbyServer	MacOS error: -25294
11:01:10.046819 +0100	EmbyServer	MacOS error: -25294
11:01:10.750331 +0100	EmbyServer	MacOS error: -25294
11:01:10.757643 +0100	EmbyServer	MacOS error: -25294
11:01:10.768761 +0100	EmbyServer	MacOS error: -25294
11:01:10.775369 +0100	EmbyServer	MacOS error: -25294
11:01:10.780889 +0100	EmbyServer	MacOS error: -25294
11:01:10.785434 +0100	EmbyServer	MacOS error: -25294
11:01:10.789267 +0100	EmbyServer	MacOS error: -25294
11:01:10.792535 +0100	EmbyServer	MacOS error: -25294
11:01:10.798001 +0100	EmbyServer	MacOS error: -25294
11:01:10.801860 +0100	EmbyServer	MacOS error: -25294
11:01:10.806072 +0100	EmbyServer	MacOS error: -25294
11:01:10.809883 +0100	EmbyServer	MacOS error: -25294
11:01:11.157593 +0100	EmbyServer	MacOS error: -25294
11:01:11.165810 +0100	EmbyServer	MacOS error: -25294
11:01:11.170190 +0100	EmbyServer	MacOS error: -25294
11:01:11.175214 +0100	EmbyServer	MacOS error: -25294
11:01:11.237708 +0100	EmbyServer	MacOS error: -25294
11:01:11.246035 +0100	EmbyServer	MacOS error: -25294
11:01:11.253197 +0100	EmbyServer	MacOS error: -25294
11:01:11.264746 +0100	EmbyServer	MacOS error: -25294
11:01:11.805328 +0100	EmbyServer	MacOS error: -25294
11:01:11.812506 +0100	EmbyServer	MacOS error: -25294
11:01:11.821216 +0100	EmbyServer	MacOS error: -25294
11:01:11.825203 +0100	EmbyServer	MacOS error: -25294
11:01:11.830081 +0100	EmbyServer	MacOS error: -25294
11:01:11.836484 +0100	EmbyServer	MacOS error: -25294
```

**Comment by cygvis** [comment]
I've copied the following from a reply of mine on the forums:

I'm on Sierra 10.12.6 (16G29).

Same thing except it wouldn't start at all yesterday so I trashed it along w/ the preferences file (only thing AppCleaner found). Didn't reboot b/c of a GPU issue.

Today, I reinstalled and it still won't start and there's no indication of it in Activity Monitor. If I open it too many times, macOS claims it can't because it’s either not responding or it's already open.

I've still got the folder in my .config folder. The files haven't been modified since yesterday.

I'll try deleting the config folder now along with the app, etc.

EDIT: I attached the logs folder. Made a copy of the config folder too, just let me know if I should attach here or send in a PM or whatever.

[logs.zip](https://github.com/MediaBrowser/Emby/files/2908264/logs.zip)

**Comment by cygvis** [comment]
ALSO: I started searching for @optikfluffel error code and came across [another similar Github issue.](https://github.com/pyinstaller/pyinstaller/issues/1804#issuecomment-331717394) Which reminded me that I tried opening from the terminal yesterday and it was the only way it started up again.

The comment below my linked one might be helpful, I'm not sure.

I just tried it again but it only opened with the -n option (opening a new instance of Emby). So there's probably two Embys running right now but only one in Activity Monitor.

**Comment by anthonylavado** [comment]
Hi there - I’m not from Emby, but as a fellow macOS user, do you have the .app in your Applications folder?

If it’s anywhere else, GateKeeper can cause some weird issues with the way the app is bundled together.

**Comment by LukePulverenti** [comment]
Are you still seeing this with the 4.1.1 release?

**Comment by optikfluffel** [comment]
@anthonylavado Yes, it's in the Application folder.
@LukePulverenti Yes. Same `MacOS error: -25294`, same dangling process after closing Emby that seems to prevent it from starting again.

When Emby is running I still have two processes (`Emby Server` and `EmbyServer`), only one of which is killed when closing Emby. The only thing different now is after I kill this process manually, I can start Emby again without logging out or rebooting.

Running:

<img width="815" alt="running" src="https://user-images.githubusercontent.com/379915/57580261-bcf45380-74a7-11e9-8127-c9a199db4d01.png">

After closing:

<img width="815" alt="after closing" src="https://user-images.githubusercontent.com/379915/57580263-c41b6180-74a7-11e9-9602-535d51e03b2b.png">

**Comment by optikfluffel** [comment]
Seems fixed in recent versions. Thanks <3
