### ISSUE TITLE
[PSA] emby 4.0.2.0 dont see chromecast if there is no https because chrome

### ISSUE THREAD

**Issue by icf20** [MediaBrowser/Emby#3527]
![image](https://user-images.githubusercontent.com/17784575/52974827-43c2f400-33c3-11e9-9322-a332652cae2a.png)

Version 72.0.3626.109

**Comment by icf20** [comment]
![image](https://user-images.githubusercontent.com/17784575/52975602-70c4d600-33c6-11e9-9145-eeafa0b67d1b.png)
Version 71.0.3578.98 


for arch user just install https://github.com/pbrisbin/downgrade and then downgrade chromium to version 71

**Comment by LukePulverenti** [comment]
Thanks for reporting. This is a Chrome requirement starting with Chrome 72. You either need to be running the web app on https or localhost. You can also use our android or iOS mobile apps. I'm going to close this as this is out of our control. Thanks.
