### ISSUE TITLE
Emby upnp does not work

### ISSUE THREAD

**Issue by brofjst** [MediaBrowser/Emby#3528]
Hi.
I'm running emby server, i've enabled upnp connection on emby and on the router.
Other applications like the torrent client works, emby does not.
I can't connect to the emby server from outside his network, neither by the emby app for android.

**Comment by LukePulverenti** [comment]
Hi, what router do you have? Our port mapping feature is not guaranteed to work with all router models, but you can always manually configure your router. Have you tried that? Can you please attach an emby server log? thanks.

**Comment by brofjst** [comment]
My routers are: asus rtn18u connected in series with a TIM HUB.
I can't access to my routers, my father owns them and he gets mad about them, he does not allow to anyone to access to them, neither my brother or me.
I just can say that upnp is enabled on both routers.
i need to get emby work with upnp or i can't use it.
I'm using Arch linux, the firewall is turned off.

[Server Logs](https://paste.ofcode.org/iKxz8phbixQ7Rdaa5tvUaG)

**Comment by LukePulverenti** [comment]
Hi, that log is coming up not found. Can you please attach it to here? thanks !

**Comment by brofjst** [comment]
[This](https://mega.nz/#!QkBCEQjT!egRQXmbc4isbXo8DjJDRKQtCIWpMFvj4xljLsEemAEU) link won't expire.

**Comment by LukePulverenti** [comment]
What installation is this? Is this our Docker package?

**Comment by brofjst** [comment]
I do not understand the question: i've installed emby by official arch linux repo [wiki](https://wiki.archlinux.org/index.php/Emby), the server's logs were taken by the emby interface expert -> Logs->embyserver.txt

**Comment by LukePulverenti** [comment]
Hi there, can you try this with the 4.1.1 release? Thanks !

**Comment by LukePulverenti** [comment]
Hi, were you able to try 4.1.1?

**Comment by LukePulverenti** [comment]
Any news?

**Comment by LukePulverenti** [comment]
Closing, but please feel free to re-open with the requested information. Thanks.
