### ISSUE TITLE
Bug: DLAN Remote

### ISSUE THREAD

**Issue by zero77** [MediaBrowser/Emby#3531]
I am using both, the newest Emby server beta  on ubuntu 18.04 also, android 9 with the newest Emby beta app.

When streaming media over DLAN to an AnyCast device it plays successfully.

But, the controls don't work except mute/unmute.
Also, pause/play but that works intermittently.

![Screenshot_2019-03-13 Emby](https://user-images.githubusercontent.com/16563034/54287129-00f8d400-459d-11e9-8c73-1ac01c1889e5.png)

![Screenshot_2019-03-13 Emby(1)](https://user-images.githubusercontent.com/16563034/54287135-03f3c480-459d-11e9-9ba4-07cd1d1f8a3d.png)

**Comment by LukePulverenti** [comment]
Why are you closing this?

**Comment by zero77** [comment]
I thought it may be better placed on the emby Forums.
