### ISSUE TITLE
docker image fails to complete startup

### ISSUE THREAD

**Issue by mnbf9rca** [MediaBrowser/Emby#3532]
I use your docker image on a Ubuntu LTS 18.04 host with kubernetes (microk8s) installed from snap. My config is located on another server, and access is via an NFS PersistentVolume with  ReadWriteOnce accessmode to prevent more than one pod accessing the DB at a time. The media is also on an NFS share accessed via a PersistentVolume. On starting the pod, the startup scripts often never finish/move beyond "Starting services":
```
2019-03-16T12:42:07.734051173Z [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
2019-03-16T12:42:07.768086426Z [s6-init] ensuring user provided files have correct perms...exited 0.
2019-03-16T12:42:07.769130114Z [fix-attrs.d] applying ownership &amp; permissions fixes...
2019-03-16T12:42:07.770515143Z [fix-attrs.d] done.
2019-03-16T12:42:07.771060011Z [cont-init.d] executing container initialization scripts...
2019-03-16T12:42:07.772421131Z [cont-init.d] done.
2019-03-16T12:42:07.773094396Z [services.d] starting services
2019-03-16T12:42:07.783508189Z [services.d] done.
```
My kubernetes config is here, along with instructions to recreate the system:
https://github.com/mnbf9rca/kubernetes_config
Other apps e.g. sonarr, couchpotato etc. all run fine.

**Comment by mnbf9rca** [comment]
i changed the liveness check timeout from 10 minutes to 1 hour, and that seems to have given it time to boot - it takes over 40 minutes...

**Comment by LukePulverenti** [comment]
Hi, is it still taking that long?

**Comment by mnbf9rca** [comment]
Yes.

On 3 Apr 2019, at 19:39, Luke <notifications@github.com> wrote:

Hi, is it still taking that long?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MediaBrowser/Emby/issues/3532#issuecomment-479609999>,
or mute the thread

**Comment by LukePulverenti** [comment]
Ok, please let me know how the upcoming 4.1 release compares. If you'd like to try it now, you can try the beta version. Thanks.

**Comment by mnbf9rca** [comment]
i tried it with `emby/embyserver:beta` and get the following state changes from Kubernetes:

- Initialized: 2019-04-22T13:18:24Z
- Started at: 2019-04-22T13:19:20Z --> after pulling the image
- Ready: 2019-04-22T13:55:38Z --> this is when it responds to a TCP connection request on port 8096

are there any log files i can pull to give more info?
