### ISSUE TITLE
[Suggestion] Exclude Channels Not Mapped from guide

### ISSUE THREAD

**Issue by poppabear8883** [MediaBrowser/Emby#3536]
I think its beneficial to NOT display the channels that have no mappings on the guide itself. This way the guide program data can be as clean as possible without having to go through several channels without data to get to more channels with data.

Ultimately, it just doesn't make sense to have the channel on the guide if there is not program data.

**Comment by MCTyler** [comment]
Well, that 1 is just not true. You have no VOD, Live Events, or 24/7 Channels with your Service? Come See me :) you will like my service I sell a lot more .

**Comment by poppabear8883** [comment]
Not sure what you mean, I'm referring to just Guide Data alone, not removing the channels from the channel listings. Yes i have VOD, 24/7, etc ... but i do not wish to see them in the `GUIDE` but only see them in the `Channel Listing` @MCTyler

**Comment by LukePulverenti** [comment]
The ability to exclude channels is coming in Emby Server 4.6.
