### ISSUE TITLE
[Suggestion] UnMap Channels

### ISSUE THREAD

**Issue by poppabear8883** [MediaBrowser/Emby#3538]
I know there is another issue ( #2651 )  similar to this, but since its been ignored for so long I thought i would open a new issue in hopes to bump this to the top.

I think its important that we have the ability to UnMap a channel. Maybe it was mapped through the auto mapper and it should not have a mapping at all.

**Comment by poppabear8883** [comment]
This is really really frustrating ... just saying!

**Comment by LukePulverenti** [comment]
Merging with #2651. Yes we plan on finally getting to this soon.

Thanks.
