### ISSUE TITLE
[Suggestion] Channel Numbers

### ISSUE THREAD

**Issue by poppabear8883** [MediaBrowser/Emby#3539]
Channel numbers should be mapped to the ones from the guide data source imo.

If my m3u file has 17345 but i mapped it to channel 7, it should use channel 7 on the guide!

**Comment by LukePulverenti** [comment]
This will be in Emby Server 4.8. The tuner setup screen will have an option to control where the channel numbers come from.

**Comment by poppabear8883** [comment]
doesn't look like this code base has even been touched in over 4 yrs ?

**Comment by LukePulverenti** [comment]
> doesn't look like this code base has even been touched in over 4 yrs ?

HI, the issue tracker is still used for those who open issues here.
