### ISSUE TITLE
need help with parallel video transcoding and streaming

### ISSUE THREAD

**Issue by phanirithvij** [MediaBrowser/Emby#3540]
Hi.
I've found that emby can play many file formats even in unsupported environments,
For eg: playing an mkv file in Firefox.

I'm having trouble doing a similar thing.
It's important, please help me. (It's a college project)

I've searched for it all over the internet and finally ended up here.
And I'm not familiar with C# so please help me.

I want to know where the logic for the `mkv to m3u8` conversion is being handled.
And how the seeking is being handled.

Thanks in advance.

**Comment by phanirithvij** [comment]
I tried these

I started this on a command line

`ffmpeg -i ../stream.mkv -hls_list_size 0 -acodec copy -vcodec copy file.m3u8`
and a simple `http-server` on another shell instance

My index.html file

```html
<html>
    <title>Welcome</title>
    <body>
        <script src="./hls.js"></script>
        <video id="video" width="400" controls></video>
        <script>
            var video = document.getElementById('video');
            if(Hls.isSupported()) {
                var hls = new Hls();
                hls.loadSource('file.m3u8');
                hls.attachMedia(video);
                hls.on(Hls.Events.MANIFEST_PARSED,function() {
                    video.play();
                });
            } else if (video.canPlayType('application/vnd.apple.mpegurl')) {
                video.src = 'file.m3u8';
                video.addEventListener('loadedmetadata',function() {
                    video.play();
                });
            }
        </script>
    </body>
</html>
```

and while it was running I went ahead and requested the server.

I was able to get the video but It only seeks as far it's converted into the ts files.

And it's random and the video length keeps increasing. It won't play sometimes and after the FFmpeg is done converting to m3u8 the video plays if I refresh the webpage.

I think this has to do with the continuous overwriting of the m3u8 file. is there a way to predetermine the file contents of m3u8 and fill it up?

**Comment by LukePulverenti** [comment]
Hi there, unfortunately I do not have the bandwidth to be able to help you with your college project, but I think this might help you:
https://www.codeproject.com/Articles/1079119/Video-Transcoding-and-Streaming-on-the-fly
Thanks.
