### ISSUE TITLE
Seeking within video on Safari 12.1 (OSX) freezes playback

### ISSUE THREAD

**Issue by ghost** [MediaBrowser/Emby#3541]
Fyi - When playing a video via the web browser on Safari 12.1 (OSX) and then seeking to any other point, the playback stops. You can't resume it either. Pause / Play won't restart it either.

It works with Firefox on OSX so I am assuming this is specific to Safari 12.1 as it worked before upgrading.

**Comment by CyberCr33p** [comment]
I have the same issue. It happens with Emby Beta (4.1.0.25) too.

**Comment by CyberCr33p** [comment]
Same issue with 4.1.0.26

**Comment by ghost** [comment]
Today I noticed that you can seek within video that you already streamed, e.g. your five min into a video, you can seek to 2m, 3m, etc. but as soon as you seek to ten min it freezes playback. 

So in short, you can't seek to any parts which haven't played yet.

**Comment by LukePulverenti** [comment]
This will be resolved in Emby Server 4.1.1. Thanks for reporting.
