### ISSUE TITLE
chromecast remote disconnect in browser 

### ISSUE THREAD

**Issue by lwhitehead1706** [MediaBrowser/Emby#3544]
hi , 

if you go to the server dashboard you lose the control over chromecast, you cannot get it back without disconnecting chromecast and then connecting again.

this also happens if you disconnect but keep the stream running , clicking on the chrome icon on emby does nothing.

thanks

**Comment by LukePulverenti** [comment]
Hi, this will be resolved in Emby Server 4.1.1. Thanks.
