### ISSUE TITLE
surround sound enabled. to adjust volume, use your tv's remote control.

### ISSUE THREAD

**Issue by lwhitehead1706** [MediaBrowser/Emby#3545]
hi ,
when streaming with ac3 codec i cannot change the volume on the tv using chromecast
thanks

**Comment by LukePulverenti** [comment]
Hi there,  have you tried using the TV remote control? This message is being displayed to you by Chromecast, not by Emby.

**Comment by lwhitehead1706** [comment]
Hi Luke thanks for the reply.
Yes it works with the remote but I only have this issue with Dolby digital 5.1 , mp3 codec works fine

**Comment by lwhitehead1706** [comment]
https://emby.media/community/index.php?/topic/60845-disable-audio-passthrough/?hl=%2Bsurround+%2Bsound+%2Benabled.+%2Badjust+%2Bvolume 

@LukePulverenti  doesnt emby now support converting ac3 to stereo ?

**Comment by LukePulverenti** [comment]
We do, but we only convert when needed. If the Chromecast receiver supports ac3 output, then we take advantage of that when possible. It is planned to add settings in the future to allow you to control this:
https://github.com/MediaBrowser/Emby/issues/3388

**Comment by LukePulverenti** [comment]
Closing as this is expected behavior. Once #3388 is implemented, you will be able to force audio conversion if you desire. Thanks.
