### ISSUE TITLE
[Feature Request] Add titles to artist overview

### ISSUE THREAD

**Issue by IceBoosteR** [MediaBrowser/Emby#3546]
Hi everyone,

when I search for an artist in my media server, and I do click on the result for artist xyz I will get an overview from all theirt albums and suggestions for other, similar artists. Often I do search for some specific tracks, not kniwing the exact name but the artist. With that overview it is impossible for me to find the track I am searching for.
Would it be possible to add another group in the artist xyz overview showing all tracks they have done?
That would be awesome.
If I have not explained enough, letme know.

For interest: When I am searching the artist, the first search page shows me "Artists" and "Tracks". Bu often the track is not in the list of "Tracks". Even tho I think the page how to show the tracks that way is not great. Artists with more than 5 songs are not well coverd IMHO - maybe a list would be better - but not that kind of scolling.

Thanks

**Comment by LukePulverenti** [comment]
Hi, this will be in Emby Server 4.6. Thanks for the feedback.
