### ISSUE TITLE
Manually downloaded images get lost on scanning with meta data replacement

### ISSUE THREAD

**Issue by godfuture** [MediaBrowser/Emby#3547]
With much work I have placed images named "folder.jpg" into my audio book folders. But somehow the genre thumbnails did not update accordingly, even album thumbnails changed. I thought, I might solve this by scanning the library and checking the option "replace images". After the operation was finished, all my "folder.jpg" images were gone, but no new images were placed into the folders. I wonder, because "replace" means to me to put something new for something old. In my case, only the old was removed but nothing new was left.

Please do not delete images for albums of which no images can be downloaded. Otherwise you end up with nothing.

Besides that it seems that genre thumbnails do not update properly after changes to mp3 tags.

Version 4.0.2.0

**Comment by LukePulverenti** [comment]
This will be resolved in Emby Server 4.4. Thanks.
