### ISSUE TITLE
Placeholder image in music's nowplaying page

### ISSUE THREAD

**Issue by Galex1223** [MediaBrowser/Emby#3548]
Hi, I've been using Emby for a couple months now and there is a little thing that annoys me.

When in the `[ip adress]/web/index.html#!/nowplaying.html` web page, the play/pause, stop, next, etc. buttons change location if there is an album image or not. 

Example : 
![image](https://user-images.githubusercontent.com/31663362/56763392-4ef22180-6770-11e9-983b-9b7566e7d6aa.png)
![image](https://user-images.githubusercontent.com/31663362/56763447-72b56780-6770-11e9-8ab9-7a348c0ef7b3.png)

Would it be possible to add a placeholder image like when browsing the full library ? 

![image](https://user-images.githubusercontent.com/31663362/56763522-a7c1ba00-6770-11e9-9900-1e9b02f586de.png)

**Comment by LukePulverenti** [comment]
This will be resolved in Emby Server 4.3. Please see here for details of the new design:
https://emby.media/community/index.php?/topic/78512-43015-new-audio-osd/

Thanks !
