### ISSUE TITLE
Fullscreen error

### ISSUE THREAD

**Issue by tobenaii** [MediaBrowser/Emby#3549]
When I try to fullscreen a video, chrome spits this error and does nothing.
![Screenshot_23](https://user-images.githubusercontent.com/30368443/56863780-eae48d00-69fd-11e9-93a0-0ddc2a9872bb.png)

**Comment by LukePulverenti** [comment]
Hi, what version of Chrome?

**Comment by LukePulverenti** [comment]
I'm not able to reproduce this. Are you still seeing this?

**Comment by LukePulverenti** [comment]
Closing, but please feel free to re-open with the requested information. I have not been able to reproduce this.
