### ISSUE TITLE
"ZXX" Language Code

### ISSUE THREAD

**Issue by chowbok** [MediaBrowser/Emby#3551]
The "ZXX" language code should be expanded to "No linguistic content".

**Comment by LukePulverenti** [comment]
Hi, where are you using this?

**Comment by chowbok** [comment]
This is the specified language code for MKV audio tracks that are music-only (for instance, silent movie accompaniments or isolated score tracks).

**Comment by LukePulverenti** [comment]
This will be in Emby Server 4.2. Thanks.
