### ISSUE TITLE
Emby can not scan serials correctly for particular name pattern 

### ISSUE THREAD

**Issue by yuriw** [MediaBrowser/Emby#3554]
If files for a series named as:

`NameX_NameY_S01_2018_WEB-DL_720p_NewStudio_SDI_Media_01.mkv`
...
`NameX_NameY_S01_2018_WEB-DL_720p_NewStudio_SDI_Media_07.mkv`
Emby will scan and show only one episode incorrectly.

Renaming files to 
`NameX_NameY_S01_2018_WEB-DL_720p_NewStudio_SDI_Media_s01e01.mkv`
...
`NameX_NameY_S01_2018_WEB-DL_720p_NewStudio_SDI_Media_s01e07.mkv`

Will work correctly.

**Comment by N8trz** [comment]
Well it needs to match one of the patterns laid out in the wiki.  Your first naming convention doesn't so you're lucky that even one of those episodes got matched up correctly. 
https://github.com/MediaBrowser/Wiki/wiki/TV-naming

**Comment by LukePulverenti** [comment]
Yes you either need to use a supported naming convention, or you'll need to use the metadata editor to manually specify the values. Thanks.
