### ISSUE TITLE
.Net crashes emby server on linux when client browses library.

### ISSUE THREAD

**Issue by voeler** [MediaBrowser/Emby#3556]
I'm using emby server on Arch linux.
Emby server works fine, until I connect to the server and browse the library. It will crash shortly after. This happens both when I access it from my browser on the server, or from my phone with the emby app.

In journalctl I can see that dotnet caused the crash, so I'm not sure how useful this is for you..
[embyserver.txt](https://github.com/MediaBrowser/Emby/files/3318573/embyserver.txt)
[journalctl.txt](https://github.com/MediaBrowser/Emby/files/3318574/journalctl.txt)

**Comment by LukePulverenti** [comment]
Hi there, please try Emby Server 4.2 once available and let me know if there's still an issue. Thanks.

**Comment by LukePulverenti** [comment]
Are you still running into this?

**Comment by voeler** [comment]
The issue seems to have been resolved, thanks!
