### ISSUE TITLE
Warning for duplicates in playlist

### ISSUE THREAD

**Issue by langfingaz** [MediaBrowser/Emby#3557]
**Feature Request:**
Show warning if user adds a song multiple times to playlist to prevent duplicate entries.

**Alternative**
Option to sort playlist by name. This way the user can easily find duplicate entries and remove them from the playlist. An issue addressing this already exists: #3380

**Comment by LukePulverenti** [comment]
This will be in Emby Server 4.8:
https://emby.media/community/index.php?/topic/117891-48030-playlist-duplicates-warning/
Thanks.
