### ISSUE TITLE
Tizen error while installing

### ISSUE THREAD

**Issue by snackk** [MediaBrowser/Emby#3558]
I was trying to install Emby from a usb drive on my Samsung TV, followed the tutorial here [install-from-usb](https://emby.media/community/index.php?/topic/74969-samsung-tizen-install-from-usb/). It keeps showing a pop up notification saying the following:

[User App]
._emby.tmg, invalid app package for security failed!

My Samsung TV Version No is UNU7120, and my current firmware version is 1260.

**Comment by LukePulverenti** [comment]
Responded to you here:
https://emby.media/community/index.php?/blog/1/entry-464-emby-for-samsung-tizen-tv-now-available-for-usb-installation/#comment_3544
Thanks.
