### ISSUE TITLE
Support Closed Captions

### ISSUE THREAD

**Issue by jeremy-schweitzer** [MediaBrowser/Emby#3559]
For those in North America (USA) OTA TV uses closed captions instead of subtitles - Emby's recordings include the closed caption streams, but aren't able to replay them. This represents a significant accessibility issue for many people. 

It would be great if Emby could display them natively. Looks like this has been requested multiple times in the forums, but hasn't been documented here before.

**Comment by RonBoyd** [comment]
Yeah, this is why I never use EMBY.

**Comment by LukePulverenti** [comment]
Closed caption support is coming in Emby Server 4.7: https://emby.media/community/index.php?/topic/103974-47019-universal-closed-captions-eia-608708-support/
Thanks.
