### ISSUE TITLE
New added content notification only sends filename

### ISSUE THREAD

**Issue by bjoerns1983** [MediaBrowser/Emby#3565]
I am using the Emby 4.2.0.40 Docker but the problem now persists for the last couple of months.
When i add a movie and i get the notification (via E-Mail or Telegram does not matter) i only get the filename without extension send. Not the Result of the Scraper, for example the Movie name.

For TV Series it mostly works fine, except i add a whole season at once.
Seems that the notifications are send "too early" when the scraper is not already done with the Job.

**Comment by LukePulverenti** [comment]
Emby Server 4.3 is beginning to roll out. Please try that and let us know how that compares. Thanks.

**Comment by bjoerns1983** [comment]
Updated to 4.3.025 and the problem remains. Maybe it is just a a problem with my server and it is screwed up somewhere.

**Comment by LukePulverenti** [comment]
This will be resolved in Emby Server 4.8. Thanks.
