### ISSUE TITLE
Restrict search to user accessible libraries

### ISSUE THREAD

**Issue by phollenberg** [MediaBrowser/Emby#3567]
Currently I've got two libraries:
1 Kids
2 Movies

I've created a user "Kids" and restricted access to library "Kids". However when I'm logged in on the Kids user account and search on "101" to find the movie "101 dalmatians" which is in library "Kids" I get search results  that include "Abuction 101" which is a horror movie located in the library "Movies". 

Both libraries are on different file locations so not mixed up on the filesystem.

Could a setting and/or default behaviour be implemented to restrict the search within the user accessible libraries?

**Comment by LukePulverenti** [comment]
Hi, we already do this. What version of Emby Server? The user can only see content in the search feature that they are allowed to see.

**Comment by phollenberg** [comment]
I can't reproduce this issue I had yesterday
