### ISSUE TITLE
[feature evolution] series autoplay

### ISSUE THREAD

**Issue by drtoio** [MediaBrowser/Emby#3568]
Hi

For now, if autoplay is enabled, when the currently viewed episode is ending, it goes to the next episode, except if you cancel it.

If you disable autoplay, it does nothing.

I'd like to have a 3rd choice : 
- if enabled, when the episode is ending, it proposes you to go to the next one (with a timer, why not) but if you don't click, it does not go to the next one. Maybe you can call it "reverse autoplay" haha.

Why need such a thing ?
I always get asleep in the bed while watching my series and it's so boring to find out when i was in the serie before sleeping...

Thanks for your hard work !

**Comment by LukePulverenti** [comment]
Hi, yes this is coming to Emby apps now. If autoplay is disabled, the episodes will still be queued up but they just won't auto-advance to the next one. You'll get a "Next Episode" button when the current episode stops. At that point you can either click that or go back to stop altogether. Thanks.
