### ISSUE TITLE
Could not find file '/dashboard-ui/userprofiles.html' and others

### ISSUE THREAD

**Issue by godfuture** [MediaBrowser/Emby#3570]
Hey guys, I just moved my docker image (latest) from 4.1.x to 4.2.1.0. Looked like it worked, but now I can't open some of the admin pages. One is the user management tab, another the plugins. But there are others as well.

If I click the element in the navigation, nothing happens. If I right click and open in new tab, I see:
`Could not find file '/dashboard-ui/userprofiles.html'.`

Does someone know something?

**Comment by LukePulverenti** [comment]
I would try clearing browsing data.

**Comment by LukePulverenti** [comment]
Did this resolve it? The url has changed, so you either have an old bookmark that is no longer valid, or perhaps some overly aggressive browser caching.

**Comment by godfuture** [comment]
Sorry for being late. I have deleted the container and redownloaded the image. The new container does not have this issue. I really don't know what was the issue. Currently I am checking the logs. Keep you updated if I find something.

**Comment by godfuture** [comment]
My disk array with md raid 5 was very busy due to resync. I guess this may had an influence on access to my bind mount.

So surely not an emby issue.
