### ISSUE TITLE
EmbyReports - Menu overlap

### ISSUE THREAD

**Issue by 42bios** [MediaBrowser/Emby#3571]
Hi, recently, when using the reports, I have a black window or the menu overlaps.
Problem exists with Safari 13.0 (macOS) and Firefox 69.0 (macOS & Windows 10), iOS App
Server: Emby 4.2.1.0 - Windows 10

Does anyone else have this problem?

[![Bild bild05.09.19um20.1270j37.jpg auf abload.de](https://abload.de/img/bild05.09.19um20.1270j37.jpg)](https://abload.de/image.php?img=bild05.09.19um20.1270j37.jpg)

**Comment by LukePulverenti** [comment]
Hi there, Emby Server 4.3 is rolling out. Please try that and let us know how that compares. Thanks.

**Comment by LukePulverenti** [comment]
Hi, this is resolved in Emby Server 4.3.1. Please re-open this ticket if you are still experiencing this. Thanks !

**Comment by 42bios** [comment]
Hi, nope sorry. Problem still exists ...  :/
edit: Already tried reinstalling on another device, same problem.

<a href="https://abload.de/img/bildschirmfoto2020-027kkje.png"><img src="https://abload.de/img/bildschirmfoto2020-027kkje.png" /></a>
