### ISSUE TITLE
Global default language setting

### ISSUE THREAD

**Issue by Influencer** [MediaBrowser/Emby#3573]
Currently we have an option on each client that we can set the preferred audio language. What I would like to see, instead of setting up the preferred language on each device, having a global default setting on the server that could be overridden by a client setting.

**Comment by LukePulverenti** [comment]
Hi, do you actually need to set the language on each device? The reason we do it this way is so that default behavior can just inherit the device language setting, at least on devices where we can get that information.

Do you have cases where you need the Emby app language to be different from the language of other apps on the same device?

**Comment by Influencer** [comment]
I've noticed on Apple TV, Roku and Fire sticks having to set the language in Emby because it will play in a different language if not set.

So to make sure I have this right, the device language setting is used if it can be and if the language isn't set in Emby.

For the devices I listed, does the setting get inherited from the device? If so maybe I need to go back and do more testing or check settings to make sure

**Comment by LukePulverenti** [comment]
Ok so you're talking about audio/subtitle language? I thought this was about the user interface text language.

Have you set the audio and subtitle preferences for your emby user? If you do this, it will apply to all apps.

**Comment by Influencer** [comment]
I think this can be closed then. I didn't pay enough attention that where I was setting it was user settings. Every time I've had this issue come up, its not unreasonable to believe it was for a different user account (wife, kids, etc). 

Although all of the users that would access my Emby server would use English, if its easily set as a user setting I see no reason it should be a global setting as well.

Edit: Yes, it is for audio/subtitle language

**Comment by LukePulverenti** [comment]
Great, thanks !
