### ISSUE TITLE
Network connection

### ISSUE THREAD

**Issue by legends-killer** [MediaBrowser/Emby#3574]
My server have two Network cards, but I use one of them to connect the internt by PPPoE(in a independant way and connect with one ISP and it is automaticly given a local IP 192.168.1.10), and another is connected to my switch(my switch connected with my all conputers, routers, phones, in another network segement(192.168.3.0) for a failover of WAN but not LAN which means I can still connect with my server by my ).After that, the emby server can only identify in the first network segement(192.168.1.0). In that way, I can't connect with emby by the switch. How can I solve it?

**Comment by LukePulverenti** [comment]
Hi there, can you please describe your issue? Thanks !

**Comment by legends-killer** [comment]
> Hi there, can you please describe your issue? Thanks !

I've refined my issue, thanks for help.

**Comment by LukePulverenti** [comment]
Where exactly is the problem manifesting itself? For example, is there a problem when using Emby apps?

**Comment by legends-killer** [comment]
> Where exactly is the problem manifesting itself? For example, is there a problem when using Emby apps?

it means that I can't connect to my emby server in my local network, but I can only do in public network in a lower speed

**Comment by legends-killer** [comment]
How can I make my emby server work in two different network segement?
