### ISSUE TITLE
Chromecast pause

### ISSUE THREAD

**Issue by v-six** [MediaBrowser/Emby#3575]
Hi there,

Emby have a recurrent issue with Chromecast. Everytime I pause a movie, and then click back on play, the playback just freeze many seconds later (it's random, but generally less than 5 minutes).

I have to restart the playback (stop and play) to continue.

**Comment by LukePulverenti** [comment]
Hi there, are you still running into this?

**Comment by LukePulverenti** [comment]
Closing, but please feel free to re-open if you'd like to continue looking into this. Thanks.
