### ISSUE TITLE
[Feature Req.] Browse by media, not by library

### ISSUE THREAD

**Issue by varac** [MediaBrowser/Emby#3577]
I have different root folders where I organize my movies (for various reasons). 
Currently, emby browses per library, but sometimes I can't recall where I put a movie.

It would be awesome if i.e. all movies across all (movie) libraries could be browsed, not matter which library holds them.
Would this be possible ? Imo this would be a huge usability improvement.

**Comment by LukePulverenti** [comment]
Why not just setup one library and add multiple folders to the library?

**Comment by varac** [comment]
@LukePulverenti That's one solution, you're right. But emby allows different libraries and I guess many users make use of it, and I'd still prefer to have a way of having a unified way of browsing all libraries together.

**Comment by LukePulverenti** [comment]
Ok thanks for the explanation. This will be handled by #1143 - Support smart views/playlists
