### ISSUE TITLE
Misunderstanding help of LAN Network settings

### ISSUE THREAD

**Issue by alxping** [MediaBrowser/Emby#3578]
According to how an empty value of the `LanNetworks` is computed (source ref below), the corresponding help field is partially correct:
> If left blank, only the server's subnet is considered to be on the local network.

Source: https://github.com/MediaBrowser/Emby/blob/dffad1c52cbc73336fbbcb91894a0f0220c4c3fb/MediaBrowser.WebDashboard/dashboard-ui/strings/en-US.json#L1797

Basically, all well-known IPv4 private subnets, according to: https://github.com/MediaBrowser/Emby/blob/dffad1c52cbc73336fbbcb91894a0f0220c4c3fb/Emby.Server.Implementations/Networking/NetworkManager.cs#L154

Instead, an indication that well-known subnets are also used should be displayed, for example:
> If left blank, only the server's subnet and common private IP subnets (eg. 10.0.0.0/8, 192.168.0.0/24, etc.) are considered to be on the local network.

**Comment by LukePulverenti** [comment]
Hi, I'll make this change for Emby Server 4.4. Thanks for the feedback.
