### ISSUE TITLE
Loading icon on Samsung tv

### ISSUE THREAD

**Issue by matthewtroup1983** [MediaBrowser/Emby#3581]
Samsung smart tv when you fast forward the loading/spinning icon does not go away... only way to clear it is to fast forward to where you want to be then back out of the movie/show and then resume play.

**Comment by LukePulverenti** [comment]
Hi, what version of the app?

**Comment by matthewtroup1983** [comment]
I am not sure its the latest from the samsung app store I do not see anywhere to see "app info for it"

**Comment by LukePulverenti** [comment]
If it's a recent version it will be displayed at the bottom of the app settings screen. If it's not displayed there, then that means you have an older build and this issue should be resolved as soon as we're able to get an update released.

**Comment by matthewtroup1983** [comment]
The app seems older then the Roku version I do not see a number but its the lastest I could pull down from the app store

**Comment by LukePulverenti** [comment]
What year is the TV?

**Comment by matthewtroup1983** [comment]
The model is UN55NU6900 I just purchased it last year at this time.

**Comment by LukePulverenti** [comment]
Ok, so then it will be resolved with the next store update. You can also use the sideload build if interested:
https://emby.media/community/index.php?/topic/74969-samsung-tizen-smarttv-2015-present-beta-app-install-from-usb/

**Comment by LukePulverenti** [comment]
Hi, did you try the USB version?

**Comment by LukePulverenti** [comment]
Closing, but please feel free to re-open with the requested information. Thanks !
