### ISSUE TITLE
Cannot show collections in librarys

### ISSUE THREAD

**Issue by cirnosaiko** [MediaBrowser/Emby#3582]
4.3.0.26
If not sort by title, Cannot show collections in librarys

**Comment by LukePulverenti** [comment]
Hi there, what do you mean exactly? Can you please discuss an example? Thanks.

**Comment by cirnosaiko** [comment]
For example, there is a library "movie", and two movies in it "forzen II" and "forzen I". A collection "american movie"  is created with these two movie. 
in the last version, i can see "american movie" instead of two movies in library "movie". but in 4.3.0.26, i can see is collection in "movie library" only when sort by title. 
Is this an necessary feature? i think it's not convenient

**Comment by LukePulverenti** [comment]
How are you trying to sort?

**Comment by cirnosaiko** [comment]
> How are you trying to sort?

![微信截图_20191126085518](https://user-images.githubusercontent.com/24890662/69590666-26dedf80-102b-11ea-9ca7-614eb8299e21.png)

**Comment by LukePulverenti** [comment]
That's by Title though. What were you trying to sort with before and it wasn't showing the collection?

**Comment by cirnosaiko** [comment]
> That's by Title though. What were you trying to sort with before and it wasn't showing the collection?

I trying to sort shows and movies.  and sort by date added, date release ...(any other except sort by title)

**Comment by LukePulverenti** [comment]
Please see my explanation here:
https://emby.media/community/index.php?/topic/80036-group-the-media-in-collections-is-no-longer-possible-since-the-update-43/?p=815931

Thanks.

**Comment by LukePulverenti** [comment]
This will be more flexible in Emby Server 4.6. Thanks.
