### ISSUE TITLE
URL only movie.nfo not working

### ISSUE THREAD

**Issue by nomandera** [MediaBrowser/Emby#3583]
It would appear that URL only movie.nfo are not working again.

As usual I attach a zip folder of a fake movie tested to very obviously not work on both Version 4.3.0.25 and Version 4.3.0.30. Simply unpack to a movie share and it will be incorrectly detected as `Gestrandet 2007` and not `Busby 2019`.

Is there any way we can find a way to add URL only movie.nfo and tvshow.nfo into the testing schedule as they are constantly prone to breakage. Happy to help even if it is just reporting here .

[Busby.2019.zip](https://github.com/MediaBrowser/Emby/files/3904475/Busby.2019.zip)

**Comment by nomandera** [comment]
Can I assist in any way because this is a pretty fundamental feature to be remain broken.

It is also super time consuming to recover all interim bad matches due to https://github.com/MediaBrowser/Emby/issues/3321

**Comment by nomandera** [comment]
Reconfirmed issue still persists with new release [4.3.1.0](https://github.com/MediaBrowser/Emby.Releases/releases/tag/4.3.1.0)

**Comment by LukePulverenti** [comment]
It's only having a problem with 8 digit imdb id's, which is a pretty new thing. I've pushed an update to the nfo plugin to resolve it. Thanks.

**Comment by nomandera** [comment]
Nice catch I never even thought to check that. Thanks for the fix, very much appreciated.

**Comment by nomandera** [comment]
Confirmed fix in:

```
Nfo Metadata
18/12/2019, 07:47:52
Version 1.0.24
```
