### ISSUE TITLE
display incorrect info about media path

### ISSUE THREAD

**Issue by monokoo** [MediaBrowser/Emby#3585]
### **The second dir path should be "\\\\192.168.2.198\ptshare2\movies",
 but actually it shows me "\\ptshare2\\\\192.168.2.198\movies" in my client.**

![a3a72b1132321f5f175b648530c1631.jpg](https://i.loli.net/2019/12/05/ZlatXcCj3iORQkg.jpg)

![Snipaste_2019-12-05_13-56-13.png](https://i.loli.net/2019/12/05/NlTDpAeGJ3tYscC.png)

**Comment by LukePulverenti** [comment]
Hi, sorry, what are you asking exactly? Can you please describe this more? Thanks.

**Comment by LukePulverenti** [comment]
Ah yes I can see why that would happen. Thanks.

**Comment by monokoo** [comment]
Hope this can help you.

**Comment by monokoo** [comment]
Just want to know which version does this issue will be fixed, thanks.

**Comment by LukePulverenti** [comment]
This will be resolved in Emby Server 4.4. Thanks.
