### ISSUE TITLE
Problem with some subtitles when playback

### ISSUE THREAD

**Issue by monokoo** [MediaBrowser/Emby#3586]
hi, i have  a problem with the lastest version(the newest server, emby for koid and IOS client). When I choose the Chinese subtitle, it doesn't work any way. But it works in PotPlayer-x64 on Windows 10.
 
I find the issue for such ass subtitles is because the format line in Events section: 
**Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding**
 ![Snipaste_2019-12-05_14-17-43.png](https://i.loli.net/2019/12/05/cBVs19ZYPe3gMF2.png)

After update to: 
**Format: Layer, Start, End, Style, Actor, MarginL, MarginR, MarginV, Effect, Text**   , the subtitle works for all clients.
Hope this could help you fix the issue.
Thanks.

**Comment by LukePulverenti** [comment]
Hi, are you still running into this with Emby Server 4.3.1 and the latest version of the iOS app?

**Comment by monokoo** [comment]
> Hi, are you still running into this with Emby Server 4.3.1 and the latest version of the iOS app?

Yes, i use the latest version of ios app and Server with 4.4.0.7 beta version. It still couldnot work well.

**Comment by LukePulverenti** [comment]
Can you provide sample subtitles for testing? thanks.

**Comment by monokoo** [comment]
> Can you provide sample subtitles for testing? thanks.

I upload the subtitle into google drive. You can download it now with [this link](https://drive.google.com/open?id=1oLk1jq02QB6msPUGpTeT19tl6TUdC3VV)
Thanks.

**Comment by benquan** [comment]
I am also having trouble with subtitles. For the moment the problem seems specific with Chromecast as when I play on my browser I can see the subtitles perfectly. Also its not all cases. Some movies show subtitles in chromecast and some don't.

Also when I play to chromecast let's say in starting in the middle of the movie, the subtitles will show up once and only once. A single line that is in sync with what they are saying, but after that it does not show any more.

**Comment by LukePulverenti** [comment]
> > Can you provide sample subtitles for testing? thanks.
> 
> I upload the subtitle into google drive. You can download it now with [this link](https://drive.google.com/open?id=1oLk1jq02QB6msPUGpTeT19tl6TUdC3VV)
> Thanks.

@monokoo The subtitle rendering library that we're using is having trouble with this file. Specifically it is complaining that these subtitles don't have a PlayResX and PlayRexY value defined. For what it's worth I can't get these subtitles to display in Vlc either.

**Comment by LukePulverenti** [comment]
> I am also having trouble with subtitles. For the moment the problem seems specific with Chromecast as when I play on my browser I can see the subtitles perfectly. Also its not all cases. Some movies show subtitles in chromecast and some don't.
> 
> Also when I play to chromecast let's say in starting in the middle of the movie, the subtitles will show up once and only once. A single line that is in sync with what they are saying, but after that it does not show any more.

@benquan can we please look at an example? Thanks.

**Comment by LukePulverenti** [comment]
> > > Can you provide sample subtitles for testing? thanks.
> > 
> > 
> > I upload the subtitle into google drive. You can download it now with [this link](https://drive.google.com/open?id=1oLk1jq02QB6msPUGpTeT19tl6TUdC3VV)
> > Thanks.
> 
> @monokoo The subtitle rendering library that we're using is having trouble with this file. Specifically it is complaining that these subtitles don't have a PlayResX and PlayRexY value defined. For what it's worth I can't get these subtitles to display in Vlc either.

A workaround for this was added in Emby Server 4.5. Please re-open if you're still having an issue and we'll dive into specifics. Thanks.
