### ISSUE TITLE
Problem with deleting downloaded subtitle files

### ISSUE THREAD

**Issue by ghost** [MediaBrowser/Emby#3587]
Hi,

I tried to delete downloaded subtitle file from webui but I desn't works.
I can see that delete action is calling to an endpoint but subtitle file is still in movie folder.
I have to delete it manual but after some time it is downloaded again (dont know why :D) 

Pls take a look on this bug, I can't find nothing in logs about deleting subtitles so can't help providing log.

I am using the newest Emby stable as docker container.

Thanks

**Comment by LukePulverenti** [comment]
Check your server log, you'll probably see an error message about access denied. That means the server is being denied access to delete the file from your folder.

**Comment by ghost** [comment]
There is nothing in log, I enabled debug mode.
Emby server has write/read access to movie folder

**Comment by LukePulverenti** [comment]
Please attach the emby server log. thanks.

**Comment by ghost** [comment]
https://pastebin.com/raw/NBeEpkqp log

**Comment by LukePulverenti** [comment]
It deleted but then it redownloaded based on your automatic subtitle download settings.

**Comment by ghost** [comment]
Are you sure it is deleted? I can see that file doesnt disapear in the folder after I click delete.
Show me the line in log that prove file is deleted please.
How to disable automatic subtitle dowload to check if it is deleted for sure?

Feature suggestion:
So if user delete subtitles manualy that means he does't want it because some reason so emby should download it again second after user delete it

**Comment by ghost** [comment]
@LukePulverenti 
Are you gonna answer?

**Comment by LukePulverenti** [comment]
The answer to this is that it deleted, then re-downloaded, You can confirm this in the log. We should improve this to prevent the re-download right after deleting. Thanks.
