### ISSUE TITLE
How to distinguish between Traditional Chinese and Simplified Chinese subtitles

### ISSUE THREAD

**Issue by InoriHimea** [MediaBrowser/Emby#3588]
Both chi and zh-TW / zh-HK / zh-CN are now just displayed in Chinese Simplified(AAS)

**Comment by monokoo** [comment]
Yes, i have the same issue. Hope this can be a feature for emby.

**Comment by LukePulverenti** [comment]
Hi, are these external subtitles? If so, how are the files named?

**Comment by monokoo** [comment]
> Hi, are these external subtitles? If so, how are the files named?

Hi, i think we can show Chinese Simplified, such as when the file name of subtitles has chs or zh-cn.

**Comment by LukePulverenti** [comment]
This will be resolved in Emby Server 4.4. Thanks.
