### ISSUE TITLE
Unrestricted access to emby library on FreeNAS from VLC android

### ISSUE THREAD

**Issue by dicecat** [MediaBrowser/Emby#3589]
## Environment:  

FreeNAS 11.2U7  
emby plugin 4.2.1.0  
Android 10  
VLC 3.2.3  

## Bug description

After a fresh install of emby plugin in jail on FreeNAS, "Emby - emby" from "Local Network" in VLC showed up, which included only "Playlists" for now.  

Then I did the following:  

1. follow the emby setup wizard and setup user 'emby' and a library;  
2. create a library which contained only media files within the jail.  

Now I can access contents in the library directly from VLC, without any login credentials.  

Then I tried to:  

1. create a user 'newuser' and make sure that "Local network sign in mode" is set to "Require a password on the local network";  
2. delete the default user 'emby';  
3. restart emby jail.  

After the restart, "Emby - emby" from "Local Network" in VLC still persists, and contents in libraries are still accessible without login credentials.  

I am a novice in *nix system, but I wonder if this is a bug.  
Or could someone give me some advice on this?

**Comment by LukePulverenti** [comment]
Hi, disable the dlna server or uninstall the dlna plugin if you don't want this.

**Comment by dicecat** [comment]
> Hi, disable the dlna server or uninstall the dlna plugin if you don't want this.

Thank you for the quick reply. Problem solved.
