### ISSUE TITLE
Split video files breaks multi-version

### ISSUE THREAD

**Issue by tobbenb** [MediaBrowser/Emby#3590]
After I started to have both 1080p and 4K versions of movies, I have started to correct the file naming of all movies and moving the same movie into one folder. Before it was in separate folders for 3D, 1080p and 4K.
This all works great unless there is a multi disc rip in the folder. As soon as there is part# or any of the other split video naming, the multi version display is not working, resulting in two movies in the list. The multi disc version now only have one file recognized (disc1) and disc2 is missing.
If I move the multi disc version to it's own folder (Movie name (year) 3D), Emby correctly identifies both discs. But of course it still shows as two movies in the list.

I have tried different naming, but no matter what I try, the result is two separate movies and the multi disc version missing the second disc.
I have attached the logs from the server. The movie is The Hobbit An unexpected journey (Extended version and 3D).
[emby log](https://github.com/MediaBrowser/Emby/files/4000562/emby.log)

**Comment by LukePulverenti** [comment]
Hi, can you provide the folder name as well as the names of the files inside the folder? Thanks.

**Comment by tobbenb** [comment]
I don't remember what the folder name was when I tested, but I think it was named `The Hobbit An Unexpected Journey (2012)`
That's how it is named now and I just tested again and it's still the same situation.

**Comment by LukePulverenti** [comment]
What are the file names?

**Comment by tobbenb** [comment]
I have tried these:
The Hobbit An Unexpected Journey (2012) - 3D pt1.mkv
The Hobbit An Unexpected Journey (2012) - part1 - 3D.mkv
The Hobbit An Unexpected Journey (2012) - 3D.part1.mkv
The Hobbit An Unexpected Journey (2012)-3D.part1.mkv
The Hobbit An Unexpected Journey (2012).3D.part1.mkv
The Hobbit An Unexpected Journey (2012).part1.3D.mkv
The Hobbit An Unexpected Journey (2012) - 3D.mvc-pt1.mkv
The Hobbit An Unexpected Journey (2012) 3D pt1.mkv

Also substituted pt# with disk, disc, dvd and cd.

Now:
The Hobbit An Unexpected Journey (2012) - 1080p.mkv
The Hobbit An Unexpected Journey (2012) - 3D pt1.mkv
The Hobbit An Unexpected Journey (2012) - 3D pt2.mkv

As soon as the multi part naming is added, multi version brakes.
You can try this yourself by creating a movie folder, adding 3 files and name them according to your Movie naming scheme.
MovieName (year) - 1080p.mkv
MovieName (year) - 4k.part1.mkv
MovieName (year) - 4k.part2.mkv

**Comment by tobbenb** [comment]
Updated to 4.4.1.0 and tried again as I saw in the changelog something about multi version, but it's still the same issue.

**Comment by tobbenb** [comment]
Over a year since the last reply. Anything happening?

**Comment by LukePulverenti** [comment]
This will be resolved in the 4.8 beta channel in 4.8.0.6+. Thanks.
