### ISSUE TITLE
Chromecast doesn't show pictures (videos an music are working)

### ISSUE THREAD

**Issue by Kejszijo** [MediaBrowser/Emby#3592]
Hi,

I can cast my Audio and my Video, only Photos won't show on Google ChromeCast ultra.
![IMG_20200113_214402](https://user-images.githubusercontent.com/13425330/72291987-cfcfb100-3650-11ea-9639-7257e66703da.jpg)
 
Emby version: 4.3.1.0

**Comment by MCTyler** [comment]
Isn't this more a ChromeCast/Device Issue?

**Comment by Kejszijo** [comment]
No. It's a brand new device. And with other media server (e.g. Plex) the picture show up.  With Jellyfin the problem same as Emby.
(https://github.com/jellyfin/jellyfin/issues/1796)

**Comment by LukePulverenti** [comment]
Hi there, I've pushed an update to resolve this. Simply restart the app you're casting from and try again. Thanks for reporting.
