### ISSUE TITLE
Suspicious fragments found by PVS-Studio Static Analyzer

### ISSUE THREAD

**Issue by ekaterinanikiforova** [MediaBrowser/Emby#3593]
Hello, 
I found some problems in your code using the PVS-Studio static code analyzer, I described the issues in the article: "Checking Emby with PVS-Studio". Not all of the analyzer's warnings have been considered in it, so I suggest that you check the project yourself. Perhaps, some of the warnings that have not been described in the article will seem more interesting to you than the ones that I found :)
To work with the analyzer you will need a key, please, use the following one:
Name: Emby
Key: HGSG-5K94-1NFG-TZGB
License Type: Team9 License up to 9 developers
License Valid Thru: Feb 15, 2020

**Comment by LukePulverenti** [comment]
Hi there, thanks for providing this information. We took at look and our newer closed source code base doesn't produce any of the reported issues. Thanks !
