### ISSUE TITLE
PHP Post - API - Set Password

### ISSUE THREAD

**Issue by SilvorMike** [MediaBrowser/Emby#3595]
As per here: https://emby.media/community/index.php?/topic/81448-emby-api-in-php/?hl=php

PHP cURL Post to URL: /Users/{userid}/Password?api_key=Key

Fails - with the error: Object reference not set to an instance of an object.

> Full log error:
> 2020-01-26 18:48:47.662 Info HttpServer: HTTP POST http://emby.domain.c...06d253/Password. UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
> 2020-01-26 18:48:47.664 Error HttpServer: Error processing request
>     *** Error Report ***
>     Version: 4.3.1.0
>     Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
>     Operating system: Unix 4.4.0.0
>     64-Bit OS: True
>     64-Bit Process: True
>     User Interactive: True
>     Runtime: file:///opt/emby-server/system/System.Private.CoreLib.dll
>     Processor count: 8
>     Program data path: /var/lib/emby
>     Application directory: /opt/emby-server/system
>     System.NullReferenceException: System.NullReferenceException: Object reference not set to an instance of an object.
>      at MediaBrowser.Api.BaseApiService.AssertCanUpdateUser(IAuthorizationContext authContext, IUserManager userManager, Int64 userId, Boolean restrictUserPreferences)
>      at MediaBrowser.Api.UserService.PostAsync(UpdateUserPassword request)
>      at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
>      at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
>      at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
>     Source: MediaBrowser.Api
>     TargetSite: Void AssertCanUpdateUser(MediaBrowser.Controller.Net.IAuthorizationContext, MediaBrowser.Controller.Library.IUserManager, Int64, Boolean)
>     
> 2020-01-26 18:48:47.664 Info HttpServer: HTTP Response 500 to 194.35.233.16. Time: 3ms. http://emby.domain.c...06d253/Password

**Comment by ceptonit** [comment]
Yes this endpoint only seems to work with the user authentication method.
Would be nice to make it work with the API key authentication method.

**Comment by LukePulverenti** [comment]
This will be resolved in Emby Server 4.5. Thanks,.
