### ISSUE TITLE
Emby Community Forum Accounts not activated

### ISSUE THREAD

**Issue by frk1** [MediaBrowser/Emby#3596]
Hello!

I tried registering in your community forum to use Emby Connect etc.

The problem: Accounts created in your forum do not get activated anymore. Instead after creating an account you get redirect to a "YOU DO NOT HAVE PERMISSION" page and can't do anything anymore. You can't browse the forums, you can't use Emby connect, you can't even log out; you have to clear all site data manually.

I tried two times with different mails, both the same result.

E-Mail used to create my account is the same as this github account:

hazefrk@gmail.com

Greets

**Comment by frk1** [comment]
Of course I did check spam folder in gmail before opening this thread.

**Comment by abobader** [comment]
Hi,
Early today I fix your account.
Regards,
