### ISSUE TITLE
AC3 5.0 breaks playback on Chromecast

### ISSUE THREAD

**Issue by krismaz** [MediaBrowser/Emby#3597]
When casting to a Chromecast 2, videos with AC3  5.0 channel audio do not play.

Instead of starting playback, the screen remains black, no video, no audio.
Other files using identical video setting but, different audio settings (AC3 5.1) works

I suspect transcoding is necessary but not performed.

#3388 would be a nice work-around for this issue

[ac3 5.0.log](https://github.com/MediaBrowser/Emby/files/4168221/ac3.5.0.log)

**Comment by LukePulverenti** [comment]
@krismaz are you still able to reproduce this?

**Comment by krismaz** [comment]
I stopped using emby so I am unfortunately no longer able to help with this
issue
