### ISSUE TITLE
Can't scan the single library, always got 204 status.

### ISSUE THREAD

**Issue by Babesun** [MediaBrowser/Emby#3598]
I'm using Emby v4.3.1.0 in Synology DS918+ with DSM 6.2.

Steps:
1. Enter the Dashboard - Library
2. Choose one of my libraries, such as the TVShow named "剧集" in Chinese
3. I clicked the More button then the Scan button, but nothing happed. No process, no loading, no warning.
4. I try to click the button in the top of this page named "扫描所有媒体库" (It may be "Scan all the libraries" in English), and it works fine, I got my libraries updated. And I can also see the process bar growing in the homepage of Dashboard.

Why scanning one library doesn't working?

**Comment by LukePulverenti** [comment]
Hi there, please go over an example and see how to report a problem:
https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/
Thanks.

**Comment by Babesun** [comment]
> Hi there, please go over an example and see how to report a problem:
> https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/
> Thanks.

I updated my issue description, please check it, thanks.

**Comment by LukePulverenti** [comment]
Hi, are you still running into this with Emby Server 4.4.3?

**Comment by Babesun** [comment]
> Hi, are you still running into this with Emby Server 4.4.3?

It doesn't appear again in the latest version, thanks.
