### ISSUE TITLE
Question: What is the best way to conveniently resume a video?

### ISSUE THREAD

**Issue by hacker-h** [MediaBrowser/Emby#3600]
Similar to netflix or plex it would be nice to have a stable url for each video that can be bookmarked to easily resume watching at a later time.
However my emby instance always redirects me to the following URL:
```
http://emby:8096/web/index.html#!/videoosd/videoosd.html
```
The video is still playable, but when the page is refreshed the player turns empty.

Is there any option to mitigate this behaviour besides always navigating to the start page?

**Comment by MCTyler** [comment]
This Video is from a IPTV/Share Site Provider?

**Comment by hacker-h** [comment]
Those videos are arbitrary series/movies that I mounted into an emby container (docker container):
The mount target paths are  `/mnt/share1` and `/mnt/share2`

**Comment by LukePulverenti** [comment]
That's a good idea for the future, but currently you'd have to go back to the homescreen and resume from there.
