### ISSUE TITLE
Question: How to add a recommendation section? 

### ISSUE THREAD

**Issue by alexfdezsauco** [MediaBrowser/Emby#3601]
I just wondering how to add a custom recommendation section? 

I'm already implemented my own approach for movie suggestions. 

**Post** 
- http://likewastoldtome.blogspot.com/2019/12/how-to-avoid-copying-movies-that-you.html

**Sources** 
- https://github.com/alexfdezsauco/SmartInbox.Emby
- https://github.com/alexfdezsauco/SmartInbox.Emby.Server

and I want to add a custom entries in the **_Suggestions_** page like this one:

- Based on your historical play back action (SmartEmby)
- Delete recommendations from the recently added movies because you probably will never play (SmartEmby) 

Is there an API available for that? Any sample code?

**Comment by nomandera** [comment]
Absolutely fascinating blogpost that deserves some attention in my humble opinion.

**Comment by LukePulverenti** [comment]
Hi, you currently can't, but this will be covered in the future by #1143. Thanks.

**Comment by alexfdezsauco** [comment]
@LukePulverenti Not sure if you understood me correctly.

There is a [Suggestions] tab. It shows Emby suggestions.

It displays [Continue Watching] , [Latest Movies], and also [Because you watched some movie]

I implemented my own deep learning recommendation approach, and also implement the a plugin for Emby to process all watched movies and save to a file the recommendations. The question is: could be possible add programmatically a suggestion section for instance [Because your historical playback action] to use my algorithm?

**Comment by chefbennyj1** [comment]
Did you end up using ml.net like you mentioned in your blog post? I have been interested in implementing something like this for a very long time.

 You could try to create  a channel class in your plugin which would create a separate library. However if you add items from the movies library to your new channel, they will duplicate in the API.

What about attempting to override the suggestion endpoint in the API with your own data, which would serialize the baseItems you want to add. 😳 Is that a possible? 
I've never tried  overriding an api endpoint before...

**Comment by alexfdezsauco** [comment]
@chefbennyj1 No. I implemented it with DL4J and it runs as a service no hosted by emby. The emby plugin just use such service. As far as I know, Emby plugins must be net standard as target platform so there is also a limitation to use ML.NET hosted in Emby (I think).

So, I build a docker image https://hub.docker.com/r/alexfdezsauco/smart-inbox-emby for the deep learning part  of the solution.

Will try to create a channel just as you suggested me. 

Thanks.

**Comment by alexfdezsauco** [comment]
@chefbennyj1 The channel idea works for me thanks.

 https://twitter.com/alexfdezsauco/status/1353846636116631552
