### ISSUE TITLE
Bug selection User on the plugins configuration web page

### ISSUE THREAD

**Issue by JohnCytron** [MediaBrowser/Emby#3604]
Hi

I'm actually on Emby 4.3.1.0 (Docked: `emby/embyserver:latest`).
I can't select any user on a plugins configuration web page:
![](https://i.imgur.com/f0fH4LQ.jpg)
I try it on Firefox or Chrome (in private mode to be sure about the cache), same problem.

But it's working perfectly with the android app:
![](https://i.imgur.com/3qcluwo.jpg)

But some plugins can't be configured with the android app (telegram for example).

Are you aware about this issues ?

**Comment by LukePulverenti** [comment]
HI, is the server behind a reverse proxy?

**Comment by JohnCytron** [comment]
Yes behind cloudflare. You're right, it working if I turn off the proxy.

**Comment by LukePulverenti** [comment]
It's due to your CSP. The plugins need to be updated to remove inline javascript, and then it will work. But for immediate resolution you'd have to update your CSP to allow it.

**Comment by LukePulverenti** [comment]
If you mention it here:
https://emby.media/community/index.php?/topic/62193-content-security-policy-csp-development
The author will have some tips for you.

**Comment by LukePulverenti** [comment]
Closing, but please let us know if you still need help with this. Thanks.
