### ISSUE TITLE
broken download link

### ISSUE THREAD

**Issue by ghost** [MediaBrowser/Emby#3607]
I would like to download Emby server for my Shield TV, so I went to:

https://emby.media/download.html

which points me to:

https://emby.media/server-android.html

which points me to:

https://github.com/MediaBrowser/Emby/releases/download/4.0.1.0/com.emby.embyserver_4.0.1.0.apk

which returns a 404 not found error on github.

**Comment by LukePulverenti** [comment]
Hi, the link is loaded dynamically via javascript to fetch the latest version, so that means either you have javascript disabled, or the requests to api.github.com are failing.

**Comment by ghost** [comment]
oh.. hmm interesting... javascript is enabled but WebGL and WASM are disabled in my browser. I am not blocking api.github.com, it seems to resolve ok from here.

I'll do some more digging, thanks.

**Comment by LukePulverenti** [comment]
If you don't want to deal with that right now, you can also get the apk from here:
https://github.com/MediaBrowser/Emby.Releases/releases/latest
