### ISSUE TITLE
AppleTV “Up Next” bar

### ISSUE THREAD

**Issue by mpearon** [MediaBrowser/Emby#3610]
In previous builds, the AppleTV client displayed an “up next” bar when the media was within a set percentage of completion (or maybe with a set number of seconds).
The bar displayed a countdown, an End Time of the next episode, and an option to continue or abort the progression to the next episode.
Are there plans to bring this back?

**Comment by LukePulverenti** [comment]
Hi, sorry for the delay. I'll pass this onto our Apple TV developer. Thanks.

**Comment by LukePulverenti** [comment]
When the next release is available this will be there when the native player option is enabled. It's currently not implemented yet when the mpv player option is selected.

**Comment by mpearon** [comment]
Luke,
     Thank you for the response!  After I opened this issue, I realized that I probably should have done so on the forum!  Sorry...I’ve been in GitHub mode for a while now. :)
