### ISSUE TITLE
Emby is selecting movies to update state on based on wrong ids

### ISSUE THREAD

**Issue by niclaslindstedt** [MediaBrowser/Emby#3611]
When I watch a movie, mark it as favourite or as played, I get a bunch of other movies marked as such as well.

These movies' metadata look like this:

![bild](https://user-images.githubusercontent.com/615926/77996615-3ac68500-732e-11ea-822d-0a4b5970d9d4.png)

I.e. their TMDb id is set to 0 (and they have no collection id), but their IMDb id is correct.

Updating the TMDb to a valid id will make this problem go away -- favourites work as expected, etc.

So it seems Emby is selecting movies to update status on based on TMDb id? It basically makes watch state / favourites / played state unusable on my system because I have a lot of movies that seems to be not fully scraped eventhough they have been identified as the correct movies.

**Comment by LukePulverenti** [comment]
Yes that's how we handle user data. The question is how did the 0 get there. Do you have nfo files?

**Comment by niclaslindstedt** [comment]
This is a pre-scraped directory and all movies had .nfo files beside them before Emby started scraping. Could that be the problem? They are kodi nfo files.

**Comment by LukePulverenti** [comment]
Can you provide an example nfo? thanks.

**Comment by niclaslindstedt** [comment]
```
  <tmdbid>0</tmdbid>
```

This was found in an nfo of a movie that was incorrectly scraped.

Maybe my media program sets this to 0 if it doesn't use tmdb for that movie.

**Comment by LukePulverenti** [comment]
OK i'll add a safeguard to the nfo plugin to guard against this.

**Comment by niclaslindstedt** [comment]
Could you perhaps also add this as a cleaning task when refreshing the library? I'm not sure how to fix this without removing the entire library and adding it back again.

**Comment by niclaslindstedt** [comment]
I replaced all the tmdbids with nothing, and now all the nfos are back to 0 for about 50% of the movies.

**Comment by niclaslindstedt** [comment]
"Refresh metadata" on movies with tmdb id 0 also does not remove the 0. It just accepts it.

Where is the "database" located so I can manually fix this?

**Comment by niclaslindstedt** [comment]
1. Remove the tmdbid = 0 from a movie's nfo file
2. Click Refresh metadata on that movie
3. The 0 is back in the nfo file.

**Comment by niclaslindstedt** [comment]
1. Change the tmdbid = 0 to a valid tmdbid in a movie's nfo file
2. Check metadata in Emby -- still 0 (cached?)
3. Refresh metadata on that movie
4. The valid tmdbid stays in the nfo file

So I just need to write a tool that finds out the valid tmdb id for all my movies

**Comment by LukePulverenti** [comment]
We've added safeguards to ignore 0 id values. Thanks for reporting.
