### ISSUE TITLE
ArchLinux Repos Incorrect Version

### ISSUE THREAD

**Issue by WaffleThief123** [MediaBrowser/Emby#3612]
ArchLinux Repos contain Incorrect Version (v4.4.0.40-1)
Emby Prompts to be updated to newest version (v4.4.1.0)

![image](https://user-images.githubusercontent.com/26676249/78469559-2a6c2c80-76d7-11ea-9a5a-d3e4a1052f4c.png)

I have updated repos, changed repos to different ones, with still same result.

**Comment by LukePulverenti** [comment]
Hi, apologies, 4.4.1 was released but is not yet in the Arch Linux repository.

It's coming very soon though. During 4.5 development we will improve this so that you don't see a notification until it's actually in the repository.

**Comment by WaffleThief123** [comment]
Awesome thank you! Am looking forward to this!
