### ISSUE TITLE
[Enhancement] Clarify networks that will be considered on local network

### ISSUE THREAD

**Issue by nomandera** [MediaBrowser/Emby#3614]
As of 4.4.1.0 the LAN network wording within the GUI says:

`LAN networks:
Comma separated list of IP addresses or IP/netmask entries for networks that will be considered on local network when enforcing bandwidth restrictions. If set, all other IP addresses will be considered to be on the external network and will be subject to the external bandwidth restrictions. If left blank, only the server's subnet and common private IP subnets (10.0.0.0/8, 192.168.0.0/24, etc.) are considered to be on the local network.
`

Either expand this list to show the complete list or add to wiki and link to there. Currently the only way to know which IPs Emby consider local is to dig about in the code https://github.com/MediaBrowser/Emby/blob/dffad1c52cbc73336fbbcb91894a0f0220c4c3fb/Emby.Server.Implementations/Networking/NetworkManager.cs#L154 or know what IANA local is and how to google it.

related discussion https://github.com/MediaBrowser/Emby/issues/3578

**Comment by LukePulverenti** [comment]
This will be in emby Server 4.5. Thanks.
