### ISSUE TITLE
Live TV - HDHomerun Channelimport not working

### ISSUE THREAD

**Issue by cherup01** [MediaBrowser/Emby#3615]
When using HDHomerun for LiveTV with an installed plugin on an Enigma2 receiver called HDHomerunProxy channelimport is not working correctly as in many channels special characters are imported (see screenshot) - so mapping fpr XMLTV is not working for these channels. 
As an example:

Sky Atlantic HD
Sky Cinema Special HD

While other channels are working fine, e.g.

TNT Comedy HD

**Comment by LukePulverenti** [comment]
We'll help you in your community topic:
https://emby.media/community/index.php?/topic/85053-livetv-hdhomerun-xmltv-mapping-problem/#entry871157
Thanks.
