### ISSUE TITLE
Emby just ignores dramas with "Sample" in its title

### ISSUE THREAD

**Issue by outloudvi** [MediaBrowser/Emby#3616]
One TV show in my library has the name "[Shomin Sample](https://thetvdb.com/series/shomin-sample)", and the typical filename of this will be like `Shomin Sample S01E01.mp4`. However, Emby will ignore it because [its filename contains " sample "](https://github.com/MediaBrowser/Emby/blob/dffad1c52cbc73336fbbcb91894a0f0220c4c3fb/Emby.Server.Implementations/Library/CoreResolutionIgnoreRule.cs#L164).

I think this "ignore sample" feature worths to be stated clearly in the naming documentation.

**Comment by LukePulverenti** [comment]
HI, yes we need to provide a little more configuration and control around this.
