### ISSUE TITLE
Who wrote that doc

### ISSUE THREAD

**Issue by Behinder** [MediaBrowser/Emby#3618]
Section for User authentication is poorly written without clarifications, not to mention it does not work because getting /Users/Public brings me 0 records. I'm trying this with Jellyfin so I assume it is obvious tactic against Jellyfin users,pity but it should be clearly stated in the docs.

**Comment by softworkz** [comment]
You are complaining that the Emby documentation does not apply to Jellyfin?

It is already clearly stated in the docs: It says "Emby" everywhere and "Jellyfin" nowhere.

**Comment by LukePulverenti** [comment]
It will return 0 users if the server admin has configured their users to be hidden from login screens. You can manage this via user edit permissions. It's not a bug or related to any other server software. I'll update the doc.
