### ISSUE TITLE
Add "group versions" for people

### ISSUE THREAD

**Issue by cheshuai123** [MediaBrowser/Emby#3619]
I have one person with different added dates. One of them is added by metadata scraper and the other one is added by Manual input recognized by myself. 
it's totally one person but splitted in two version.
![image](https://user-images.githubusercontent.com/22605709/82433530-25670f00-9ac4-11ea-87c4-2bc44f126a38.png)

**Comment by LukePulverenti** [comment]
Hi, in the latest version of Emby Server it should no longer be possible to even create this situation.
