### ISSUE TITLE
Deleting upper-level folder [possible very serious bug]

### ISSUE THREAD

**Issue by artiomn** [MediaBrowser/Emby#3623]
I had a broken movie in the "Films" media library.
Rela path of the film was like: "/tank0/user_data/videos/Films/Документальные/Film Name", but emby works inside Docker container.
To fix it, I have renamed it and removed the previous entity in the Emby interface.
But then all my documentary films were deleted (73 entries, directory "/tank0/user_data/videos/Films/Документальные").

I have never had such a situation before, but I rarely use deletion.
Emby version was 4.5.0.10 beta.

**Comment by LukePulverenti** [comment]
Hi, can you try updating to a newer beta and see how that compares? Thanks.

**Comment by artiomn** [comment]
Hello.

I have updated already. But checking is difficult: I use beta version (because it's not alpha) for the real home video collection, and I beware to lost my videos.

**Comment by LukePulverenti** [comment]
This should no longer be an issue. Thanks.
