### ISSUE TITLE
LibraryManager doesn't send ItemUpdated/ItemRemoved events when removing an item from collection

### ISSUE THREAD

**Issue by firecore** [MediaBrowser/Emby#3627]
**Description:**
The LibraryManager doesn't send ItemUpdated or ItemRemoved events when an item is removed from a collection.
If plugin registers handlers for ILibraryManager events, then ItemUpdated is called when items are added to a collection, but not when items are removed.

Without notification from ILibraryManager, it is not possible to register collections' changes in the [InfuseSync](https://github.com/firecore/InfuseSync) plugin and sync them to the Infuse client.

**Environment:**
macOS 10.15.5, Emby 4.4.3.0
 
**Steps:**
1. Registers a handler for ILibraryManager.ItemUpdated event. 
2. Add a collection to the server.
3. Add an item to the collection.
4. Note that ItemUpdated handler is called.
5. Remove an item from the collection.
4. Note that ItemUpdated handler is not called.

**Expected:**
ILibraryManager.ItemUpdated is called when the contents of the collection change.

**Server logs:**
[embyserver.txt](https://github.com/MediaBrowser/Emby/files/5006807/embyserver.txt)

**Comment by LukePulverenti** [comment]
HI, it does now in Emby Server 4.6 now that collections are metadata of an item.
