### ISSUE TITLE
No Chromecast icon in iPhone app

### ISSUE THREAD

**Issue by JimBobSquarePants** [MediaBrowser/Emby#3628]
I’m using Emby for iPhone 1.9.7 with iOS 13.5.1 and there is no option to use Chromecast. 

![6328DDDE-90FE-4329-B603-50444C2CFC86](https://user-images.githubusercontent.com/385879/89738121-08602d80-da6e-11ea-8c69-ae1a26b7a677.png)

By my understanding, according to the documentation there should be an icon on the top right of the screen.

https://support.emby.media/support/solutions/articles/44001161600-chromecast

I’m serving the media from my downloads if that makes a difference.

**Comment by LukePulverenti** [comment]
Hi, we don't currently support casting downloaded media, but it's planned for the future. Thanks.

**Comment by JimBobSquarePants** [comment]
Thanks for the prompt reply. Looking forward to seeing it. Should I leave this issue open for tracking the feature or do you want me to close it?

**Comment by LukePulverenti** [comment]
There is a ticket for it, #3425 . Thanks.
