### ISSUE TITLE
Play audio novels. Error occurs when the number of MP3 files exceeds 400.

### ISSUE THREAD

**Issue by 3038922** [MediaBrowser/Emby#3630]
emby -v : 4.4.3.0
os -v: ubuntu 20.04
nginx -v :1.18.0
Google Chrome 85.0.4183.83

Too many files in the same directory can cause this problem

![image](https://user-images.githubusercontent.com/33926386/91965097-9617fb80-ed42-11ea-8add-4f6b1bd4633d.png)
```
Uncaught (in promise) TypeError: Cannot read property 'ServerId' of undefined
```

**Comment by LukePulverenti** [comment]
Hi there, are you still running into this with Emby Server 4.5.2?

**Comment by 3038922** [comment]
> Hi there, are you still running into this with Emby Server 4.5.2?

emby -v 4.5.1.0

**Comment by LukePulverenti** [comment]
Hi, have you tried this with Emby Server 4.5.4?

**Comment by 3038922** [comment]
There is no problem with the PC side.
emby -v 4.5.4
thank you
