### ISSUE TITLE
Add New Content type for E-learning 

### ISSUE THREAD

**Issue by ghost** [MediaBrowser/Emby#3631]
Please add a new content type to support E-learning media's in Emby media player

Although TV series section replicate certain functionality, Currently have to add each course under each library.

By adding this section Emby can be used as Easy to access Personal learning media player

This is the regular pattern of course content
https://gist.github.com/Kah01/6d9e198815b031aa55266fd12661767c

Thank you

**Comment by LukePulverenti** [comment]
Hi, couldn't you just do a home videos library?

**Comment by ghost** [comment]
Hey @LukePulverenti,  just tried this category for my folder can say it does a very decent job thanks a lot :)  

Implementing such [feature](https://forums.plex.tv/t/text-document-reader/6037/18)  (Render pdf in the browser) will be a nice to have functionality alongside e-learning folders 

Anyway thanks again
