### ISSUE TITLE
"Delete" is the default/highlighted context menu option

### ISSUE THREAD

**Issue by allywilson** [MediaBrowser/Emby#3632]
When clicking the triple-dot context menu button in the web interface on an episode or movie, the very first option that is highlighted by the cursor is "Delete" (when the full screen allows it).

Although accidentally clicking "Delete" does cause another prompt, I don't feel this is the safest place for default when clicking something accidentally (you still get people who click twice out of habit, or frustration).

Not really an issue, more a feature request to move any option for removal of data away from being the default.

Pic uploaded of context/triple-dot button highlighted and the menu that appears when you click it showing the Delete option highlighted.

![UI defaults to delete](https://user-images.githubusercontent.com/470127/92307844-22b7f900-ef91-11ea-80e2-e1e5fc94eb89.png)

Using Firefox 80 on Linux Mint 20, Emby is 4.4.3.0

**Comment by LukePulverenti** [comment]
Hi, this will be resolved in Emby Server 4.5. Thanks for reporting.
