### ISSUE TITLE
I forgot the password of my emby administrator account

### ISSUE THREAD

**Issue by ugokin** [MediaBrowser/Emby#3633]
Hello, I forgot the password of my emby administrator account. How to reset it? I built it on Ubuntu

**Comment by ugokin** [comment]
can you help  me

**Comment by LukePulverenti** [comment]
Hi there, have you tried the forgot password function on the login screen?

**Comment by LukePulverenti** [comment]
Closing, but please feel free to re-open if you'd like to continue the discussion. Thanks.
