### ISSUE TITLE
Errors in Email notification plugin

### ISSUE THREAD

**Issue by yuriw** [MediaBrowser/Emby#3634]
It's on Ubuntu 20.04 LXC

While testing email notification, I am seeing errors bu email actually gets sent (!)
No actual notifications sent from emby tho.

![image](https://user-images.githubusercontent.com/3876474/92953226-3393bf00-f416-11ea-9f5e-480e3417a96b.png)

```
2020-09-11 10:03:19.264 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 4.4.3.0
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Unix 5.4.34.1
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///opt/emby-server/system/System.Private.CoreLib.dll
	System.Environment.Version: 3.1.2
	Processor count: 12
	Program data path: /var/lib/emby
	Application directory: /opt/emby-server/system
	System.NullReferenceException: System.NullReferenceException: Object reference not set to an instance of an object.
	   at MediaBrowser.Plugins.SmtpNotifications.Notifier.<>c__DisplayClass8_0.<GetOptions>b__0(SMTPOptions i)
	   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
	   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
	   at MediaBrowser.Plugins.SmtpNotifications.Notifier.GetOptions(User user)
	   at MediaBrowser.Plugins.SmtpNotifications.Notifier.SendNotification(UserNotification request, CancellationToken cancellationToken)
	Source: MediaBrowser.Plugins.SmtpNotifications
	TargetSite: Boolean <GetOptions>b__0(MediaBrowser.Plugins.SmtpNotifications.Configuration.SMTPOptions)
	
2020-09-11 10:03:19.264 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 4.4.3.0
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Unix 5.4.34.1
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///opt/emby-server/system/System.Private.CoreLib.dll
	System.Environment.Version: 3.1.2
	Processor count: 12
	Program data path: /var/lib/emby
	Application directory: /opt/emby-server/system
	System.NullReferenceException: System.NullReferenceException: Object reference not set to an instance of an object.
	   at MediaBrowser.Plugins.SmtpNotifications.Notifier.<>c__DisplayClass8_0.<GetOptions>b__0(SMTPOptions i)
	   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
	   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
	   at MediaBrowser.Plugins.SmtpNotifications.Notifier.GetOptions(User user)
	   at MediaBrowser.Plugins.SmtpNotifications.Notifier.SendNotification(UserNotification request, CancellationToken cancellationToken)
	Source: MediaBrowser.Plugins.SmtpNotifications
	TargetSite: Boolean <GetOptions>b__0(MediaBrowser.Plugins.SmtpNotifications.Configuration.SMTPOptions)
```

**Comment by yuriw** [comment]
any input ?

**Comment by yuriw** [comment]
Here is the configuration file that throws an error above:

cat /var/lib/emby/plugins/configurations/MediaBrowser.Plugins.SmtpNotifications.xml 
<?xml version="1.0"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Options>
    <SMTPOptions>
      <Enabled>true</Enabled>
      <EmailFrom>yuri.weinstein@gmail.com</EmailFrom>
      <EmailTo>yuri.weinstein+emby@gmail.com</EmailTo>
      <Server> smtp.gmail.com</Server>
      <Port>587</Port>
      <UseCredentials>true</UseCredentials>
      <Username>yuri.weinstein@gmail.com</Username>
      <Password>YelizavetA</Password>
      <MediaBrowserUserId>0af9a67d1a0f49619b8d66ce81b709f6</MediaBrowserUserId>
      <SSL>true</SSL>
    </SMTPOptions>
    <SMTPOptions>
      <Enabled>true</Enabled>
      <EmailFrom>yuri.weinstein@gmail.com</EmailFrom>
      <EmailTo>yuri.weinstein+emby@gmail.com</EmailTo>
      <Server>smtp.gmail.com</Server>
      <Port>587</Port>
      <UseCredentials>true</UseCredentials>
      <Username>yuri.weinstein@gmail.com</Username>
      <Password>xdatvmbearhfcmjz</Password>
      <MediaBrowserUserId>376bbece91114796ab33c57ca892bb0e</MediaBrowserUserId>
      <SSL>true</SSL>
    </SMTPOptions>
    <SMTPOptions>
      <Enabled>true</Enabled>
      <EmailFrom>yuri.weinstein@gmail.com</EmailFrom>
      <EmailTo>yuri.weinstein@gmail.com</EmailTo>
      <Server>smtp.gmail.com</Server>
      <Port>587</Port>
      <UseCredentials>true</UseCredentials>
      <Username>yuri.weinstein@gmail.com</Username>
      <Password>xdatvmbearhfcmjz</Password>
      <MediaBrowserUserId>a63bb43d670c4d5492ddbc3e28e0c8bf</MediaBrowserUserId>
      <SSL>true</SSL>
    </SMTPOptions>
  </Options>
</PluginConfiguration>





And this file on a different emby server works fine:

cat /var/lib/emby/plugins/configurations/MediaBrowser.Plugins.SmtpNotifications.xml
<?xml version="1.0"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Options>
    <SMTPOptions>
      <Enabled>true</Enabled>
      <EmailFrom>yuri.weinstein@gmail.com</EmailFrom>
      <EmailTo>yuri.weinstein+emby@gmail.com</EmailTo>
      <Server> smtp.gmail.com</Server>
      <Port>587</Port>
      <UseCredentials>true</UseCredentials>
      <Username>yuri.weinstein@gmail.com</Username>
      <Password>YelizavetA</Password>
      <MediaBrowserUserId>0af9a67d1a0f49619b8d66ce81b709f6</MediaBrowserUserId>
      <SSL>true</SSL>
    </SMTPOptions>
    <SMTPOptions>
      <Enabled>true</Enabled>
      <EmailFrom>yuri.weinstein@gmail.com</EmailFrom>
      <EmailTo>yuri.weinstein+emby@gmail.com</EmailTo>
      <Server>smtp.gmail.com</Server>
      <Port>587</Port>
      <UseCredentials>true</UseCredentials>
      <Username>yuri.weinstein@gmail.com</Username>
      <Password>xdatvmbearhfcmjz</Password>
      <MediaBrowserUserId>376bbece91114796ab33c57ca892bb0e</MediaBrowserUserId>
      <SSL>true</SSL>
    </SMTPOptions>
  </Options>
</PluginConfiguration>

**Comment by LukePulverenti** [comment]
We're discussing this in the community so let's continue there. Going forward if you need to open an issue for the plugin, please do so here:
https://github.com/MediaBrowser/email-notifications
Thanks.
