### ISSUE TITLE
XSS in dashboard message feature

### ISSUE THREAD

**Issue by Roughsket** [MediaBrowser/Emby#3636]
Was able to load google via the message feature in dashboard on the admin account 
Input 

```<meta http-equiv="refresh" content="0; URL='http://google.com'" />```

Client executes code

![IMG_20200918_035351-1](https://user-images.githubusercontent.com/71478738/93550745-fecabf00-f963-11ea-90d3-dc6e013eb312.jpg)

Client used webOS emby theater 1.0.24

**Comment by LukePulverenti** [comment]
Hi, it's resolved for the next release, thanks.

**Comment by Cave-Johnson** [comment]
Should this be public until next release is out?
