### ISSUE TITLE
Roku glitches trying to play a file beyond 24 hours

### ISSUE THREAD

**Issue by jakabo27** [MediaBrowser/Emby#3637]
I have a supercut movie file that is 52 hours long, and it plays flawlessly on the Roku all the way until around 23 hours 20 minutes, which is when I suspect it's trying to preload beyond 24 hours into the movie.  First the audio stops and the movie keeps playing, if I pause and play it the audio starts back but is offset by however long it took me to press pause and play.  Then if you try to fast forward or rewind anywhere beyond that time it can't load the movie and just gets stuck "loading".  The play time remaining/watched also glitches at this same time. I'm guessing it's an issue with how the time is referenced beyond 23:59.

**Comment by LukePulverenti** [comment]
Hi, have you tried this with Emby Server 4.5.4?

**Comment by LukePulverenti** [comment]
Closing, but please feel free to re-open with the requested information. Thanks.
