### ISSUE TITLE
Has Synology x86 architecture support been dropped?

### ISSUE THREAD

**Issue by noodle-** [MediaBrowser/Emby#3638]
I'm trying to update my Emby installation from version 4.4.3.0 to version 4.5.X on my DS214play. 

The usual way of updating, through the Synology Package Center doesn't seem to work as there's no update available. Checking the Synology tab on https://emby.media/nas-server.html does not show any mention of x86.

Am I blind and missing something obvious or did I just run out of luck? :(

**Comment by noodle-** [comment]
This might be related 😢 

https://emby.media/community/index.php?/topic/78267-is-running-emby-server-on-x86-still-possible/

> ... we no longer have an x86 Linux package, sorry.
> No [it's not possible] because there is no .net core runtime for x86.

EDIT: more info, from https://emby.media/emby-server-45-released.html
> New Install & Update Process for Synology
>
>Going forward, there is a new procedure for installing and updating Emby Server on Synology. Please follow the instructions on >the download page of our website. This will bring the following benefits:
>
>    Built with .NET Core (no more mono runtime)

**Comment by LukePulverenti** [comment]
Hi, not yet. Please see here: https://emby.media/community/index.php?/topic/40411-xpenology-users-read-me/&do=findComment&comment=930510

**Comment by noodle-** [comment]
Sweeeeeet, thanks for the information (and all the amazing work you guys are doing)!

Any other threads I should keep an eye on?

**Comment by LukePulverenti** [comment]
https://emby.media/community/index.php?/topic/90690-emby-server-synology_4520_x86_64spk-cannot-be-installed/

**Comment by noodle-** [comment]
Ah splendid!
