### ISSUE TITLE
Problem occurs starting EmbyServer on Synology X64.

### ISSUE THREAD

**Issue by xslingcn** [MediaBrowser/Emby#3639]
Today earlier,I updated my EmbyServer on Synology using SSH from 4.4.3.0 to 4.5.0.50 and then 4.6.0.1,they both can't get started.
When I start it on Synology web interface,the status turns to running and then go to stopped,I tried to start it using  
> sudo synopkg start EmbyServer
>  sudo synopkg status EmbyServer

and it turns out:

> EmbyServer package status is stopped but unit is active, it is possible that package encounters an error after it was started successfully
Status: [310]

Here is the log(embyserver-xxxxxxxxxxx.txt):
https://pastebin.com/kmcCe6Cn

**Comment by xslingcn** [comment]
Problem solved by 

> sudo chmod 777 -R /volume1/Emby

But it might not be that safe this way(It's fine for me ;D).

**Comment by LukePulverenti** [comment]
Hi , just to confirm, you didn't try a beta between 4.4.3 and now, right?

**Comment by xslingcn** [comment]
> Hi , just to confirm, you didn't try a beta between 4.4.3 and now, right?

Actually I'm using 4.6.0.1 beta now,but I didn't try any other beta version before that,it's just 4.4.3.0->4.5.0.50(Problem Occurs)->4.6.0.1(Problem still but chmod 777 works for me).

**Comment by LukePulverenti** [comment]
Did you first install 4.4.3 within the last couple weeks, or prior to that?

**Comment by xslingcn** [comment]
> Did you first install 4.4.3 within the last couple weeks, or prior to that?

It was 4.4.3.

**Comment by LukePulverenti** [comment]
Did you first install it within the last couple weeks, or prior to that?

**Comment by xslingcn** [comment]
> Did you first install it within the last couple weeks, or prior to that?

About one month ago.
