### ISSUE TITLE
 May I choose not to read metadata from the media folder?

### ISSUE THREAD

**Issue by gitnoobbbb** [MediaBrowser/Emby#3640]
Hi, I am a PT player and have some problems.
Before using emby scraping, i have unchecked the Save media image to the media folder and unenable .nfo in the settings.
The directory always contains .nfo files and .jpg files with the same name as the video file when they were downloaded.The downloaded video files need to be continuously seeded and cannot be changed. 
Its structure is often as follows:

> 

      -->%DirectoryName%
           -->%VideoName%.mkv
           -->%VideoName%.jpg or cover.jpg
           -->%VideoName%.nfo
Emby will automatically recognize the `%VideoName%.jpg` or `cover.jpg` as a cover picture. 
If I want to select other picture as the cover, the picture in the media folder will be deleted and I will not be able to seed.

Could you please add an option to let me decide whether to read metadata from the source folder or let me decide which folder to read metadata,and it will solve the problem...

Thanks..

**Comment by gitnoobbbb** [comment]
Solved by establishing hard links to the video files.And add emby source folder to the links files.

**Comment by LukePulverenti** [comment]
Hi, sorry, to answer the question, no, there's currently no way to prevent reading of local files, but it's something i've been meaning to add.

**Comment by gitnoobbbb** [comment]
> Hi, sorry, to answer the question, no, there's currently no way to prevent reading of local files, but it's something i've been meaning to add.

ohhhh,we have replied almost at the same time.

Solved,thank you...
