### ISSUE TITLE
[Feature Request] Allow items with tags in addition to maximum parental rating

### ISSUE THREAD

**Issue by mikestir** [MediaBrowser/Emby#3643]
I think it would be useful to be able to individually allow items rated above the configured parental rating limit.

Use case: We have a "kids" account configured only to allow access to movies rated up to GB-PG, but there are some (but by no means all) 12A rated films that we would allow them to watch.

I could not see any way to achieve this currently other than by tagging every single allowed movie including those rated U and PG. It feels like this feature could be added quite easily by adding an "also allow items with these tags" to the restrict items with tags feature.

**Comment by nomandera** [comment]
Does the existing custom rating feature not fulfill this?

`A custom rating is used for parental control evaluations but is not displayed. The parental rating field is still displayed.`

**Comment by LukePulverenti** [comment]
This will be in Emby Server 4.8. Thanks.
