### ISSUE TITLE
Wrong media played

### ISSUE THREAD

**Issue by thomasazar** [MediaBrowser/Emby#3644]
This morning, my kiddo attempted to watch a movie called _Truck Tunes Favorites_ that we have available on our local Emby server. Instead of playing the selected video, Emby served a clip from the movie _Monster Trucks_, which we don't have at all on the server. (Indeed, I had never even heard of it. [Some searching found the clip in question available on IMDb.](https://www.imdb.com/video/vi1605417241))

I have no idea how Emby chose to play the clip from a completely different video. After the clip stopped, and Emby returned to the screen for the movie, hitting Play again actually played the correct video. I searched the logs for anything referencing imdb.com but found nothing.

What additional information could I provide to help with this bug?

**Comment by LukePulverenti** [comment]
Hi, sounds like you've enabled Cinema Intros in server settings. Please try turning that off.

**Comment by thomasazar** [comment]
Thanks for the tip. I have turned off Cinema Intros for "Internet trailers: Include trailers from older movies". It was the only box checked. Cinema Intros for Movies and Episodes were both already unchecked. Hopefully that does it, because it just happened again.

I see that under "Internet trailers", there is green text saying that these features require Emby Premiere, to which I do not currently subscribe.

**Comment by thomasazar** [comment]
Alright, mystery solved: the video clip in question is played when the "Trailer" button, located next to the "Play" button, is pushed. It's likely that the kiddo hit "Trailer" by accident, and Emby couldn't find a match, so it picked a random clip that sorta matched.

Thanks for pointing me in the right direction.
