### ISSUE TITLE
Web UI recurent display bug 

### ISSUE THREAD

**Issue by Ho2x** [MediaBrowser/Emby#3646]
Hello,

For 1 year +/- I have regularly this display bug
![IMG_20201028_160002](https://user-images.githubusercontent.com/23018181/97454806-70206900-1937-11eb-8c03-48414d804851.jpg)
![IMG_20201028_160018](https://user-images.githubusercontent.com/23018181/97454820-73b3f000-1937-11eb-9087-cb330b3dec62.jpg).
Do you have an idea ?
When I go through:
https: //my-domain.tld: 8096 no problem.
When I go through:
Https: //my-domain.tld I have the problem.
So if I add the port. No problem.

**Comment by Ho2x** [comment]
It seems to me that before the update, or you went to close source, I never had the problem.

**Comment by LukePulverenti** [comment]
Hi, what exactly is the issue?

**Comment by Ho2x** [comment]
As shown in the photo, all the menus are shift up.

**Comment by Ho2x** [comment]
I specify, that I made a proxypass in apache (ispconfig)

**Comment by LukePulverenti** [comment]
What do you mean exactly by shift up? You mean the page is scrolled up?

**Comment by Ho2x** [comment]
https://youtu.be/cmG0HctDuLQ

**Comment by LukePulverenti** [comment]
OK so you're saying you can't scroll up to the top? Is that correct? What browser and version is this? Does it happen when not in full screen mode?

**Comment by Ho2x** [comment]
I'm sending you a video that compares the two.

When I am on my normal domain, domaine.tld, the problem appears.
But if I add the port, domain.tld: 8096, I don't have the problem anymore.

**Comment by LukePulverenti** [comment]
Can you please answer the questions that I just asked? Thanks.

**Comment by Ho2x** [comment]
No the problem is not related to full screen. It does it all the time. I put the link to you provisionally.

V4.5.1 
Centos 7 
Apache

**Comment by LukePulverenti** [comment]
What browser and version is this?

**Comment by Ho2x** [comment]
Chrome, but the problem is on all browsers.
I don't think it has to do with that.
If you go via
Xxxx
the problem will be gone.

**Comment by Ho2x** [comment]
OK in fact I think it's linked to ssl. Sorry

**Comment by Ho2x** [comment]
Yes it comes from ssl.
When I use https it doesn't work. But with http it doesn't bug.
I will correct this. Sorry for the inconvenience 😉

**Comment by LukePulverenti** [comment]
Thanks for the feedback.

**Comment by Ho2x** [comment]
Unfortunately, the problem persists.
After an update of emby to the last version the problem disappeared but after some time it comes back.

It's as if the top bar with "Home and Favorites" hides part of the page. I have the same in the admin menu.
It looks like this problem but not sure
https://emby.media/community/index.php?/topic/62404-dashboard-scrollbar-google-chrome-v69/page/2/

**Comment by Ho2x** [comment]
![IMG_20201029_195541](https://user-images.githubusercontent.com/23018181/97619715-d9c87200-1a20-11eb-9a77-124fc94c05d3.jpg)

No bug 

![IMG_20201029_195515](https://user-images.githubusercontent.com/23018181/97619758-e5b43400-1a20-11eb-9a48-2841e7892d33.jpg)

BUG

**Comment by LukePulverenti** [comment]
Are you using a reverse proxy?

**Comment by Ho2x** [comment]
The apache server is on server A and the domain has a ProxyPass configuration to server B which hosts emby.
I have no problem with jellyfin, plex, ombi with the same configuration

Really strange...

**Comment by LukePulverenti** [comment]
I would take a look at your reverse proxy configuration. If anything is altering the output, such as minifying, applying http compression, a CSP, etc, try turning that off. If it's not experienced locally then it's most likely tied to the proxy configuration.

**Comment by Ho2x** [comment]
I just did this

ProxyPass "/" "http://ip-server-B:8096/"
ProxyPassReverse "/" "http://ip-server-B:8096/"

**Comment by LukePulverenti** [comment]
Not sure it will matter, but please let me know how 4.5.3 compares, once you have that. Thanks.

**Comment by LukePulverenti** [comment]
Hi, have you tried this with Emby Server 4.5.4?

**Comment by LukePulverenti** [comment]
I'd be curious to know if the issue still remains for you in Emby Server 4.6. We're happy to continue assisting you with this if you're still having an issue. Thanks.
