### ISSUE TITLE
Last Commit 2 years Ago?

### ISSUE THREAD

**Issue by kferrone** [MediaBrowser/Emby#3647]
https://github.com/MediaBrowser/Emby/commit/1d7c2ab4bfebdae31f89fdaabd3b68782ccf495a

Why so long since last commit? Is this something to do with code going closed source?

**Comment by LukePulverenti** [comment]
Hi, yes exactly, but we have other open source repositories that still get commits.

**Comment by kferrone** [comment]
I see. Thanks
