### ISSUE TITLE
When can emby server support amd cpu?

### ISSUE THREAD

**Issue by skypjsfly** [MediaBrowser/Emby#3648]
When can emby support amd cpu,my new synology is DS1621+.It seems that emby server does not support this new machine. The cpu is amd v1500b.

**Comment by LukePulverenti** [comment]
Hi, did you try our 64-bit package?

**Comment by skypjsfly** [comment]
Yes，I have tried emby-server-synology_4.6.0.4_x86_64.spk  and emby-server-synology_4.5.2.0_x86_64.spk，but neither of them can be installed
![-1b2497de6bf852a](https://user-images.githubusercontent.com/32484309/97786492-ebf40d00-1be6-11eb-8005-fb6e41e4c3c5.png)

**Comment by LukePulverenti** [comment]
What does that say?

**Comment by skypjsfly** [comment]
It says this suite is not supported on the synology nas, or is not compatible with the current DSM version.
My DSM version is 6.23，and my old ds918+ can install it correctly.

**Comment by LukePulverenti** [comment]
Hi, can you try downloading the beta install package again? Thanks.

**Comment by skypjsfly** [comment]
Yeah,it can be installed now,thanks.

**Comment by LukePulverenti** [comment]
Thanks for the feedback.
