### ISSUE TITLE
Video overlay sticks when the episode is changed

### ISSUE THREAD

**Issue by DragonEmbers** [MediaBrowser/Emby#3650]
When watching a multi-episode series the video control overlay gets stuck on once the episode changes and remains until some user interaction is performed (eg change volume, pause+resume, fullscreen toggle).

Emby: 4.5.2.0
Browser: Firefox 82.0.3 (Not repeatable on Edge 44.19041.423.0)
OS: Windows 10 2004

Browser: Firefox-esr (78.4.1esr-1~deb10u1)
OS: Debian 10 (Buster) LXDE

**Comment by LukePulverenti** [comment]
Hi, is the second video playing when this happens?

**Comment by DragonEmbers** [comment]
Yes it is, that element of it seems to continue to work

**Comment by LukePulverenti** [comment]
Ok, please let me know if you're still seeing this with 4.5.3, once you have that. Thanks.

**Comment by DragonEmbers** [comment]
Sorry for the late response, I'm still seeing this issue on 4.5.4.0

**Comment by LukePulverenti** [comment]
Hi, are you seeing this with Emby Server 4.6.3?

**Comment by LukePulverenti** [comment]
Closing, unable to reproduce. But please feel free to re-open with the requested information. Thanks.
