### ISSUE TITLE
Broken link to version info from the Dashboard

### ISSUE THREAD

**Issue by DragonEmbers** [MediaBrowser/Emby#3651]
Clicking the version number in the dashboard takes you to the following (seemingly broken) URI:
http://{host:port}/web/dashboard/releasenotes.html?version={version:4.5.2.0}

![image](https://user-images.githubusercontent.com/6331359/98858658-e43f2e80-2458-11eb-8b35-71ac317f7d81.png)

**Comment by LukePulverenti** [comment]
Hi, that's strange. Can you try another browser for comparison purposes?

**Comment by LukePulverenti** [comment]
@DragonEmbers  ?

**Comment by LukePulverenti** [comment]
Closing, but please feel free to reopen with the requested information. Thanks.

**Comment by softworkz** [comment]
I know this bug. It existed around the time of the initial 4.5.(0) release (or slightly before), but it's fixed at least since the first 4.6.x beta.

**Comment by DragonEmbers** [comment]
Apologies on not replying - I hadn't had a chance to check it out. I was seeing it in Edge (Chromium) as well. If I get a chance, I will check the version softworkz suggested.
