### ISSUE TITLE
emby server only use ipv6 on centos

### ISSUE THREAD

**Issue by raiots** [MediaBrowser/Emby#3656]
What ever I do, the emby-server just only use ipv6 but not ipv4.
CentOS7 with BBR
latest emby-server version

![image](https://user-images.githubusercontent.com/60507671/100688925-57163800-337b-11eb-952c-c62fcd2a6e14.png)

**Comment by LukePulverenti** [comment]
Hi, are you having an issue with this on Emby Server 4.6.3?

**Comment by LukePulverenti** [comment]
HI, closing this ticket, but please feel free to re-open if you're still having an issue. Thanks !
