### ISSUE TITLE
Webhook payload format?

### ISSUE THREAD

**Issue by FoxxMD** [MediaBrowser/Emby#3657]
Hi I'm the author a scrobbling application and would like to integrate Emby's [webhook](https://support.emby.media/support/solutions/articles/44001848859-webhooks) functionality into my application (https://github.com/FoxxMD/multi-scrobbler/issues/12). However I do not currently use Emby and cannot pay for Premiere just to test this feature. And unfortunately the knowledge base is lacking...

Where can I find a reference payload and possible event types for webhook requests? If it helps I've already implemented Plex webhooks in my application...

**Comment by LukePulverenti** [comment]
Hi, the next update to the webhook plugin will have this built-in. You'll be able to click a button and get a popup dialog box to see a sample payload:
![Untitled](https://user-images.githubusercontent.com/3607463/196056965-91f91d7d-1a1b-41fd-8e1d-ff7d90610840.png)

**Comment by LukePulverenti** [comment]
This has been included in the new 4.7.9 server release. Thanks.
