### ISSUE TITLE
Subtitles failed to download - extraction failed

### ISSUE THREAD

**Issue by alejandrofm** [MediaBrowser/Emby#3659]
Hi, I'm having this issue with two movies, maybe are special cases but is filling the Alerts on the Emby Dashboard.
![image](https://user-images.githubusercontent.com/19591174/101990568-5d16ed80-3c86-11eb-8e29-e15ade8df7cb.png)

This is the error log:
[error log.txt](https://github.com/MediaBrowser/Emby/files/5683497/error.log.txt)

Info about Emby version and environment:
```
2020-12-12 00:00:00.012 Info App: Application version: 4.5.3.0
2020-12-12 00:00:00.017 Info App: Emby
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 5.4.72-v7l+ (dom@buildbot) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #1356 SMP Thu Oct 22 13:57:51 BST 2020
	Framework: .NET Core 3.1.7
	OS/Process: arm/arm
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /config
	Application path: /system
```

Tell me please if you need more info.
Thanks!

**Comment by LukePulverenti** [comment]
Hi, the 4.5.4 release resolves this in many cases, but not all. In the Emby Server 4.6 release, this will be fully resolved now. Thanks.
