### ISSUE TITLE
Delete issue? / Question

### ISSUE THREAD

**Issue by mgaulton** [MediaBrowser/Emby#3663]
Love the project, keep up the good work.

I ran into something unexpected that i wanted to ask about.
I was going through mymovie library and noticed that there were duplicates of movies. Turning out to be, CouchPotato seems to be creating multiple copies of movies with different extensions. That's a side issue 👍 
In going through, I verified which file I wanted to keep and attempted to delete the one I didn't want.
This appears to have nuked the entire folder and not the specific file that was referenced in the entry I was deleting.
As it stands, I lost like 50 movies from what i can tell.

Is this expected? Is there a way to detect and resolve a case where there are multiple copies with different extensions in the same folder?
I have a bash script that I can find the files manually, but hoping to use Emby as a frontend for cleanup so I can test the files as I go.

**Comment by Penkethboy** [comment]
I would post this on the emby forums you will get a better and faster response that way

**Comment by LukePulverenti** [comment]
Hi, this is not expected, but I think I recall helping you in the forum at the time of this happening.

Anyway, newer server versions will tell you exactly what file and folder paths are going to be deleted so that you can confirm this before proceeding.
