### ISSUE TITLE
All library content does not show，version embyserver:4.6.0.20

### ISSUE THREAD

**Issue by yyysuo** [MediaBrowser/Emby#3672]
When I upgrade emby server docker version from 4.6.0.10 to 4.6.0.20,All the content in all library does not show, I recreate container using 4.6.0.10，It just works fine.

**Comment by LukePulverenti** [comment]
Hi, try just running a library scan.

**Comment by yyysuo** [comment]
> Hi, try just running a library scan.

Is this necessary?

**Comment by yyysuo** [comment]
> Hi, try just running a library scan.

thanks ,it works!

**Comment by LukePulverenti** [comment]
Thanks for the feedback. Apologies for the disruption.
