### ISSUE TITLE
XSS in Log function.

### ISSUE THREAD

**Issue by EstamelGG** [MediaBrowser/Emby#3673]
For version 4.5.4.0 Windows

Select one log file in Advanced - Logs 

![image](https://user-images.githubusercontent.com/46676047/106120057-dd3ed700-6190-11eb-926b-d25068295263.png)

Edit url as "**/web/index.html?#!/log?name=%3c%69%6d%67%20%73%72%63%3d%31%20%6f%6e%65%72%72%6f%72%3d%61%6c%65%72%74%28%31%29%3e**"  (urlencoded)

![image](https://user-images.githubusercontent.com/46676047/106119978-c5ffe980-6190-11eb-94ef-40978867aef0.png)

Browse the url will trigger an alert dialog. 

Also I designed a javascript and remote load it to stole admin API value from page.

![image](https://user-images.githubusercontent.com/46676047/106119837-9a7cff00-6190-11eb-8090-f6b4a716944e.png)

**Comment by LukePulverenti** [comment]
Resolved for next release, thanks.

**Comment by Cave-Johnson** [comment]
Should this not be public until next release is out?
