### ISSUE TITLE
libgcc_s.so.1 must be installed for pthread_cancel to work

### ISSUE THREAD

**Issue by yyysuo** [MediaBrowser/Emby#3680]
emby version 4.6.0.34

4.6.0.33 has no problem

![image](https://user-images.githubusercontent.com/10081071/112022118-ee8ed900-8b6c-11eb-9f76-a406ec13139f.png)

![image](https://user-images.githubusercontent.com/10081071/112022450-49c0cb80-8b6d-11eb-8a20-dc82d70f1a07.jpeg)

**Comment by yyysuo** [comment]
problem have been soloved,thank you very much.

**Comment by LukePulverenti** [comment]
Thanks for the feedback. Apologies for the disruption.
