### ISSUE TITLE
HDR &Dolby Vision  Dolby Atmos

### ISSUE THREAD

**Issue by nikleechan** [MediaBrowser/Emby#3681]
plex&jellyfin are already supporting hdr &dolby cinema.So Take HDR &Dolby Vision  Dolby Atmos into consideration please!!!

**Comment by LukePulverenti** [comment]
Hi, we support them as well.

**Comment by LukePulverenti** [comment]
If you have a specific issue that needs looking at, we're happy to do that, but Emby already supports playing these formats.
