### ISSUE TITLE
Chromecast pause won't resume

### ISSUE THREAD

**Issue by benquan** [MediaBrowser/Emby#3682]
When you pause a chromecast video, it will not show in chromecast as paused, therefore you cannot resume playback. You can resume it in emby app but not through chromecast (or google home).

**Comment by LukePulverenti** [comment]
Hi, yes we're looking into it. You can follow along here:
https://emby.media/community/index.php?/topic/97856-chromecast-google-home-playpause-problems/
Thanks.
