### ISSUE TITLE
【Bug】Emby for Android TV crashed on HarmonyOS TV

### ISSUE THREAD

**Issue by bluecradle** [MediaBrowser/Emby#3685]
Emby client for Android TV (v1.8.55g）crashed in Huawei HarmonyOS TV when startsup.

It seems that the device might not have interface at URL content://android.media.tv/channel, so IllegalArgumentException was thrown.

I can find the solution for same issue in Kodi.   
"[Android] fixed crash on harmony os TV. xbmc#19133 #19171"
https://github.com/xbmc/xbmc/pull/19171

Please check and fix it,  thank you.

**Comment by LukePulverenti** [comment]
Hi, looks like we're helping you here, so let's pick up there: https://emby.media/community/index.php?/topic/97231-issue-emby-for-android-tv-crashed-on-harmonyos-tv
Thanks.
