### ISSUE TITLE
Mark Played/Watch Progress Not Working

### ISSUE THREAD

**Issue by j3ffpa1n3** [MediaBrowser/Emby#3690]
New update, 4.6.3, does not track progress of watched content or allow marking items as played. Ubuntu server w Fire Stick TV

**Comment by LukePulverenti** [comment]
Hi there, can you please go over an example? Thanks.

**Comment by j3ffpa1n3** [comment]
Sure, so watching a show or movie and pause or exit - Emby does not track progress. I have to start from beginning and fast forward to where I left off. Also, if I try to mark an movie or show as Played from the landing page, the button does not work.  I have rolled back to 4.6.2 and functionality is back.

**Comment by LukePulverenti** [comment]
Hi, please go over a specific example and attach the corresponding Emby Server log from that example. Thanks.

**Comment by LukePulverenti** [comment]
@j3ffpa1n3 ?

**Comment by j3ffpa1n3** [comment]
Luke, apologies for delay. I just updated to 4.6.4 and the watch history is now working. Apologies I do not have logs from 4.6.3. I will close out Issue.

**Comment by LukePulverenti** [comment]
Great, thanks for following up !
