### ISSUE TITLE
Parental Controls do not cover parts of Live TV

### ISSUE THREAD

**Issue by Seanstoppable** [MediaBrowser/Emby#3692]
I am working on putting together a child account.

I've selected "Block items with no or unrecognized rating information:" for Live TV. Which works great for channels.

However, if you go to Live TV, the first tab of "Programs" has a subsection of "Shows", where these shows are not being filtered out if they have no ratings, and you can click through and play content that otherwise I would expect not to be available.

**Comment by LukePulverenti** [comment]
Hi, did you also assign a maximum allowed parental rating for the user?

**Comment by Seanstoppable** [comment]
Yep! Set to TV-Y/Approved/G/E/EC/TV-G.
As far as I can tell it works pretty much everywhere. Shows/movies on other screens. TV channels and guide. It is just the 'Shows' section of live TV which doesn't appear to filter correctly.

**Comment by LukePulverenti** [comment]
What version of the server are you on?

**Comment by Seanstoppable** [comment]
4.6.4.0

**Comment by LukePulverenti** [comment]
Hi, have you updated to Emby Server 4.6.7?

**Comment by LukePulverenti** [comment]
Closing. Resolved in newer versions of Emby Server. Thanks.
