### ISSUE TITLE
The same video in the computer can be normal to dial the phone can not

### ISSUE THREAD

**Issue by waterfall531** [MediaBrowser/Emby#3694]
Same video
with ass subtitles

![pc](https://i.imgur.com/I9HRcbU.png)

![android](https://i.imgur.com/mri7Gib.jpg)

android pixel4 xl + chrome 91.0.4472.120 + android 11

**Comment by LukePulverenti** [comment]
Hi, what is the second screenshot? Is that the web app, or our android app? What version of Emby Server?

**Comment by waterfall531** [comment]
in my android cellphone pixel and in chrome 

android pixel4 xl + chrome 91.0.4472.120 + android 11

**Comment by waterfall531** [comment]
What version of Emby Server?
A: 4.6.4.0

**Comment by LukePulverenti** [comment]
Hi, are you still seeing this with Emby for Android 3.2.31+?

**Comment by waterfall531** [comment]
Maybe
thx for ur helping

**Comment by LukePulverenti** [comment]
Hi, this is resolved now in newer versions of Emby for Android. Please feel free to re-open if you're still having an issue. Thanks.
