### ISSUE TITLE
Bad Emby Server beta on the release page

### ISSUE THREAD

**Issue by wibuf** [MediaBrowser/Emby#3697]
Here on this page: 
https://github.com/MediaBrowser/Emby.Releases/releases/tag/4.7.0.7

The emby-server-deb_4.7.0.7_amd64.deb is only 37KB and breaks the server on install

Image: https://i.imgur.com/vG4GlYy.jpg

**Comment by LukePulverenti** [comment]
Thanks, we're looking into it.

**Comment by LukePulverenti** [comment]
It should be good now. Thanks.
