### ISSUE TITLE
Webhook trigger seems to be in the code, but not usuable/configurable 

### ISSUE THREAD

**Issue by quorn23** [MediaBrowser/Emby#3699]
Looking at the webhooks in line 93 is a function to trigger when an item is added to the database.
[https://github.com/randomevents/Emby.WebHooks/blob/master/Emby.WebHooks/WebHook.cs](https://github.com/randomevents/Emby.WebHooks/blob/master/Emby.WebHooks/WebHook.cs)

This can't be enabled within the webhooks:
[https://imgur.com/a/eilyxHn](https://imgur.com/a/eilyxHn)

In the Slack Plugin for example it's supported. Could this be updated so such triggers are available for the webhooks?
This would help integrate it with Notfifiarr and other.

**Comment by LukePulverenti** [comment]
Hi, that repository is for a community webhooks plugin and is not related to our official one. The discussion area for the community plugin can be found here:
https://emby.media/community/index.php?/topic/53254-webhooks
Thanks.
