### ISSUE TITLE
After Dlna was updated to 1.0.69 it becomes extremly buggy

### ISSUE THREAD

**Issue by j0rg3ns3n** [MediaBrowser/Emby#3700]
After my server has automatically updated Dlna to version 1.0.69, DLNA has stopped working properly. I have an dlna-enabled speaker (Libratone) where I play music to, but after the new update, it is not working. If I click on "play to Libratone" and pick a music folder, and "play all" the speaker plays the first song fine, but there is no player to control it, and if I click on the cast logo and then "remote" it looks like no song is been played, no playlist, only volume works (See attached photo). After the first song it just stops. If I instead play the song first and then click on "play to Libratone" the player shows up, but it only plays 2-6 seconds and stops. This was not a problem before the update

![Unavngivet](https://user-images.githubusercontent.com/89143452/130294988-9b456ca5-dc95-43a6-a71f-335dcb7fc067.png)

**Comment by LukePulverenti** [comment]
Hi, please attach the emby server log from when this happened. thanks.

**Comment by j0rg3ns3n** [comment]
I made a video that explains the problem far better. You can watch it here: https://youtu.be/dzoSCztrZak

Also the log file for that session is here: https://pastebin.com/UjTfHVwF

**Comment by LukePulverenti** [comment]
Hi, are you still having an issue with this with Emby Server 4.7.5?

**Comment by LukePulverenti** [comment]
@j0rg3ns3n  closing, but please feel free to reopen with the requested information. Thanks !
