### ISSUE TITLE
No Secure Integrity Check

### ISSUE THREAD

**Issue by jayant766** [MediaBrowser/Emby#3703]
Steps
Go to a website. 
Go to profile and then click on edit profile.
Now there I can add ant type of file or executable
It may be a ransomware or a virus.

Impact - The system can be compromised as the file is not being scanned by the website itself ( has not integrity check).

**I want to fix this bug. Please let me know what I can do for it.**

![Screenshot (202)](https://user-images.githubusercontent.com/73739820/130799985-7e6de689-e582-45d8-8024-27c33b8bfdc5.png)

**Comment by LukePulverenti** [comment]
HI, since this is about our forum, please post here: https://emby.media/community/index.php?/forum/15-general-discussion/
Thanks.
