### ISSUE TITLE
Web Browser Playback Menu - incorrect menu name

### ISSUE THREAD

**Issue by oregonpillow** [MediaBrowser/Emby#3704]
Surely, this should say 'Audio quality', not 'Internet Quality'.

<img width="1219" alt="Capture" src="https://user-images.githubusercontent.com/53374403/133227090-d0b71a63-5f65-46bd-8a76-4564590df796.PNG">

what is the file that it needs to be corrected in?

**Comment by LukePulverenti** [comment]
Hi, if it only said audio quality then that would imply that it is used for all connections, but it says internet quality to denote the quality when you are away from home. We can look improving the label though. Thanks.
