### ISSUE TITLE
Devices API

### ISSUE THREAD

**Issue by danchamorro** [MediaBrowser/Emby#3706]
I am building a program to delete devices older than x amount days. During testing, when I hit the DELETE devices API it also deletes any API key on the account. Why does this happen. What do devices have to do with API keys?

**Comment by LukePulverenti** [comment]
Hi, it deletes everything associated with that device, including authenticated sessions.  If you manually create an api key in the API keys section of the server dashboard, it won't delete that.

Does that answer your question?

**Comment by danchamorro** [comment]
Thanks.
