### ISSUE TITLE
API for Live TV and EPG Refresh

### ISSUE THREAD

**Issue by dietcoke73** [MediaBrowser/Emby#3708]
I cannot find a route that will allow to refresh the LiveTV channel m3u, is that file being watched for change?  If not can we have an API that forces an EPG update, and a Channel list refresh.

**Comment by LukePulverenti** [comment]
Hi, yes you can use the API to run the refresh guide scheduled task. The m3u file is not watched for changes, so the refresh is purely periodic.

**Comment by LukePulverenti** [comment]
Let us know if you need anything else. Thanks.
