### ISSUE TITLE
DEB armhf build issue

### ISSUE THREAD

**Issue by AVGitUser** [MediaBrowser/Emby#3709]
Hi,

For Emby Server, the debian armhf build looks like it might be broken as it is very small compared to the others (only 36KB)

**Comment by AVGitUser** [comment]
https://github.com/MediaBrowser/Emby.Releases/releases/download/4.7.0.14/emby-server-deb_4.7.0.14_armhf.deb

**Comment by LukePulverenti** [comment]
Hi, should be resolved now. Thanks.
