### ISSUE TITLE
BUG: security ,  https://{emby.url}:8920/Videos/{videoID}/stream.mp4?Static=true , play videos without authentication

### ISSUE THREAD

**Issue by enimath** [MediaBrowser/Emby#3710]
You don't need to authorizate to server to watch Movies.
You just need to know VideoID's and type it as below:
https://{emby.url}:8920/Videos/{videoID}/stream.mp4?Static=true

BR Simon

**Comment by LukePulverenti** [comment]
Hi, this is only true for requests that are detected to be inside the local network. Outside the local network, they will be blocked.

But in the upcoming 4.7 release, all of these will be blocked regardless of where they are requested from.
