### ISSUE TITLE
please comment on reported vulnerabilities

### ISSUE THREAD

**Issue by pedrompcaetano** [MediaBrowser/Emby#3713]
Thanks for your work on the project, I use it daily and went the premium way.

Can we hear from the developers on this?
https://securitylab.github.com/advisories/GHSL-2021-051-emby/

I believe this issue is related: https://github.com/MediaBrowser/Emby/issues/3710

BR

**Comment by LukePulverenti** [comment]
Hi, it's not related to that. Regarding the issues in that report, we'll take a look at them, and get any required changes into the very next beta/stable releases. Thanks.

**Comment by LukePulverenti** [comment]
HI, these are resolved in 4.6.7+. Thanks.
