### ISSUE TITLE
Release 4.7.0.18-Beta 

### ISSUE THREAD

**Issue by MaDTaZ** [MediaBrowser/Emby#3715]
I have a auto updater and it is trying to download the DEB for this release are you planing on releasing this version in DEB

**Comment by LukePulverenti** [comment]
Hi, yes it is coming. You can follow here:
https://emby.media/community/index.php?/topic/103402-problem-compiling-builds/
Thanks.

**Comment by MaDTaZ** [comment]
Ya I dont normally check I figured it would soon be there hehehe
