### ISSUE TITLE
Feature request- Public Playlists

### ISSUE THREAD

**Issue by andyle9191** [MediaBrowser/Emby#3720]
It would be an awesome feature if users(or possibly just admins) could make a playlist public to the other users. 
This could be used as way of recommending content to the other users.
If could possibly show up on the bottom of the home screen and be similar to the "latest content" from the libraries.

**Comment by LukePulverenti** [comment]
HI, all playlists are already public, and in Emby Server 4.8 this will change and they'll be private to the user who created it. There will be a new context menu option to share it with other users:
https://emby.media/community/index.php?/topic/60826-public-and-private-playlists/page/8/#comment-1200131
