### ISSUE TITLE
deleting xmltv and m3u profiles in emby does not purge the old epg data

### ISSUE THREAD

**Issue by merrychrishna** [MediaBrowser/Emby#3721]
os: windows 10
server version:  4.7.0.19 beta
XMLTV: ErsatzTV v0.3.5-alpha

deleting xmltv and m3u profiles in emby does not purge the old epg data. i have not found a fix. i have also tried deleting %userprofile%\AppData\Roaming\Emby-Server\programdata\cache the entire folder but that did not fix it.  the content being played is updated when i add the xmltv and m3u back, but only the old epg data is displayed in the TV guide. as well as refreshing the guide does not update the epg with the new guide data

i believe it is related to the Jellyfin issue here https://github.com/jellyfin/jellyfin/issues/6103 since jellyfin is the same base code as emby.

i checked the xmltv file in ersatzTV and i see the epg has indeed changed in the xml so i dnt think the problem is ersatz.

To Reproduce:
Set up some channels, add tuner using m3u and xmltv guide, save and load xml.
Add/remove available channels (in ErsatzTV for example), change channel contents
Reload xml

expected behaviour:
emby should purge the old epg and be updated with the new xmltv data upon refreshing the guide or at the very least when i delete the xmltv and m3u profiles in emby or by deleting the emby cache folder.

**Comment by LukePulverenti** [comment]
HI, are you still seeing this in the latest versions? I can't reproduce this.

**Comment by merrychrishna** [comment]
No it's not happening anymore but I forget what I did

**Comment by LukePulverenti** [comment]
Great, thanks.
