### ISSUE TITLE
web and mobile app, loading the movie will appear black squares

### ISSUE THREAD

**Issue by 5536086** [MediaBrowser/Emby#3726]
web and mobile app, loading the movie will appear as a black square, requiring a very long wait for the actual, or a complete exit from the app before reloading.
![emby_20220305164238](https://user-images.githubusercontent.com/20472307/156875784-7e2193b5-d5ba-4539-80f6-997b9d958e0d.jpg)

**Comment by LukePulverenti** [comment]
Hi, please attach the emby server log from when this happened. Thanks.

**Comment by 5536086** [comment]
> Hi, please attach the emby server log from when this happened. Thanks.

Thank you for your answer, here is the log file
[embyserver-63782208000.txt](https://github.com/MediaBrowser/Emby/files/8193954/embyserver-63782208000.txt)

**Comment by LukePulverenti** [comment]
HI, are you still seeing this with Emby Server 4.7.5?

**Comment by 5536086** [comment]
> HI, are you still seeing this with Emby Server 4.7.5?

Yes, the problem still exists, when I drag the list very fast, this problem appears, I think this is caused by EMBY's image loading method, because I use plex to test and this problem does not appear

**Comment by LukePulverenti** [comment]
Hi, is this still an issue in newer versions?

**Comment by LukePulverenti** [comment]
Closing, but please feel free to reopen with the requested information. Thanks.
