### ISSUE TITLE
Request support for FFmpeg multithreading

### ISSUE THREAD

**Issue by Greeed-islanl** [MediaBrowser/Emby#3727]
Request support for FFmpeg multithreading

**Comment by qcgzxw** [comment]
It's too slow to generate thumbnail images.
Especially when there are hundreds movies.

**Comment by LukePulverenti** [comment]
There's lots of granular controls coming in Emby Server 4.8, such as the ability to control this for each codec individually:
![Untitled](https://user-images.githubusercontent.com/3607463/231339239-5d9cda00-5f33-487d-bd80-69c7adde82cf.png)
![Untitled1](https://user-images.githubusercontent.com/3607463/231339245-84344b70-d2c5-4ce4-954f-b346a5873e68.png)

If this isn't what you were asking for, then please re-open and provide more specifics. Thanks !
