### ISSUE TITLE
Random error - No playback streams available error when watching Live TV

### ISSUE THREAD

**Issue by tamahau30494** [MediaBrowser/Emby#3729]
I am getting this error when watching TV at random points. I am using an HD HomeRun Prime. Logs are attached.

[ffmpeg-transcode-8dae6c01-53d4-4195-b147-773c8f23e9f7_1.txt](https://github.com/MediaBrowser/Emby/files/8367344/ffmpeg-transcode-8dae6c01-53d4-4195-b147-773c8f23e9f7_1.txt)

[embyserver.txt](https://github.com/MediaBrowser/Emby/files/8367345/embyserver.txt)

**Comment by tamahau30494** [comment]
I am using version 4.6.7.0

**Comment by LukePulverenti** [comment]
Hi, are you still seeing this with Emby Server 4.7.5?

**Comment by tamahau30494** [comment]
Luke,

After some testing, I think this issue has been resolved.

Thanks again for your great work!

**Comment by LukePulverenti** [comment]
Thanks !
