### ISSUE TITLE
AppleTV app not respecting "Display in secondary home screen sections"

### ISSUE THREAD

**Issue by Fabeson** [MediaBrowser/Emby#3730]
As per Emby Support Forum:
https://emby.media/community/index.php?/topic/104472-appletv-app-not-respecting-display-in-secondary-home-screen-sections/#comment-1099792

This was raised in DEC 2021 but it is still present now

**Current setup and versions in use**
- Emby Server (Open Media Vault) version 4.7.0.31 beta (but also occured on latest stable before switching to beta)
- Empy AppleTV app version 1.5.7 (1)
- Apple TVOS 15.4 (19L440) / latest available to me as of 31.03.2022

**Error description / How to reproduce:**
- Under server settings > Home Screen add "Latest Media" to a Home Screen Section of choice
- Scroll down and de-select "Display in secondary home screen sections such as latest media and continue watching" from one of the available Libraries
-> Observe the de-selected library content being shown on the TVOS homescreen "Latest Media" section

This only occurs on AppleTV and **only affects "Latest Media"** - "Continue Watching" is not showing the omitted library (as expected).
When I open Emby in the browser, the de-selected library contents are not displayed in either of the sections (as expected)

**Unsuccesful attempts to fix:**
- Uninstall / Re-Install Emby on Apple TV
- Restarting Emby on Apple TV and Emby Server
- prior this year: Switching to the BETA release cycle

Observation:
The browser immediately respects changes to this setting, including where on the home screen the section should appear (top to bottom arrangements) - It seems, the AppleTV app somehow does not get an update from this settings menu? It takes a full hard reset (ie. cut power) for the app to respect the section arrangement - Maybe a starting point?

**Comment by LukePulverenti** [comment]
OK so it is respecting it, but just not updating immediately when changes are made in other apps, right?

**Comment by Fabeson** [comment]
Hi @LukePulverenti 
Not quite, apart from the delayed top-bottom arrangement, only the "Continue Watching" section is respecting the exclusion.
"Latest Media" still does not respect the excluded library and shows its content on the home screen.

**Comment by LukePulverenti** [comment]
OK yes I can reproduce. It is resolved for the next update to the app. Thanks.

**Comment by Fabeson** [comment]
Great news! Thanks a lot Luke :)
