### ISSUE TITLE
[BUG] Back button not functional after shuffle play (AppleTV)

### ISSUE THREAD

**Issue by Fabeson** [MediaBrowser/Emby#3732]
As per title

How to reproduce:
- Navigate to any media library
- Start watching library content with the Shuffle option
- back out of the media playback using the "BACK" button on either
-- the iOS remote
-- TV remote
-- AppleTV remote
- try to use BACK button again to return to dashboard / previous menu

Expected result:
- Subsequent use of back button navigates to previous menu

Actual result:
- Subsequent use of back button does nothing and navigation is stuck to highlighted Shuffle button

Workaround:
- navigate left or right and then use the BACK button: it will work as expected.

**Comment by LukePulverenti** [comment]
HI, are you still seeing this with the latest update to the Emby Apple TV app?

**Comment by Fabeson** [comment]
Hey @LukePulverenti 

Thanks for checking back, I am on the Beta branch by now and it was fixed there some weeks ago. If they have been merged after that should be good, but currently cannot confirm myself, sorry :/

**Comment by LukePulverenti** [comment]
Great, thanks !

**Comment by Fabeson** [comment]
Hi @LukePulverenti 
Afraid this one has popped back up again - I am still on Beta branch 1.6.2 (1) on AppleTVOS and the issue is even worse now:

- As long as your "pointer" is not highlighting anything on the Top navigation or in actual movie playback, the Back button is not working at all

https://user-images.githubusercontent.com/26404897/193918198-f098e54b-645b-4882-8697-454b730a4129.MOV

- If you navigate into the detail view of a movie, you cannot navigate to "More" if there are more than 6 tiles in that row. The selector just stops on the tile next to "More" and cannot move further right

https://user-images.githubusercontent.com/26404897/193918238-674e77ae-bedc-45e5-b5a6-99ba53a20c64.MOV

- If you actually get into the "More" tile, the "More" menu options are not highlighted and the cursor stays in the background (you can actually move up and down and see it change behind the blurred "More" option overlay. You have to navigate "left" after accessing "More" to be able to choose options like "Delete"

https://user-images.githubusercontent.com/26404897/193918284-7c15233a-1e8c-4405-813e-64985e0a3da3.MOV

-- Only workaround currently seems to navigate in unintuitive directions (or all the way "up") in order to get the back button action to register correctly. It also seems it gets initiated on a offscreen position, but that is just a hunch.

Could it be, that AppleTVOS updates somehow affect the navigation behaviour inside Emby? Otherwise I cannot explain, as I am running the same version it was fixed in. AppleTVOS by now is on 16.0

I have attached some video examples to better explain the encountered issues. Just as a note, while I am using the TV remote in this example, the behaviour is exactly the same on the original Apple Remote and the remote app on the iPhone.

Thanks again for the great support and kind regards!

**Comment by LukePulverenti** [comment]
Hi, thanks we're looking into these.

**Comment by Fabeson** [comment]
Hey @LukePulverenti 

Thanks, the navigation issues are mostly fixed in 1.6.4!

One last thing remaining, is that you cannot navigate to "More" if the movie has more than 6 navigation tiles (see above comment for details). 

Both back button and the navigation in the "More" menu are fixed now, great job :)

**Comment by LukePulverenti** [comment]
Hi, the number of buttons is resolved for the next update to the Emby Apple TV app. Thanks.

**Comment by Fabeson** [comment]
Can confirm it works in 1.6.6 (3)
You guys are amazing, thanks a bunch Luke!
