### ISSUE TITLE
Request: Episode title TBA update on rescan.

### ISSUE THREAD

**Issue by Akirainblack** [MediaBrowser/Emby#3733]
Just as a suggestion. When Emby does a metadata refresh could it also attempt to update any episodes/series with TBA in the title of the episode?
e.g. Moon Knight S01:E01 TBA
is refreshed on a library rescan any time one is performed until it changes to.
Moon Knight S01:E01 The Goldfish Problem
At which point it stops being refreshed.
A plugin exists for Jellyfin to do this:
https://github.com/SenorSmartyPants/jellyfin-plugin-refreshsparse

**Comment by LukePulverenti** [comment]
HI, this will be in Emby Server 4.8:
https://emby.media/community/index.php?/topic/117953-48030-refresh-option-for-tba-episodes/
