### ISSUE TITLE
iOS and macOS 4k video direct play error

### ISSUE THREAD

**Issue by RockJohnson503** [MediaBrowser/Emby#3734]
direct play fails when playing bluray 4k video on ios and macOS, but WEBDL 4k video can be played directly, also bluray 4k video can be played directly on android

**Comment by LukePulverenti** [comment]
Hi there, what exactly do you mean by fails? Can you please go over an example? Thanks.

**Comment by LukePulverenti** [comment]
HI, newer versions should perform better. If you're still having an issue, please feel free to reopen this ticket with the requested information. Thanks !
