### ISSUE TITLE
ffmpeg on beta 4.7.0.35 crashing

### ISSUE THREAD

**Issue by SBachman** [MediaBrowser/Emby#3735]
ffmpeg is unable to read the transcode graphs and crashing on loop. This happens across chrome on desktop and the android app, direct play and transcoding, hardware and software encoding, with or without subtitles. 

As a workaround replacing the ffmpeg binaries with the official ones from [here](https://www.gyan.dev/ffmpeg/builds/) fixes playback but does break HDR tone

**Comment by softworkz** [comment]
Could you please post here: https://emby.media/community/index.php?/forum/102-emby-server/

Also please attach the information requested in [how to report a media playback issue](https://emby.media/community/index.php?/topic/790-how-to-report-a-problem/). 
Thanks!

**Comment by SBachman** [comment]
done 

https://emby.media/community/index.php?/topic/107737-ffmpeg-on-beta-47035-crashing/
