### ISSUE TITLE
Films metadata corrupted.

### ISSUE THREAD

**Issue by Akirainblack** [MediaBrowser/Emby#3737]
I logged onto my Emby server this morning and all of the film metadata appears to be corrupt.
The Intern (2015)
Is showing the correct picture, however is labelled as:
The Lady in the Van (2015)
The synopsis is for Lady in the Van
The tagline is for The Intern.

Please advise how I can get this fixed.

**Comment by LukePulverenti** [comment]
Hi, try using the identify feature. Thanks.

**Comment by LukePulverenti** [comment]
Hi, has this helped? How are your files named and organized?

**Comment by LukePulverenti** [comment]
Closing, but please feel free to re-open with the requested information. Thanks.
