### ISSUE TITLE
Episode slider not working via cloudflare

### ISSUE THREAD

**Issue by ghost** [MediaBrowser/Emby#3738]
I am not able to traverse media while playing when the service is behind cloudflare.

The 10 sec skip buttons work, but if you use the slider, the media player will start from the beginning.

I access the server without cloudflare and the functionality works.

The request to skip ahead (or back) probably isn't unique enough. (A guess, I haven't tried to diagnose).

**Comment by LukePulverenti** [comment]
Hi, try turning off cloudfare caching as it is likely not using the http range requests correctly.

**Comment by LukePulverenti** [comment]
Hi, please see this: https://emby.media/community/index.php?/topic/103165-how-to-recommended-cloudflare-settings/

Then feel free to re-open if you still have an issue. Thanks.
