### ISSUE TITLE
Is there a way to save the subtitle settings instead keep doing it every time?

### ISSUE THREAD

**Issue by nammminn2** [MediaBrowser/Emby#3743]
<img width="684" alt="CleanShot 2022-07-11 at 19 08 57@2x" src="https://user-images.githubusercontent.com/64177573/178386483-f765920c-16a0-4bb8-bc87-bdd00d2d9573.png">

**Comment by LukePulverenti** [comment]
Hi, is this in the web app? Sounds like your browsing data is getting cleared.

**Comment by LukePulverenti** [comment]
@nammminn2 this is the reason why. Please let us know if you have additional questions. Thanks.

**Comment by nammminn2** [comment]
It doesn't have a save button I have to do it everytime I love emby

**Comment by LukePulverenti** [comment]
> It doesn't have a save button I have to do it everytime I love emby

It saves automatically. That's not your issue. Your issue I think is that when you close the browser, your browsing data is getting cleared. Does that sound right?
