### ISSUE TITLE
scan library files can‘t be stopped

### ISSUE THREAD

**Issue by vbwei** [MediaBrowser/Emby#3744]
I have a library with about fifteen thousand movies,every time add new moives to the library and scan it,it gets identify but the scan doesn't stop...the progress keeps for 90%-97% looping,I have to manually restart the emby service to complete the scan...

**Comment by LukePulverenti** [comment]
Hi there, can you please provide the emby server log from the library scan? thanks.

**Comment by LukePulverenti** [comment]
@vbwei ?

**Comment by LukePulverenti** [comment]
Closing, but please feel free to reopen with the requested information. Thanks.
