### ISSUE TITLE
Linux: Availability in Snap Store

### ISSUE THREAD

**Issue by Hans03430** [MediaBrowser/Emby#3745]
Good day, development team. I've been trying this app and so far, i've enjoyed what i tested, well on android at least. However, for linux, i came to discover the app, the theater and the server, are not available in Ubuntu's store. I know that there are two Snap packages already available for download, but i think it would be also quite useful for normal users to be able to install the apps from the Snap Store itself, since installing the downloaded snap packages require using the command line.

Is there any chance that the theater and server apps for linux ever make it to the Snap Store for Ubuntu?

**Comment by LukePulverenti** [comment]
Hi, we'd like to be in the snap store. We were communicating with them a while back and they had some issues they needed to workout related to apps built with the .NET runtime. We followed up several times but they kind of just stopped responding to us. We can take another look at it and see if anything has changed. Thanks.

**Comment by Hans03430** [comment]
Oh! I thought that the emby client for linux was made in electron? I found the old github repo for that and, as far as i know, electron is doing quite well in the snap store.

I must admit that i've never used the c# stuff for snap apps but hopefully, the documentation (https://snapcraft.io/docs/dotnet-plugin) has something useful related to the situation.

Here's hoping we can see emby client and server in the snap store in the future. it would be a boon! Thank you for the work you put into these apps!

**Comment by LukePulverenti** [comment]
The client, yes. We had been in discussion with the snap team about the server.

**Comment by Hans03430** [comment]
In case the server snap can't be hosted in the Snap Store, would there still be plans to host the client application in there?

**Comment by LukePulverenti** [comment]
We're now on Snapcraft: 
https://emby.media/snap-server.html
https://emby.media/snap-theater.html
