### ISSUE TITLE
Why Synology docker emby can only play about 15mins?

### ISSUE THREAD

**Issue by ztgreenleaves** [MediaBrowser/Emby#3748]
i get the premiere,but i can only play about 15mins on sony tv emby. Then the tv app and phone app can look video's poster but can't watch video

**Comment by LukePulverenti** [comment]
Hi there, can you please provide an example and attach the emby server log? Thanks.

**Comment by ztgreenleaves** [comment]
> Hi there, can you please provide an example and attach the emby server log? Thanks.
Thank you! I will post the log tonight when i back home ! This confuse me a long time😭

**Comment by LukePulverenti** [comment]
Great, thanks !

**Comment by ztgreenleaves** [comment]
[embyserver-63803085571.txt](https://github.com/MediaBrowser/Emby/files/9938029/embyserver-63803085571.txt)
Thank you! This is the log on that day. It's start on 2022-11-03 15:18:42.790. Thank you again!
I think Emby is very good, hope you can help me!

**Comment by ztgreenleaves** [comment]
😭

**Comment by LukePulverenti** [comment]
Hi, are you still running into this? Have you updated to Emby Server 4.7.10?

**Comment by ztgreenleaves** [comment]
I still running this and i already update to 4.8.9，it's very good！Thank you!

**Comment by LukePulverenti** [comment]
HI, so this does or doesn't still happen to you?

**Comment by LukePulverenti** [comment]
HI, newer versions should perform better. If you're still having an issue, please feel free to reopen this ticket with the requested information. Thanks !
