### ISSUE TITLE
user cloning issues

### ISSUE THREAD

**Issue by aniel300** [MediaBrowser/Emby#3753]
When cloning users there are some settings that don't carry over, is this working as design or is this a bug, i tried with latest docker stable and beta, same result.

**Comment by LukePulverenti** [comment]
Hi, can you please provide an example of a setting? Thanks.

**Comment by aniel300** [comment]
the few i have seems are: changed default view for channels, tags etc, changed default channel order, and few more things, if u want more details and proof and are willing to fix this, let me know and i can do my part to give more detals on this behavior

**Comment by LukePulverenti** [comment]
Hi, it's true that not all settings are copied at this stage, but we're going to keep on improving it over time so that it will include as much as possible. Thanks.

**Comment by aniel300** [comment]
so am assuming there is no eta for when this will fix then?

**Comment by LukePulverenti** [comment]
We’re planning on revamping the way some settings are stored and then many more will be copied when cloning a user.

**Comment by aniel300** [comment]
ok can't wait for this, keep up the good work.

**Comment by aniel300** [comment]
do u have an eta for this?

**Comment by LukePulverenti** [comment]
HI, in Emby Server 4.9, the cloning feature will capture user settings now.

**Comment by aniel300** [comment]
> HI, in Emby Server 4.9, the cloning feature will capture user settings now.

very good, thank you for this
