### ISSUE TITLE
Out of sync and not playing

### ISSUE THREAD

**Issue by lwlbeng** [MediaBrowser/Emby#3756]
1. The audio and video are not synchronized
2.When the video has its own subtitles, the video will not play
Android, Macos, the web all have this problem

**Comment by lwlbeng** [comment]
![image](https://user-images.githubusercontent.com/24000731/204438870-bc366ab3-9f17-49ee-8245-6a4786ffb26a.png)
![image](https://user-images.githubusercontent.com/24000731/204438938-2a67582e-62ab-4455-af61-cc45206962a6.png)
![image](https://user-images.githubusercontent.com/24000731/204439026-ff385b51-f190-4e4b-92b1-7075b40c1f5a.png)
![image](https://user-images.githubusercontent.com/24000731/204439178-8952494d-c561-45f8-beec-cee2b3ea9594.png)

**Comment by LukePulverenti** [comment]
HI, are you still running into this with Emby for Android 3.2.90 and Emby Server 4.7.11?

**Comment by LukePulverenti** [comment]
Closing, but please feel free to reopen with the requested information. Thanks.
