### ISSUE TITLE
Emby Server BETA 4.8.0.21 - .ignore file not working as expected

### ISSUE THREAD

**Issue by Fabeson** [MediaBrowser/Emby#3759]
After updating to Emby Server BETA 4.8.0.21 data from previously ignored folders started appearing in my libraries.
They have been excluded using the method documented here: https://support.emby.media/support/solutions/articles/44001159118-excluding-files-folders - ie. adding a file name ".ignore" in the folder.

This used to work as intended and documented up until the latest BETA release.

Thanks for having a look @LukePulverenti and happy holidays to you and the team!

**Comment by LukePulverenti** [comment]
This is resolved in the latest build. Thanks.
