### ISSUE TITLE
Small size display error

### ISSUE THREAD

**Issue by desdal** [MediaBrowser/Emby#3760]
![errEmby](https://user-images.githubusercontent.com/7411743/210107943-66743547-2195-41b3-a36f-823a608e6f34.png)
The left button on jacket in small size, have some error to display (the «view» button)

Sorry for my english i'm french speakink
_____________________________________________
Le bouton de gauche sur l'image de présentation en taille petite n'affiche pas ou seulement partiellement. (le bouton «Vu»).

**Comment by LukePulverenti** [comment]
Hi, yea it's just a little too small I guess. We'll take a look at it. Thanks .

**Comment by desdal** [comment]
i very like smal size,
the buttons could be vertical align at right, resize image button for more smaller or reduce margin/padding right-left of button.

Anyway thank you for your work!!!

**Comment by LukePulverenti** [comment]
Hi, this is resolved in the upcoming 4.8 server release. Thanks.
