### ISSUE TITLE
Android device Brightness cannot be adjusted

### ISSUE THREAD

**Issue by Venompool888** [MediaBrowser/Emby#3763]
apk downloaded from the official website, the brightness become low when play the flim and The brightness can't be ctrl, just extremely dark. Already re-install or renew the app but still not solve the problem

**Comment by NicciZar** [comment]
did you change the brightness of your phone?

Also try the version from Google Play Store if you can

**Comment by Venompool888** [comment]
> 

I tried,the brightness was locked

**Comment by Venompool888** [comment]
solve it the latest version can change the brightness![Screenshot_20230124_143624.jpg](https://user-images.githubusercontent.com/94547252/214227053-ce127fbd-31f6-4a02-8bbb-dad5900aa676.jpg)

**Comment by NicciZar** [comment]
Great. You can close the issue on github for your own :)
