### ISSUE TITLE
[Bug] TV Shows Artwork Not Downloading

### ISSUE THREAD

**Issue by zero77** [MediaBrowser/Emby#3764]
I have only selected primary in fetch for the library but only backdrops are downloaded for any new shows added.
This is the same when i refresh the metadata and replace images for that show but, i can only add a primary image when i manually search for it, in edit Images.

OS: Debian
Emby Version: 4.8.0.19 beta
Logs: https://pastebin.com/raw/qs14nYcv

**Comment by LukePulverenti** [comment]
Hi, please try updating to the latest 4.8 build and let us know if there's still an issue. Thanks.

**Comment by zero77** [comment]
@LukePulverenti 
I am using Version 4.8.0.29 and after a rescan and image replace this is still happening with some shows.

**Comment by LukePulverenti** [comment]
Hi, are you still having an issue with this?

**Comment by zero77** [comment]
Sorry for the slow response but, yes it looks like this is working at the moment

**Comment by LukePulverenti** [comment]
Thanks!
