### ISSUE TITLE
Music player jumps to next title when closing image viewer

### ISSUE THREAD

**Issue by godfuture** [MediaBrowser/Emby#3765]
server version [4.7.11.0]
firefox 109 win10 x64

1. Play a song such that music player starting in web
2. Navigate to a folder with a picture
3. Open the picture
4. Klick arrow left upper corner for closing the picture viewer
5. Music player jumped to next title

The music player should not jump to next title when image viewer is closed.

**Comment by LukePulverenti** [comment]
Hi, this is resolved for the next release. Thanks for reporting.
