### ISSUE TITLE
TV series can't be recognized 

### ISSUE THREAD

**Issue by Venompool888** [MediaBrowser/Emby#3767]
![Screenshot_20230205_201757.jpg](https://user-images.githubusercontent.com/94547252/216818316-12f364ed-145d-4be0-b145-f795bb1dcdd5.jpg)

As u see, I download the Western World season 1 but it can't be recognized automatically.
![Screenshot_20230205_201804.jpg](https://user-images.githubusercontent.com/94547252/216818412-c6a2c1ea-1b96-4eab-9ddb-39977e7b3870.jpg)
this is my jellyfin, their library is the same folder.jellyfin has successfully recognized it automatically but emby don't, they use the same metadata downloader.
![Screenshot_20230205_201826.jpg](https://user-images.githubusercontent.com/94547252/216818557-2e0eb9f3-4265-4390-b2d0-d7906cdce57f.jpg)

Here's the folder,the metadata has already been there but emby still can't recognize them even I have already make it scan the library over and over again

**Comment by Venompool888** [comment]
Has anyone encountered this before?

**Comment by Venompool888** [comment]
Has anyone encountered this before?

**Comment by LukePulverenti** [comment]
Hi there, how are your folders organized?

**Comment by Venompool888** [comment]
> Hi there, how are your folders organized?
same like this
\TV
    \Glee (2009)
       \Season 1
          Glee S01E01.mp4
          Glee S01E02.mp4


Other series in the same folder are all correctly recognized. I think there is sth wrong with those metadata tools

**Comment by Venompool888** [comment]
Anyone got idea about this problem?😭

**Comment by LukePulverenti** [comment]
Hi, what folder did you add to Emby library setup? What is the content type of the library?

**Comment by LukePulverenti** [comment]
Closing, but please feel free to reopen with the requested information Thanks !
