### ISSUE TITLE
can not search item by api ​/Users​/{UserId}​/Items

### ISSUE THREAD

**Issue by fuchenw** [MediaBrowser/Emby#3771]
GET
​/Users​/{UserId}​/Items
Gets items based on a query.

GET
​/Users​/{UserId}​/Items​/Resume
Gets items based on a query.

i can search by ​/Users​/{UserId}​/Items​/Resume, but ​cant with /Users​/{UserId}​/Items, it always returns CollectionFolder, help!

**Comment by fuchenw** [comment]
IncludeItemTypes=Movie&Recursive=true&SearchTerm=

**Comment by LukePulverenti** [comment]
Can you please provide the complete query url that you're using?

As an example, here's what the web app sends:

`Users/{id}/Items?SortBy=SortName&SortOrder=Ascending&IncludeItemTypes=Movie&ImageTypeLimit=1&Recursive=true&SearchTerm=bourne&Limit=100`

**Comment by fuchenw** [comment]
> 

/emby/Users/{id}/Items?api_key=' + apiKey + '&IncludeItemTypes=Movie&Recursive=true&SearchTerm=

**Comment by fuchenw** [comment]
> Can you please provide the complete query url that you're using?
> 
> As an example, here's what the web app sends:
> 
> `Users/{id}/Items?SortBy=SortName&SortOrder=Ascending&IncludeItemTypes=Movie&ImageTypeLimit=1&Recursive=true&SearchTerm=bourne&Limit=100`

/emby/Users/{id}/Items?api_key=' + apiKey + '&IncludeItemTypes=Movie&Recursive=true&SearchTerm=

**Comment by softworkz** [comment]
The SearchTerm must be two characters long at least.

**Comment by LukePulverenti** [comment]
HI, has this answered your question?
