### ISSUE TITLE
[bug] Not the source of 4K HDR, the screen image will get stuck

### ISSUE THREAD

**Issue by Romic77** [MediaBrowser/Emby#3773]
[Android TV] After a long period of testing, it has been found that regardless of the official version, the Xiaomi version, or the terminal version of Embry, the existing version of v2. X and above, domestic TV systems (Huawei, Xiaomi, etc.) will experience a screen jam when transcoding 4K non HDR film sources, while the v1.8. x version will normally transcode and play

**Comment by LukePulverenti** [comment]
Hi, can you please provide a specific example? Thanks.

**Comment by LukePulverenti** [comment]
Closing, but please feel free to reopen with the requested information. Thanks.
