### ISSUE TITLE
Bigscreen DLNA doesn't work

### ISSUE THREAD

**Issue by atrauzzi** [MediaBrowser/Emby#3774]
It just sits there with the spinning green indicator.

I can use bigscreen to communicate to other DLNA servers, so it's unlikely that their implementation is the issue.

Is there any chance this can be fixed?

**Comment by LukePulverenti** [comment]
Hi, this is resolved in the Emby DLNA plugin version 1.1.4+. Thanks !

**Comment by atrauzzi** [comment]
Works!
