### ISSUE TITLE
Seeking within video on Firefox 111.0.1 (Win10 x64) freezes playback

### ISSUE THREAD

**Issue by godfuture** [MediaBrowser/Emby#3776]
When playing a video via the web browser on FF and then seeking to any other point, the playback stops. You can't resume it either. Pause / Play won't restart it either. Sometimes using 30s jump button helps, but not always.

I couldn't find any hint in logs.

Emby: 4.7.11.0

**Comment by LukePulverenti** [comment]
Hi there, can you please provide an example and attach the emby server and ffmpeg log files? How does Chrome compare?

**Comment by LukePulverenti** [comment]
HI, newer versions should perform better. If you're still having an issue, please feel free to reopen this ticket with the requested information. Thanks !
