### ISSUE TITLE
Lossless Transcoding not available H.265

### ISSUE THREAD

**Issue by thaddelice** [MediaBrowser/Emby#3777]
I tried to convert my h264 library to h265, but I couldn't find a setting to convert lossless to h265.

In the diagnostic option is a field to control FFmpeg a little bit, but it is not enough. 

In Advanced Transcoding you can't set the CRF for x265 to 0, which would allow a lossless conversion.

**Comment by LukePulverenti** [comment]
Hi, you'll be able to do this in the upcoming 4.8 server release. In fact there will be a lot of new codec-specific options that you'll probably enjoy related to this. It is in the 4.8 beta channel if you'd like to try it. Thanks.
