### ISSUE TITLE
[BUG]Some bug about cover

### ISSUE THREAD

**Issue by wubushanyan** [MediaBrowser/Emby#3778]
Enter the TV program and click on the top button as “Genres”. 
You can see the covers of similar automatic collections in many different genres.
**But there will be episodes that shouldn't be there cover.**
**These episodes are set as inaccessible in those users, but users can see the cover of the inaccessible episodes here**

Really need fix it.

**Comment by LukePulverenti** [comment]
Duplicate of #3014
