### ISSUE TITLE
slow home screen loading, slow scanning, slow live guide refresh and probably more that i haven't yet bum into

### ISSUE THREAD

**Issue by aniel300** [MediaBrowser/Emby#3779]
i am having this issue where after a while my emby server will become slow. rebooting the server/ container fix it sometimes but not always. the main thing that tells me am having an issues is when going to the home screen most of the time it will take 5 to 10 seconds to fully load all the icons. issue still happens even when no custom/ extra plugin is present. i also discovered a new behavior. if i go to the home menu for the first time and wait the 5 to 10 seconds for it to fully load (some time it gets stuck and it doesn't load at all) and click on live tv and/or library and the go back using using the back arrow there is no refreshing (everyting is there) but if i use the home button then that is when the issue happens (i can confirm this behavior on the weui and ios).

can anybody help?

original post: https://emby.media/community/index.php?/topic/118172-extremely-long-media-library-scan-and-slow-unresponsive-apps

**Comment by LukePulverenti** [comment]
Hi, we'll continue helping you in your forum topic. Thanks.

**Comment by aniel300** [comment]
ok np and thank u.

**Comment by aniel300** [comment]
am still waiting for assistance? @LukePulverenti
