### ISSUE TITLE
slow to load home screen and library scan stuck at 88.3

### ISSUE THREAD

**Issue by aniel300** [MediaBrowser/Emby#3781]
please i need help since this is getting ridiculous and am just getting ignore, i need assistance as soon as possible.  i am having this issue where after a while my emby server will become slow. rebooting the server/ container fix it sometimes but not always. the main thing that tells me am having an issues is when going to the home screen as most of the time it will take 5 to 10 seconds to fully load all the icons.  issue still happens even when no custom/ extra plugin is present. i also discovered a new behavior. if i go to the home menu for the first time and wait the 5 to 10 seconds for it to fully load (some time it gets stuck and it doesn't load at all) and click on live tv and/or library and the go back using using the back arrow there is no refreshing (everyting is there) but if i use the home button then that is when the issue happens (i can confirm this behavior on the weui and ios).

credit: mickle026
"My Home is not particulary slow but it is definately slower than before.  Same with the dashboard. The server behaves like Navigation has to complete for each section rather than is cancelled when you click on something and this is across all devices.

Homepage keeps loading and click tvshows, it will be blank page until all data for hompeage is loaded, then it will start to load.  This never used to happen, I think its new.

This is how it appears to be behaving for me.

 

Library scans go really slow between 75% and 100%, this is where its looking up stuff from the internet or appling data to the database.  I do not know if duplicate metadata requests were ever fixed.  I pointed that out a while ago (see link), this was where there where several images  were available, Emby was requesting each and every provider many times the same requests for images, if 7 images were available in total across all providers, each provider was queried 7 times each - this was the issue here, like I said do not know if that was resolved." 

original post: https://emby.media/community/index.php?/topic/118172-extremely-long-media-library-scan-and-slow-unresponsive-apps

**Comment by LukePulverenti** [comment]
Hi, we'll continue helping you in your forum topic. Thanks.

**Comment by aniel300** [comment]
well that is the thing it feels like u are ignoring me because i couple occasion i have to quote u 2 or 3 times for u to reply to me.

**Comment by LukePulverenti** [comment]
Hi, things take time. I can assure your issue is being looked into. Thanks.

**Comment by aniel300** [comment]
show me proof

**Comment by aniel300** [comment]
> Hi, things take time. I can assure your issue is being looked into. Thanks.

hello, can u show me any proof?

**Comment by ztgreenleaves** [comment]
me too! and i have the  Emby Premiere，but it's not display in the top of the page

**Comment by LukePulverenti** [comment]
Closing to avoid having the same conversation both here and in the forum. Thanks.
