### ISSUE TITLE
Cropped thumbnails of live TV channels on Emby for Apple TV with app version 1.7.4

### ISSUE THREAD

**Issue by julianbalog** [MediaBrowser/Emby#3786]
Live TV channel thumbnails are partially displayed (cropped) on Emby for Apple TV v1.7.4(2) (see attached image).
![emby-apple-tv-1 7 4(2)](https://github.com/MediaBrowser/Emby/assets/851322/d0f59b0c-be10-42fe-9f4e-eb505867e3a3)

**Comment by LukePulverenti** [comment]
HI, this is resolved in the next update to Emby for Apple TV. Thanks.
