### ISSUE TITLE
In the Live TV Favorites view, only 10 channels are shown on Emby for Apple TV with app version 1.7.4

### ISSUE THREAD

**Issue by julianbalog** [MediaBrowser/Emby#3787]
With Emby for Apple TV (app version 1.7.4), only the first 10 Live TV channels (tagged as favorites) are displayed in the Live TV Favorites view. Removing a favorite channel brings in the next one in the Favorites view.

Also, the Favorites view is only showing the Live TV channels in a single row, with multiple lateral scrolls required to view more channels. The user experience would be much better with a multi-row thumbnail view (as the regular Live TV channels are displayed).

**Comment by LukePulverenti** [comment]
Hi, this is resolved for the next update to the Emby Apple TV app. Thanks.
