### ISSUE TITLE
Emby Server Live TV channels not displaying all m3u my channels

### ISSUE THREAD

**Issue by storoyr** [MediaBrowser/Emby#3788]
Why does only **2427** channels show in Emby  when there are actually **8028** channels in my playlist.m3u?

![playlist TOTAL](https://github.com/MediaBrowser/Emby/assets/26773223/38be757e-946e-4991-9009-9547670de527)
![emby channels](https://github.com/MediaBrowser/Emby/assets/26773223/c85a161b-f624-4e4f-a6a6-39b8560d63b4)

**Comment by michalkulik** [comment]
You need to de-duplicate or delete tvg-id parameter in your m3u list - if it's duplicated, Emby won't show either of channels.

**Comment by storoyr** [comment]
THANKS, Wonder why Luke didn't tell me!
