### ISSUE TITLE
Problem sorting between films and TV series

### ISSUE THREAD

**Issue by schumissimo63** [MediaBrowser/Emby#3791]
Hello, Previously I used plex but recently I migrated to Emby, I encountered a difficulty, as a media library path I put /home/user1/torrents, the folder where the torrents are downloaded, I created a media library, one for films and one for TV series, previously with plex the sorting was done automatically, now with emby films are found in the “TV series” media library. What configuration should be adopted to no longer encounter this inconvenience? Thanks for your help.

**Comment by LukePulverenti** [comment]
Hi, are you saying you have two libraries pointing to the same folder, but with different content types?

**Comment by LukePulverenti** [comment]
Closing, but please feel free to reopen with the requested information. Thanks.
