### ISSUE TITLE
No x86 Windows build for latest beta?

### ISSUE THREAD

**Issue by stevehoek** [MediaBrowser/Emby#3792]
Don't see the x86 native Windows build in the list of assets this time?

**Comment by softworkz** [comment]
I can't tell what happened, but I'm curious: Why are you (still) interested in an x86 version of the server?

**Comment by stevehoek** [comment]
> I can't tell what happened, but I'm curious: Why are you (still) interested in an x86 version of the server?

x86_64 to be more specific.  I run Emby on my Windows Server.  Used to run on QNAP NAS but getting better perf on the bare metal of the server.

**Comment by softworkz** [comment]
> x86_64 to be more specific.

Ah, I thought you meant 32bit.

Anyway, there has been an issue with the current beta build. A new beta will follow shortly.
Thanks

**Comment by LukePulverenti** [comment]
It's up now.
