### ISSUE TITLE
the interface stops at emby logo

### ISSUE THREAD

**Issue by paraliine** [MediaBrowser/Emby#3794]
On my two servers with Ubuntu 22.04, when I open http://localhost:8096 in brower, the interface stops at the emby logo, just like the picture below.
![image](https://github.com/MediaBrowser/Emby/assets/116947561/ffbc2753-c6d7-4098-849d-425219f8f454)
And I wait for quite a long time, there is still no respond.

**Comment by LukePulverenti** [comment]
Hi, can you please supply the contents of the browser debug console? thanks.

**Comment by paraliine** [comment]
> Hi, can you please supply the contents of the browser debug console? thanks.

![IMG_20231116_163809](https://github.com/MediaBrowser/Emby/assets/116947561/1fe3b30c-58e8-4904-bd59-409759f3ea6c)

These are the contents of the browser debug console.

**Comment by LukePulverenti** [comment]
Can you try clearing browsing data and see if that resolves your issue?

**Comment by paraliine** [comment]
> Can you try clearing browsing data and see if that resolves your issue?

This does solve the problem. Thanks.

**Comment by paraliine** [comment]
> > Can you try clearing browsing data and see if that resolves your issue?
> 
> This does solve the problem. Thanks.

I now find that using a VPN might be the issue.

**Comment by LukePulverenti** [comment]
Did you find the problem with the vpn?

**Comment by LukePulverenti** [comment]
Closing, but please feel free to reopen with the requested information. Thanks.
