### ISSUE TITLE
Webhooks firing on ANY EVENT

### ISSUE THREAD

**Issue by Node815** [MediaBrowser/Emby#3795]
Emby Version 4.7.14.0

For the Holidays, I have a media library called "Holiday Movies"  and use Home Assistant.    I set the web hook in Home Assistant to fire a scene in response to the webhook to set my lights to the colors we want.  This works without issue,  The test firing of the hooks as well work within Emby when setting them up.

These are my settings:

As User TV:

The following actions need to be met:
![image](https://github.com/MediaBrowser/Emby/assets/20736534/c00def20-0750-46e1-9dad-59f7a746d30a)

Then if that is met I would expect it to follow this condition:

![image](https://github.com/MediaBrowser/Emby/assets/20736534/ef3b2353-0549-496f-a0fb-395c84865165)

The problem I am having is it doesn't matter what I play, as long as the condition of TV Playing is met, it fires off the task.  I tested this with a different user in my server and it at least properly respects the user setting of the account "TV" 

Whatever logs I can collect for this so I can help please let me know!

**Comment by Node815** [comment]
I tested the beta version and it works as expected:
![image](https://github.com/MediaBrowser/Emby/assets/20736534/b0301261-2276-45b4-8be5-3534c777badb)

**Comment by LukePulverenti** [comment]
Thanks for doing that !
