### ISSUE TITLE
[Feature request] Metadata Offline directly into File

### ISSUE THREAD

**Issue by Ed1ks** [MediaBrowser/Emby#3799]
Hello,
please add an option for library to never search and download any metadata.

please add also the option, for writting metadata directly into the file.

**Comment by LukePulverenti** [comment]
Hi, these options already exist in Emby library setup. Just turn on or off the features that you do or do not want.

**Comment by Ed1ks** [comment]
I cant find the options. I have deactivated all sources for metadata but in context menu the option for reloading metadata still exists. Using it resets the metadata.

Setting metadata just create some metadata in /config directory in an random? structure. The metadata inside of my audiobook/mp3 dont change

**Comment by LukePulverenti** [comment]
> I cant find the options. I have deactivated all sources for metadata but in context menu the option for reloading metadata still exists. Using it resets the metadata.
> 
> Setting metadata just create some metadata in /config directory in an random? structure. The metadata inside of my audiobook/mp3 dont change

Right, that option will always be there. it will reprobe your files if you use it.

**Comment by Ed1ks** [comment]
But if I change the metadata, the metadata in files will not be changed. Just in seperate nfo file. This makes it easy to destroy all metadata by misclicking on refresh all metadata.
I request the option, that metadata will be written directly into the files.
