### ISSUE TITLE
[Feature Request] Global Privacy Settings

### ISSUE THREAD

**Issue by Ed1ks** [MediaBrowser/Emby#3801]
Hello,

I request some Privacy Settings:
I dont want to see the acitivities of my users, and I want that no one can play something on an device from another user nor can download something on a different users device. This needs to be absolutely strict.

Also default user settings would be nice.
Also changing settings for many users at one would be also good.

**Comment by LukePulverenti** [comment]
Hi, you can restrict remote control permissions of other devices for each user, and then they won't be able to do either of those two things.

**Comment by Ed1ks** [comment]
Set default settings would be nice.
Also changing settings for many users at once. E.g. selecting users and change settings.

**Comment by LukePulverenti** [comment]
Closing because this can be controlled using remote control permissions.

As for the default user, we now have the ability to copy settings and data from an existing user when creating a new one.
