### ISSUE TITLE
By using search, you can find videos in media libraries without permission and watch them

### ISSUE THREAD

**Issue by Jafeyyu** [MediaBrowser/Emby#3805]
By using search, you can find videos in media libraries without permission and watch them

**Comment by LukePulverenti** [comment]
Example?

**Comment by pcheck** [comment]
Something has changed with the permissions in the latest update.
I have my folders set up as the following
TV Shows
->TV Shows - Child
->TV Shows - Mine
->TV Shows - Shared
My son has access to child and shared, but not mine. He is also set to a maximum rating of TV-Y7-FV.
He was able to see Step by Step on his account, even though it is under TV Shows - Mine. Even going into TV Shows and then folders, doesn't show the folder TV Shows - Mine. I changed the rating to TV-PG and that removed it from showing under his account, however, if I search for Step by Step, it shows up in the results and takes him to the show. It appears the search results are showing the episodes of Step by Step that have a TV-G rating, even though I changed the shows overall rating to TV-PG. Changing an individual episode to TV-PG removes it from the search results. Also, going to the Episodes tab in TV Shows lists the Step by Step episodes.

**Comment by pcheck** [comment]
I ended up removing the TV Shows - Mine folder from the TV Shows library, letting it scan all libraries, add the folder back to the library, let scan all the libraries and it removed Step by Step from showing under his account, as well as the search. There are several other TV Shows library folders that are still showing up when searching which my son does not have access to under his account settings. I'll try removing them from the library and add them back and see if that removes them when searching.

**Comment by LukePulverenti** [comment]
Hi, please try the 4.8.1 release and let us know if this resolves the issue. Thanks.

**Comment by LukePulverenti** [comment]
This should be resolved in newer 4.8.x builds. Thanks.
