### ISSUE TITLE
Emby subtitle recognition error

### ISSUE THREAD

**Issue by Stdocdure** [MediaBrowser/Emby#3808]
Docker installed EMBY cannot correctly recognize traditional Chinese and simplified Chinese characters。
![微信图片_20240116172722](https://github.com/MediaBrowser/Emby/assets/82276349/2e1ca684-9a18-4b76-8b2e-81c86fa51fd9)
![微信图片_20240116172714](https://github.com/MediaBrowser/Emby/assets/82276349/2ecceef1-9a88-434e-9bdc-ce55f4d9db46)

**Comment by LukePulverenti** [comment]
Hi, what characters are you referring to?

**Comment by LukePulverenti** [comment]
We're having this discussion in the Emby community as well:
https://emby.media/community/index.php?/topic/124973-emby-subtitle-recognition-error
So let's continue there. Thanks.
