### ISSUE TITLE
Update the .Policy.SimultaneousStreamLimit with API

### ISSUE THREAD

**Issue by bilyboy785** [MediaBrowser/Emby#3809]
Hello,

i'm trying to update the .Policy.SimultaneousStreamLimit value of each users with API, but seem's to not be OK.

API returns : 

```
Value cannot be null. (Parameter &#39;newName&#39;)
```

I tried : 

```
curl -X POST 'https://domain.com/Users/XXXXXXXX?api_key=XXXXXXXX' -H 'accept: application/json' -d '{"Name":"mail@domain.com","Policy":{"SimultaneousStreamLimit":"3"}}'
```

I tried the full json output too... 

Someone can help me to do it ?

**Comment by LukePulverenti** [comment]
HI, you need to first retrieve the full user object, update the value, and then send the whole thing back.

In the upcoming 4.8 release, some api's have been added that will accept partial json, so gradually over time you'll be able to do what you're doing more and more.

**Comment by bilyboy785** [comment]
Thank's @LukePulverenti , I already tried this, but got this error : 

```
#  curl -X POST 'https://domain.com/Users/xxxxxxxxxx?api_key=xxxxxxxxxx' -H 'accept: application/json' -d @data.json
Form key length limit 2048 exceeded.
```

**Comment by bilyboy785** [comment]
@LukePulverenti do you have any idea about this error ?

**Comment by bilyboy785** [comment]
I found the solution by get /user full Json, filtering only the Policy array and sending this updated Policy array on the /user/ID/Policy POST api method ;)

**Comment by LukePulverenti** [comment]
Thanks for following up !
