### ISSUE TITLE
8920 connection refused

### ISSUE THREAD

**Issue by Venompool888** [MediaBrowser/Emby#3810]
I built my emby server on Synology7. It has been working good for almost two hundred days but recently I found 8920 can't be visited no matter it's in my local network or from Internet but Tcping is still avaliable. I disabled the firewall but the problem still lies. I can use 8096 to visit my emby but http connection is not safe. 
I attempt to use different ports to reverse the connections on 8096 and 8920, but still received a connection refused result....
![309492b916dbc48c0d73b6a543f39ace](https://github.com/MediaBrowser/Emby/assets/94547252/43ec7bb7-f5bd-44a7-a855-50f4583e6ba2)
[embyserver.txt](https://github.com/MediaBrowser/Emby/files/14000973/embyserver.txt)

**Comment by LukePulverenti** [comment]
Hi, did you setup https in Emby Server network settings? You need to do this before you can use https.

**Comment by LukePulverenti** [comment]
HI, you need to setup an SSL certificate in Emby Server network settings. Once you've done that, if you're still having an issue, then please feel free to reopen this ticket and we'll look into it further. Thanks.
