### ISSUE TITLE
[Bug] Audio/Music libraries | Artist Name missing in Genre view

### ISSUE THREAD

**Issue by Regolith-3dp** [MediaBrowser/Emby#3811]
Following the 4.8.1.0 update, the Genre view for my Audio, Audiobook and Music Video libraries does not show Artist or Album Artist for any view except Table. Artist / Album Artist is not also not user-selectable under Show Fields.

![Screenshot - Audio libraries missing Artist](https://github.com/MediaBrowser/Emby/assets/72182480/b72f26ce-d7f9-4031-9c17-eec99e0bdca7)

**Comment by LukePulverenti** [comment]
Hi, we'll take a look at this. Thanks for reporting.

**Comment by LukePulverenti** [comment]
This will be resolved in the upcoming 4.8.2 maintenance release. Thanks.
