### ISSUE TITLE
[Bug] Vanished Categories After changing Homepage 

### ISSUE THREAD

**Issue by Ed1ks** [MediaBrowser/Emby#3813]
After Changing the viewable Categories, they just vanish and its not possible to get them back. Bug existed in 4.7 and persist in 4.8

![image](https://github.com/MediaBrowser/Emby/assets/46250296/92b5fa60-d6f2-49be-9d19-9cccfd7b489e)

![image](https://github.com/MediaBrowser/Emby/assets/46250296/040f8910-18ca-4192-9b5e-81e9606a97e6)

**Comment by LukePulverenti** [comment]
Hi, why isn't is possible to get them back? Cant' you just go back into home screen settings and re-enable them?

**Comment by Ed1ks** [comment]
Hi,
sadly it is not possible to re-enable them. I set them like the upper screenshot and the result is the screenshot below.

**Comment by LukePulverenti** [comment]
What sections are missing? Maybe they just have nothing to show? If they're empty then they won't show.

Can you please provide an example of what should be showing that isn't? Thanks.

**Comment by Ed1ks** [comment]
I would like to see the categories which are enabled in screenshot 1.
If I select the the media Library, these categories will be shown. But not in Homescreen:
![image](https://github.com/MediaBrowser/Emby/assets/46250296/8ea2c9cb-dd8d-4a2c-aadb-c5dc9cfe1f1f)
![image](https://github.com/MediaBrowser/Emby/assets/46250296/623ee190-4ac2-414a-af55-613b7ee81bbd)

**Comment by LukePulverenti** [comment]
OK i think you're expecting the entire music library screen to be duplicated onto the main home screen. It doesn't work that way.

**Comment by Ed1ks** [comment]
@LukePulverenti 
I am expecting, that the settings for the home screen dont vanish the categories.
Look. After I`ve created new user, homescreen looks like this:
![image](https://github.com/MediaBrowser/Emby/assets/46250296/a1b6011d-8a4b-4252-8103-fd55c94d8f63)
If I listen to something, the recently listened category also pops up.

So I am not expecting any duplicates. Just that the settings for the homescreen do work and not vanish the categorie which were existing.

Edit:
If I remove a category at new user, I can get it back. But the main user cant do this 🤔
something weird here.

**Comment by LukePulverenti** [comment]
In home screen settings for that user, is the box checked to hide played media from latest sections?

**Comment by Ed1ks** [comment]
> In home screen settings for that user, is the box checked to hide played media from latest sections?

I guess we found the issue. I looked after the checkbox and saw it was unchecked. After checking it, these categories popped up. Probably the description "second Page" is a little bit irritating. I tought second page is the media page.

**Comment by LukePulverenti** [comment]
Where do you see second page?

**Comment by Ed1ks** [comment]
![image](https://github.com/MediaBrowser/Emby/assets/46250296/b3de22a9-9199-410e-a392-6bd3751d9f53)

Maybe a translation thing

**Comment by LukePulverenti** [comment]
So maybe that's a translation error?
