### ISSUE TITLE
[Bug] Songtext not refreshing

### ISSUE THREAD

**Issue by Ed1ks** [MediaBrowser/Emby#3815]
If I change the .lrc file, emby doesnt recognize the change.
Even if I delete the songtext in Emby and reupload it, it shows the previous songtext.

Edit: It seems the text is cached. After cleaning Website cache it is showing the right songtext.
Case closed

**Comment by LukePulverenti** [comment]
HI, what website cache did you clear? Do you mean in the browser?

**Comment by Ed1ks** [comment]
Hi,
Yes, I cleaned the browser cache. I lost all design settings too, but it worked
