### ISSUE TITLE
Notifications with images 

### ISSUE THREAD

**Issue by tommyMX** [MediaBrowser/Emby#3816]
Hi

Please add through notifications to add images ;-)

E.G telegram 

thank you

**Comment by LukePulverenti** [comment]
Hi, this is up to the developer of the telegram plugin to add this.

**Comment by tommyMX** [comment]
I thought that’s a problem from the emby frame work ?

**Comment by LukePulverenti** [comment]
Not that I'm aware of.

**Comment by tommyMX** [comment]
I have already checked it and the Emby notification framework does not support it.

https://emby.media/community/index.php?/topic/105395-telegram-notifications-plugin/

**Comment by LukePulverenti** [comment]
It does. Just need to give him an example. Thanks.

**Comment by tommyMX** [comment]
Yes please give a example him ;-)

**Comment by tommyMX** [comment]
Can you give him an example please ? You didn’t it in the thread :-/
