### ISSUE TITLE
Please update the Synology NAS package VERSION to 4.8.x or 4.9.x

### ISSUE THREAD

**Issue by MoConWu** [MediaBrowser/Emby#3821]
![2024225-222139](https://github.com/MediaBrowser/Emby/assets/33497338/80b64dee-bc26-4d4d-aa6f-1a28d289440d)

You can see，the SynologyNAS package version is only 4.7.x.

Please update the Synology NAS package VERSION to 4.8.x or 4.9.x!

Thanks!

**Comment by LukePulverenti** [comment]
Hi, 4.8.8 is available in Package Center now.
