### ISSUE TITLE
Consider replacing `Discvover` with `Discover`

### ISSUE THREAD

**Issue by jsoref** [MediaBrowser/Emby#3824]
Hi,

I understand that this is a public API (I ran into it in a consumer), but I was wondering if you'd consider adding a `/Discover` endpoint and deprecating `Discvover`:

https://github.com/MediaBrowser/Emby/blob/1d7c2ab4bfebdae31f89fdaabd3b68782ccf495a/MediaBrowser.Api/LiveTv/LiveTvService.cs#L684

**Comment by LukePulverenti** [comment]
HI, this is being added in Emby Server 4.9. Thanks.
