### ISSUE TITLE
AMD64 release package not available for Version 4.8.4.0 

### ISSUE THREAD

**Issue by tritethunder** [MediaBrowser/Emby#3832]
Hi, I can't see any release for AMD64 package [at](https://github.com/MediaBrowser/Emby.Releases/releases/tag/4.8.4.0) and that makes this [script](https://github.com/tteck/Proxmox/blob/main/ct/emby.sh) failing that used by thousand of people to download emby on their proxmox homelab. please fix this.  

`curl -s -o /dev/null -w "%{http_code}" https://github.com/MediaBrowser/Emby.Releases/releases/download/4.8.4.0/emby-server-deb_4.8.4.0_amd64.deb` 

returns 404

**Comment by tritethunder** [comment]
seems there is a huge gap between release packages for different platform

**Comment by LukePulverenti** [comment]
HI, it's up now. Apologies for the delay.
