### ISSUE TITLE
Web interface: Overlay is killing performance, 30fps down to 2

### ISSUE THREAD

**Issue by frostbitten** [MediaBrowser/Emby#3835]
Hi there. My laptop is a bit old but gets the job done with most video services. Sometimes if my device is strained the overlay (the controls that pop up when you move the mouse) seems to drop the performance by a consider amount. I see my CPU usage bumps up from ~30 to ~50 percent, no change in GPU, and video playback slows to as low as 2 fps. I reduced the streaming quality and resolution but that doesn't help keep the overlay from affecting performance by much. I tried 144p and it got up to about 10fps but that's impractical.

Using chrome.

```
Processor	Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz   2.60 GHz
Installed RAM	8.00 GB
```
Anything I can do on my end? Or perhaps anything in the code worth me looking at?

**Comment by LukePulverenti** [comment]
Hi, this should be resolved in the next release. We’re just going to go back to disabling the blur effect in chrome.
