### ISSUE TITLE
Allow API Login to use Email

### ISSUE THREAD

**Issue by sgtcoder** [MediaBrowser/Emby#3838]
When using the API, the username is the first name/last name. This makes it challenging and confusing to people logging in. It would be nice to be able to login with the email address.

I verified I could use Email for logging through the Emby API.

https://github.com/Fallenbagel/jellyseerr/issues/749

**Comment by Fallenbagel** [comment]
We weren't claiming its an emby issue. Youre still misunderstanding the entire thing.

We NEVER USED emails. We have always USED usernames. We cannot SUPPORT emails until we refactor jellyseerr.

**Comment by Fallenbagel** [comment]
We weren't claiming its an emby issue. Youre still misunderstanding the entire thing.

We NEVER USED emails. We have always USED usernames. We cannot SUPPORT emails until we refactor jellyseerr.

**Comment by sgtcoder** [comment]
> So it is EMBY'S issue that they set the first name last name as the username when connected through emby connect. Not ours. All we do is authenticate using whatever username is available through emby

I am not sure what you mean though? Just pass the email address to the AuthenticateByUsername.

I will find some time to look over the Jellyseer codebase to see what's going on. But it appears that AuthenticateByUsername does work with Emby Connect Email addresses. I tested it out myself and it works and returns a User object response.

**Comment by sgtcoder** [comment]
It turns out there will be an update on Jellyseer side to address this issue. https://github.com/Fallenbagel/jellyseerr/pull/685

Closing this issue out.
