### ISSUE TITLE
How does Emby render video in mkv format to play on web browser

### ISSUE THREAD

**Issue by 292210278** [MediaBrowser/Emby#3854]
I use FFmpeg to convert a video from MKV to MP4, but it's too slow.

**Comment by LukePulverenti** [comment]
Hi, Chrome and other Chromium based browsers can direct play some mkv's, depending on supported audio/video codecs. Other browser will require mkv to be repackaged on the fly to a compatible container.

**Comment by 292210278** [comment]
> Hi, Chrome and other Chromium based browsers can direct play some mkv's, depending on supported audio/video codecs. Other browser will require mkv to be repackaged on the fly to a compatible container.

OK,thanks.Do you know whitch compatible container I can use

**Comment by LukePulverenti** [comment]
mp4 is the most universally compatible container if you want to maximize direct play and minimize server transcoding.

**Comment by 292210278** [comment]
> mp4 is the most universally compatible container if you want to maximize direct play and minimize server transcoding.

Yesterday, I checked the network tab while Emby was playing, and I noticed that Emby seems to convert H.265-encoded videos into H.264 videos and segment them into .ts file format. This improves Emby’s transcoding efficiency and ensures a smooth viewing experience for users. Is my understanding correct?

**Comment by LukePulverenti** [comment]
> > mp4 is the most universally compatible container if you want to maximize direct play and minimize server transcoding.
> 
> Yesterday, I checked the network tab while Emby was playing, and I noticed that Emby seems to convert H.265-encoded videos into H.264 videos and segment them into .ts file format. This improves Emby’s transcoding efficiency and ensures a smooth viewing experience for users. Is my understanding correct?

Hi, yes this is done to either make the format compatible with the device playing, or to reduce the bitrate to ensure smoother playback.

**Comment by 292210278** [comment]
Ok,I kown.For video slicing, does emby upload the slicing to the front end after it has been completed, or does EMby slice the video during the playback process? If it's the first, doesn't this add extra user memory.

**Comment by 292210278** [comment]
> > > mp4 is the most universally compatible container if you want to maximize direct play and minimize server transcoding.
> > 
> > 
> > Yesterday, I checked the network tab while Emby was playing, and I noticed that Emby seems to convert H.265-encoded videos into H.264 videos and segment them into .ts file format. This improves Emby’s transcoding efficiency and ensures a smooth viewing experience for users. Is my understanding correct?
> 
> Hi, yes this is done to either make the format compatible with the device playing, or to reduce the bitrate to ensure smoother playback.

Ok,I know.As for video slicing, the back end completes the video slicing in advance and then sends it to the front end, or slicing the video when the video is playing. If it is the first, won't this increase the user's computer memory?

**Comment by LukePulverenti** [comment]
>  the back end completes the video slicing in advance 

Yes, but not very far in advance. More like just in time. And yes, it will require temporary storage but this is cleaned up when playback stops.

**Comment by LukePulverenti** [comment]
Please let us know if you need anything else. Thanks.

**Comment by 292210278** [comment]
> Please let us know if you need anything else. Thanks.

Sorry for not replying in time, I have no more questions now, and I sincerely thank you for your answers
