### ISSUE TITLE
Deleting a video file after watching it can result in deletion of videos in subdirectories or entire media library

### ISSUE THREAD

**Issue by DaveAlot** [MediaBrowser/Emby#3855]
*deleted since this project appears to be dead*

**Comment by nomandera** [comment]
> _deleted since this project appears to be dead_

Can we clarify if this is an issue.

The project is not dead just no longer open source, but a bug of this potential magnitude should be analyzed in detail no matter where it is reported to.

To recap from memory. The report details a condition where entire collections of media can be deleted by mistake if sub-directories exist under the media file that was deleted intentionally.

**Comment by LukePulverenti** [comment]
HI, the project is not dead. can we please look at an example of your issue? Thanks !

**Comment by DaveAlot** [comment]
Thanks for taking an interest.  Here's the reddit thread where I was directed to post here: https://www.reddit.com/r/emby/comments/1fhjvoy/serious_emby_bug_that_can_result_in_deletion_of/

**Comment by DaveAlot** [comment]
Any thoughts on this?

**Comment by DaveAlot** [comment]
Deleted since there's zero engagement.

**Comment by DaveAlot** [comment]
closing

**Comment by LukePulverenti** [comment]
Hi, can we please look at an example of your issue? Thanks !

**Comment by LukePulverenti** [comment]
@DaveAlot ?
