### ISSUE TITLE
API key in latest release are not working.

### ISSUE THREAD

**Issue by gborri** [MediaBrowser/Emby#3856]
Semms that the api key configured in the latest release is not working. all scraper plugin.

**Comment by LukePulverenti** [comment]
Hi there, can you please provide a specific example of your issue? Thanks.

**Comment by gborri** [comment]
sorry about that, seems now it's wotking. on sunday the api (also from chrome) was saying that the key was not valid. I will close the issue. In order to scrape my library i have had to switch on beta.
