### ISSUE TITLE
Emby server stopped responding

### ISSUE THREAD

**Issue by noodle-** [MediaBrowser/Emby#3857]
It had been running smoothly for a few weeks, then it suddenly stopped responding.

Please see [embyserver-63863147934.txt](https://github.com/user-attachments/files/17175686/embyserver-63863147934.txt)

I can't make much sense of the logs as it seems to have been just crashing continuesly..? I can't see in earlier logs when the first crash might have been. As I see tons of crashes in every log from the last five days.

A restart seems to have fixed the issue, but I do see errors being spammed in the log yet again 🤔

See [embyserver.txt](https://github.com/user-attachments/files/17176117/embyserver.txt)

Running Emby Server Version [4.8.8.0](http://app.emby.media/dashboard/releasenotes.html?version=4.8.8.0) on my Synology NAS.

If any additional info might help let me know!

**Comment by LukePulverenti** [comment]
Hi, are you still seeing this occur? if so, then try removing the anime and playback reporting plugins, then restart the server and see how things compare. Thanks.

**Comment by noodle-** [comment]
@LukePulverenti Hi! No, this isue seemed has only happened this once for me so far.

**Comment by LukePulverenti** [comment]
Thanks. Please let us know if you run into it again.
