### ISSUE TITLE
DLNA 

### ISSUE THREAD

**Issue by Maxa-S** [MediaBrowser/Emby#3859]
Your DLNA server is the stupidest, it either renames files at its own discretion, or does not show something, or extracts from folders.
Why were there no problems with Twonky (pre-installed version on WD MBL)?

I changed the settings and recreated the database many times and still some incomprehensible nonsense.

**Comment by LukePulverenti** [comment]
Hi there, can you please provide a specific example? Thanks.

**Comment by Maxa-S** [comment]
It's easier for me to describe what I need to get.
I need all my videos, Singles and series, to be displayed in one category, and not in movies / series.
Then, so that DLNA does not rename them.
So that all files are placed in the folders where they are.

I tried certain combinations of settings, and something was always wrong.

Here are the latest settings
![Снимок экрана 2024-10-01 204804](https://github.com/user-attachments/assets/22da6c3e-ff3a-457a-87bf-5ed95de78e65)
![Снимок экрана 2024-10-01 204856](https://github.com/user-attachments/assets/b3a51d61-8726-4e5d-9a4d-1bc0e65c5cf4)
![Снимок экрана 2024-10-01 204921](https://github.com/user-attachments/assets/dfb4459d-fc3f-49ce-9531-17a7cdc0bbfb)
![Снимок экрана 2024-10-01 204936](https://github.com/user-attachments/assets/c710ecd4-2cb0-4b7f-875b-7771477e0e44)
![Снимок экрана 2024-10-01 204944](https://github.com/user-attachments/assets/87e1cab3-1dd7-4db7-bd6f-f059e0546143)
![Снимок экрана 2024-10-01 204956](https://github.com/user-attachments/assets/5fccadd2-4fd3-4a6b-b14d-91bc92db5b39)
![Снимок экрана 2024-10-01 205004](https://github.com/user-attachments/assets/6b9a102f-025f-4f7e-81cb-744e3522a965)
![Снимок экрана 2024-10-01 205013](https://github.com/user-attachments/assets/f5e8c34d-b459-4811-b9dd-3879946882fc)
![Снимок экрана 2024-10-01 205021](https://github.com/user-attachments/assets/229c566a-151d-46e7-8bf7-5acca24fc5f3)
![Снимок экрана 2024-10-01 205028](https://github.com/user-attachments/assets/ae1d7f4f-620d-41c9-a7db-dd322952dc80)
![Снимок экрана 2024-10-01 205035](https://github.com/user-attachments/assets/c1dc4a37-aad7-48fc-bfbd-0aaaf9f4e978)
![Снимок экрана 2024-10-01 205045](https://github.com/user-attachments/assets/ee59362b-47c0-43ad-84de-5ff8139df03e)
![Снимок экрана 2024-10-01 205107](https://github.com/user-attachments/assets/19beff66-7d9c-460e-b20b-d7ca8027d39b)

and in its natural form it looks like this (and this is the most harmless example).

![photo_2024-10-01_20-55-57](https://github.com/user-attachments/assets/3ad7c51b-af62-4512-84d4-447ca76b92c0)
![photo_2024-10-01_20-55-54](https://github.com/user-attachments/assets/afe78e8b-3d6f-4c9a-93a2-aa90c0888d57)
![photo_2024-10-01_20-55-52](https://github.com/user-attachments/assets/43cc1096-687b-4d06-b2a1-bac652f7141d)

**Comment by LukePulverenti** [comment]
OK if you just want a plain folder view then you might do best using the home videos content type.

**Comment by LukePulverenti** [comment]
@Maxa-S has this helped?

**Comment by Maxa-S** [comment]
> @Maxa-S has this helped?
Yes, "Home Video and Photos" is exactly what you need.
Thank you very much.
![Снимок экрана 2024-11-17 231500](https://github.com/user-attachments/assets/885083ce-8f97-4aa5-bdf1-cdbc14fae5e8)

**Comment by LukePulverenti** [comment]
Thanks for confirming !
