### ISSUE TITLE
[feature request] - android server - app shortcut to scan libraries

### ISSUE THREAD

**Issue by spice42** [MediaBrowser/Emby#3861]
ive check the option for each library to monitor filesystem, i guess android app server filesystem is not supported 

its quite a pain to open the web ui and go to library to scan libraries 

would be awesome is the android server app had an app shortcut to click to scan libraries

thank you for your work

**Comment by LukePulverenti** [comment]
Hi, yes this is a good idea. Our android app already adds app shortcuts for app-related actions. The android server could do this for server-related things.

**Comment by spice42** [comment]
Nice. 

Probably a simple check to see if the android emby server is running and if not ask the user if they want to run server and scan library files
Otherwise, if the android emby server is already running, just scan library files

another way, which would help the emby project, is to add this to the emby client android app, so, users will hopefully download the emby client app from the playstore and use the app shortcut on the emby client app to scan all libraries, maybe help with popularizing the app on the playstore 

either way, glad you like the idea,

thanks again for your work 

Edit:
or  even a checkbox, to 'scan library at server startup' option below 'monitor changes in filesystem' for each library

**Comment by spice42** [comment]
i found 

Scheduled Tasks > Scan Media Library > Trigger > On Server Startup

so its a decent workaround for the moment :)
