### ISSUE TITLE
第三方软件播放时读取的地址不正确导致无法播放

### ISSUE THREAD

**Issue by fanjian998** [MediaBrowser/Emby#3864]
![Image](https://github.com/user-attachments/assets/1d6b4157-8b54-4b15-8b39-6ea3b129294d)
 ![Image](https://github.com/user-attachments/assets/269a985c-abc3-415e-844d-639cd525d7f5)
如上图所示 POT和VLC获取的地址都是没有:的 导致无法播放

**Comment by LukePulverenti** [comment]
Hi, where did the address come from?

**Comment by fanjian998** [comment]
> Hi, where did the address come from?

![Screenshot_2024-11-27-09-41-37-535_com.android.chrome.jpg](https://github.com/user-attachments/assets/fb04e7d6-349f-40da-80a2-f3c9fc5d84bd)

2345端口下 点击POT或VLC播放 自动获取的地址

**Comment by LukePulverenti** [comment]
Those VLC buttons are not Emby buttons .Someone customized their web app. You will need to contact them for support on that.

**Comment by fanjian998** [comment]
> Those VLC buttons are not Emby buttons .Someone customized their web app. You will need to contact them for support on that.

不好意思，我不知道这些，打扰了
