### ISSUE TITLE
Support resume for audio books

### ISSUE THREAD

**Issue by LukePulverenti** [MediaBrowser/Emby#507]

**Comment by quentinus95** [comment]
Hi @LukePulverenti, is there a simple solution to create a library for audiobooks, and play/resume them in Emby now ? Thx !

**Comment by popy2k14** [comment]
+1 play/resume of audio books (mp3s) would be a nice feature!

**Comment by yousefmd** [comment]
playback speed adjustment as well, 1.0, 1.25, 1.5, 1.75, 2.0

forced to use iTunes for Audiobooks, Emby is useless without play/resume + playback speed controls for audiobooks

**Comment by LukePulverenti** [comment]
we have play and resume for audio books now.
