### ISSUE TITLE
Support airplay

### ISSUE THREAD

**Issue by LukePulverenti** [MediaBrowser/Emby#554]

**Comment by sprig** [comment]
Hi,

Just wondering - why did you close this issue?

**Comment by LukePulverenti** [comment]
This was closed as a server ticket because the feature is generally better off being embedded into the client applications.

In terms of AirPlay with the apps, we did have AirPlay support with iOS for a little while, mostly for free thanks to the LG Connect SDK. The problem is the Connect SDK is a little heavy and comes with it's own set of issues, so eventually we had to remove it from the iOS app and implement the features directly ourselves. At that point that's when AirPlay got lost in the shuffle.

**Comment by sprig** [comment]
Thanks for the explanation!
I agree that it is more of a "client" feature, except the server also features a client as well (i.e. the browser based interface). I looked around a bit and it seems there is at least one open source library for sending airplay (e.g. https://github.com/chevil/raop2_play). 

Would you be open to accepting an implementation into the server (or even implementing ;-)? Alternatively, would it be better served via a plugin?

**Comment by LukePulverenti** [comment]
Yes, definitely open and not against adding it to the server. We only removed it from our issue list because we didn't consider having it server-side to be a priority anymore.

**Comment by sprig** [comment]
Alright, thanks! I don't know if I get around to it myself anytime soon,
but at least I know that in when I do, the effort won't be wasted.
