### ISSUE TITLE
Support selection of absolute & dvd order per series

### ISSUE THREAD

**Issue by LukePulverenti** [MediaBrowser/Emby#684]

**Comment by atcronin** [comment]
+1 for me.

**Comment by atcronin** [comment]
Currently working on this.
Was pretty easy to add basic functionality for cases like Firefly. Simple check box at series level and [Refresh] switches between Aired and DVD perfectly.
However for Multi-Part episodes with TVDB numbering like ep1.1,ep1.2,ep1.3 I have to merge the episode xml files into a base "ep1" file.
Alternatively if it is possible to change the episode number file scrapping pattern to support names like "Stargate Atlantis S01E01.0E01.1 Rising" then these episode would be handled like current "S01E01E02"  files.
I will contine with the xml merging code, but let me know if it will be easier to adjust the file scrapper instead.

regards,
Andrew

**Comment by LukePulverenti** [comment]
That is not going to be easy because it likely means api changes for apps in the way handle multi-part episodes all throughout the system. That really should be left for me, but you can ignore multi-part handling for now and continue on with the series level checkbox.

**Comment by atcronin** [comment]
Will do, though after reading the title of this issue I better switch to a drop-down list to select between Aired|DVD|Absolute

**Comment by psxlover** [comment]
Can this be per media folder? I'd like anime to appear in absolute order while keeping my tv series in either aired or dvd order.

**Comment by atcronin** [comment]
It would be per selectable per Series.

**Comment by Nerdy314159265** [comment]
Has there been any progress on getting this added in? It really hampers adding certain types of media to one's library.

**Comment by jonretting** [comment]
It still does

**Comment by wiza** [comment]
+1

**Comment by wdomburg** [comment]
Bump.  This has me seriously considering giving Plex a shot again, just for this feature.

**Comment by Nerdy314159265** [comment]
I think it's interesting that this issue, which in some situations could be considered a critical failure of the software, has not only not been fixed in almost a full year since my last comment but over 3 years.

This is a basic feature that so many other media softwares have already figure out and implemented. It's hard to believe Emby could be so stunted.

**Comment by LukePulverenti** [comment]
@Nerdy314159265 What is considered a basic feature is not the same as it would have been five years ago, ten years ago, etc. If more people cared about this, we obviously would have done it sooner, but that hasn't been the case.

**Comment by LukePulverenti** [comment]
However having said that, it has been long enough so this has been added for the next release.

You can edit the display order on a per series basis using the metadata editor.

**Comment by jonretting** [comment]
Thanks!

**Comment by EnigmaSolved** [comment]
Awesome -- thanks @LukePulverenti!!! :) So when adding a new series, will we be able to name the files with DVD order filenames (regarding episode numbers), or do we need to still name them according to air date order and then change things at the series level in the metadata editor to get Emby to change the display order?

**Comment by Nerdy314159265** [comment]
@LukePulverenti I very much appreciate the fix. As you probably can tell from my comment, this has been a sensitive issue for me for awhile.

**Comment by LukePulverenti** [comment]
Yes you will name the files by dvd order if you want dvd, and then change the setting for that series in the metadata editor.

**Comment by h45rd** [comment]
Thanks for implementing this, Luke. Much appreciated.

A quick test reveals a pitfall that should be addressed before pushing to production:
When refreshing existing series metadata after switching display order, there seem to be inconsistencies with the feature to display missing episodes.

Example: [Futurama S02E20 (Airdate Order) = S02E16 (DVD Order)](https://en.wikipedia.org/wiki/List_of_Futurama_episodes#Season_2_(1999–2000))
Setting the ordering to "DVD Order" and refreshing metadata correctly identifies the file named _Futurama.S02E16.Anthology.Of.Interest.I_ as what it is, but the season overview now shows S02E20 (Anthology Of Interest) as missing, even though there is no S02E20 in dvd order.

The metadata manager does not seem to provide a way to delete these "missing" episodes either.

**Comment by h45rd** [comment]
@LukePulverenti 
Did you miss my post because the issue was already closed (should I open a new one?) or am I the only one experiencing this problem hence the cause might be on my end?

**Comment by LukePulverenti** [comment]
No, just haven't had a chance to look at it yet.

**Comment by h45rd** [comment]
Understood.
If you need logs or any further information to reproduce the issue, let me know.
