### ISSUE TITLE
Security Vulnerability

### ISSUE THREAD

**Issue by nmbshiva** [MediaBrowser/Emby#894]
Media Browser Server has two vulns that are of concern.

Firstly is the fact the system is internet accessible and does not require users to set up a password. Default user as admin with no password = bad.

This could be fixed by requiring a password to be setup at first use, at the same time the user sets their name.

Secondly, the system is vulnerable to XSS.
When creating a user, an attacker can set the name using script tags.

< script>alert("XSS Found")</ script> will pop an alert.
< script>window.open("<URL>");</ script> will open a new window/tab to a URL specified.
< script>window.location.replace("<URL>");</ script> will load a page in the same window.

The XSS vuln can obviously be used to redirect the user to a page hosting malware. Additionally, loading a new page in the same window would mean the user would no longer be able to log in to the Media Browser system.

This can be fixed by not allowing any special characters in usernames, allowing only a-z, 0-9.

**Comment by LukePulverenti** [comment]
Special characters are no longer allowed in usernames.

**Comment by bigjohn322** [comment]
Only going forward or will existing usernames with special characters be required to change?

**Comment by LukePulverenti** [comment]
going forward but the change was made at least six months ago so it's been in place for a while.

**Comment by bigjohn322** [comment]
Thanks
